greenbone/gsa

src/html/classic/ng/src/gmp/models/certbund.js, src/html/classic/ng/src/gmp/models/cpe.js, src/html/classic/ng/src/gmp/models/cve.js, src/html/classic/ng/src/gmp/models/dfncert.js, src/html/classic/ng/src/gmp/models/info.js, src/html/classic/ng/src/gmp/models/nvt.js, src/html/classic/ng/src/gmp/models/ovaldef.js
The response of a info entity contains a sub element with the actual
data. This includes the user_tags. Therefore to parse the user tags
correctly in the Model base class the actual data must be moved to the
main object BEFORE parsing the properties in the Model calss.
This adds a generic data movement into the Info base class and calls
Model.parseProperties afterwards.
=> Fix parsing user_tags of info models

src/html/classic/ng/src/web/pages/ovaldefs/row.js
Remove the link to the old legacy details page from the list of
ovaldefs.
=> Remove link to legacy details page

src/html/classic/ng/src/gmp/models/certbund.js, src/html/classic/ng/src/gmp/models/dfncert.js
To be able to compare severities all severities should be parsed as a js
number. Therefore use the parser function parse_severity in cert bund
and dfn cert models.
=> Parse severity of cert models

src/gsad.c
In the gsad.c:handle_request function an invalid response size was used
in cases where get_system_report_omp does not set it.
Now the string length is used in these cases.
=> Fix response size for error messages in system_report case.

src/html/classic/ng/CMakeLists.txt, src/html/classic/ng/src/web/utils/state.js
The new State component uses the render props pattern to store a state.
The state can be changed by calling onValueChange(value, name).
Afterwards value will be stored in the passed state e.g. state[name] ===
value.
Example for using the State component:
```jsx
<State>
{({
state,
onValueChange,
}) => {
const {myvalue} = state;
return (
<TextField
value={myvalue}
name="myvalue"
onChange={onValueChange}
/>
<button onClick={() => onSave(state)} />
);
}}
</State>
```
With the state component it will not be necessary to re-implement the
state handling in components using forms.
=> Add a State component

.gitignore, src/html/classic/ng/public/index.html
With this change it is possible to add a config.local.js file under
ng/public/config.local.js that may local config settings. the
config.local.js file is ignored for git.
=> Allow to override config locally

src/html/classic/ng/CMakeLists.txt, src/html/classic/ng/src/web/components/dialog/savedialog.js
Add a new SaveDialog component. This new component is the first user of the Save component.
At the end SaveDialog should replace all dialogs using the withDialog HOC.
Disclaimer: The SaveDialog isn't used currently. Therefore it may contain issues.
=> Add a new dialog component for saving data

src/html/classic/ng/src/web/pages/groups/listpage.js, src/html/classic/ng/src/web/pages/groups/row.js
Avoid duplicate code (e.g. opening the group edit/create dialog) by
using the GroupComponent also for the group list page.
=> Refactor group list page to use GroupComponent

src/html/classic/wizard.xsl
The refresh is only supposed to be set by the "Quick First Task" wizard,
while other wizards should leave the refresh interval as it is.
=> Remove refresh_interval in Advanced Task and Modify Task wizards. (GSA 7.0)

ng/src/web/entity/container.js, ng/src/web/pages/certbund/detailspage.js, ng/src/web/pages/cpes/detailspage.js, ng/src/web/pages/cves/detailspage.js, ng/src/web/pages/dfncert/detailspage.js, ng/src/web/pages/groups/detailspage.js, ng/src/web/pages/hosts/detailspage.js, ng/src/web/pages/notes/detailspage.js, ng/src/web/pages/nvts/detailspage.js, ng/src/web/pages/os/detailspage.js, ng/src/web/pages/ovaldefs/detailspage.js, ng/src/web/pages/overrides/detailspage.js, ng/src/web/pages/results/detailspage.js, ng/src/web/pages/roles/detailspage.js, ng/src/web/pages/targets/detailspage.js, ng/src/web/pages/tasks/detailspage.js, ng/src/web/pages/users/detailspage.js
Get rid of the EntityComponent loadPermissions prop and cleanup loading of permissions list at the different details pages.
=> Entity permission loading

src/html/classic/js/gsa_bubble_chart.js, src/html/classic/js/gsa_chart_helpers.js, src/po/gsad_js-de.po, src/po/gsad_xsl-de.po
The labels in the "Duration Timeline" chart and a few other elements were lacking German translations,
which should be fixed with these changes.
=> Update the German translations for GSA 7.0

gsad/src/po/CMakeLists.txt, tools/js2pot
Building the .pot files from XSLT didn't work for me and the file from JS was missing the old scripts
because js2pot did not follow the symlinks to them.
=> Fixes for building .pot files

ng/src/web/components/bar/menubar.js
Update the menubar to link to the new user settings page instead of using legacy.
=> Add usersettings to menubar

src/gsad_omp.c
The value -2 should be ignored like 0 when storing the filt_id in the
last_filt_ids field of the current user credentials.
Otherwise it would cause problems where pages revert to a built in
filter selecting all items when they should not.
=> Do not store filt_id in last_filt_ids if it is -2 (GSA 7.0)

ng/src/web/entities/container.js
Log the loaded entities object. It should always be a CollectionList.
=> Allow for easier debugging at entites pages

gsad/src/gsad_gmp.c
The value -2 should be ignored like 0 when storing the filt_id in the
last_filt_ids field of the current user credentials.
Otherwise it would cause problems where pages revert to a built in
filter selecting all items when they should not.
=> Do not store filt_id in last_filt_ids if it is -2 (GSA master)

ng/CMakeLists.txt, ng/src/gmp/models/filter.js, ng/src/gmp/models/scanner.js, ng/src/web/app.js, ng/src/web/pages/scanners/component.js, ng/src/web/pages/scanners/details.js, ng/src/web/pages/scanners/detailspage.js, ng/src/web/pages/scanners/listpage.js, ng/src/web/pages/scanners/row.js, ng/src/web/pages/scanners/table.js
Add components for scanner details. The details of a OSP Scanner are not tested. Can't get a working OSP Scanner.
=> Scanner details

ng/src/web/components/link/target.js
In Firefox the link target overlayed the content below it, making e.g.
links not clickable. With a set position this issue can be avoided
(position: relative;).
=> Fix z-Index of link targets to work in Firefox

ng/src/web/entity/container.js, ng/src/web/entity/page.js, ng/src/web/entity/tags.js, ng/src/web/entity/tagshandler.js, ng/src/web/pages/reports/detailscontent.js, ng/src/web/pages/reports/summary.js, ng/src/web/pages/tags/component.js
Cleanup the tag handling for details pages. Most detail pages contain a tag list. Reuse more code by using the TagComponent in the TagHandler. The TagHandler is now only responsible for passing the right params to TagComponets handlers.
=> Entity tags edit

ng/src/web/pages/ldap/ldappage.js
Objects are not valid as React child. Return empty array in case there
are no certificate infos.
=> Fix empty certificate infos.

ng/src/web/components/form/spinner.js
Record the value set from the parent component and only update internal
value if the external value has changed. Before when editing the spinner
manually the value was overridden after the re-rendering caused by any
reload.
=> Fix updating the spinner value

ng/src/web/pages/groups/listpage.js, ng/src/web/pages/portlists/listpage.js, ng/src/web/pages/roles/listpage.js
Added IconDivider to toolbars for roles, groups, and port lists.
=> Fix toolbar icon margins

gsad/src/gsad_http_handler.c
To avoid warning messages when handling help pages that do not have
a language specific .xsl file, find_element_in_xml_file is only
called if xsl_filename is not NULL.
=> Test whether xsl_filename is NULL in help handler

src/gsad.c
To avoid warning messages when handling help pages that do not have
a language specific .xsl file, find_element_in_xml_file is only
called if xsl_filename is not NULL.
=> Test whether xsl_filename is NULL in help handler (GSA 7.0)

ng/src/web/components/dialog/button.js, ng/src/web/components/dialog/footer.js, ng/src/web/components/dialog/savedialog.js, ng/src/web/components/dialog/withDialog.js
Note: The button has not been set to "disabled" explicitly. I tested clicking it several times while it was in "loading-mode" and it did not create new queries in the network-tab in the browser's Dev-Tools.
=> Show busy indicator on save button while loading

src/html/classic/js/greenbone.js, src/html/classic/wizard.xsl
The label of the confirmation button of dialogs will now only change on
clicking if labeled "Create" and "Save" as the automatic change only
makes sense for these cases.
The label for the "Modify Task Wizard" has been changed to "Save" as
it is on other edit dialogs.
=> Fix confirmation button labels in Wizards

src/html/classic/js/greenbone.js
To make it clearer when auto-refresh is disabled, remove the drop-down
list completely instead of just graying it out.
=> Remove drop-down when auto-refresh is disabled.

ng/src/gmp/commands/performance.js
Use own gmp/utils.js map() to map through array of reports. The previous
usage of Array.prototype.map() threw a "map is not a function" error.
=> Fix array-mapping for reports-array

ng/src/web/components/link/link.js
We need to be able to pass query params ?name=value to links to be able
to pass additional data to pages.
=> Allow to add query params to Link components

ng/src/web/pages/extras/cvsscalculatorpage.js
With this change it is possible to set an initial cvss vector at the
cvss calculater page via url params. This will be required to be able to
link to the calculator with a specific cvss vector.
=> Allow to pass the cvss vector as url param

ng/src/gmp/utils.js
This concludes issue #20 and removes the autobind function from gmp/utils.js
=> Get rid of autobind

ng/src/web/components/form/button.js
The x in the close-buttons for dialogs is now centered by using
justifyContent: 'center'.
=> Fix button-text alignment

ng/src/web/pages/help/about.js
When the `ExternalLinkDialog` opened within a `<p>`, DOM-nesting broke,
because `<div>` can't be a descendant of `<p>`. This is now fixed by using a `<div>` instead of `<p>` (DivP).
=> Fix DOM-nesting

ng/src/web/pages/reports/listpage.js, ng/src/web/pages/reports/row.js
The former onEntityDelete handler got removed from the entites container
component. Therefore the reports page must provide an own implementation
of the handler.
Also add error handlers to get notified about occuring errors. Don't use
entityCommand prop anymore. This prop should also no longer be provided
by the entities container in future.
=> Fix deleting a report at the report list page

gsad/src/html/classic/js/gsa_bar_chart.js, gsad/src/html/classic/js/gsa_bubble_chart.js, gsad/src/html/classic/js/gsa_chart_helpers.js, gsad/src/html/classic/js/gsa_cloud_chart.js, gsad/src/html/classic/js/gsa_donut_chart.js, gsad/src/html/classic/js/gsa_gantt_chart.js, gsad/src/html/classic/js/gsa_h_bar_chart.js, gsad/src/html/classic/js/gsa_line_chart.js, gsad/src/html/classic/js/gsa_topology_chart.js, ng/src/web/app.js
Use react routers history api to change locations to the ng details or
list pages when clicking at a chart.
=> Quick fix for linking to ng from charts

ng/src/web/entity/page.js
The flexbox around the toolbar needed an explicit command to justify its
contents at the start (Firefox only).
=> Fix position of details-toolbar in Firefox

ng/src/web/pages/scanconfigs/detailspage.js
If no values for the scan config details tables are available then even
don't show a table header.
=> Don't show empty tables at scan config details

ng/src/web/entity/container.js, ng/src/web/entity/tagshandler.js, ng/src/web/pages/certbund/detailspage.js, ng/src/web/pages/dfncert/detailspage.js
Allow to set resource type to be able to create new tags for dfn cert
advs and cert bund advs because name differs for them compared to the
resource type.
=> Fix creating of new tags for secinfo

ng/src/web/pages/reports/detailscontent.js
Allow to go back to the report list page from a report details page by
clicking on the list icon.
=> Add icon to got back to the reports list page

src/html/classic/js/greenbone.js, src/html/classic/js/gsa_polyfill.js
When preparing a POST request in OMPRequest.do, simply passing the form
element to the FormData constructor could include duplicate fields,
so the function will now add the data by itself, excluding fields
contained in a div hidden with an inline "display: none".
A polyfill for the Element.matches function used is also added.
=> Remove fields from hidden divs in OMP POST.

ng/src/web/components/dialog/scrollablecontent.js
Firefox has a different behavior when calulating the height of the
scrollable content flexbox automatically compared to chrome. Therefore
resizing the dialogs caused rendering the content with full height.
Setting overflow to hidden fixes this behavior and the height is
adjusted to the max. possible height for the flexbox content and shows
the scrollbars instead.
=> Fix resizing of dialogs in firefox

ng/src/web/entities/container.js, ng/src/web/entities/table.js
Entities tables become transparent while they are updating to a new
page. This gives users feedback that their page change request or filter
query was registered.
=> Indicate updating of entities tables

src/html/classic/js/greenbone.js
The custom FormData in OMPRequest.prototype.do was not including textarea
elements before, so they are now handled together with input elements.
=> Include textarea elements in OMP POST requests

src/gsad_omp.c
Handle the case where no "autogenerate" param is given, which can now
happen when the radio buttons for it are hidden, e.g. when the type
is "Client Certificate" ("cc").
=> Fix "New Credential" dialog for type "cc"

ng/package.json, ng/src/gmp/http.js, ng/src/gmp/models/alert.js, ng/src/gmp/models/cve.js, ng/src/gmp/models/ovaldef.js, ng/src/gmp/models/report/parser.js, ng/src/gmp/models/report/tlscertificate.js, ng/src/gmp/parser.js, ng/src/gmp/utils.js, ng/src/web/pages/cves/details.js, ng/src/web/pages/usersettings/usersettingspage.js, ng/src/web/utils/withCache.js, ng/yarn.lock
For browsers not supporting es6+ features (especially ie11) we need polyfills. Using babel-polyfill did include all polyfills in our bundle. We are currently only using some specific es6 features which aren't transpiled with babel like Object.entries and Object.values. Therefore there is no need to use babel-polyfill.
=> Include only specific polyfills for es6+ features

src/gsad_omp.c
The Alert and Permission dialogs always expected some fields that are
invisible when they can be hidden and omitted under some conditions:
- filter_id is only used for Task status alerts, so only check if this
type is selected.
- the condition can be missing if not applicable to SecInfo Alerts,
so a fall back to "Always".
- In the "Edit Permission" dialog id_or_empty can be missing altogether.
=> Fix hidden fields in Alert and Permission dialogs

ng/src/web/entities/table.js, ng/src/web/pages/reports/table.js, ng/src/web/pages/vulns/table.js
In the upper left corner of entities tables is a small icon to toggle
all details pages of the currently visible rows.
This option is switched off for the reports and vulnerabilities tables.
=> Add "Toggle All Details" feature

ng/src/web/entities/table.js
The logic in handleToggleAllDetails() was broken after the last revision
and is now reset to a working state.
=> Fix Toggle All Details

ng/src/gmp/models/report/vulnerability.js, ng/src/gmp/models/result.js, ng/src/gmp/parser.js, ng/src/web/pages/reports/vulnerabilitiestable.js
The qod (quality of detection) consists of a type and value field. We
should always parse both. Before the report vulnerabilities only had the
value as vuln.qod which did broke the sorting. On the opposite report
results didn't parse the value as a float.
=> Use common function to parse qod

ng/src/web/pages/reports/hoststable.js
If the parsed host has no asset rendering the report hosts table should
not crash.
=> Don't crash if asset is not available

ng/src/web/components/table/head.js, ng/src/web/pages/tasks/table.js
Reduce necessary codelines for setting sorting on TableHeaders. Pass common props of all headers via an object. All table can now be refactored to use this new pattern.
=> Simplify table header sort

src/html/classic/omp.xsl
In newer CERT-Bund advisories the update number is not given in a
"Version" element but as an "update" attribute of the "Ref_Num"
element.
The details page will now consider both options and also
contain the revision history if available.
=> CERT-Bund details: Fix version field, add history

.github/CODEOWNERS
The CODEOWNERS file is used to add reviewers in pull requests
automatically.
For details see https://help.github.com/articles/about-codeowners/
=> Add a github CODEOWNERS file

ng/src/web/entities/table.js
Cve, Ovaldef, and Allsecinfo tables got broken by
050ca75883544367eb98fa78571d730dd9358eb8
Allow again to deactivate parts of the EntitiesTable by setting
the corresponding properties to false.
=> Fix rendering of entities tables

src/html/classic/omp.xsl
The New/Edit Schedule page only allowed years up to 2017, so the years
2018 to 2020 have been added to the drop-down selection.
=> Add years 2018 to 2020 on New/Edit Schedule page

gsad/CMakeLists.txt, gsad/src/CMakeLists.txt, gsad/src/gsad.c, gsad/src/gsad_base.c
The code had an optional method to use the xsltproc command line tool.
By default it was not used and rather the xslt library was used.
This patch make the use of the library mandatory and removes any
code path for the xsltproc tool.
Note that the tool is still in use for build-time to check validity
of the installed xsl-files.
* gsad/CMakeLists.txt: Drop handling of USE_LIBXSLT. Since it was the
last element to determine about MANDATORY_TOOL_MISSING, the handling
of this variable is also removed entirely.
* gsad/src/CMakeLists.txt: Drop handling og USE_LIBXSLT.
* gsad/src/gsad.c (register_signal_handlers): Make the code path for
USE_LIBXSLT the only one.
* gsad/src/gsad_base.c (gsad_base_init, gsad_base_cleanup,
xsl_transform_with_stylesheet): Make the code path for
USE_LIBXSLT the only …
=> Remove optional use of xsltproc command line tool.

gsad/src/gsad_http_handler.c
This removal was missing in the recent removal of the
XSLT login page.
gsad/src/gsad_http_handler.c (handle_login_page): Removed.
=> Remove handler for XSL-login page.

ng/src/web/components/dashboard/legacy/chart/topology.js
Pass the expected svg element to the renderEmptyText method.
=> Fix rendering of empty toplogy charts

gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_http.h, gsad/src/gsad_http_handler.c
The "backurl" were "omp?"-Calls offered in case of problems. Those are invalid in NG.
=> Remove the "backurl" elements.

ng/src/web/pages/reports/listpage.js
Use default icon size for the upload report icon. This allows to use a
IconProvider to change its size.
=> Fix icon size for upload report at report list page

ng/src/gmp/models/__tests__/filter.js
This is a very common filter so we should ensure that the severity range
is parsed correctly.
=> Add filter parse test for severity range

ng/src/gmp/capabilities/capabilities.js, ng/src/gmp/commands/roles.js, ng/src/gmp/http/utils.js, ng/src/gmp/models/filter/filterterm.js, ng/src/gmp/models/nvt.js, ng/src/gmp/models/report/parser.js, ng/src/gmp/models/report/port.js, ng/src/gmp/parser.js, ng/src/gmp/promise.js, ng/src/gmp/utils.js, ng/src/web/components/bar/statusbar.js, ng/src/web/components/icon/osicon.js, ng/src/web/components/link/link.js, ng/src/web/components/link/manuallink.js, ng/src/web/components/powerfilter/severitylevelsgroup.js, ng/src/web/components/sticky/container.js, ng/src/web/entities/container.js, ng/src/web/entity/tags.js, ng/src/web/pages/alerts/emailmethodpart.js, ng/src/web/pages/hosts/identifiers.js, ng/src/web/pages/reports/deltaresultsfiltergroup.js, ng/src/web/pages/reports/detailspage.js, ng/src/web/pages/reports/emptyresultsreport.js, ng/src/web/pages/results/details.js, ng/src/web/utils/cpe.js, ng/src/web/utils/os.js, ng/src/web/utils/render.js
Older browsers like IE 11 don't support most newer JavaScript features.
Therefore polyfills are required to use these features. In the past we
did used babel-polyfill but that includes all available polyfills also
not used and unnecessary once.
These commit adds polyfills for:
Set
Promise
Array.prototype.includes
String.prototype.includes
String.prototype.endsWith
String.prototype.startsWith
=> Add polyfills for newer JavaScript features

ng/public/index.html, ng/src/web/components/dialog/dialog.js
The Dialog component should be rendered outside of the current
components DOM tree to not inherit styles from parent elements. With
React 16 the portals feature (https://reactjs.org/docs/portals.html) was
introduced to exactly do this.
This fixes the styling of the external link dialogs.
=> Use portals for rendering Dialog

ng/src/web/pages/loginpage.js
The type url param was used to display a message if a user had to
re-authenticate while beeing on an old xslt based page. The param has
been removed from gsad with PR #269 in commit
dc6375dc3cd26cb16c4ec6633cc495904aeb1b6a
=> Remove the type query parameter from login page

ng/src/web/components/menu/menuentry.js
This fixes setting the onClick handler e.g. for the wizard icon menu
entries.
=> Pass MenuEntry props to Layout

ng/src/web/components/dashboard/withDashboard.js
Get rid of the "Stateless function components cannot be given refs"
warning. The Dashboard is a composed component which root component is a
function component. Therefore it's not possible to use the ref here. To
avoid this all used HOCs of Dashboard would have to implement the
innerRef pattern to be able to get the ref to the actual Dashboard
component.
But here we can avoid that because calling the reload method of
Dashboard wasn't used at all. Therefore we can remove the ref and
convert the DashboardWrapper also to a stateless function component.
=> Get rid of react warning

COPYING
No file shipped with gsa repo has APLv2 anymore.
=> Remove Apache License Version 2 from COPYING

src/html/classic/gsad.xsl, src/html/classic/omp.xsl
If an asset details page cannot be accessed, show an error message
instead of a blank page.
This can happen during normal use when a user does not have the
permission to access a particular asset while the report page shows
a link to it.
=> Add error message for asset details page

gsad/src/gsad_gmp.c
In responses with an action_result XML element, add a details element
there. Commands using response_from_entity will get this from the
status_details element of the original GMP response if it exists.
=> Add status details to the action_result XML.

src/gsad_omp.c
In responses with an action_result XML element, add a details element
there. Commands using response_from_entity will get this from the
status_details element of the original GMP response if it exists.
=> Add status details to the action_result XML. (GSA 7.0)

gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp_auth.h, gsad/src/gsad_user.c, gsad/src/gsad_user.h
The refresh interval is meanwhile fully and automatically handled in the client.
* gsad/src/gsad.c: (init_validator): drop validator for referesh_interval.
(exec_gmp_post): drop the parameter for autorefresh and do not handle
autorefresh anymore.
* gsad/src/gsad_gmp.c (envelope_gmp): Don't add refresh_interval to the
envelope anymore.
(edit_task, openvas_connection_open): Don't handle refresh_interval anymore.
(authenticate_gmp): Remove parameter "autorefresh".
* gsad/src/gsad_gmp_auth-.h: Update header accordingly.
* gsad/src/gsad_user.c (user_add, user_find): Remove parameter "autorefresh".
(user_set_autorefresh): Removed.
(credentials_new, credentials_free): Remove handling of autrefesh in the credentials structure.
* gsad/src/gsad_user.h: Update headers and struct accordingly.
=> Remove handling of refresh interval.

ng/src/web/pages/loginpage.js
The aspect ratio of the Icon was broken in IE, so size calculation had
to be changed mainly relying in width instead of height.
Additionally, IE11 moved the "insecure"-message flush to the username
input field when the browser height was decreased. A spacer is only
added in IE to prevent this.
=> Fix loginpage for Internet Explorer

ng/CMakeLists.txt, ng/src/web/components/sortable/grid.js, ng/src/web/components/sortable/item.js, ng/src/web/components/sortable/resizer.js, ng/src/web/components/sortable/row.js, ng/src/web/stories/sortable/index.js
=> Sortable grid part #4

ng/src/web/components/sortable/resizer.js
The difference must be calculated to the position at the last
notification.
=> Update resize difference notification

ng/src/web/components/dialog/closebutton.js
Due to dependencies from form buttons, the font size was set to 11px.
The button now has its own independent style.
=> Fix design of dialog closebutton

ng/src/web/components/form/datepicker.js
For the sake of UX, a calendar icon is added next to the date to
indicate that it is not just written there but also includes a
datepicker to change it.
=> Add Icon to DatePicker

ng/src/web/components/dialog/scrollablecontent.js
ScrollableContent is now 100% height of its parent and e.g. opened Selects
may use the free space of enlarged dialogs. Before this change, they were basically
"overflow: auto"-hidden behind the dialog footer.
=> Fix content growth in dialogs

gsad/src/gsad_gmp.c
In the gsad function append_alert_method_data, add the method
"TippingPoint SMS" and the corresponding data items so the method data
can be sent to the manager when creating or modifying an alert with that
method.
=> Add TippingPoint alert method data in gsad.

gsad/src/gsad.c
Fix displaying warnings with newer libmicrohttp versions:
"MHD_USE_THREAD_PER_CONNECTION must be used only
with MHD_USE_INTERNAL_POLLING_THREAD. Flag
MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting
MHD_USE_INTERNAL_POLLING_THREAD explicitly."
=> Set MHD_USE_INTERNAL_POLLING_THREAD explicitly

ng/src/web/pages/alerts/dialog.js
FormFields with radio buttons didn't move, when resizing dialogs (in
contrast to all the other fields). An uneccessary vertical divider
seemed to cause the problem, so it is removed.
=> Fix alert dialog styling for radio buttons

src/gsad.c
The "Host" HTTP header used in redirects now has to refer to a known
host name or address, which by default includes 127.0.0.1, ::1,
localhost and either all addresses given by the --listen option or
all local interface addresses.
Additional host names or addresses can be given with the new command
line option --allow-header-host.
=> Add test for HTTP header Host in redirects

ng/src/web/components/form/field.js
In Chrome autofilled input fields are set to be yellow and there is
currently no option to change this (since almost 8 years now:
https://bugs.chromium.org/p/chromium/issues/detail?id=46543).
In order to still get the fields white, add a white box-shadow on the
inside of the field.
=> Fix yellow login input fields in Chrome

ng/src/web/components/dialog/scrollablecontent.js
A Layout within the hierarchy from ScrollableContent to root was not set
100%. Chrome's default behavior prevented correct display of resized
dialog contents.
=> Fix dialog resizing in Chrome

src/html/classic/js/greenbone.js
The contents of the status details are added to the OMP error dialogs if
they are in an action_result element and not empty.
This is used to show the detailed error message from test_alert.
=> Add status details to error dialogs.

src/html/classic/omp.xsl
The date limits of the datepicker in the schedule dialogs have been
deactivated to allow setting dates in the past.
=> Deactivate limits in schedule datepicker.

ng/src/web/pages/reports/detailscontent.js
Change required proptype to 'number' instead of the 2-part (x of y)
collection counts.
=> Fix warning for tab titles

gsad/src/gsad_cmd.c, gsad/src/gsad_cmd.h, gsad/src/gsad_gmp.c, ng/src/gmp/commands/alerts.js, ng/src/web/pages/alerts/component.js
Change gsad to return only 4xx/5xx responses in case of unexpected error when calling test_alert gmp command. 
Display error details in dialog if available.
Cleanup gsad code.
=> Update testing an alert

src/gsad_omp.c
The "Edit My Settings" does not need the settings included in the
response when submitting the changes, so it will only return the error
message if the old password is invalid.
The HTTP return code has also been changed to 400 as it makes more sense
for an invalid user input than 500.
=> Return gsad_message if password is invalid

ng/src/web/entities/page.js, ng/src/web/entity/page.js, ng/src/web/entity/permissions.js, ng/src/web/entity/tags.js, ng/src/web/pages/scanconfigs/listpage.js
Most of the sections that are foldable got replaced by tabs. Therefore,
remove the foldable prop where it is not needed anymore.
The last remaining instance, in which foldable is used, is for the scan
configs edit dialog.
=> Remove folding prop where not needed

ng/src/web/pages/scanconfigs/detailspage.js
When adding a tag for an entity on its details page, port lists and scan
configs yielded an error message "invalid resource type"). The
TagsHandler set the resourceType for its render-method to the name of
the entity by default. Removing this default fixes the bug.
=> Fix adding tags

ng/src/web/components/provider/gmpprovider.js
Get rid of proptype warning in GmpProvider.
=> Fix copy and paster mistake

gsad/src/CMakeLists.txt, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_http_handler.c, gsad/src/gsad_i18n.c, gsad/src/gsad_i18n.h, gsad/src/gsad_log_conf.cmake_in
Since the module is not about xslt anymore, just about i18n,
the renaming makes sense.
Along with the plain renaming in the source code, also the log
domain is renamed from xslt to i18n.
=> Rename module xslt_i18n to gsad_i18n.

ng/src/web/pages/hosts/component.js, ng/src/web/pages/hosts/dialog.js
The withDialog HOC is replaced by using the SaveDialog component.
Probably needs to be revisited, once Target dialogs are rewritten,
because hosts have another dialog for creating targets.
Contributes to #28
=> Use SaveDialog for Hosts

ng/src/web/pages/reports/detailspage.js
Allow to pass an undefined filter to load method which doesn't get
overriden with the current applied filter from the state. Setting the
filter to undefined will reset the filter to the default.
=> Allow resetting of report filter

.gitignore, gsad/src/gsad_http_handler.c, ng/CMakeLists.txt, ng/po/CMakeLists.txt, ng/src/gmp/locale.js
Allow to use the localization files from the development web server. Therefore generate them into ng/public/locales dir. 
With `yarn build` they will be copied into _build/locales_ automatically. This dir is picked up by `make install`.
=> Languages #2

ng/src/web/components/dialog/savedialog.js
The title of the button can be changed by setting the
buttonTitle prop when calling SaveDialog.
If no buttonTitle is set, the standard is "Save".
=> Allow to change the title of the button in SaveDialog

ng/src/web/components/chart/donut.js, ng/src/web/components/chart/donut3d.js, ng/src/web/components/chart/pie.js, ng/src/web/components/chart/utils/__tests__/path.js, ng/src/web/components/chart/utils/arc.js, ng/src/web/components/chart/utils/path.js
Add own implementations for path and arc calculations. This will allow to use same code (svg arc path and centroid position) for Donut and Donut3D components.
=> Chart helper classes

ng/src/web/utils/proptypes.js
Raising an error if no value is set for the prop is done by additonal
isRequired.
=> Only raise warning if the prop has a value

ng/src/web/components/bar/progressbar.js
Avoid longer progress bars then 100% if a progress bigger then 100 is
reported by gvmd.
=> Limit width of progress bar to 100%

ng/src/web/components/form/selectelements.js
The select dropdown position must always be re-calculated when any
scrolling occurs.
=> Fix select components part 101

ng/src/gmp/utils/array.js
Import required polyfill for Object.is in IE11
=> Fix array_equals for IE11

ng/src/web/entity/link.js
Update EntityLink to fix checking for the current users permissions. The
permissions property is always undefined since a while. The model/entity
permissions are now parsed as user_capabilities for each model instance
and are always defined.
Don't create a link to the entity details if the capabilities have
permissions defined (areDefined is returning true) and the current
entity type can't be accessed.
=> Fix checking for user permissions

src/html/classic/js/greenbone.js
In OMP dialogs, add content of file input fields to the request only if
the file content is defined, i.e. the user has actually chosen a file to
upload, otherwise ignore the field.
This prevents "undefined" being sent as the file content if no file is
selected.
=> Ignore empty files in OMP dialogs.

ng/src/web/components/chart/topology.js
LinkForces, forceX and forceY (formerly known as gravity), and charge
are set to keep the spread of the graph covenient.
=> Set forces for topology chart

ng/src/web/components/layout/autosize.js
The new component can be used to provide the available width and height
for a sub-component.
=> Add a component to calculate height and width automatically

ng/src/web/utils/globalcss.js
Now it's obvious where the small did come from. The font css property
was used in the global css for the body content and not the font-family.
=> Fix setting the default font family

src/po/gsad_js-fr.po
Build of the translations will currently fail with the following error:
```
Traceback (most recent call last):
File "/usr/src/gsa-7.0.3/tools/po2json", line 66, in <module>
main()
File "/usr/src/gsa-7.0.3/tools/po2json", line 62, in main
convert(sys.argv[1], sys.argv[2])
File "/usr/src/gsa-7.0.3/tools/po2json", line 45, in convert
po_f = polib.pofile(in_name)
File "/usr/lib/python2.7/dist-packages/polib.py", line 138, in pofile
return _pofile_or_mofile(pofile, 'pofile', **kwargs)
File "/usr/lib/python2.7/dist-packages/polib.py", line 86, in _pofile_or_mofile
instance = parser.parse()
File "/usr/lib/python2.7/dist-packages/polib.py", line 1320, in parse
self.process(keywords[tokens[0]])
File "/usr/lib/python2.7/dist-packages/polib.py", line 1464, in process
self.current_line)
IOError: …
```
=> Fix syntax error in french translation

ng/src/web/pages/tasks/row.js
At the task list don't display severity and trend for container tasks.
This reproduces the same behavior as in gsa 7 with openvas 9.
=> Don't display severity and trend for container tasks

ng/src/web/components/dashboard2/dashboard.js, ng/src/web/components/dashboard2/data/display.js, ng/src/web/components/dashboard2/display.js, ng/src/web/components/sortable/grid.js, ng/src/web/components/sortable/item.js
Items in the grid can now be dragged with the header only.
=> Make Grid items draggable at header only

ng/src/web/pages/tasks/dashboard/loaders.js, ng/src/web/pages/vulns/dashboard/loaders.js
Fix displaying the charts at the tasks dashboard by always passing the
children to the Loader components.
=> Always pass children to Loader components

ng/src/web/pages/scanconfigs/component.js
Updating "Select all NVTs" after changing selections in
EditConfigFamilyDialog works by merging the resulting state from
loadEditScanConfigSettings() into the component state.
Selecting all NVTs also for the EditConfigFamilyDialog is done by
actively/manually selecting all NVTs if "Select all NVTs" button is
checked.
=> Fix updating ScanConfigDialog

ng/src/web/components/sortable/item.js
With react-beautiful-dnd 7.0.0 the provided.placeholder got removed and
isn't necessary anymore.
=> Update sortable item for api changes

ng/src/web/components/chart/bar.js, ng/src/web/components/chart/schedule.js
Labels that are too long will not be cut off by the display anymore.
Instead the chart will be moved to the right to make space for longer
labels. If the label exceeds a MAX_LABEL_LENGTH = 25 it will be
shortened.
=> Fix yAxis labels for schedule charts

ng/src/web/components/dashboard2/controls.js
If the dashboard items couldn't be loaded because e.g. of an error don't
crash the app.
=> Don't crash if items are null or undefined

src/html/classic/omp.xsl
To make sorting by multiple columns work in detached charts, also
generate the attributes data-sort-fields, data-sort-stats and
data-sort-orders from the request parameters, not just their singular
versions data-sort-field, data-sort-stat and data-sort-order.
=> Fix multiple column sort in detached charts

ng/src/web/components/dashboard2/controls.js, ng/src/web/components/dashboard2/settings/actions.js
Normally this should not happen but it is more safe to ensure we don't
crash if the items array is actually empty.
=> Don't crash if items are an empty array

src/html/classic/omp.xsl
Because long lists of hosts can use a lot of screen space abbreviate
them to 500 characters in the trashcan list like in the normal list
and to 1000 characters on the details page.
=> Abbreviate long hosts list of targets

src/html/classic/omp.xsl
Instead of the credential type, use the newly added formats OMP element
to decide which download icons to show on the list and details pages.
=> Use new formats elem in credential download icons

src/html/classic/help_de.xsl
This updates the German help contents page to contain the same items as
the English version.  However, this does not add any new translations.
=> Update German help contents page

src/gsad_omp.c, src/html/classic/js/greenbone.js, src/html/classic/omp.xsl
When saving the LDAP or Radius authentication configuration, reload the
page instead of jumping to the Tasks page.
Also show dialog boxes during the save request and when errors occur.
=> More user-friendly saving of auth config

ng/src/web/components/dashboard2/display/datadisplay.js
Pass isLoading prop to title func and always display title string
instead of "Loading". Now it's possible to adjust the title in the
loading case by the title function itself.
=> Update handling of data display title

ng/src/web/components/sticky/container.js, ng/src/web/components/sticky/sticky.js
Reuse the subscription components for notifications in Sticky components
to not having to implement notificiation twice.
=> Use subscription components for Sticky container

.circleci/config.yml
The name of the Docker images used for the CI steps has changed to
better reflect their purpose and to refer to the images stored in the
organizational account instead of an individual user account on Docker
hub.
=> Update location of the Docker images

src/gsad_omp.c
When getting a result for the new override or note dialog, skip counting
all the results to make the OMP request faster when opening the dialog
from a report results page.
=> Skip result counts for new override / note

src/gsad.c
The parameters for optional lists of hosts like the host access fields
in the user editing and creation now also allow colons.
Without this it wasn't possible to enter IPv6 addresses.
=> Allow colon in optional hosts parameters.

src/html/classic/js/greenbone.js
Do not add send the Select2 search field to the form data in OMP POST
requests to prevent warnings about params without name.
=> Do not send Select2 search field.

ng/src/gmp/commands/agents.js, ng/src/gmp/commands/credentials.js
The downloads for Agents and Credentials now use "arraybuffer" as the
response type so binary files are handled correctly.
=> responseType arraybuffer for Agents / Credentials

ng/src/web/components/dashboard2/display/datadisplay.js
Calling setState with the same data as before seems to issue re-renders
despite nothing has changed. Therefore avoid re-renders if the hasSvg
variable in the state doesn't change. This fixes an infinite loop
(render -> componentDidUpdate -> render -> componentDirUpdate -> ...).
=> Update state only if necessary for svgRef

ng/src/web/components/sortable/grid.js
The item margin must only be subtracted once.
=> Fix width calculation for grid items

src/gsad_omp.c
Free the entity and response in get_aggregate_omp once they are no
longer needed, i.e. after an error or after copying to the regular
response.
Also get the status code from the entity and remove an unnecessary
case for the return value -1 of the omp function.
=> Fix handling entity and response of get_aggregate.

ng/src/web/components/chart/donut3d.js
innerRef can't be used as a key because innerRef changes during
rendering. Allow to pass an explicit key for a label.
Also update coding style.
=> Fix setting the key of the donut3d labels

ng/src/gmp/commands/reports.js
The http get request for a delta report must be transformed into an
actual Report model instance.
Seems to have been broken due to some refactoring some time ago.
=> Transfrom delta report response to a Report model

gsad/src/gsad.c, gsad/src/gsad_settings.c, gsad/src/gsad_settings.h
The maximum number of connections per IP address can now be changed with
a new gsad command line argument, per-ip-connection-limit.
This can be useful when GSA is accessed through a proxy.
=> Add option to change per-IP connection limit

ng/src/gmp/models/filter.js
All SecInfo items use the filtertype 'info' instead of having an own
type such as e.g. 'nvt'.
=> Fix FilterTypes for SecInfos

gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp.h
This adds the back-end functionality to create multiple tags in one request
with the new create_tags GMP command.
=> Add create_tags GMP command.

ng/src/web/components/link/certlink.js
DFN-CERT and CERT-Bund links in the References section of detailspages
(Results) are now clickable.
=> Fix displaying links for references on detailspages.

gsad/src/gsad.c, ng/src/web/pages/usersettings/usersettingspage.js, ng/src/web/utils/proptypes.js, ng/src/web/utils/severity.js
This severity class is no longer used provided by Manager.
=> Remove support for severity class OpenVAS Classic

ng/src/web/pages/start/page.js
* Don't show default "Overview" dashboard if the main dashboard settings aren't loaded yet
* Don't ever override any setting by using a different dashboard uuid for the "Overview" dashboard
=> Main dashboard loading fixes

ng/src/gmp/gmp.js
Use correct parameters to also remove the user token from gsad. Before
the token was still valid after calling gmp.logout()
=> Fix calling logout http request in gmp api

ng/src/gmp/models/schedule.js, ng/src/web/components/chart/schedule.js, ng/src/web/components/form/timezoneselect.js, ng/src/web/pages/schedules/component.js, ng/src/web/pages/schedules/dialog.js, ng/src/web/pages/schedules/render.js, ng/src/web/pages/tasks/actions.js, ng/src/web/pages/tasks/dashboard/schedulesdisplay.js, ng/src/web/pages/tasks/icons/scheduleicon.js
Part 2
* Improve recurrence information
* Update Next Scheduled Task Chart to use ical event data
* Update ScheduleIcon to use ical event data
* Fix timezone selection when editing a Schedule
* Update editing a Schedule to use ical event data
=> Extended schedules

ng/src/web/pages/scanconfigs/editdialog.js
New scanner option test_empty_vhost introduced with https://github.com/greenbone/openvas-scanner/pull/124
=> Add test_empty_vhost scanner option to is_radio

ng/src/gmp/locale/date.js, ng/src/web/pages/reports/scaninfo.js
Move the duration function into reports scaninfo module because it is
only used at this place. Also it doesn't display a formatted duration
instead it calculates a duration between two dates and converts it to a
readable string more or less specific for scan durations.
=> Convert duration function into scanDuration

ng/src/web/components/form/spinner.js
Store step and value in the state instead of the component instance
itself. When changing the value up and down this will use the correct
current value now.
=> Fix getting current step and value

gsad/src/gsad_gmp.c
The scanner type isn't required for updating a task. Therefore don't
require it in gsad.
=> Don't require scanner_type when modifying a task

gsa/package.json, gsa/yarn.lock
The 2.0.0 version breaks our comparison for the chart data. It seems to
compare something recursively which causes a js stack error.
=> Revert update of fast-deep-equal dependency

gsa/src/gmp/utils/string.js
We are still using different variants for the entity/resource types.
Therefore add a conversion function from gvmd resource types to gsa
entity names.
=> Add a normalizeType function

gsa/package.json, gsa/src/web/components/chart/wordcloud.js, gsa/yarn.lock
Temporarily downgrade to react 16.3. to fix rendering issues caused by https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops
=> Fix rendering charts

gsa/src/web/components/dashboard/dashboard.js, gsa/src/web/components/sortable/grid.js, gsa/src/web/store/dashboard/settings/__tests__/actions.js, gsa/src/web/store/dashboard/settings/__tests__/reducers.js, gsa/src/web/store/dashboard/settings/__tests__/selectors.js, gsa/src/web/store/dashboard/settings/actions.js, gsa/src/web/store/dashboard/settings/reducers.js, gsa/src/web/store/dashboard/settings/selectors.js
* Only fallback to defaults if no dashboard settings aren't available
* Show loading indicator if the settings aren't loaded yet
* Separate the defaults from the loaded settings in the store
=> Improve loading of dashboard charts

gsa/src/web/store/dashboard/data/loader.js
If data has been loaded don't pass undefined data to the Loader
children. This avoids displaying a loading indicator in a dashboard
DataDisplay twice for the initial data loading with the default filter.
A loading indicator is should only be shown if we haven't loaded any
data yet.
=> Avoid passing undefined data to Loader children

gsa/src/web/entities/container.js, gsa/src/web/entities/tagsdialog.js, gsa/src/web/pages/tags/listpage.js
- disable bulk tags option for tags
- the tags dialog (bulk tags) now allows to create a new tag "on the fly"
=> Improve tags

gsa/src/web/components/dashboard/controls.js
The state layout for the dashboard settings has been changed. The
defaults (including the permittedDisplays setting) aren't put in the
same state object as the loaded settings anymore.
=> Fix getting the allowed displays for a Dashboard

gsa/src/web/entities/container.js
entitiesSelected must be undefined or a Set. Therefore don't initialize
them as an object.
=> Fix propType warning for entitiesSelected

gsad/src/gsad.c
This allows using SecInfo ids like NVT OIDs and CVE IDs for actions on
generic resources like adding them to tags.
=> Make resource_ids:value an alias of info_id

gsa/CMakeLists.txt, gsa/src/web/pages/tasks/details.js, gsa/src/web/store/entities/__tests__/filters.js, gsa/src/web/store/entities/__tests__/schedules.js, gsa/src/web/store/entities/reducers.js, gsa/src/web/store/entities/schedules.js, gsa/src/web/store/entities/utils/testing.js
* Add a testAll utility function
* Put Schedule entities in the store
* Load Schedule on demand at the TaskDetails
=> Entities Loading

gsa/src/gmp/commands/entities.js
In order to fully function the previously deleted process_bulk in gsad needs to be restored and renamed to bulk_export.
=> Fix bulk actions delete and export

gsa/src/gmp/models/result.js, gsa/src/web/pages/reports/detailsfilterdialog.js, gsa/src/web/pages/reports/sort.js, gsa/src/web/pages/results/filterdialog.js, gsa/src/web/pages/results/row.js, gsa/src/web/pages/results/table.js
This adds the hostname to the "Host" column of the results list and the
report details and a new filter option for it.
The column header now has two subcolumns: IP and Hostname to easily sort
by both.
=> Add result hostname to list pages

src/html/classic/omp.xsl
If a list page is empty but the filter still returns items, enable the pagination and add a hint about using it to go back to a page with content.
One common case where this could happen is after deleting all the items on the last page of a list.
=> Enable and hint to pagination for empty list pages

gsad/src/utils.c
The standard string.h header file is needed for strcmp.
=> Add #include for string.h to utils.c

gsa/src/web/entity/tags.js
onTagDeleteClick was replaces by onTagRemoveClick therefore it is
unused. gmp prop was never used. Therefore it is removed to fix all prop
type warnings.
=> Remove unnecessary prop(-types) from EntityTags

gsa/src/web/app.js
Drop the proptype to remove the warning from the console.
=> Remove obsolete PropType of App component

gsa/src/web/entities/container.js
* Passing an array as gmpname isn't used anymore.
* Use pluralizeType for settings the plural name of the command.
=> Update setting the gmp command name in EntitiesContainer

gsa/src/gmp/models/event.js
It's not necessarily and error. Therefore only log it as warning.
=> Don't log next date calculation error as error

gsad/src/CMakeLists.txt, gsad/src/gsad.c, gsad/src/gsad_base.c, gsad/src/gsad_credentials.c, gsad/src/gsad_credentials.h, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp.h, gsad/src/gsad_http.c, gsad/src/gsad_http.h, gsad/src/gsad_http_handler.c, gsad/src/gsad_session.c, gsad/src/gsad_session.h, gsad/src/gsad_user.c, gsad/src/gsad_user.h
* Move credentials and users/session list into own c modules.
* Shrink credentials. Credentials are only containing request specific
data now.
* Don't allow direct access on credential members. Use accessor
functions instead.
* Rework the session/users list out of the user module.
* Always work on a copy of a user. Don't access the user object in the
session directly. This avoids having to block the thread when
accessing user data.
* Actually only block a thread when accessing the session for reading
and writing users. This should improve concurrent http requests a lot.
Before nearly only one thread could run simultaneously because they
have been blocked for user access.
=> Rework user session handling

gsa/src/gmp/models/tag.js, gsa/src/web/pages/tags/detailspage.js
Resources under the "Assigned Resources" tab are now limited to 40 items
being listed.
To list all resources a link will be shown (in case there is more than
40) that leads to the respective resource-entities listpage filtered
with the new tag_id filter keyword.
=> Update resources-list in Tags detailspages

gsa/src/web/components/badge/badge.js
icon is set via react reference. The reference is set to null if it
isn't available. Therefore checking only for undefined when calculating
the margins did crash.
Also update the imports to use full paths and no .js ending.
=> Don't crash if reference is not set in Badge component

gsa/src/web/components/link/link.js
It seems to much efford to convert all Link component occurences to pass
a Filter instance to Link. Also most of the filter strings are very
simple so it's an overhead to parse them in a Filter before.
=> Allow Filter model and String as filter for Link components

gsa/src/gmp/http/gmp.js, gsad/src/gsad_http_handler.c
Use /gmp?token=... instead of the old /omp?token=... now.
=> Update url for http gmp api calls

gsad/src/gsad_gmp.c
Check the param before accessing it. This avoids a crash in gsad if the
param is missing in the request.
Also use str_equal for string comparisions.
=> Don't crash if include_related param is missing

src/gsad.c, src/validator.c, src/validator.h
Add an is_binary flag to validator rules to skip checks like UTF-8
validation and the regex test.
Apply those to allow non-text files as the installer param for agents
and as method_data:pkcs12 for alerts.
=> Allow binary file uploads in validator (7.0)

gsad/src/gsad.c, gsad/src/validator.c, gsad/src/validator.h
Add an is_binary flag to validator rules to skip checks like UTF-8
validation and the regex test.
Apply those to allow non-text files as the installer param for agents
and as method_data:pkcs12 for alerts.
=> Allow binary file uploads in validator

gsa/public/config.js
By default use an autorefresh interval of five seconds now. Two seconds
is a way to fast when some pages need 200 ms and more for rendering.
=> Use an interval of five seconds for the autorefresh interval

src/html/classic/omp.xsl
The "New Target" dialog will now properly recognize if the parameter
host_count is missing, so it will count the bulk_selected parameters
instead, making the selection of hosts by checkboxes work.
=> Fix host count of checkbox selection for target

gsa/src/web/components/dialog/dialog.js
With the lower height, there should be less issues with the Save-button
being unreachable.
=> Reduce default max height for dialogs

gsa/src/web/entities/container.js
A list page is updating if the user actually did change the data, e.g.
if the next page has been requested. If no data is available from the
store yet and the data must be loaded from the backend isUpdating must
be true to indicate the loading process.
=> Fix showing loading indicator for updating case

gsa/package.json, gsa/src/gmp/log.js, gsa/src/web/components/badge/badge.js, gsa/src/web/components/bar/menubar.js, gsa/src/web/components/bar/titlebar.js, gsa/src/web/components/menu/menu.js, gsa/src/web/components/menu/menuentry.js, gsa/src/web/components/menu/menuhelpentry.js, gsa/src/web/components/menu/menusection.js, gsa/src/web/utils/theme.js, gsa/yarn.lock
The Menu is changed in design and styled-components is used instead of glamorous.
Some minor fixes are also performed for Badge and logging color as well as translatability for the TitleBar.
This is the first commit regarding issue #643.
=> Use styled-components for the menu

gsa/src/web/components/menu/menu.js
Links in the first (and only first) menu sections were not high enough 
and not centered vertically.
=> Fix Menu in IE11

gsa/src/web/entities/page.js
Drop usage of Wrapper at EntitiesPage and set the layout explicitly.
=> Use column layout for list pages by default

gsa/src/gmp/models/scanconfig.js, gsa/src/gmp/models/scanner.js, gsa/src/web/pages/usersettings/defaultspart.js, gsa/src/web/pages/usersettings/dialog.js, gsa/src/web/pages/usersettings/usersettingspage.js
Also split scanconfigs and scanners into openvas and osp options.
=> Overwrite default filters when loading entities in user settings

gsa/src/web/entities/page.js, gsa/src/web/entities/withEntitiesContainer.js, gsa/src/web/pages/login/loginpage.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/usersettings/usersettingspage.js, gsa/src/web/store/entities/utils/__tests__/actions.js, gsa/src/web/store/entities/utils/actions.js, gsa/src/web/store/entities/utils/testing.js, gsa/src/web/store/usersettings/__tests__/actions.js, gsa/src/web/store/usersettings/actions.js, gsa/src/web/store/usersettings/defaults/__tests__/actions.js, gsa/src/web/store/usersettings/defaults/actions.js
All action creators should now have one of the following signatures
```js
actionCreator(configureParams)(params)(dispatch, getState)
```
or
```js
actionCreator(params)(dispatch, getState)
```
or
```js
actionCreator(params)
```
=> Action creator function signature changes

gsa/src/web/pages/results/detailspage.js
Fix rendering the result details if the result entity is loaded from a
get results entities response. In thas case entity task isn't available
yet.
=> Don't crash if task and report aren't available

gsa/src/web/pages/tags/resourcelist.js
Update ResourceList to load the entity resources from the redux store.
=> Load related tag resources from redux store

tools/generate-cpe-icon-dict.sh, tools/generate-zone-dict.sh
Pulled the patch from https://sources.debian.org/patches/greenbone-security-assistant/7.0.3+dfsg.1-1/0001-make-the-build-reproducible.patch/ to make the build reproducible.
Rationale:
> One shell script does not normalize the locale while sorting, and
another one relies on echo interpreting escape sequences by default.
> 
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843110
=> [gsa-7.0] make the build reproducible (pulled from downstream)

gsa/src/web/pages/help/about.js
Greenbone clearly does endorse the content of greenbone.net so it is 
unsuitable to show such a dialog.
=> Don't show external link dialog when clicking on greenbone.net link

gsa/src/gmp/parser.js, gsa/src/web/pages/extras/cvsscalculatorpage.js, gsa/src/web/pages/extras/trashcanpage.js, gsa/src/web/pages/ldap/ldappage.js, gsa/src/web/pages/performance/performancepage.js, gsa/src/web/pages/radius/radiuspage.js, gsa/src/web/pages/usersettings/usersettingspage.js, gsa/src/web/store/usersettings/defaults/__tests__/actions.js, gsa/src/web/store/usersettings/defaults/actions.js
Update user session if the user interacts with non details and non list pages.
=> Session handling

gsa/CMakeLists.txt, gsa/src/gmp/commands/users.js, gsa/src/gmp/utils/__tests__/number.js, gsa/src/gmp/utils/number.js, gsa/src/web/components/dashboard/display/severity/severityclasstransform.js, gsa/src/web/components/form/numberfield.js, gsa/src/web/components/form/spinner.js, gsa/src/web/pages/overrides/row.js
Centralize formatting of numbers to fix saving the default severity user setting.
=> Usersettings default severity

gsa/CMakeLists.txt, gsa/src/gmp/commands/users.js, gsa/src/web/components/observer/locationobserver.js, gsa/src/web/components/observer/sessionobserver.js, gsa/src/web/routes.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp.h
Implement auto logout feature. Using the feature needs an up to date gsad.
=> Auto logout

gsa/src/web/components/form/radio.js, gsa/src/web/components/loading/loading.js, gsa/src/web/components/panel/infopanel.js, gsa/src/web/components/powerfilter/powerfilter.js, gsa/src/web/components/section/section.js, gsa/src/web/components/sortable/emptyrow.js, gsa/src/web/components/sortable/item.js, gsa/src/web/components/sortable/resizer.js, gsa/src/web/components/sortable/row.js, gsa/src/web/utils/theme.js
=> Convert glamorous to styled-components #4

gsa/src/web/components/form/field.js, gsa/src/web/components/form/formgroup.js, gsa/src/web/components/form/multiselect.js, gsa/src/web/components/form/selectelements.js, gsa/src/web/components/form/textarea.js, gsa/src/web/components/form/timezoneselect.js, gsa/src/web/components/panel/infopanel.js, gsa/src/web/pages/reports/emptyresultsreport.js
=> Convert glamorous to styled-components #5

gsa/src/web/components/dialog/button.js, gsa/src/web/components/dialog/error.js, gsa/src/web/components/dialog/footer.js, gsa/src/web/components/dialog/linkconfirmationdialog.js, gsa/src/web/components/dialog/overlay.js, gsa/src/web/components/form/datepicker.js
=> Convert glamorous to styled-components #6

gsa/src/gmp/commands/reports.js, gsa/src/web/entities/container.js, gsa/src/web/pages/reports/detailscontent.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/emptyresultsreport.js, gsa/src/web/pages/reports/listpage.js, gsa/src/web/pages/reports/resultstab.js, gsa/src/web/pages/reports/row.js, gsa/src/web/store/entities/__tests__/reports.js, gsa/src/web/store/entities/reducers.js, gsa/src/web/store/entities/reports.js, gsa/src/web/store/entities/utils/__tests__/selectors.js, gsa/src/web/utils/constants.js
Load the report data from store and adjust auto reload for report details.
=> Report load from store

gsa/src/web/components/form/selectelements.js, gsa/src/web/components/pagination/pagination.js, gsa/src/web/components/section/header.js, gsa/src/web/components/sortby/sortby.js, gsa/src/web/entities/table.js, gsa/src/web/entities/tagsdialog.js, gsa/src/web/entities/withRowDetails.js, gsa/src/web/entity/box.js, gsa/src/web/entity/info.js, gsa/src/web/entity/note.js, gsa/src/web/entity/override.js, gsa/src/web/entity/tags.js, gsa/src/web/pages/alerts/method.js
=> Convert glamorous to styled-components #7

gsad/src/gsad_gmp.c
Giving one of these resource types as the resource_type or the related
resource type will create asset permissions like get_assets.
=> Accept types "host" and "os" in create_permissions

gsa/src/web/pages/reports/applicationstable.js, gsa/src/web/pages/reports/detailscontent.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/reportentitiescontainer.js, gsa/src/web/pages/reports/resultstab.js
Keep the sorting when new report data arrives.
=> Report details sorting

gsa/CMakeLists.txt
Use the variable for cmake instant of hard coded cmake call.
=> Let it work with cmake and cmake3.

gsa/src/web/components/chart/bar.js, gsa/src/web/components/chart/donut.js, gsa/src/web/components/chart/donut3d.js, gsa/src/web/components/chart/group.js, gsa/src/web/components/chart/legend.js, gsa/src/web/components/chart/line.js, gsa/src/web/components/chart/svg.js, gsa/src/web/components/chart/tooltip.js, gsa/src/web/components/chart/topology.js, gsa/src/web/components/dashboard/dashboard.js, gsa/src/web/components/dashboard/display/datadisplay.js, gsa/src/web/components/dashboard/display/datatable.js, gsa/src/web/entity/permissions.js, gsa/src/web/pages/extras/cvsscalculatorpage.js, gsa/src/web/pages/extras/trashcanpage.js, gsa/src/web/pages/help/about.js
=> Convert glamorous to styled-components #8

gsa/public/config.js, gsa/src/gmp/__tests__/gmpsettings.js, gsa/src/gmp/__tests__/log.js, gsa/src/gmp/gmp.js, gsa/src/gmp/gmpsettings.js, gsa/src/gmp/log.js
Allow runtime configuration of logging.
To change the default log level just put the following code into your browsers console:
```js
gmp.log.setDefaultLevel('debug')
```
to enable all debug output or
```js
gmp.log.setDefaultLevel('error')
```
to enable only error output.
=> Logging configuration

gsa/CMakeLists.txt
This will be needed, to build it without internet connection.
In this case all needed npm packages can be preloaded into the yarn cache.
=> Add Yarn offline mode option.

INSTALL.md
Follow-up of https://github.com/greenbone/gsa/pull/945. The changes done there requires apt-transport-https to be installed which might be not the case on most Debian installs.
=> Include apt-transport-https install instructions

gsa/src/web/components/dialog/container.js, gsa/src/web/components/dialog/content.js, gsa/src/web/components/dialog/title.js, gsa/src/web/components/folding/folding.js, gsa/src/web/components/form/button.js, gsa/src/web/components/form/spinner.js, gsa/src/web/components/form/togglebutton.js, gsa/src/web/components/icon/withIconSize.js, gsa/src/web/components/label/severityclass.js, gsa/src/web/components/layout/divider.js, gsa/src/web/components/layout/withLayout.js, gsa/src/web/components/table/stripedtable.js, gsa/src/web/components/table/table.js, gsa/src/web/pages/hosts/dashboard/vulnscoredisplay.js, gsa/src/web/pages/hosts/details.js, gsa/src/web/pages/hosts/detailspage.js, gsa/src/web/pages/hosts/identifiers.js, gsa/src/web/pages/performance/performancepage.js, gsa/src/web/pages/reports/reportpanel.js
=> Convert glamorous to styled-components #10

gsa/package.json, gsa/src/web/stories/chart/bar.js, gsa/src/web/stories/chart/legend.js, gsa/src/web/stories/chart/topology.js, gsa/src/web/stories/dashboard/display.js, gsa/src/web/stories/datepicker/index.js, gsa/src/web/stories/multiselect/index.js, gsa/src/web/stories/powerfilter/index.js, gsa/src/web/stories/select/index.js, gsa/src/web/stories/sortable/grid.js, gsa/src/web/stories/sortable/resizer.js, gsa/src/web/stories/tabs/index.js, gsa/yarn.lock
Converts stories for storybook to styled-components and removes glamorous dependencies.
Contributes to and finally closes #643
=> Convert glamorous to styled-components #12

.circleci/config.yml
This commit modifies the CircleCI configuration to use the appropriate
Docker image for Node 8 for the `js_lint` and `js_test` jobs (instead of
Node 6).
=> Use Node 8 for CircleCI tests

gsa/src/web/components/chart/bar.js, gsa/src/web/components/chart/donut3d.js, gsa/src/web/components/chart/line.js, gsa/src/web/components/dashboard/display/datadisplay.js, gsa/src/web/components/dashboard/display/datatable.js
* Change appearance of overlay
* Use placeholder in some charts
* Fix x-Axis label in BarChart when FilterTerm is shown
=> Change IconOverlay in DataDisplay

src/html/classic/omp.xsl
The height CSS declaration has been removed from the inline style
because the check boxes would not appear correctly in some browsers
like Chrome.
=> Remove height CSS from bulk selection check boxes.

README.md
Add the Greenbone logo and add bages for release and codecov.io.
Inspired by https://github.com/greenbone/gvm-tools/pull/82
=> Add Greenbone logo and additional badges to README

gsa/yarn.lock
yarn 1.10 adds sha512 hashes for each node package for integrity checks.
=> Update yarn.lock file for yarn 1.10

gsa/src/web/components/dashboard/display/display.js, gsa/src/web/components/dialog/button.js, gsa/src/web/components/dialog/closebutton.js, gsa/src/web/components/dialog/content.js, gsa/src/web/components/dialog/resizer.js, gsa/src/web/components/dialog/title.js, gsa/src/web/components/form/button.js, gsa/src/web/components/form/spinner.js, gsa/src/web/components/table/stripedtable.js
Includes:
* Table padding
* Display shadows
* Spinner colors
* Dialogs
=> Change appearance

CHANGES.md, gsa/src/web/entity/page.js, gsa/src/web/pages/nvts/details.js, gsa/src/web/pages/nvts/detailspage.js, gsa/src/web/pages/nvts/nvtpreference.js, gsa/src/web/pages/nvts/preferences.js, gsa/src/web/pages/nvts/references.js, gsa/src/web/pages/nvts/table.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/reportentitiescontainer.js, gsa/src/web/pages/reports/scaninfo.js, gsa/src/web/pages/reports/summary.js
* Put NVT preferences inside own tab on detailspage
* Fix filtering download options of ReportFormats
* Change Table for Report summary
* ...some clean-up
=> GUI miscellaneous

gsa/src/web/components/form/download.js
Deactivate eslint warning with next version of create-react-app (2.0).
=> Don't expect anchor having a href property

gsa/src/gmp/models/cve.js, gsa/src/gmp/models/tag.js, gsa/src/web/components/table/data.js, gsa/src/web/pages/cves/row.js, gsa/src/web/pages/filters/component.js, gsa/src/web/pages/results/details.js, gsa/src/web/pages/results/detailspage.js, gsa/src/web/pages/scanconfigs/editdialog.js
* Fix ScanConfigDialog tables
* Fix translating FilterTypes
* Fix CVEs table
* Change titles in Result details
* ... some clean-up
=> GUI miscellaneous #2

gsa/src/web/entity/withEntityContainer.js, gsa/src/web/pages/results/table.js, gsa/src/web/pages/scanconfigs/editconfigfamilydialog.js, gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js, gsa/src/web/pages/scanconfigs/importdialog.js
* some Layout adjustments
* Split Results Host column into IP and Name
* Fix loading of CPE details
=> GUI miscellaneous #3

cmake/FindYarn.cmake, gsa/CMakeLists.txt
Versions beyond 1.0 will fail because the command shortcut `yarn install` isn't supported. It would have been possible to support versions lower then 1.0 by adjusting the package install command but yarn 1.0 is the first stable version and already more then one year old. Therefore supporting older versions doesn't make sense to me.
=> Require yarn 1.0

src/gsad_omp.c
This should fix the redirects to SecInfo details pages, e.g. after
deleting a tag on them.
=> Consider "details" and "..._type" in next_page_url

src/html/classic/omp.xsl
The type "Scanner" was missing in the list of resource types of the
"New Tag" and "Edit Tag" dialogs.
=> Add "Scanner" to tag resource type list

src/html/classic/graphics.xsl
The chart has been moved to the "nvt-charts" template so it is available
on both the main and SecInfo dashboards, not just the NVTs page.
=> Add "NVTs by solution type" to all dashboards

gsa/src/web/components/dashboard/controls.js, gsa/src/web/components/dashboard/dashboard.js, gsa/src/web/store/dashboard/settings/__tests__/actions.js, gsa/src/web/store/dashboard/settings/__tests__/reducers.js, gsa/src/web/store/dashboard/settings/actions.js, gsa/src/web/store/dashboard/settings/reducers.js
* Remove state sync in Dashboards
* Make reset more explicit
* Cleanup dashboard settings actions
* Don't store constant settings like maxRows into the backend
=> Dashboard improvements

src/gsad_omp.c
With this filters containing quote marks and other XML reserved
characters can be used to create a new host.
=> XML escape asset_hosts filter for create_target

gsa/src/web/entity/permissions.js, gsa/src/web/entity/tags.js
* Center Actions column
* Remove toggleDetailsIcon from permissions tab
=> Improve entity tags and permissions table layout

gsa/src/gmp/models/__tests__/certbund.js, gsa/src/gmp/models/__tests__/dfncert.js, gsa/src/gmp/models/certbund.js
Always return an array for categories.
Also, add tests for DFNCert model, because it was already in my commit pipeline...
=> Fix CertBund model categories parsing

src/html/classic/omp.xsl
This removes the 80 character limit of the text field for entering the
hosts of notes and overrides manually.
=> Remove maxlength of hosts for notes and overrides

gsa/src/web/pages/users/confirmdeletedialog.js, gsad/src/gsad_gmp.c
Due to a stray comma in the dialog selecting "Current User" resulted in
no user inheriting the resources of the deleted user.
The typo is fixed and a check has been added to see if the inheritor_id
is given but invalid.
=> Fix "Current User" inheritance on "Delete User"

src/gsad.c, src/gsad_omp.c
This addresses a segfault that could occur if the last preference on an NVT preferences edit dialog is skipped, e.g. when it's a password that's not overwritten, or possibly if no preferences are sent at all.
The first commit is about preventing the segfault in case a NULL response is passed to send_response, while the second one prevents save_config_nvt_omp from returning a NULL response under the conditions above.
=> Fix segfault due to NULL save_config_nvt_omp response

gsad/src/gsad_gmp.c, gsad/src/gsad_http.c
This is the master branch version of #1044, which fixes a potential segfault when saving NVT preferences.
=> Fix segfault due to NULL save_config_nvt_omp response (master)

gsa/CMakeLists.txt, gsa/src/web/app.js, gsa/src/web/components/dashboard/dashboard.js, gsa/src/web/components/dashboard/display/display.js, gsa/src/web/components/dialog/savedialog.js, gsa/src/web/components/errorboundary/errorboundary.js, gsa/src/web/entities/page.js, gsa/src/web/entity/page.js, gsa/src/web/pages/extras/cvsscalculatorpage.js, gsa/src/web/pages/extras/feedstatuspage.js, gsa/src/web/pages/extras/trashcanpage.js, gsa/src/web/pages/help/about.js, gsa/src/web/pages/ldap/ldappage.js, gsa/src/web/pages/radius/radiuspage.js, gsa/src/web/pages/start/page.js, gsa/src/web/pages/usersettings/usersettingspage.js
Add new ErrorBoundary component and use it where seemingly appropriate.
=> Error boundaries

gsa/CMakeLists.txt, gsa/src/web/components/dialog/footer.js, gsa/src/web/components/dialog/linkconfirmationdialog.js, gsa/src/web/components/dialog/savedialog.js, gsa/src/web/components/dialog/twobuttonfooter.js, gsa/src/web/components/powerfilter/withFilterDialog.js
* Make the two button footer an own component
* Use it where appropriate (powerfilter and all savedialogs)
Both buttons can be titled and given handlers independently.
Default title for the left button is "Cancel".
Loading indicator only on right button.
=> Two Buttons in DialogFooter

gsad/src/gsad_gmp.c
The name of the tried socket was missing which makes error
analysis difficult.
=> Improve error message in case of a socket problem.

gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http_handler.c, gsad/src/validator.c, gsad/src/validator.h
This changes basically the names of the validator functions and of
the server connection function.
It is a plain name change, no change in functionality.
=> Rename openvas to gvm where no relation to scanner

src/gsad_omp.c
When modifying SNMP credentials, the privacy algorithm can now be
updated without changing the privacy password.
=> Modify privacy password and algorithm separately (7.0)

gsad/src/gsad_gmp.c
When modifying SNMP credentials, the privacy algorithm can now be
updated without changing the privacy password.
=> Modify privacy password and algorithm separately

gsa/src/web/pages/ldap/ldappage.js, gsa/src/web/pages/performance/performancepage.js, gsa/src/web/pages/radius/radiuspage.js, gsa/src/web/pages/usersettings/usersettingspage.js
Toolbar icons are set to "small" for pages: ldap, radius, performance, 
and usersettings.
=> Adjust icon size

gsa/public/img/host.svg, gsa/public/img/ldap.svg, gsa/public/img/result.svg
The icons got namespaces reintroduced during publication, which led to erroneous 
displays. This commit cleans the source code of those icons and merges paths.
=> Replace erroneous icons

gsa/src/web/components/dashboard/display/utils.js
We (GSF-dev and GVM-dev) should stick to the 11 QoD-values defined in the manual (https://docs.greenbone.net/GSM-Manual/gos-4/en/glossary.html#quality-of-detection-qod ).
This PR fixes the 76% to 75% value and GSF-dev will update the VTs that introduced 76% and 60% values.
=> Fix QoD value for qodColorScale

gsa/po/gsa-ar.po, gsa/po/gsa-de.po, gsa/po/gsa-fr.po, gsa/po/gsa-pt_BR.po, gsa/po/gsa-ru.po, gsa/po/gsa-tr.po, gsa/po/gsa-zh_CN.po
Actually, this change has no effect. But with this patch
my QA system does not complain anymore about the use of "omp"
in these files.
=> Renamed omp_status to gmp_status in translation files.

gsa/src/web/pages/reports/alertactions.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/downloadreportdialog.js, gsa/src/web/pages/reports/triggeralertdialog.js, gsa/src/web/store/usersettings/__tests__/reducers.js, gsa/src/web/store/usersettings/reducers.js
Save IDs of alert and RFP to report content composer and use those defaults when loading
=> Save alert and RFP to report content composer defaults

gsa/src/web/components/dialog/composercontent.js, gsa/src/web/pages/reports/alertactions.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/downloadreportdialog.js, gsa/src/web/pages/reports/triggeralertdialog.js
Also, drop filler words in dialogs
=> Remove "applyOverrides" from report content composer

src/html/classic/omp.xsl
If an xref URL does not have the scheme prefix "http://", "https://",
"ftp://" or "ftps://", the link URL will have "http://" added in front
so it will not be handled as a relative path if the scheme is missing.
=> Fix xref URLs without scheme prefix

src/gsad.c, src/gsad_omp.c, src/html/classic/omp.xsl
This adds dialog fields for the Alemba vFire alert method, including a
way to specify multiple report formats for methods that support it.
Requires greenbone/gvmd#285.
=> Add Alemba vFire alert method (GSA 7.0)

gsa/src/gmp/commands/dashboards.js
When requesting the dashboard settings from the backend don't throw if
no setting is returned from the response which will lead to a promise
rejection. Instead return an empty object for the settings.
Should fix #1098
=> Don't reject promise if no setting is available

gsad/src/gsad.c, gsad/src/gsad_gmp.c
This PR is a port of the gsad portions #1092 from GSA 7.0 to master
and adds alert data params for the Alemba vFire method including a
way to specify multiple report formats for methods that support it.
=> Add Alemba vFire alert method to gsad

gsa/src/web/components/icon/osicon.js
The OsIcon doesn't need Icon functionality and actually is rendered 
incorrectly when used as Icon
=> Make OsIcon an Img component

gsad/src/gsad.c, gsad/src/gsad_gmp.c
This lets gsad accept the smb_file_path_type alert method data and allows creating the tag
"smb-alert:file_path" with a Windows path as the value.
=> GSAd changes for SMB alert updates

CHANGES.md, gsa/src/gmp/commands/alerts.js, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/alerts/dialog.js, gsa/src/web/pages/alerts/smbmethodpart.js
Requires PR #1107 and https://github.com/greenbone/gvmd/pull/294 to work properly
=> Smb alerts file path type

gsad/src/gsad_gmp.c
This GMP feature is not used by the new single page app UI.
All functionality is using advanced alternatives and
eventually the type element value "assets" for get_reports
will be deprecated.
**Checklist**:
=> Remove unused code paths for report type "assets".

CHANGES.md, gsa/src/gmp/commands/alerts.js, gsa/src/web/pages/alerts/dialog.js, gsa/src/web/pages/alerts/smbmethodpart.js
smb_file_path_type handling is removed from GSA.
**Checklist**:
=> Revert #1109

src/gsad_omp.c, src/html/classic/omp.xsl
The options are no longer used because manager decides how to interpret the file path automatically.
**Checklist**:
- Tests N/A
- [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) Entry N/A
=> Revert use of smb_file_path_type [7.0]

gsad/src/gsad_gmp.c
This reverts commit d4d21824751f08e2933283c4ad5b626232fe935e.
The manager no longer uses smb_file_path_type to decide how to
interpret the path.
**Checklist**:
- Tests N/A
- [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) N/A
=> Revert "Add smb_file_path_type alert method data to gsad" [master]

gsad/src/gsad_http.c
GSA requires an envelope root element. Therefore always put
gsad_response elements as a child of envelope.
=> Always put gsad_message responses into an <envelope> element

CHANGES.md, gsad/src/gsad.c
With this, the smb-alert:file_path tag can use placeholders.
Also, a CHANGES entry is added for the tag validator changes.
**Checklist**:
- Tests N/A
=> Allow percent signs in tag values and add CHANGES entry

CHANGES, src/gsad.c
By allowing percent signs in the tag values, the smb-alert:file_path tag can use placeholders.
**Checklist**:
- Tests N/A
=> Allow percent signs in tag values

CHANGES, src/gsad_omp.c, src/html/classic/omp.xsl
This adds the "Password only" credential type and the selection fields
in the Alert dialogs.
**Checklist**:
- Tests N/A
=> Add Sourcefire PKCS12 password support

CHANGES.md, gsa/src/gmp/commands/alerts.js, gsa/src/gmp/models/credential.js, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/alerts/dialog.js, gsa/src/web/pages/alerts/sourcefiremethodpart.js, gsa/src/web/pages/credentials/dialog.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c
Added support for the PKCS12 password used by sourcefire. This includes adding a new credential type (pw) to gsa and gsad.
**Checklist**:
=> Support Sourcefire PKCS12 password

src/gsad_omp.c
Sending an empty string would make manager reject the alert because
it cannot find the credential.
**Checklist**:
- Tests N/A
- [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) Entry N/A
=> Do not send pkcs_credential if it is empty

gsa/src/gmp/models/report/parser.js, gsa/src/web/pages/reports/detailscontent.js
Show Loading indicator while loading report results instead of the empty report page.
**Checklist**:
=> Report loading

gsa/src/web/pages/reports/detailscontent.js
The last change to the counts was erroneous. The counts that were displayed were taken from some cache. When the cache is now empty the TabTitle showed only "x of " as count. This PR fixes this issue by basically reverting part of the change connected with showing the loading indicator for reports.
**Checklist**:
=> Fix showing counts in report detailscontent tab titles

CMakeLists.txt
When PROJECT_BETA_RELEASE is 0 "+alpha" will be added to the version
string to make the prerelease status more explicit.
Also additional instructions for version numbers have been added.
**Checklist**:
- Tests N/A
- [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) Entry N/A
=> Mark versions before beta releases as alpha

gsa/src/web/entities/container.js, gsa/src/web/entities/table.js, gsa/src/web/pages/reports/detailscontent.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/resultstab.js
Show transparent tables at the result details page tabs if a user has causes a new loading procedure by changing the current filter. Currently there is no indicator that we are actually updating the data in the background if the filter has changed and we have a lot of data. In that case the user might think that nothing has changed and updating the filter doesn't work.
=> Report details update indicators

gsa/src/web/pages/tickets/table.js
After Modification Time has been added to the remediation tickets table
columns the size for the details and footer was broken. This commit
increments both sizes to mach the number of columns.
=> Fix column size for footer and details at tickets table

gsa/src/gmp/commands/reports.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp.h
Resolve the gsad command "import_report" and use the actual
GMP command create_report instead.
Drop the (already unused) option to create a task while creating a
report. This makes it mandatory to to apply a task_id for create_report.
Cleanup and simplify the code for create_report_gmp.
**Checklist**:
=> Consolidate create_report 

gsa/CMakeLists.txt, gsa/src/web/components/qod/__tests__/__snapshots__/qod.js.snap, gsa/src/web/components/qod/__tests__/qod.js, gsa/src/web/components/qod/qod.js, gsa/src/web/pages/nvts/row.js, gsa/src/web/pages/results/row.js, gsa/src/web/pages/vulns/row.js
A new Qod component is added that takes care of formatting (no linebreak) and adding a '%' to the value supplied.
**Checklist**:
- [ X ] Tests
=> Prevent linebreak in QoD values at listpage table rows

gsa/src/gmp/models/task.js
Neither first_report nor second_last_report is used.
Those elements will not be present anymore in the GMP
response of get_tasks.
**Checklist**:
=> Remove considering unused reports in get_tasks.

gsa/src/gmp/commands/scanconfigs.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c
Now NVT preferences are stored in OID:PrefType:PrefName format.
Depends on PRs in scanner https://github.com/greenbone/openvas-scanner/pull/275 and gvmd https://github.com/greenbone/gvmd/pull/394
**Checklist**:
=> Adjust for changes in NVT preferences format.

gsa/src/gmp/__tests__/parser.js, gsa/src/gmp/models/report/parser.js, gsa/src/gmp/models/report/vulnerability.js, gsa/src/gmp/parser.js
Entity names will now manually be unescaped as well as NVT names from within reports. The latter are parsed separately.
Changes for the other missing entities and corresponding tests will follow for master.
**Checklist**:
=> Unescape names

gsa/src/gmp/__tests__/parser.js, gsa/src/gmp/models/nvt.js, gsa/src/gmp/models/report/parser.js, gsa/src/gmp/parser.js
This fixes unescaping of special characters in vulnerability 
descriptions such as "Insight" taken from the tags-string.
**Checklist**:
- [ X ] Tests
=> Fix parsing vulnerability descriptions in reports

gsa/src/web/pages/operatingsystems/table.js
This PR fixes a small typo in the Operating Systems table.
**Checklist**:
=> Fix typo in OS table header

gsa/src/gmp/commands/__tests__/tag.js, gsa/src/gmp/commands/tags.js
TagCommand.getElementFromRoot() accessed an array of two 
get_tags_response elements. As we currently only have one 
of those elements there was no array to access, therefore yielding 
an 'undefined' when calling get_tags_response[0].tag
**Checklist**:
- [ X ] Tests
=> Fix getting a tag

gsa/src/web/components/bar/menubar.js, gsa/src/web/components/menu/menu.js
This fixes wrongly displayed menues. We need to make sure that the first child of a Menu is a MenuEntry and not a MenuSection.
**Checklist**:
=> Menu permissions

CHANGES.md, gsa/src/web/pages/scanconfigs/editconfigfamilydialog.js
Allow to sort the nvts at the edit scan config families dialog by name,
oid, severity, timeout and selected. Sorting by selected is a bit
"hackish" because the selected information isn't contained in the nvts
array.
**Checklist**:
- [N/A] Tests
=> Allow to sort scan config nvts in edit dialog

CHANGES.md, gsa/src/gmp/models/__tests__/credential.js, gsa/src/gmp/models/credential.js
We likely get a second pgp credential for signing in future.
**Checklist**:
=> Display PGP Encryption Key for crendential type pgp

gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js
Render summary and affected fields with preformatted whitespace. The nvt
adds newlines to formatting. Therefore the whitespace for the nvt tags
should be handles the same in the edit dialog as at the details page.
=> Update nvt tags formatting for edit nvt details dialog

gsa/CMakeLists.txt, gsa/src/web/pages/radius/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/radius/__tests__/dialog.js, gsa/src/web/pages/radius/dialog.js, gsa/src/web/pages/radius/radiuspage.js
Needs https://github.com/greenbone/gsa/pull/1212 for changes to currentAuthSettings() command
**Checklist**:
=> Upgrade RADIUS page

gsa/src/web/pages/tasks/row.js
When clicking on the number of reports of a task in the task 
view, the reports view is opened with a specific filter. This PR fixes 
the filter so that reports will be sorted by descending date.
**Checklist**:
=>  Adjust filter term for task specific Reports view

gsa/package.json, gsa/yarn.lock
Fixes collapsed line chart scales
For further information on the API change of vx/shape see https://github.com/hshoff/vx/pull/383
**Checklist**:
=> Downgrade to vx/shape 0.0.179

gsa/src/web/components/errorboundary/errorboundary.js, gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap, gsa/src/web/pages/ldap/ldappage.js
* Don't  crash LDAP page when CertificateInfo is undefined
* Use StNonAvialableIcon in ErrorBoundary
**Checklist**:
=> GUI miscellaneous #12

CHANGES.md, gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter.js, gsa/src/gmp/models/filter/__tests__/convert.js, gsa/src/gmp/models/filter/convert.js
Filter keywords first with a value less then 1 are not allowed. Therefore all values less then 1 are converted to 1 automatically.
Also for rows and first must always use the equal = relation. Other relations like >, < are not defined.
**Checklist**:
=> Avoid undefined behavior in filters with first and rows keywords

CHANGES, src/gsad_omp.c
This fixes bulk deleting assets selected by a filter by giving the
previously missing subtype like "host" to the GMP command used to
get the list of UUIDs to delete.
**Checklist**:
- N/A Tests
=> Consider subtype in bulk delete of assets

CHANGES.md, gsa/src/web/pages/targets/dialog.js
This change lets the user see all possible credential dropdowns and 
instead "hides" the Reverse Lookup Only and Reverse Lookup Unify options. 
The only indication that they are there is the scrollbar on the right, 
but I don't regard this as problem as it seems to be consensus that those 
settings are "advanced mode" anyway.
**Checklist**:
=> Change order of options in TargetDialog

gsa/public/img/os_unknown.svg
For unknown reasons the questionmark was reduced in scale and moved to 
the lower left. It's know recognizable and centered again.
**Checklist**:
=> Enlarge questionmark in os_unknown.svg icon

CHANGES.md, gsa/src/web/pages/performance/performancepage.js
Use current time if start or end date is invalid.
**Checklist**:
=> Don't crash performance page if passed dates are invalid

gsa/src/web/pages/reports/detailscontent.js
Instead of "X of Y" results, just show "X"
**Checklist**:
=> Adjust Results TabTitle in report for delta status

CHANGES.md, gsa/src/gmp/commands/users.js, gsa/src/gmp/models/filter.js, gsa/src/web/pages/filters/component.js, gsa/src/web/pages/usersettings/dialog.js, gsa/src/web/pages/usersettings/filterpart.js, gsa/src/web/pages/usersettings/usersettingspage.js
Clean up some related code as well.
Needs https://github.com/greenbone/gvmd/pull/447 to work.
**Checklist**:
=> Add option for default hosts and os filters

CHANGES.md, gsa/src/gmp/__tests__/gmpsettings.js, gsa/src/gmp/gmpsettings.js, gsa/src/web/pages/login/__tests__/__snapshots__/loginform.js.snap, gsa/src/web/pages/login/__tests__/loginform.js, gsa/src/web/pages/login/loginform.js, gsa/src/web/pages/login/loginpage.js, gsa/src/web/utils/testing.js
Support for guest user login. With this change a config.js file with the following content
```javascript
config = {
guestUsername: 'foo',
guestPassword: 'bar',
}
```
can be provided to activate a `Login as Guest` button at the login page. To actually use this user
a user with the role Guest and the specified username/password combination must be created.
**Important**: It is not checked if the user is a restricted guest user. It would also be possible to auto login via a super admin user!
Additionally by adding a `disableLoginForm: true` to the config object in the `config.js` file it is possible to deactivate the *normal* login form at the login page to only provide the `Login as Guest` button.
**Checklist**:
=> Guest user

CHANGES.md, gsa/src/web/pages/omp.js, gsa/src/web/routes.js
Redirect from old secinfo urls like
https://secinfo.greenbone.net/omp?cmd=get_info&info_type=nvt&token=...
to the new version of that page.
**Checklist**:
- [n/a] Tests
=> Omp url redirect

gsa/src/web/pages/nvts/references.js
With MANY references, users might be forced to scroll a bit, but the new layout is a lot more easier to read and with the average number of references being rather low, it's absolutely preferable to the "one long line" list.
**Checklist**:
- [ N/A] [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) Entry
=> Put each NVT reference in a new line

gsad/src/gsad_gmp.c
GSA expects a enveloped response when requesting a single report.
=> Envelope get_report response

CHANGES.md, gsa/src/gmp/commands/alerts.js, gsa/src/web/pages/alerts/component.js
=> Fix testing alerts

CHANGES.md, gsa/src/gmp/commands/reports.js, gsad/src/gsad_gmp.c
Remove unused code paths from get_report function in gsad. Most of this
original code has become obsolete with GSA 8. It was required to pass
arbitrary parameters to the XSLT transformation in GSA 7.
**Checklist**:
- [N/A] Tests
=> Cleanup get_report function in gsad

CHANGES.md, CMakeLists.txt, cmake/GetGit.cmake, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http_handler.c, gsad/src/gsad_settings.c, gsad/src/gsad_user.c, gsad/src/gsad_user.h
* Drop obsolete CLI arguments from gsad
* Fix handling of git revision for gsad build
* Update copyright in printed with --version
Related to #1258
**Checklist**:
- [n/a] Tests
=> Cleanup gsad

CHANGES.md, gsa/src/web/components/dialog/composercontent.js, gsa/src/web/components/form/checkbox.js, gsa/src/web/pages/alerts/contentcomposerdialog.js, gsa/src/web/pages/reports/downloadreportdialog.js, gsa/src/web/pages/reports/triggeralertdialog.js
=> Composer UX concerning (saving) filters

CHANGES.md, gsa/src/web/pages/alerts/emailmethodpart.js
=> Add tooltips to deactived textfields in AlertDialog

gsa/src/web/components/form/__tests__/__snapshots__/selectelement.js.snap, gsa/src/web/components/form/selectelements.js
Fixes opening Select menus in dialogs, where they moved into the background with #1273.
**Checklist**:
- [ X ] Tests
=>  Fix z-Index of Select

CHANGES.md, gsa/src/gmp/commands/__tests__/result.js, gsa/src/gmp/commands/__tests__/results.js, gsa/src/gmp/commands/results.js, gsa/src/gmp/commands/testing.js
Update getting the result object from the response. The response got
changed with 892110429d9f9b1c6d83304e31e2516d17cec513 and dropped the
commands_response part by using the standard code for retrieving a
single entity in gsad.
**Checklist**:
=> Fix getting the result object from the response

CHANGES.md, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/alerts/contentcomposerdialog.js, gsad/src/gsad_gmp.c
Fix opening the content composer from the alert dialog.
- Always open dialog independent of loading errors
- Remove unnecessary loading of set filter
- Use undefined in state for not set filter id value
Fixes #1276 
**Checklist**:
- [n/a] Tests
=> Alert content composer

gsa/src/web/components/link/userlink.js
The UserLink is render after a successfull login. Set sessionTimeout is
put into the redux store after the login. Therefore the sessionTimeout
may be undefined for a short amount of time.
**Checklist**:
- [n/a] Tests
=> Don't require sessionTimeout for UserLink

gsa/src/web/pages/alerts/emailmethodpart.js, gsa/src/web/pages/alerts/sendmethodpart.js, gsa/src/web/pages/alerts/smbmethodpart.js, gsa/src/web/pages/alerts/snmpmethodpart.js, gsa/src/web/pages/targets/dialog.js, gsa/src/web/pages/targets/row.js
Avoid raising PropType warnings by removing the obsolete box prop from
several Layout elements.
**Checklist**:
- [n/a] Tests
=> Don't pass obsolete box props to layouts

CHANGES.md, gsa/src/web/components/dialog/__tests__/__snapshots__/errordialog.js.snap, gsa/src/web/components/dialog/__tests__/errordialog.js, gsa/src/web/components/dialog/errordialog.js, gsa/src/web/pages/extras/trashcanpage.js
=> Add errordialog to fix missing error messages in trashcan

CHANGES.md, gsa/src/web/wizard/advancedtaskwizard.js, gsa/src/web/wizard/modifytaskwizard.js, gsa/src/web/wizard/taskwizard.js
=> Update text for Task Wizard, Advanced Task Wizard and Modify Task Wizard

CHANGES.md, gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter.js, gsa/src/gmp/models/filter/__tests__/convert.js, gsa/src/gmp/models/filter/convert.js, gsa/src/web/components/powerfilter/powerfilter.js, gsa/src/web/entities/container.js, gsa/src/web/entities/table.js, gsa/src/web/pages/reports/listpage.js
Fix several issues with filter handling
* Delta report selection must set first=1
* Fix pagination with default filter (reset filter.id if filter is changed)
* Improve the powerfilter by not syncing the filter state
* Fix setting filters at report details page with quotes in the value
**Checklist**:
=> Filter fixes

CHANGES.md, gsa/src/web/entities/container.js, gsa/src/web/entity/container.js, gsa/src/web/pages/reports/detailspage.js
Avoid running multiple timers for the same page. This could happen
before when changing the filter while a timer was running.
**Checklist**:
- [n/a] Tests
=> Don't start reload timer if a timer is already running

CHANGELOG.md, gsad/src/gsad.c
Add the debug flag for libmicrohttpd only if NDEBUG is not set. This is
only the case for CMAKE_BUILD_TYPE Debug.
**Checklist**:
- [n/a] Tests
=> Don't add debug flag for libmicrohttpd in production

gsa/src/web/pages/scanconfigs/editdialog.js
- use_mac_addr was removed from scanner https://github.com/greenbone/openvas-scanner/pull/181
- There are two 'ping_hosts' checks, remove one.
**Checklist**:
- [] Tests N/A
- [] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry N/A
=> Backport #1297

CHANGELOG.md, gsa/src/web/pages/targets/table.js
=> Remove sort by credential from Target view

CHANGELOG.md, gsa/src/gmp/commands/permissions.js, gsa/src/web/pages/permissions/multipledialog.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c
* Drop unused code from create permission functions in gsad
* Cleanup and improve create permissions functions in gsad
* Fix creating multiple permissions with write mode
**Checklist**:
- [n/a] Tests
=> Permission fixes

gsa/src/web/components/powerfilter/createnamedfiltergroup.js
Avoid proptype warning for changing from uncontrolled to controlled.
=> Initialize filterName with an empty string

CHANGELOG.md, gsa/src/gmp/models/filter.js, gsa/src/web/pages/permissions/listpage.js
Add a permissions filter filter for permission list page
**Checklist**:
- [n/a] Tests
=> Allow to load all permission filters at the permissions list page

CHANGELOG.md, gsad/src/gsad_gmp.c
Fix creating and editing of alerts
**Checklist**:
- [n/a] Tests
=> Alert filter issues

gsad/src/gsad_gmp.c
Fix build by removing the compile warning for a unused variable in gsad.
This got introduced with #1314
=> Remove unused overrides variable

gsa/package.json
The variable was used by create-react-app to determine the source
directory for absolute imports. This mechanism is depreacted with
create-react-app 3 and replaced by jsconfig.json settings now.
**Checklist**:
- [n/a] Tests
=> Remove NODE_PATH variable from package.json

gsad/src/gsad_gmp.c
filt_id must be 0 or not set to work correctly in gvmd. filt_id="" is an
invalid filter id...
This got introduced with #1314 
**Checklist**:
- [n/a] Tests
=> Fix using a filter string for get_report

CHANGELOG.md, gsa/src/web/pages/targets/component.js
Set to "All IANA assigned TCP 2012-02-10" instead of "OpenVAS default"
**Checklist**:
- [N/A] Tests
=> Change Default PortList for NewTargetDialog

CHANGELOG.md, gsa/src/gmp/locale/date.js, gsa/src/web/components/date/datetime.js, gsa/src/web/pages/certbund/row.js, gsa/src/web/pages/cpes/row.js, gsa/src/web/pages/cves/row.js, gsa/src/web/pages/dfncert/row.js, gsa/src/web/pages/hosts/row.js, gsa/src/web/pages/nvts/row.js, gsa/src/web/pages/operatingsystems/row.js, gsa/src/web/pages/ovaldefs/row.js, gsa/src/web/pages/reports/row.js, gsa/src/web/pages/reports/scaninfo.js, gsa/src/web/pages/results/row.js, gsa/src/web/pages/schedules/row.js, gsa/src/web/pages/secinfo/row.js, gsa/src/web/pages/tags/row.js, gsa/src/web/pages/tasks/row.js, gsa/src/web/pages/tickets/table.js, gsa/src/web/pages/vulns/row.js
=> Render dates in current configured timezone

CHANGELOG.md, gsa/src/web/pages/performance/performancepage.js
If the performance timeline is calculated from a duration also consider
the current user timezone.
**Checklist**:
- [] Tests
=> Consider timezone when using durations for performance

CHANGELOG.md, gsa/po/CMakeLists.txt
Install the locales from the gsa/public/locales directory instead of
from the nodejs build dir. It seems that under some circumstances the
locale files haven't been put into the nodejs build dir.
**Checklist**:
- [] Tests
=> Fix installation of locale files

CHANGELOG.md, gsa/src/gmp/models/scanconfig.js, gsa/src/web/pages/scanconfigs/header.js, gsa/src/web/pages/scanconfigs/row.js, gsa/src/web/pages/scanconfigs/table.js
=> Add type column to scan config to allow filter and sort by type

CHANGELOG.md, gsa/src/gmp/locale/date.js, gsa/src/web/components/date/datetime.js, gsa/src/web/pages/certbund/detailspage.js, gsa/src/web/pages/cpes/details.js, gsa/src/web/pages/credentials/detailspage.js, gsa/src/web/pages/hosts/identifiers.js, gsa/src/web/pages/notes/detailspage.js, gsa/src/web/pages/notes/dialog.js, gsa/src/web/pages/ovaldefs/detailspage.js, gsa/src/web/pages/overrides/detailspage.js, gsa/src/web/pages/overrides/dialog.js, gsa/src/web/pages/reports/detailscontent.js, gsa/src/web/pages/reports/tlscertificatestable.js, gsa/src/web/pages/scanners/dialog.js, gsa/src/web/pages/schedules/details.js, gsa/src/web/pages/tickets/details.js
Display more dates in current user timezone
**Checklist**:
- [] Tests
=> Dates with timezone

CHANGELOG.md, gsa/src/web/pages/reports/detailspage.js
Don't reset to the filter passed by props (which is the default filter)
when reloading the report details page. Instead use the current applied
filter.
**Checklist**:
- [] Tests
=> Use last set filter when reloading

CHANGELOG.md, gsa/src/web/components/bar/__tests__/__snapshots__/progressbar.js.snap, gsa/src/web/components/bar/__tests__/__snapshots__/severitybar.js.snap, gsa/src/web/components/bar/__tests__/__snapshots__/statusbar.js.snap, gsa/src/web/components/bar/__tests__/__snapshots__/titlebar.js.snap, gsa/src/web/components/bar/__tests__/__snapshots__/toolbar.js.snap, gsa/src/web/components/bar/__tests__/progressbar.js, gsa/src/web/components/bar/__tests__/severitybar.js, gsa/src/web/components/bar/__tests__/statusbar.js, gsa/src/web/components/bar/__tests__/titlebar.js, gsa/src/web/components/bar/__tests__/toolbar.js, gsa/src/web/components/bar/progressbar.js
=> Add some tests for bar

CHANGELOG.md, gsa/src/web/pages/targets/details.js
=> Fix list of excluded hosts formatting

CHANGELOG.md, gsa/src/web/entities/container.js
If the timer is not reset it is not possible to start a new one.
**Checklist**:
- [n/a] Tests
=> Reset timer to undefined if the timer is cleared

gsa/src/web/pages/tasks/component.js
The credentials are only loaded when opening the advanced task wizard.
Therefore they must not be required.
**Checklist**:
- [n/a] Tests
=> Don't require credentials for TaskComponent

CHANGELOG.md, gsa/src/web/components/date/datetime.js
Don't crash DateTime component if no date is passed. Instead render
nothing by returning null if date prop is undefined.
**Checklist**:
- [] Tests
=> Make DateTime component resilient

CHANGELOG.md, gsa/src/web/pages/reports/detailspage.js
* Clear possible running timer if load is called (resets timer when
user requests reload)
* Reset timer id to undefined when timer is cleared (allows to start a
new timer)
**Checklist**:
- [n/a] Tests
=> Fix timer handling at report details page

.circleci/config.yml
The old cache may not fit to the current build because of changes to the
configuration and paths.
=> Only use exact circleci cache

CHANGELOG.md, gsa/src/web/entities/container.js
Always use the actual displayed and used loaded filter. Avoid using a
new filter that hasn't data yet. Using a not displayed filter may result
in unexpected behavior.
**Checklist**:
- [] Tests
=> Use loaded filter from state in EntitiesContainer

CHANGELOG.md, gsa/src/web/pages/roles/component.js, gsa/src/web/pages/roles/dialog.js
=> Fix editing roles

gsa/.eslintrc.js
Support for these eslint rules is end-of-life
https://eslint.org/blog/2018/11/jsdoc-end-of-life
**Checklist**:
- [n/a] Tests
=> Remove validation of jsdoc comments

CHANGELOG.md, gsa/src/gmp/__tests__/gmp.js, gsa/src/gmp/gmp.js, gsa/src/gmp/http/__tests__/rejection.js, gsa/src/gmp/http/http.js, gsa/src/gmp/http/rejection.js, gsa/src/web/authorized.js, gsa/src/web/components/bar/titlebar.js, gsa/src/web/store/entities/utils/__tests__/reducers.js, gsa/src/web/store/entities/utils/reducers.js
=> Improve logout

CHANGELOG.md, gsa/src/web/pages/reports/importdialog.js, gsa/src/web/pages/reports/listpage.js, gsa/src/web/pages/tasks/containerdialog.js
=> Import report improvements

CHANGELOG.md, gsa/src/web/app.js, gsa/src/web/authorized.js, gsa/src/web/components/bar/__tests__/titlebar.js, gsa/src/web/components/bar/menubar.js, gsa/src/web/components/bar/titlebar.js, gsa/src/web/components/observer/sessionobserver.js, gsa/src/web/pages/login/loginpage.js, gsa/src/web/routes.js, gsa/src/web/store/usersettings/__tests__/actions.js, gsa/src/web/store/usersettings/__tests__/reducers.js, gsa/src/web/store/usersettings/__tests__/selectors.js, gsa/src/web/store/usersettings/actions.js, gsa/src/web/store/usersettings/reducers.js, gsa/src/web/store/usersettings/selectors.js
Put and use user login status from redux store. This ensures re-rendering components if the login status has changed.
**Checklist**:
=> User login status from redux store

CHANGELOG.md, gsa/src/web/pages/tasks/icons/scheduleicon.js
=> Fix scheduled task tooltip time format

CHANGELOG.md, gsad/src/gsad.c
Fixes https://github.com/greenbone/gsa/issues/1375
I don't have a dev environment, so please test it!
**Checklist**:
- [] Tests
=> Remove copyright from gsad version output

CHANGELOG.md, gsa/src/gmp/commands/users.js, gsa/src/web/pages/usersettings/dialog.js, gsa/src/web/pages/usersettings/usersettingspage.js
This will prevent a race condition when opening the EditDialog. Before this change, it was possible that the dialog opened before all settings (filters in particular) where loaded.
**Checklist**:
=> Disable EditIcon while loading filters (also fix loading filters)

CHANGELOG.md, gsa/src/web/pages/tasks/row.js
=> Fix showing the observer group name

CHANGELOG.md, gsa/src/web/entities/container.js
Of course resetting the timer id to undefined must be done after
clearing the timer.
**Checklist**:
- [] Tests
=> Fix clearing timer

CHANGELOG.md, gsa/src/web/pages/reports/detailspage.js
Use filter and entity from props and not from state. Also reload after
removing and adding the assets to update the listed hosts.
**Checklist**:
- [n/a] Tests
=> Fix adding and removing host assets

CHANGELOG.md, gsa/src/web/components/form/radio.js, gsa/src/web/components/powerfilter/solutiontypegroup.js
=> change checkboxes for solution types to radio buttons

CHANGELOG.md, gsa/src/gmp/models/__tests__/result.js, gsa/src/gmp/models/result.js, gsa/src/web/pages/results/detailspage.js, gsa/src/web/pages/results/row.js
=> Fix host links

CHANGELOG.md, gsa/src/web/pages/reports/detailspage.js
Ensure all filters and report formats are loaded at the report details
page not only the default row count.
**Checklist**:
- [] Tests
=> Load all entities at report details page

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/__snapshots__/solutiontypegroup.js.snap, gsa/src/web/components/powerfilter/__tests__/solutiontypegroup.js
=> Add test for solution type group

CHANGELOG.md, gsa/src/gmp/__tests__/parser.js, gsa/src/gmp/model.js, gsa/src/gmp/models/__tests__/alert.js, gsa/src/gmp/models/__tests__/reportformat.js, gsa/src/gmp/models/__tests__/task.js, gsa/src/gmp/models/testing.js, gsa/src/gmp/parser.js, gsa/src/web/pages/roles/component.js, gsa/src/web/pages/roles/dialog.js, gsa/src/web/pages/scanners/dialog.js, gsa/src/web/pages/targets/dialog.js
=> Model boolean parsing

CHANGELOG.md, gsa/po/gsa-de.po, gsa/src/web/pages/tasks/dashboard/statusdisplay.js, gsa/src/web/pages/tasks/trend.js
=> Fix some translation issues for tasks

CHANGELOG.md, gsa/package.json, gsa/src/gmp/commands/login.js, gsa/src/gmp/http/__tests__/rejection.js, gsa/src/gmp/http/__tests__/response.js, gsa/src/gmp/http/rejection.js, gsa/src/gmp/http/response.js, gsa/src/gmp/http/transform/__tests__/fastxml.js, gsa/src/gmp/http/transform/__tests__/xml.js, gsa/src/gmp/http/transform/fastxml.js, gsa/src/gmp/http/transform/x2js.js, gsa/src/gmp/http/transform/xml.js, gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter/__tests__/convert.js, gsa/src/gmp/models/filter/convert.js, gsa/src/gmp/models/nvt.js, gsa/src/gmp/models/report/parser.js, gsa/src/gmp/models/result.js, gsa/src/gmp/models/testing.js, gsa/src/gmp/parser.js, gsa/yarn.lock
Fix decoding of xml entities with fast-xml-parser
**Checklist**:
=> Fast xml parser encoding

CHANGELOG.md, gsa/src/web/components/form/__tests__/__snapshots__/radio.js.snap, gsa/src/web/components/form/__tests__/radio.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severitylevelsgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/severitylevelsgroup.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/trend.js.snap, gsa/src/web/pages/tasks/__tests__/trend.js
=> Add tests for severitylevelsgroup, radio and task trend

CHANGELOG.md, gsa/src/web/pages/scanconfigs/editdialog.js
Fix error introduced by 51d80a1e1d5aa12d6acc7e236b14b9b22f7e722d
**Checklist**:
=> Fix showing Scanner Preferences in EditScanConfigDialog

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/__snapshots__/applyoverridesgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/autofpgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/filterstringgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/firstresultgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/minqodgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/resultsperpagegroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/sortbygroup.js.snap, gsa/src/web/components/powerfilter/__tests__/applyoverridesgroup.js, gsa/src/web/components/powerfilter/__tests__/autofpgroup.js, gsa/src/web/components/powerfilter/__tests__/filterstringgroup.js, gsa/src/web/components/powerfilter/__tests__/firstresultgroup.js, gsa/src/web/components/powerfilter/__tests__/minqodgroup.js, gsa/src/web/components/powerfilter/__tests__/resultsperpagegroup.js, gsa/src/web/components/powerfilter/__tests__/sortbygroup.js
=> Add tests for filter groups

gsa/.storybook/config.js, gsa/src/stories/snackbar.js, gsa/src/web/components/snackbar/__tests__/__snapshots__/snackbar.js.snap, gsa/src/web/components/snackbar/__tests__/snackbar.js, gsa/src/web/components/snackbar/snackbar.js
=> Add snackbar component

gsa/src/web/pages/alerts/method.js
While this is a FIXME which will probably disappear in the future we should still keep the language in English.
=> Replace german "ist" with englisch "is" in a comment.

CHANGELOG.md, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js, gsa/src/web/components/link/certlink.js
=> Consolidate new refs from NVTs

CHANGELOG.md, gsa/src/gmp/commands/login.js, gsa/src/gmp/models/__tests__/login.js, gsa/src/gmp/models/login.js
timezone and i18n are not found in the response.data but response.meta, 
so login variables have to be stitched together from both those fields.
This solves several issues including non-workign user settings and the 
performance page.
**Checklist**:
- [ X ] Tests
=> Fix loading timezone and locale at login

CHANGELOG.md, gsa/src/web/pages/vulns/listpage.js
There is no vulnerability resource type for tags, so don't offer bulk 
tagging at vulns listpage.
**Checklist**:
=> Don't allow tagging vulnerabilities

CHANGELOG.md, gsa/src/web/entities/container.js
=> Fix "given type was invalid" error for saving filters

CHANGELOG.md, gsa/src/web/pages/portlists/dialog.js, gsa/src/web/pages/targets/dialog.js
If corresponding radio buttons are not checked, the FileFields belonging to them are disabled to prevent confusion.
**Checklist**:
=> Disable some FileFields

CHANGELOG.md, gsa/src/gmp/commands/permissions.js
=>  Fix sending related resources in permissions.create()

CHANGELOG.md, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js, gsa/src/web/components/link/certlink.js, gsa/src/web/pages/nvts/references.js
=> Allow dynamic ref types for NVT model

.circleci/config.yml, .clang-format, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_user.c
This adds clang-format checks to CircleCI for the C code, similar to the other modules.
**Checklist**:
- [] Tests N/A
- [] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry N/A
=> Add C source format CircleCI check

CHANGELOG.md, gsa/src/gmp/commands/__tests__/auth.js, gsa/src/gmp/commands/__tests__/convert.js, gsa/src/gmp/commands/__tests__/user.js, gsa/src/gmp/commands/auth.js, gsa/src/gmp/commands/convert.js, gsa/src/gmp/commands/testing.js, gsa/src/gmp/commands/users.js, gsa/src/gmp/models/__tests__/settings.js, gsa/src/gmp/models/settings.js, gsa/src/web/pages/ldap/__tests__/dialog.js, gsa/src/web/pages/ldap/dialog.js, gsa/src/web/pages/ldap/ldappage.js, gsa/src/web/pages/radius/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/radius/__tests__/dialog.js, gsa/src/web/pages/radius/dialog.js, gsa/src/web/pages/radius/radiuspage.js, gsa/src/web/pages/users/dialog.js
Update code paths for LDAP and Radius configurations.
References #1339 
**Checklist**:
=> LDAP and Radius improvements

CHANGELOG.md, gsa/src/gmp/commands/__tests__/nvtfamilies.js, gsa/src/gmp/commands/nvtfamilies.js, gsa/src/gmp/commands/scanconfigs.js, gsa/src/gmp/gmp.js, gsa/src/web/pages/scanconfigs/component.js, gsa/src/web/pages/scanconfigs/editdialog.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp.h
Get rid of cmd=edit_config
**Checklist**:
=> Drop edit config command

CHANGELOG.md, gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter/__tests__/filterterm.js, gsa/src/gmp/models/filter/filterterm.js, gsa/src/web/components/powerfilter/__tests__/filterstringgroup.js
Amended FilterTerm to change all filter keywords to lowercase.
**Checklist**:
=> all filter strings to lower case

CHANGELOG.md, gsa/src/gmp/commands/__tests__/results.js, gsa/src/gmp/commands/results.js, gsa/src/web/pages/notes/dialog.js
Needs https://github.com/greenbone/gvmd/pull/603 to work.
With this PR, notes and overrides are shown on results detailspages and an icon indicator is present in the rows on results listpage and report results lists.
**Checklist**:
- [ X ] Tests
=> Show Notes and Overrides of Results

CHANGELOG.md, gsa/src/web/components/chart/bar.js
modified y-domain to avoid range [0,0]. The previous version had y-domain [0,0] with default data.
**Checklist**:
- [] Tests
=> modified y-domain to avoid range [0,0]

CHANGELOG.md, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp.h
This adds the commands create_tls_certificate, delete_tls_certificate,
get_tls_certificate, get_tls_certificates and save_tls_certificate
to gsad.
**Checklist**:
- Tests N/A
=> Add tls_certificate commands to gsad

gsad/src/gsad.c, gsad/src/gsad_gmp.c
This makes it possible to create configs and tasks to be used as
compliance policies and audits.
**Checklist**:
- N/A Tests
=> Add usage_type for configs and tasks.

CHANGELOG.md, gsad/src/gsad_gmp.c
For consistency with other asset types, TLS certificates will no longer
use the trashcan in upcoming gvmd changes.
**Checklist**:
- N/A Tests
=> Remove gsad trash case for tls_certificates

cmake/FindYarn.cmake
Debian Buster ships with a yarn package that's compatible with gsa but it's executable name is `yarnpkg`
**Checklist**:
- [] Tests - N/A
- [] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry - N/A
=> Add Buster yarn package executable

CHANGELOG.md, gsad/src/gsad_gmp.c
This allows viewing only tasks and configs of a certain usage_type.
**Checklist**:
- Tests N/A
=> Add usage_type to get_tasks and get_configs

cmake/FindPythonModule.cmake, gsa/po/CMakeLists.txt
**Fixes (missing: PY_POLIB) error on build time.**
Actual behavior:
```
-- Could NOT find PY_polib (missing: PY_POLIB) 
CMake Warning at gsa/po/CMakeLists.txt:108 (message):
Could not build translation files: Python interpreter or polib Python
module not found.
```
Expected behavior:
`-- Found polib: /usr/lib64/python3.6/site-packages/polib.py (found version "1.1.0")`
After fix:
`-- Found polib: /usr/lib64/python3.6/site-packages/polib.py (found version "1.1.0")`
I tried to push gsa-8.0 branch but messed it up, sorry :)
Old PR https://github.com/greenbone/gsa/pull/1482
=> Find python modules correctly

CHANGELOG.md, cmake/FindPythonModule.cmake, gsa/po/CMakeLists.txt
Backport #1483 for gsa-8.0
**Checklist**:
- [n/a] Tests
=> Find python module

CHANGELOG.md, gsa/src/web/components/form/__tests__/__snapshots__/multiselect.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/select.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/selectelement.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/timezoneselect.js.snap, gsa/src/web/components/form/multiselect.js, gsa/src/web/components/form/selectelements.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/relationselector.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severityvaluesgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/sortbygroup.js.snap, gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/createdialog.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/editdialog.js.snap, gsa/src/web/pages/tickets/createdialog.js
**Checklist**:
And updated snapshots.
- [] Tests
=> added grow option to multiselect

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/__snapshots__/booleanfiltergroup.js.snap, gsa/src/web/components/powerfilter/__tests__/booleanfiltergroup.js, gsa/src/web/components/powerfilter/booleanfiltergroup.js, gsa/src/web/pages/notes/filterdialog.js, gsa/src/web/pages/reports/detailsfilterdialog.js, gsa/src/web/pages/reports/filterdialog.js, gsa/src/web/pages/results/filterdialog.js, gsa/src/web/pages/tasks/filterdialog.js
=> added BooleanFilterGroup and changed notes filter dialog

CHANGELOG.md, gsa/src/web/pages/reports/detailsfilterdialog.js, gsa/src/web/pages/reports/filterdialog.js, gsa/src/web/pages/vulns/filterdialog.js
=> modified filterdialogs for reports and vulnerabilities

CHANGELOG.md, gsa/package.json, gsa/src/web/components/form/__tests__/__snapshots__/multiselect.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/select.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/selectelement.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/timezoneselect.js.snap, gsa/src/web/components/form/__tests__/select.js, gsa/src/web/components/form/__tests__/selectelement.js, gsa/src/web/components/form/multiselect.js, gsa/src/web/components/form/select.js, gsa/src/web/components/form/selectelements.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/relationselector.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severityvaluesgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/sortbygroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/ticketstatusgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/relationselector.js, gsa/src/web/components/powerfilter/__tests__/severityvaluesgroup.js, gsa/src/web/components/powerfilter/__tests__/ticketstatusgroup.js, gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/createdialog.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/editdialog.js.snap, gsa/yarn.lock
=> Select components fixes

gsa/src/web/pages/performance/startendtimeselection.js
fixed issue where the StartEndTimeSelection component was not setting state from props.
**Checklist**:
- [] Tests
=> fixed datepicker state not being set properly

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/__snapshots__/tasktrendgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/tasktrendgroup.js, gsa/src/web/components/powerfilter/tasktrendgroup.js, gsa/src/web/pages/overrides/filterdialog.js, gsa/src/web/pages/tasks/filterdialog.js
- Changed the filter dialogues for tasks and overrides
- added tasktrendgroup component.
**Checklist**:
=> Changed the filter dialogues for tasks and overrides

CHANGELOG.md, gsa/src/web/pages/login/__tests__/loginpage.js, gsa/src/web/pages/login/loginpage.js
Redirect to main page if the user is already logged in when visiting the
login page instead of clearing his token.
**Checklist**:
=> Don't logout user at login page

CHANGELOG.md, gsa/src/web/pages/tasks/details.js
This concerns max_checks and max_hosts, which were parsed to another
field in the task model
**Checklist**:
- [n/a] Tests
=> Show correct information at task details

CHANGELOG.md, gsad/src/gsad.c
The login/login.html url doesn't exists anymore. It still works because
/login<*> will show the login js page but actually the old page doesn't
exist anymore.
Always redirect to the root location now. The js code is responsible for
showing the login page now.
**Checklist**:
- [n/a] Tests
=> Fix redirect from http to https

CHANGELOG.md, gsa/src/web/pages/schedules/dialog.js
- Added a "now" button to help users jump to current date
- Added year dropdown in case users deal with timeframes far from now, to avoid excessive clicking.
- Changed some titles to hopefully make explicit to the user values they're changing
**Checklist**:
- [] Tests
=> modified edit schedule dialog to avoid start date in the past

gsa/src/web/pages/reports/hoststable.js
While ``authentification`` is correct according to e.g. https://english.stackexchange.com/questions/7844/is-authentification-a-real-word or https://en.wiktionary.org/wiki/authentification rename the word to ``authentication`` to keep / use the same wording like in the documentation:
https://docs.greenbone.net/GSM-Manual/gos-4/en/search.html?q=authentication
Note that even some spellcheckers like the build-in of Firefox is also directly reporting a spelling error for ``authentification``.
Replacement for #1520
**Checklist**:
- [] Tests
=> Change authentification to authentication.

gsa/src/web/entities/withEntitiesContainer.js
The evaluation of the meaning of isLoading is done in the EntitiesPage
component. Therefore pass it from the store directly to down the
component tree.
**Checklist**:
- [] Tests
=> Pass isLoading value directly to list pages

CHANGELOG.md, gsa/src/gmp/models/__tests__/event.js, gsa/src/gmp/models/event.js
Fix calculating the next date of a schedule ical event. ical times are evil :imp: 
**Checklist**:
=> Ical date recurrence fix

CHANGELOG.md, gsa/src/web/components/form/__tests__/__snapshots__/multiselect.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/select.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/timezoneselect.js.snap, gsa/src/web/components/form/multiselect.js, gsa/src/web/components/form/select.js, gsa/src/web/components/layout/withLayout.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/sortbygroup.js.snap, gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/createdialog.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/editdialog.js.snap
=> (Multi)Select clickable area

CHANGELOG.md, gsa/src/web/pages/tasks/row.js
=> Fix showing SensorIcon for GMP Scanner tasks

gsa/src/web/pages/scanners/component.js, gsa/src/web/pages/scanners/listpage.js
Show a dialog in case of success of scanner verification. Also, in case of failure, show the correct error message (when there is one) instead of "Unknown Error". I moved handleVerifyFailure out of handleVerifyScanner because I was planning some sort of handleVerifySuccess before. If that is not necessary I can put it back in.
**Checklist**:
- [] Tests
=> dialog confirmation for verifying scanners

CHANGELOG.md, gsa/src/web/pages/reports/detailspage.js
=> Default report filter and sorting

gsa/package.json, gsa/yarn.lock
lint-staged depends on the execa package in version 2 which requires
node in version >= 8.12 (https://github.com/sindresorhus/execa/pull/319).
Because we only need lint-stage for git hooks we should not require this
node version.
**Checklist**:
- [] Tests
=> Downgrade lint-staged to latest 8 release to not require node >= 8.12

CHANGELOG.md, gsa/src/web/pages/tasks/dialog.js
=> Fix "once" option for schedules in TaskDialog

cmake/FindYarn.cmake
On Debian >= Buster yarn is now shipped but the binary is called "yarnpkg" instead of "yarn":
https://packages.debian.org/buster/all/yarnpkg/filelist
**Checklist**:
- [] Tests
=> Search for "yarnpkg" in FindYarn.cmake

CHANGELOG.md, gsa/src/web/pages/reports/operatingsystemstable.js
=> Fix table column title for Operating Systems table of Reports

CHANGELOG.md, gsa/src/web/pages/tasks/dialog.js
=> added tooltips for settings that cant be edited once task has been run

gsad/src/gsad_http_handler.c
Bigger svg images are put into static/media now. It seems this has
changed in create-react-app some day.
**Checklist**:
- [] Tests
=> Also ship all files from static/media via gsad

CHANGELOG.md, gsa/src/gmp/__tests__/parser.js, gsa/src/gmp/parser.js
I changed all SINGLE_INSTANCES to SINGLE_INSTANCE including in tests. Looked at the backend response and the auth term is SINGLE_INSTANCE.
**Checklist**:
- [] Tests
=> CVSS Base Score v2 Calculator 

CHANGELOG.md, gsa/src/web/pages/hosts/component.js, gsa/src/web/pages/hosts/listpage.js, gsa/src/web/pages/targets/component.js
=> Fix bulk-create-target from hosts

CHANGELOG.md, gsa/src/web/pages/reports/alertactions.js
=> trigger alert button disabled in report details page when no permission

CHANGELOG.md, gsa/src/web/pages/scanconfigs/editdialog.js
Adding loading indicator to spin for 500ms before dialog content is rendered.
**Checklist**:
- [] Tests
=> added loading indicator to edit config dialog

CHANGELOG.md, gsa/CMakeLists.txt, gsa/src/gmp/capabilities/capabilities.js, gsa/src/gmp/models/report/report.js, gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap, gsa/src/web/components/layout/__tests__/__snapshots__/globalstyles.js.snap, gsa/src/web/pages/permissions/multipledialog.js, gsa/src/web/pages/tags/component.js, gsa/src/web/pages/tlscertificates/details.js, gsa/src/web/pages/tlscertificates/detailspage.js, gsa/src/web/pages/tlscertificates/row.js, gsa/src/web/pages/tlscertificates/table.js, gsa/src/web/routes.js
=> Extend TLS Certificate Assets

gsa/src/web/entity/withEntityContainer.js
In tests it is currently not possible to set the id of the entity to be
rendered. This commit extends withEntityComponent to allow overriding
the id of the entity to be loaded.
=> Allow to override id prop for Details pages

CHANGELOG.md, gsa/src/gmp/models/__tests__/scanconfig.js, gsa/src/gmp/models/scanconfig.js
=> Add parseTrend() function to ScanConfig model

CHANGELOG.md, gsa/src/web/components/layout/__tests__/__snapshots__/globalstyles.js.snap, gsa/src/web/pages/policies/__tests__/__snapshots__/details.js.snap, gsa/src/web/pages/policies/__tests__/__snapshots__/detailspage.js.snap, gsa/src/web/pages/policies/__tests__/details.js, gsa/src/web/pages/policies/__tests__/detailspage.js, gsa/src/web/pages/policies/detailspage.js, gsa/src/web/pages/scanconfigs/detailspage.js
=> Improve policy detailspage and add tests for policy detailspage and details

CHANGELOG.md, gsad/src/gsad.c, gsad/src/gsad_gmp.c
This allows getting the certificate file of TLS certificate assets
without requesting the full details including the sources.
**Checklist**:
- [] Tests
=> Add include_certificate_data to gsad

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/__snapshots__/ticketstatusgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/ticketstatusgroup.js, gsa/src/web/components/powerfilter/ticketstatusgroup.js
Changed select value from status integers to status strings. I'm not completely sure about the "Fix Verified". The other values are single words and can be used without double quotes, but "Fix Verified" absolutely needs it.
**Checklist**:
Changed
=>  ticketstatusgroup updated with new filter strings

CHANGELOG.md, gsad/src/gsad_http.c, gsad/src/gsad_http.h, gsad/src/gsad_http_handler.c
Fix #1601 and use js to handle nearly all urls now.
=> Update invalid url handling

CHANGELOG.md, gsa/src/web/pages/extras/trashcanpage.js
Change the EmptyTrashButton to use LoadingButton instead, so users will have feedback when they empty the trashcan.
**Checklist**:
- [] Tests
=> Added a loading timer for empty trash button

CHANGELOG.md, gsa/src/web/components/dialog/__tests__/__snapshots__/twobuttonfooter.js.snap, gsa/src/web/components/dialog/__tests__/twobuttonfooter.js, gsa/src/web/components/dialog/twobuttonfooter.js, gsa/src/web/pages/reports/alertactions.js, gsa/src/web/pages/reports/detailspage.js
=> Loading indication for content composers

CHANGELOG.md, gsa/src/web/entities/withEntitiesContainer.js, gsa/src/web/pages/audits/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/audits/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/audits/__tests__/listpage.js, gsa/src/web/pages/audits/__tests__/table.js, gsa/src/web/pages/audits/listpage.js, gsa/src/web/pages/policies/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/policies/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/policies/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/policies/__tests__/dialog.js, gsa/src/web/pages/policies/__tests__/listpage.js, gsa/src/web/pages/policies/__tests__/table.js, gsa/src/web/pages/policies/listpage.js
=> Add tests for tables and listpages for policies and audits

CHANGELOG.md, gsa/src/web/entities/container.js, gsa/src/web/entity/container.js, gsa/src/web/pages/reports/detailspage.js
Add a function that handles setting the default reload interval to less
or equal to 0 to disable the reloading of entities. Update load and
getReloadInterval methods to stop loading if the calculated reload
interval is less or equal to 0.
**Checklist**:
- [n/a] Tests
=> Allow to disable reload timer

CHANGELOG.md, gsa/src/web/components/bar/__tests__/__snapshots__/progressbar.js.snap, gsa/src/web/components/bar/__tests__/__snapshots__/severitybar.js.snap, gsa/src/web/components/bar/__tests__/progressbar.js, gsa/src/web/components/bar/__tests__/severitybar.js, gsa/src/web/components/bar/__tests__/statusbar.js, gsa/src/web/components/bar/progressbar.js, gsa/src/web/components/bar/statusbar.js, gsa/src/web/utils/theme.js
=> Fix statusbar content can be more than 100 percent

CHANGELOG.md, gsa/src/gmp/commands/__tests__/feedstatus.js, gsa/src/gmp/commands/feedstatus.js
=> Fix feed status command

CHANGELOG.md, gsa/src/gmp/commands/reports.js, gsad/src/gsad_gmp.c
Adjust gsa to send details=1 for get_report and change gsad to forward details to gvmd.
**Checklist**:
- [] Tests
=> send details=1 for get_report

CHANGELOG.md, gsa/src/web/pages/audits/component.js
Use the uuid of the greenbone compliance report format in GOS 6 to check if the format is available. This means that using an imported version of the format will not work anymore, only the standard that is available in GOS 6 is supported.
**Checklist**:
- [] Tests
=> Use uuid to get greenbone compliance report format

CHANGELOG.md, gsa/src/web/pages/secinfo/listpage.js, gsa/src/web/pages/vulns/listpage.js
=> Adjust gmpname vulnerability and secinfo

CHANGELOG.md, gsa/src/gmp/models/filter.js, gsa/src/web/entities/__tests__/filterprovider.js, gsa/src/web/entities/filterprovider.js
Handle errors safely
**Checklist**:
=> Filterprovider improvements

CHANGELOG.md, gsa/src/gmp/models/__tests__/schedule.js, gsa/src/gmp/models/schedule.js, gsa/src/web/pages/schedules/details.js, gsa/src/web/pages/schedules/row.js
=> Schedule improvements

CHANGELOG.md, gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap, gsa/src/web/entity/permissions.js, gsa/src/web/pages/permissions/multipledialog.js
=> Fixed userId, roleId and groupId not rendering in create entity permissions dialog

gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js
When requesting nvts via get_info the response element contains an
additional info element e.g. <get_info_reponse><info><nvt>. Also add
tests to ensure that these nvts are parsed correctly.
**Checklist**:
=> Fix parsing nvt models from info responses

CHANGELOG.md, gsa/src/web/pages/tasks/dialog.js
Summary of changes:
- moved handleScannerChange out of ScannerSelect
- Refactored ScannerSelect into function
- Added state variables configType and prevConfigType, and calculate/update them in handleScannerChange, and upon onScanConfigChange.
Expected behavior:
- Changing between scanners of the same config type should not change displayed scan config selection
- Edit dialog should show correct scan config
- Scan config should default to "Full and Fast" when 1. creating a new task 2. changing configType from something else TO openvas config type.
**Checklist**:
- [] Tests
=> Decide whether to default to full and fast scan config (task dialog)

CHANGELOG.md, gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter.js, gsa/src/gmp/utils/identity.js, gsa/src/web/pages/reports/detailspage.js
Avoid and fix several issues with filter being null now.
**Checklist**:
=> Fix comparing filters

gsa/src/web/pages/reports/listpage.js
Sort the list of reports by newest descending.
=> Set a fallback filter for the report list page

gsa/src/gmp/commands/__tests__/nvt.js, gsa/src/gmp/commands/nvt.js
Merge gsa-8.0 into gsa-9.0 and fix getting a config nvt for the scan config dialog.
**Checklist**:
=> Merge gsa-8.0 into gsa-9.0

CHANGELOG.md, gsa/src/gmp/__tests__/gmpsettings.js, gsa/src/gmp/gmpsettings.js, gsa/src/web/app.js
=> Gmp store logging

CHANGELOG.md
The level of the heading was wrong and also the url for the diff.
=> Fix changelog entry for next 9.0 release

CHANGELOG.md, gsa/src/gmp/commands/reports.js, gsa/src/web/pages/reports/detailscontent.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/reportentitiescontainer.js, gsa/src/web/pages/reports/resultstab.js, gsa/src/web/pages/reports/scaninfo.js, gsa/src/web/store/entities/__tests__/reports.js, gsa/src/web/store/entities/reports.js, gsad/src/gsad_gmp.c
=> Load "small" before "full" report

CHANGELOG.md, gsa/src/web/pages/reports/detailspage.js
=> Fix setting user default filter in report results

CHANGELOG.md, gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter.js, gsa/src/web/components/powerfilter/filterdialog.js
=> Filter dialog does not duplicate filter term

.circleci/config.yml
It seems clang-format is formatting the code very differently with newer
versions. It doesn't make sense to run a check without being able to
format the code automatically.
=> Don't run c code format check on circleci

CHANGELOG.md, gsa/src/web/components/bar/__tests__/__snapshots__/titlebar.js.snap, gsa/src/web/components/bar/menubar.js, gsa/src/web/components/menu/__tests__/__snapshots__/usermenu.js.snap, gsa/src/web/components/menu/usermenu.js
Instead of the inner Divider component the click handler is now set to the menu Entry itself.
The empty menu section is removed, when the user doesn't have the correct permissions in the Administration menu
**Checklist**:
=> Increase clickable area for Logout / Adjust menubar

CHANGELOG.md, gsa/src/gmp/models/event.js, gsa/src/web/components/chart/schedule.js, gsa/src/web/pages/tasks/dashboard/schedulesdisplay.js
=> Next Scheduled Tasks now displays timezone
