gsa/src/gmp/commands/__tests__/http.js, gsa/src/gmp/commands/entities.js, gsa/src/gmp/commands/entity.js, gsa/src/gmp/commands/gmp.js, gsa/src/gmp/commands/hosts.js, gsa/src/gmp/commands/http.js, gsa/src/gmp/commands/infoentities.js, gsa/src/gmp/commands/infoentity.js, gsa/src/gmp/commands/notes.js, gsa/src/gmp/commands/os.js, gsa/src/gmp/commands/overrides.js
Refactor adding parameters for http commands.
=> Http command params

CHANGELOG.md, gsa/src/web/pages/audits/__tests__/__snapshots__/details.js.snap, gsa/src/web/pages/audits/__tests__/__snapshots__/detailspage.js.snap, gsa/src/web/pages/audits/__tests__/details.js, gsa/src/web/pages/audits/__tests__/detailspage.js, gsa/src/web/pages/audits/details.js, gsa/src/web/pages/audits/detailspage.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tasks/detailspage.js
=> Improve audit detailspage and add tests for audit details and detailspage

gsa/src/gmp/commands/__tests__/tlscertificates.js, gsa/src/gmp/commands/tlscertificates.js
=> Add tests for TLS certificate asset commands

gsa/src/web/components/form/filefield.js
=> Refactored filefield into function component

CHANGELOG.md, gsa/src/web/components/dashboard/display/datadisplay.js
=> Enable downloading csv in table dashboard

gsa/src/web/components/form/radio.js
=> Added change methods to radio component (no more withChangeHandler HOC)

gsa/src/web/components/label/__tests__/__snapshots__/severityclass.js.snap, gsa/src/web/components/label/severityclass.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severitylevelsgroup.js.snap
=> Increase SeverityClassLabel width to accomodate German translation

CHANGELOG.md, gsa/src/gmp/commands/__tests__/reports.js, gsa/src/gmp/commands/reports.js
=> Report list loading without details

CHANGELOG.md, gsa/src/gmp/commands/__tests__/results.js, gsa/src/gmp/commands/results.js
=> Param order

gsad/src/gsad_gmp.c
=> Gsad get reports fixes

CHANGELOG.md, gsa/src/gmp/commands/__tests__/reports.js, gsa/src/gmp/commands/__tests__/results.js, gsa/src/gmp/commands/reports.js, gsa/src/gmp/commands/results.js, gsa/src/web/components/dashboard/display/datadisplay.js, gsa/src/web/components/dialog/__tests__/__snapshots__/twobuttonfooter.js.snap, gsa/src/web/components/dialog/__tests__/twobuttonfooter.js, gsa/src/web/components/dialog/twobuttonfooter.js, gsa/src/web/components/label/__tests__/__snapshots__/severityclass.js.snap, gsa/src/web/components/label/severityclass.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severitylevelsgroup.js.snap, gsa/src/web/pages/extras/trashcanpage.js, gsa/src/web/pages/reports/alertactions.js, gsa/src/web/pages/reports/detailspage.js, gsad/doc/gsad.8
=> Merge gsa 8 into master

gsa/src/web/components/form/__tests__/__snapshots__/checkbox.js.snap, gsa/src/web/components/form/checkbox.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/autofpgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/createnamedfiltergroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severitylevelsgroup.js.snap, gsa/src/web/pages/ldap/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/radius/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/editconfigfamilydialog.js.snap, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/editdialog.js.snap
=> Added change methods to CheckboxComponent

CHANGELOG.md, gsa/po/gsa-de.po, gsa/src/web/components/icon/foldstateicon.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/tasktrendgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/tasktrendgroup.js, gsa/src/web/components/powerfilter/tasktrendgroup.js, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/editdialog.js.snap, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tlscertificates/detailspage.js, gsa/src/web/pages/tlscertificates/row.js
=> Update German Translation

CHANGELOG.md, gsa/src/gmp/commands/__tests__/user.js, gsa/src/gmp/commands/users.js, gsa/src/web/pages/filters/component.js, gsa/src/web/pages/tlscertificates/listpage.js, gsa/src/web/pages/usersettings/dialog.js, gsa/src/web/pages/usersettings/filterpart.js, gsa/src/web/pages/usersettings/usersettingspage.js
Needs https://github.com/greenbone/gvmd/pull/750 to work
**Checklist**:
=> Introduce TLS certificate filter type and default filter to GSA

gsa/src/web/components/tab/tabs.js, gsa/src/web/pages/hosts/identifiers.js
=>  Refactored Tabs, Identifiers components to not use componentWillReceiveProps

gsa/src/gmp/models/__tests__/scanconfig.js, gsa/src/gmp/models/scanconfig.js
=> Fix scanconfig families trend

CHANGELOG.md, gsa/src/web/pages/usersettings/generalpart.js
Also added notification when new passwords are entered but old one isn't.
**Checklist**:
- [] Tests
=> Added text notification when old password is entered but new password isn't

gsa/src/web/components/form/field.js
A quick fix to pass props.value to the displayed value of Field when props.value changes.
**Checklist**:
- [] Tests
=> Added useEffect to watch for props.value change in Field component

gsa/src/web/entity/container.js, gsa/src/web/pages/scanners/detailspage.js
=> Trigger alert on verify scanner on detailspage

CHANGELOG.md, gsa/src/gmp/commands/reports.js
=> Fix report download

CHANGELOG.md, gsa/src/gmp/commands/__tests__/report.js, gsa/src/gmp/commands/reports.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c
Requires https://github.com/greenbone/gvmd/pull/745
**Checklist**:
- [] Tests
=> Lean report

gsa/src/web/components/dashboard/dashboard.js
=> Extracted error.message from error object for dashboard

gsa/src/web/components/form/field.js
=> Update value proptype of Field component

CHANGELOG.md, gsa/src/web/pages/audits/component.js, gsa/src/web/pages/audits/row.js
=> Audit improvements

CHANGELOG.md, gsa/src/web/pages/users/dialog.js
=> Fixed auth_method preselection for user dialog

CHANGELOG.md, gsa/src/gmp/commands/alerts.js, gsa/src/gmp/commands/trashcan.js, gsa/src/gmp/commands/wizard.js
=> Fix things about model changes

CHANGELOG.md, gsa/src/gmp/commands/alerts.js, gsa/src/gmp/commands/trashcan.js, gsa/src/gmp/commands/wizard.js
=> Merge gsa8 into gsa9

gsa/src/web/components/badge/badge.js, gsa/src/web/components/menu/usermenu.js
=> Refactor components into function

gsa/src/web/components/powerfilter/__tests__/__snapshots__/filterstringgroup.js.snap, gsa/src/web/components/powerfilter/filterstringgroup.js
=> Long filter strings not cut off in filter dialog

gsad/src/gsad_gmp.c
Replaces https://github.com/greenbone/gsa/pull/1669
Rebased against gsa-9.0 and fixed the formatting issue with running `clang-format -i -style=file gsad/src/gsad_gmp.c`
=> Saberlynx osp sensor bug

gsa/src/gmp/commands/__tests__/scanconfig.js, gsa/src/gmp/commands/scanconfigs.js
Fix scan config command for gsa 8
**Checklist**:
=> Fix editing scan config nvt

CHANGELOG.md, gsa/src/gmp/models/__tests__/tlscertificate.js, gsa/src/gmp/models/tlscertificate.js, gsa/src/web/pages/tlscertificates/detailspage.js, gsa/src/web/pages/tlscertificates/filterdialog.js, gsa/src/web/pages/tlscertificates/row.js, gsa/src/web/pages/tlscertificates/table.js
=> Improve TlsCertificates

gsa/src/web/pages/page.js
=> Remount ErrorBoundary on path change

gsa/src/gmp/model.js
=> Empty user comment fix

gsa/src/web/components/form/select.js
=> Added close method to Select ArrowIcon

gsa/src/web/pages/tasks/row.js
=> Sensor Icon for Greenbone Sensor in listpage

gsa/src/web/components/form/__tests__/__snapshots__/select.js.snap, gsa/src/web/components/form/__tests__/__snapshots__/timezoneselect.js.snap, gsa/src/web/components/form/select.js, gsa/src/web/components/powerfilter/__tests__/__snapshots__/relationselector.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severityvaluesgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/sortbygroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/tasktrendgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/ticketstatusgroup.js.snap, gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap, gsa/src/web/pages/audits/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/policies/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/editdialog.js.snap, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/createdialog.js.snap, gsa/src/web/pages/tickets/__tests__/__snapshots__/editdialog.js.snap
This should enable clicking the select box to open/close. Lots of snapshot updates.
**Checklist**:
- [] Tests
=> Enable open/close behavior in Select box

CHANGELOG.md, CMakeLists.txt
Try to get a version related code as close as possible.
=> Update version in CMakeLists.txt

gsa/src/web/components/dialog/confirmationdialog.js, gsa/src/web/components/form/datepicker.js, gsa/src/web/components/form/spinner.js
=> More hooks

CHANGELOG.md, gsa/src/gmp/models/report/host.js, gsa/src/web/components/dashboard/display/utils.js, gsa/src/web/components/powerfilter/filtersearchgroup.js, gsa/src/web/pages/credentials/dialog.js, gsa/src/web/pages/results/diff.js, gsa/src/web/pages/schedules/render.js, gsa/src/web/pages/tasks/dashboard/statusdisplay.js, gsa/src/web/pages/tickets/dashboard/statusdisplay.js, gsa/src/web/pages/tlscertificates/dashboard/timestatusdisplay.js, gsa/src/web/store/index.js
=> Fix IE11 with importing polyfills

CHANGELOG.md, gsa/src/web/pages/audits/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/policies/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/tlscertificates/component.js
=> Fix TLS certificate download

gsa/src/web/pages/permissions/dialog.js
The command modify_report is being removed with
https://github.com/greenbone/gvmd/pull/823
**Checklist**:
- [] Tests N/A
- [] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry N/A
=> Remove entry for modify_report.

gsad/src/gsad_gmp.c
=> Allow empty credential_id when modifying to Greenbone Sensor

CHANGELOG.md, gsa/src/web/entities/filterprovider.js, gsa/src/web/entities/withEntitiesContainer.js, gsa/src/web/pages/reports/detailspage.js
=> Improve filter handling in report detailspage

CHANGELOG.md, gsa/src/web/components/chart/bar.js
=> Adjust BarChart labeling

CHANGELOG.md, gsa/src/web/components/form/select.js
=> Select scrolls to last selected item

CHANGELOG.md, gsa/src/web/pages/certbund/listpage.js, gsa/src/web/pages/cpes/listpage.js, gsa/src/web/pages/cves/listpage.js, gsa/src/web/pages/dfncert/listpage.js, gsa/src/web/pages/nvts/listpage.js, gsa/src/web/pages/ovaldefs/listpage.js, gsa/src/web/pages/secinfo/listpage.js
=> Change SecInfo sorting to more meaningful columns

CHANGELOG.md, gsa/src/web/components/bar/menubar.js, gsa/src/web/pages/ldap/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/ldap/dialog.js, gsa/src/web/pages/ldap/ldappage.js, gsa/src/web/pages/radius/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/radius/dialog.js, gsa/src/web/pages/radius/radiuspage.js
=> RADIUS and LDAP page tweaks

CHANGELOG.md, gsa/src/gmp/commands/reports.js
=> Fix get delta report needs to send details=1

CHANGELOG.md, gsa/src/gmp/commands/__tests__/user.js, gsa/src/gmp/commands/users.js
=> Allow change to/from LDAP and RADIUS 

CHANGELOG.md, gsa/src/web/pages/results/row.js, gsa/src/web/pages/results/table.js
=> Fix "created" column for results

CHANGELOG.md, gsa/src/web/pages/overrides/dashboard/activedaysdisplay.js
=> No override negative days

CHANGELOG.md, gsa/src/gmp/models/note.js
=> No note negative days 

CHANGELOG.md, gsa/src/web/pages/reports/hoststable.js
=> Fix High column in hosts table of reports

CHANGELOG.md, gsa/src/gmp/commands/reports.js
Include results in a report download by setting details=1
**Checklist**:
- [] Tests
=> Fix empty report download

CHANGELOG.md, gsa/src/gmp/commands/reports.js
Backport of #1724 
**Checklist**:
- [] Tests
=> Fix details of delta reports

CHANGELOG.md, gsa/src/web/pages/reports/downloadreportdialog.js
=> Don't simplify filter in report content composer

CHANGELOG.md, gsa/src/web/components/dialog/__tests__/__snapshots__/multistepfooter.js.snap, gsa/src/web/components/dialog/__tests__/multistepfooter.js, gsa/src/web/components/dialog/multistepfooter.js, gsa/src/web/components/dialog/savedialog.js, gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap, gsa/src/web/components/layout/__tests__/__snapshots__/globalstyles.js.snap, gsa/src/web/pages/scanners/dialog.js
Summary of Changes: 
- Added a MultiStepFooter with previous/next buttons
- Changed SaveDialog to be able to use MultiStepFooter. multiStep is by default false. Added step change method.
- Changed ScannerDialog to multiStep = true, and put form fields in different tabs.
**Checklist**:
=> Multistep dialog feature, implemented on scanner dialog

CHANGELOG.md, gsa/package.json, gsa/yarn.lock
=> Fix react-scripts dependency in order to fix tooltips

CHANGELOG.md, gsa/src/gmp/__tests__/gmpsettings.js, gsa/src/gmp/gmpsettings.js, gsa/src/web/components/loading/__tests__/reload.js, gsa/src/web/components/loading/reload.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/listpage.js, gsa/src/web/pages/tasks/detailspage.js, gsa/src/web/pages/tasks/listpage.js
=> Merge gsa 8 into 9

CHANGELOG.md, gsa/src/web/pages/scanners/component.js
=> Pass port number to scanner dialog

CHANGELOG.md, gsa/src/web/pages/scanconfigs/editdialog.js
=> Fix trend and select values in scanconfig editdialog reset after every rerender

gsa/src/gmp/__tests__/gmpsettings.js, gsa/src/gmp/gmpsettings.js, gsa/src/gmp/http/http.js
All defaults for settings should be specified and applied at
gmpsettings.
**Checklist**:
=> Move DEFAULT_TIMEOUT to gmpsettings

CHANGELOG.md, gsa/src/gmp/commands/__tests__/task.js, gsa/src/gmp/commands/tasks.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/containerdialog.js.snap, gsa/src/web/pages/tasks/__tests__/containerdialog.js, gsa/src/web/pages/tasks/containerdialog.js
=> Remove auto delete field from container task dialog

CHANGELOG.md, gsa/src/gmp/commands/__tests__/policy.js, gsa/src/gmp/commands/policies.js, gsa/src/gmp/models/scanconfig.js, gsa/src/web/pages/scanconfigs/__tests__/dialog.js, gsa/src/web/pages/scanconfigs/dialog.js
=> Add base config to create scan config dialog and make it new default

.github/ISSUE_TEMPLATE/issue-report.md
See https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
for details.
=> Convert issue template into new format

CHANGELOG.md, gsa/src/gmp/model.js
=> Single space summary no longer breaks view

CHANGELOG.md, gsa/src/web/components/dashboard/display/status/statusdisplay.js, gsa/src/web/pages/tlscertificates/dashboard/timestatusdisplay.js, gsa/src/web/pages/tlscertificates/table.js
=> TLS Cert Filtering

CHANGELOG.md, gsa/src/web/pages/results/detailspage.js
=> Changed new override dialog defaults

CHANGELOG.md, gsa/src/gmp/model.js, gsa/src/web/components/layout/__tests__/__snapshots__/globalstyles.js.snap, gsa/src/web/entity/permissions.js, gsa/src/web/entity/tags.js, gsa/src/web/pages/extras/__tests__/cvsscalculatorpage.js, gsa/src/web/pages/extras/cvsscalculatorpage.js, gsa/src/web/pages/permissions/dialog.js, gsa/src/web/pages/results/details.js, gsa/src/web/pages/results/detailspage.js
=> Merge GSA-8 into GSA-9

CHANGELOG.md, gsa/src/web/pages/results/listpage.js
Delete comment and fix typo
**Checklist**:
- [] Tests
=> Small fixes

CHANGELOG.md, gsa/src/web/pages/audits/dialog.js
=> Fix undefined policy in create audit dialog

CHANGELOG.md, gsa/src/gmp/models/report/parser.js, gsa/src/web/pages/reports/details/closedcvestable.js
=> Closed cve fixes

gsa/src/web/pages/users/dialog.js
=> Fix user auth method preselection

CHANGELOG.md, gsad/src/gsad_gmp.c
Requires https://github.com/greenbone/gvm-libs/pull/305.
**Checklist**:
- [] Tests
=> Use read_string_c for the XML get_report case (9.0)

gsad/src/gsad_credentials.c
=> Unify return style (9.0)

gsa/src/web/pages/reports/details/__tests__/applicationstab.js, gsa/src/web/pages/reports/details/__tests__/closedcvestab.js, gsa/src/web/pages/reports/details/__tests__/cvestab.js, gsa/src/web/pages/reports/details/__tests__/errorstab.js, gsa/src/web/pages/reports/details/__tests__/hoststab.js, gsa/src/web/pages/reports/details/__tests__/operatingsystemstab.js, gsa/src/web/pages/reports/details/__tests__/portstab.js, gsa/src/web/pages/reports/details/__tests__/tlscertificatestab.js
Add tests for the different tabs on the report detailspage.
**Checklist**:
=> Report Details Tabs Tests

CHANGELOG.md, gsa/po/gsa-de.po, gsa/src/web/pages/reports/details/__tests__/emptyreport.js, gsa/src/web/pages/reports/details/__tests__/emptyresultsreport.js, gsa/src/web/pages/reports/details/__tests__/thresholdpanel.js, gsa/src/web/pages/reports/details/emptyresultsreport.js, gsa/src/web/pages/reports/details/thresholdpanel.js
=> Update text for empty results report and threshold panel

gsa/src/web/pages/reports/__tests__/deltadetailscontent.js, gsa/src/web/pages/reports/__tests__/detailscontent.js, gsa/src/web/pages/reports/details/__tests__/deltaresultstab.js, gsa/src/web/pages/reports/details/__tests__/hoststab.js
=> Tests for report details content and delta details content

CHANGELOG.md, gsa/src/gmp/commands/overrides.js
=> Fix override new severity being invalid

gsa/src/web/components/sortable/emptyrow.js, gsa/src/web/components/sortable/grid.js, gsa/src/web/components/sortable/item.js, gsa/src/web/components/sortable/resizer.js, gsa/src/web/components/sortable/row.js, gsa/src/web/pages/start/__tests__/page.js, gsa/src/web/pages/tasks/__tests__/listpage.js
=> Tests for Startpage and Task Detailspage

CHANGELOG.md, gsa/src/web/entity/link.js
=> Fix showing resource as orphaned when it's not

CHANGELOG.md, gsa/src/web/entity/link.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/listpage.js.snap
=> Fix broken entity links for reportformat, scanconfig and portlist

CHANGELOG.md, gsa/src/web/pages/results/details.js
=> Made delta report diffs more explicit

CHANGELOG.md, gsa/src/gmp/models/__tests__/dfncert.js, gsa/src/gmp/models/dfncert.js
=> Fix parsing DFN-Cert VCE entries

CHANGELOG.md, gsa/src/gmp/commands/__tests__/entities.js, gsa/src/gmp/commands/entities.js
=> Fix deleteById() returning response

CHANGELOG.md, gsa/src/gmp/models/__tests__/audit.js, gsa/src/gmp/models/__tests__/task.js, gsa/src/gmp/models/audit.js, gsa/src/gmp/models/task.js
=> Fix auto_delete_value of 0 set by wizard

CHANGELOG.md, gsa/src/web/pages/help/about.js
=> Adjust About page text

CHANGELOG.md, gsa/src/web/pages/nvts/__tests__/row.js, gsa/src/web/pages/nvts/row.js
Change filter after click on nvt family links to show nvts of the selected family.
**Checklist**:
=> Fix nvt family links

gsa/src/gmp/commands/dashboards.js, gsa/src/gmp/models/event.js, gsa/src/web/components/dashboard/utils.js, gsa/src/web/components/sortable/grid.js, gsa/src/web/pages/start/page.js
https://github.com/uuidjs/uuid/blob/master/README.md#deep-requires-now-deprecated
**Checklist**:
- [N/A] Tests
=> Fix deprecation warning for uuid about deep requires

CHANGELOG.md, gsa/src/web/components/processmap/__mocks__/mockprocessmap.js, gsa/src/web/components/processmap/__tests__/processmap.js, gsa/src/web/components/processmap/__tests__/processpanel.js, gsa/src/web/pages/processmaps/__tests__/processmapspage.js
Move mockprocessmap to separate file to keep tests from running multiple times.
**Checklist**:
=> move mockprocessmap to separate file

CHANGELOG.md, gsa/src/web/components/processmap/processmap.js, gsa/src/web/components/processmap/processpanel.js
This PR includes:
* adding hostnames to host selection in ProcessPanel
* error dialog when invalid characters are in ProcessName and hosts should be added
* Fixing jumping processes when zoom and dragging are both appllied
**Checklist**:
- [N/A] Tests
=> Advance BPM

CHANGELOG.md, gsa/src/gmp/models/report/parser.js, gsa/src/web/pages/reports/__mocks__/mockdeltareport.js, gsa/src/web/pages/reports/__mocks__/mockreport.js
=> Fix Report details hosts tab counts flickering

gsa/src/web/entity/icon/__tests__/observericon.js, gsa/src/web/entity/info.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/details.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/row.js.snap, gsa/src/web/pages/tasks/__tests__/actions.js, gsa/src/web/pages/tasks/__tests__/details.js, gsa/src/web/pages/tasks/__tests__/row.js, gsa/src/web/pages/tasks/__tests__/status.js, gsa/src/web/pages/tasks/__tests__/table.js, gsa/src/web/pages/tasks/actions.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tasks/graphql.js, gsa/src/web/pages/tasks/listpage.js, gsa/src/web/pages/tasks/status.js, gsa/src/web/utils/graphql.js
So far all test cases are fixed except detailspage
**Checklist**:
=> Update task-related tests and refactor task-related components

gsa/src/web/components/date/datetime.js, gsa/src/web/components/menu/usermenu.js, gsa/src/web/utils/__tests__/useUserIsLoggedIn.js, gsa/src/web/utils/__tests__/useUserName.js, gsa/src/web/utils/__tests__/useUserSessionTimeout.js, gsa/src/web/utils/__tests__/useUserTimezone.js, gsa/src/web/utils/useUserIsLoggedIn.js, gsa/src/web/utils/useUserName.js, gsa/src/web/utils/useUserSessionTimeout.js, gsa/src/web/utils/useUserTimezone.js
=> Update usersettings hooks

CHANGELOG.md, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/credentials/dialog.js
=> Pass credential errors to dialog if opened from AlertDialog

CHANGELOG.md, gsa/src/gmp/models/__tests__/tlscertificate.js, gsa/src/gmp/models/tlscertificate.js
=> Unify source reports and hosts in TlsCertificatesModel (GSA-9)

CHANGELOG.md, gsa/src/web/pages/reports/details/__tests__/tlscertificatestab.js, gsa/src/web/pages/reports/details/tlscertificatestable.js
=> Adjust report TlsCertificate table headers to match new TLS assets

CHANGELOG.md, gsa/src/gmp/models/__tests__/tlscertificate.js, gsa/src/gmp/models/tlscertificate.js, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/credentials/dialog.js, gsa/src/web/pages/reports/details/__tests__/tlscertificatestab.js, gsa/src/web/pages/reports/details/tlscertificatestable.js
=> Merge GSA-9 into Master

gsa/src/web/utils/__tests__/useCapabilities.js, gsa/src/web/utils/useCapabilities.js
This will allow to receive the current user capabilties via a react
hook.
**Checklist**:
=> Add a useCapabilities react hook

CHANGELOG.md, gsa/src/web/pages/notes/dashboard/index.js
=> Adjust NOTES_DASHBOARD_ID

CHANGELOG.md, gsa/src/web/components/processmap/processmap.js, gsa/src/web/entity/icon/trashicon.js, gsa/src/web/pages/reports/__tests__/deltadetailscontent.js, gsa/src/web/pages/reports/__tests__/detailscontent.js, gsa/src/web/pages/reports/details/__tests__/closedcvestab.js, gsa/src/web/pages/reports/details/applicationstable.js, gsa/src/web/pages/reports/details/closedcvestable.js, gsa/src/web/pages/tlscertificates/component.js
afaics this fixes all warnings coming up during tests except "setting state on unmounted component" for SvgIcon and onActivate and isActive props on DOM elements.
**Checklist**:
=> Get rid of warnings in tests and components

gsa/src/web/pages/login/loginpage.js
I looked into testing this component, but think it might not be worth it just for this demonstration. Reason being, we don't want to deprecate gmp.login right away in prod, but in order for tests to pass we have to not test whether gmp.login was called (because it isn't). But I expect that once we're putting this in production we'll soon need gmp.login (and to test whether it was called) again.
**Checklist**:
=> Use hyperion with loginpage

gsa/src/web/entity/__tests__/block.js, gsa/src/web/entity/__tests__/box.js, gsa/src/web/entity/__tests__/info.js, gsa/src/web/entity/__tests__/link.js, gsa/src/web/entity/__tests__/note.js, gsa/src/web/entity/__tests__/override.js
=> Add some tests for entity components

gsa/src/gmp/models/schedule.js, gsa/src/web/components/link/detailslink.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tasks/detailspage.js, gsa/src/web/pages/tasks/graphql.js
Todo: Task permissions, ~~fix delete icon~~, ~~investigate start icon~~.
**Checklist**:
=> Enable detailspage without gsad

gsad/src/gsad.c
=> Update --version copyright

CHANGELOG.md, gsa/src/web/pages/operatingsystems/row.js
This adjusts the filter to match changes made in gvmd with greenbone/gvmd#1027
**Checklist**:
- [N/A] Tests
=> Adjust filter in OS row link

CHANGELOG.md, gsa/src/web/pages/operatingsystems/row.js
=> Merge GSA 8 into GSA 9

gsa/src/web/pages/login/__tests__/loginpage.js, gsa/src/web/pages/tasks/__mocks__/mocktasks.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/details.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/detailspage.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/row.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/tasks/__tests__/actions.js, gsa/src/web/pages/tasks/__tests__/details.js, gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/pages/tasks/__tests__/listpage.js, gsa/src/web/pages/tasks/__tests__/row.js, gsa/src/web/pages/tasks/__tests__/status.js, gsa/src/web/pages/tasks/__tests__/table.js, gsa/yarn.lock
Clean up tests in hyperion-gsa. Move mocks for tasks to a separate file and import them in all task component tests. Fix failing tests or alternatively skip them for now.
**Checklist**:
=> Clean up hyperion-gsa tests

gsa/src/gmp/__tests__/model.js, gsa/src/gmp/model.js, gsa/src/gmp/models/__tests__/scanner.js, gsa/src/gmp/models/__tests__/task.js, gsa/src/gmp/models/scanner.js, gsa/src/gmp/models/task.js, gsa/src/web/pages/tasks/__mocks__/mocktasks.js, gsa/src/web/pages/tasks/graphql.js
=> Update gsa to reflect hyperion api changes

gsa/src/gmp/commands/dashboards.js, gsa/src/web/components/dashboard/dashboard.js, gsa/src/web/pages/tasks/graphql.js, gsa/src/web/utils/useGetSettings.js
=> Task dashboards do not crash

CHANGELOG.md, gsa/src/web/pages/reports/details/toolbaricons.js
=> Fix message in TriggerAlertDialog

CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsa/public/locales/gsa-de.json, gsa/src/web/pages/help/about.js, gsad/CMakeLists.txt
=> Update for release change 20.04 -> 20.08

gsa/src/gmp/__tests__/gmp.js, gsa/src/gmp/commands/login.js, gsa/src/gmp/gmp.js, gsa/src/gmp/models/login.js, gsa/src/setupTests.js, gsa/src/web/pages/login/__tests__/__snapshots__/loginpage.js.snap, gsa/src/web/pages/login/__tests__/loginpage.js, gsa/src/web/pages/login/loginpage.js, gsa/src/web/utils/testing.js
Allow to login with gsad again and add more verbose error output if the hyperion authentication did fail.
**Checklist**:
=> Improve login and errors during login

gsa/src/web/app.js
Clear the redux store and remove possible gsad session token if hyperion's session has ended.
=> Auto logout

gsa/src/gmp/models/__tests__/task.js, gsa/src/gmp/models/task.js, gsa/src/web/components/dashboard/dashboard.js, gsa/src/web/components/link/detailslink.js, gsa/src/web/components/link/link.js, gsa/src/web/components/table/data.js, gsa/src/web/entities/actions.js, gsa/src/web/pages/audits/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/audits/__tests__/row.js, gsa/src/web/pages/tasks/__mocks__/mocktasks.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/row.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/status.js.snap, gsa/src/web/pages/tasks/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/tasks/__tests__/row.js, gsa/src/web/pages/tasks/__tests__/status.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tasks/detailspage.js, gsa/src/web/pages/tasks/graphql.js, gsa/src/web/pages/tasks/row.js, gsa/src/web/pages/tasks/status.js, gsa/src/web/utils/testing.js
=> Schema adjustments for counts

gsa/src/web/app.js, gsa/src/web/components/menu/__tests__/usermenu.js, gsa/src/web/components/menu/usermenu.js, gsa/src/web/routes.js
=> Check authentication status in routes and add logout mutation

gsa/src/web/components/form/useFormValidation.js, gsa/src/web/pages/tickets/createdialog.js, gsa/src/web/pages/tickets/editdialog.js
=> Improve form validation variable names

gsa/src/web/app.js, gsa/src/web/authorized.js, gsa/src/web/routes.js
Refactor 401 response handling for auto logout of current user.
=> Auto session logout

gsa/src/web/app.js, gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/graphql.js
Add a getScanners query and use it to load the scanners for the task dialogs.
**Checklist**:
=> Make scanners work with graph ql

gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/graphql.js
Add useGetScanConfigs and useGetTargets. Use them on the task page to load the corresponding entities for the task dialogs.
**Checklist**:
=> Add scanConfigs and targets to hyperion-gsa

gsa/src/web/pages/login/loginpage.js
Fix login case with active gsad.
=> Fix login with locale

gsa/src/web/components/menu/usermenu.js, gsa/src/web/utils/__tests__/useUserSessionTimeout.js, gsa/src/web/utils/useUserSessionTimeout.js
Hide implementation detail of extending the users session.
=> Refactor use user session timeout hook

gsa/src/web/app.js
=> Clear Apollo cache after logout

gsa/src/web/authorized.js, gsa/src/web/components/menu/usermenu.js, gsa/src/web/components/observer/__tests__/sessionobserver.js, gsa/src/web/components/observer/sessionobserver.js, gsa/src/web/graphql/auth.js, gsa/src/web/utils/testing.js
=> Session observer hyperion

CHANGELOG.md, gsa/src/web/components/link/__tests__/externallink.js, gsa/src/web/components/link/externallink.js, gsa/src/web/pages/help/about.js
- Adjust link to license text to lead to AGPL 3.0+
- Fix closing the dialog when clicking resume
**Checklist**:
=> Update license and link on AboutPage

gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/graphql.js
Requires backend changes.
**Checklist**:
=> Extend task mutation

gsa/src/web/pages/tasks/detailspage.js
=> Do not load entities if only hyperion is enabled

gsa/src/web/pages/tasks/details.js
=> Task details shows source interface

gsa/src/web/pages/tasks/component.js
Fix task edit dialog setting snake case names.
**Checklist**:
=> Change edit dialog inputs to hyperion names

gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/graphql.js
Requires backend pull request
**Checklist**:
=> Add all variables to create task mutation

CHANGELOG.md, CMakeLists.txt, gsa/package.json
=> Prepare Release 9.0.1

gsa/src/web/pages/tasks/graphql.js, gsa/src/web/utils/graphql.js
=> Convert task mutations to use input objects

gsa/src/web/entities/filterprovider.js, gsa/src/web/utils/__tests__/usePageFiler.js, gsa/src/web/utils/usePageFilter.js
=> Introduce a usePageFilter custom hook

gsa/src/web/entities/filterprovider.js, gsa/src/web/graphql/__mocks__/tasks.js, gsa/src/web/graphql/__tests__/tasks.js, gsa/src/web/graphql/tasks.js, gsa/src/web/store/dashboard/data/loader.js, gsa/src/web/utils/__tests__/usePageFiler.js, gsa/src/web/utils/usePageFilter.js
=> Refactor task queries

gsa/src/web/pages/credentials/component.js, gsa/src/web/pages/credentials/dialog.js, gsa/src/web/pages/ldap/ldappage.js, gsa/src/web/pages/performance/performancepage.js, gsa/src/web/pages/scanners/component.js, gsa/src/web/pages/scanners/dialog.js
=> Hyperion renew session #2

gsa/src/web/authorized.js
=> Renew session on refresh

gsa/src/gmp/model.js, gsa/src/gmp/models/task.js, gsa/src/web/pages/extras/trashcanpage.js, gsa/src/web/pages/tasks/row.js
=> Use gql renewSession for trashcan page and fix trashcan task parsing

CHANGELOG.md, gsa/CMakeLists.txt, gsa/src/web/components/processmap/__tests__/hosttable.js, gsa/src/web/components/processmap/__tests__/processmap.js, gsa/src/web/components/processmap/__tests__/processpanel.js, gsa/src/web/components/processmap/__tests__/resultstable.js, gsa/src/web/components/processmap/hosttable.js, gsa/src/web/components/processmap/processmap.js, gsa/src/web/components/processmap/processmaploader.js, gsa/src/web/components/processmap/processpanel.js, gsa/src/web/components/processmap/resultstable.js, gsa/src/web/pages/processmaps/__tests__/processmapspage.js
This PR adds new result information for each host that can be selected. It also adds a hostname column to the HostTable
**Checklist**:
=> Add Result information and hostnames to BPM

gsa/src/gmp/locale/lang.js, gsa/src/gmp/models/login.js
Set locale in setLocale to undefined if Browser Language is selected. This should ensure it is set correctly in one central place.
**Checklist**:
=> fix browser language not set at login

gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/graphql.js, gsa/src/web/utils/graphql.js
=> Task component refactor

gsa/src/web/pages/reports/detailspage.js
=> Use graphql renewSession with report details

gsa/src/web/pages/reports/details/alertactions.js, gsa/src/web/pages/results/detailspage.js, gsa/src/web/pages/usersettings/usersettingspage.js
=> Convert pages to use graphql renew session

gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter.js, gsa/src/web/entities/page.js, gsa/src/web/graphql/__mocks__/tasks.js, gsa/src/web/graphql/__tests__/tasks.js, gsa/src/web/graphql/tasks.js, gsa/src/web/pages/tasks/__tests__/listpage.js, gsa/src/web/pages/tasks/listpage.js
Requires a merged PR in the hyperion backend.
=> Support pagination in hyperion-gsa

CHANGELOG.md, CMakeLists.txt, gsa/src/gmp/models/__tests__/cpe.js, gsa/src/gmp/models/cpe.js, gsa/src/web/pages/policies/component.js, gsa/src/web/pages/reports/details/__tests__/applicationstab.js, gsa/src/web/pages/reports/details/__tests__/emptyreport.js, gsa/src/web/pages/reports/details/toolbaricons.js
=> merge gsa9 into master

gsa/src/web/__tests__/authorized.js, gsa/src/web/authorized.js, gsa/src/web/graphql/__mocks__/auth.js, gsa/src/web/graphql/__tests__/auth.js
=> Authorized error handling

gsa/src/web/graphql/__mocks__/auth.js, gsa/src/web/graphql/__mocks__/tasks.js, gsa/src/web/graphql/__tests__/auth.js, gsa/src/web/graphql/__tests__/tasks.js, gsa/src/web/graphql/auth.js, gsa/src/web/graphql/tasks.js, gsa/src/web/pages/login/__tests__/loginpage.js, gsa/src/web/pages/login/loginpage.js, gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/pages/tasks/detailspage.js, gsa/src/web/utils/graphql.js
=> Remove graphql helpers part 1

gsa/src/web/components/notification/withDialogNotifiaction.js
Allow to close dialogs opened via withDialogNotification.
=> Fix withDialogNotification

gsa/src/web/graphql/__mocks__/settings.js, gsa/src/web/graphql/__tests__/settings.js, gsa/src/web/graphql/settings.js
=> Refactor use get settings

gsa/src/web/graphql/__mocks__/tags.js, gsa/src/web/graphql/__tests__/tags.js, gsa/src/web/graphql/tags.js, gsa/src/web/pages/tags/component.js, gsa/src/web/pages/tasks/detailspage.js
Supports remove, create, edit and toggle tags.
**Checklist**:
=> GraphQL create and modify tag

gsa/src/web/graphql/scanconfigs.js, gsa/src/web/graphql/scanners.js, gsa/src/web/graphql/settings.js, gsa/src/web/graphql/targets.js, gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/dialog.js
=> Fix queries with filterstring

gsa/src/web/pages/tasks/dialog.js
=> Replace withCapabilities HOC with useCapabilities hook

gsa/src/web/pages/tasks/component.js
Remove possible error from last time when the dialog was opened.
**Checklist**:
=> Reset error when the task dialog is opened

gsa/src/web/components/loading/__tests__/useReload.js, gsa/src/web/components/loading/useReload.js, gsa/src/web/pages/tasks/listpage.js, gsa/src/web/utils/__tests__/useGmpSettings.js, gsa/src/web/utils/__tests__/useInstanceVariable.js, gsa/src/web/utils/__tests__/useTiming.js, gsa/src/web/utils/useGmpSettings.js, gsa/src/web/utils/useInstanceVariable.js, gsa/src/web/utils/useTiming.js
Implement reloading with graphql
**Checklist**:
=> Reload with graphql

gsa/src/web/pages/tasks/detailspage.js
Remove implementation for start task from task detailspage and use start and stop from task component instead.
**Checklist**:
=> use start and stop from task component for detailspage

gsa/src/web/graphql/__mocks__/targets.js, gsa/src/web/graphql/__tests__/targets.js, gsa/src/web/graphql/targets.js, gsa/src/web/pages/tasks/component.js
=> Update get targets

CHANGELOG.md, gsa/src/gmp/models/__tests__/host.js, gsa/src/gmp/models/host.js, gsa/src/web/pages/hosts/identifiers.js
=> Fix host identifier references

CHANGELOG.md, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js, gsa/src/web/pages/nvts/__tests__/row.js, gsa/src/web/pages/nvts/details.js, gsa/src/web/pages/nvts/row.js, gsa/src/web/pages/nvts/solution.js, gsa/src/web/pages/reports/__mocks__/mockdeltareport.js, gsa/src/web/pages/reports/__mocks__/mockreport.js, gsa/src/web/pages/reports/details/deltaresultstab.js, gsa/src/web/pages/results/details.js, gsa/src/web/pages/results/row.js
=> Unified nvt solution type

CHANGELOG.md, gsa/CMakeLists.txt
The json translation files need to be installed in the destination
directory via cmake.
**Checklist**:
=> Install json based translation files

gsa/src/web/pages/tasks/detailspage.js, gsa/src/web/pages/tasks/listpage.js
Add automatic reload to task detailspage similar to the reload on the listpage.
**Checklist**:
=> add automatic reload to task detailspage

gsa/src/web/graphql/__mocks__/scanners.js, gsa/src/web/graphql/__tests__/scanners.js, gsa/src/web/graphql/scanners.js, gsa/src/web/pages/tasks/component.js
=> Refactor useGetScanners

gsa/public/locales/gsa-de.json, gsa/src/web/components/processmap/processpanel.js
=> Fix a typo.

gsa/src/web/graphql/__mocks__/tasks.js, gsa/src/web/graphql/__tests__/tasks.js, gsa/src/web/graphql/tasks.js, gsa/src/web/pages/tasks/listpage.js
=> Rename graphql bulk delete queries

CHANGELOG.md, gsa/src/web/pages/overrides/component.js
=> Fix separating hosts in override dialog via comma

gsa/src/gmp/utils/__tests__/entitytype.js, gsa/src/gmp/utils/entitytype.js, gsa/src/web/entities/container.js
=> Merge GSA 9 into 20.08

CHANGELOG.md, gsa/src/gmp/models/__tests__/cve.js, gsa/src/gmp/models/cve.js, gsa/src/web/pages/cves/details.js
=> Merge9into20.08

CHANGELOG.md
Add a new changelog section for 21.04
**Checklist**:
=> add changelog section for 21.04

CHANGELOG.md, gsa/src/gmp/model.js
=> Remove unnecessary comment and summary parsing in Model

CHANGELOG.md, gsa/src/web/pages/hosts/dialog.js
=> Merge GSA-8.0 into GSA-9.0

CHANGELOG.md, gsa/src/web/pages/hosts/dialog.js
=> Merge GSA-9.0 in GSA-20.08

CHANGELOG.md, gsa/src/web/routes.js
=> Fix loading delta report detailspage

CHANGELOG.md, gsa/src/web/pages/extras/trashactions.js
=> Fixed report formats undeletable and unrestorable

CHANGELOG.md, gsa/src/web/pages/scanners/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/scanners/__tests__/dialog.js, gsa/src/web/pages/scanners/dialog.js
=> Remove multistep feature from scanner dialog

CHANGELOG.md, gsa/src/gmp/commands/wizard.js, gsa/src/gmp/models/__tests__/event.js, gsa/src/gmp/models/event.js, gsa/src/web/pages/schedules/details.js, gsa/src/web/wizard/modifytaskwizard.js
=> Merge 9 into 20.08

CHANGELOG.md, gsa/src/web/entity/icon/__tests__/editicon.js, gsa/src/web/entity/icon/editicon.js, gsa/src/web/pages/extras/feedstatuspage.js, gsa/src/web/pages/policies/detailspage.js, gsa/src/web/pages/policies/row.js, gsa/src/web/pages/portlists/detailspage.js, gsa/src/web/pages/portlists/row.js, gsa/src/web/pages/reportformats/detailspage.js, gsa/src/web/pages/reportformats/row.js, gsa/src/web/pages/scanconfigs/detailspage.js, gsa/src/web/pages/scanconfigs/row.js
This is to reflect https://github.com/greenbone/gvmd/pull/1196 in the GUI for the user.
**Checklist**:
=> Disable EditIcons for data objects from feed

CHANGELOG.md, gsa/src/web/pages/nvts/listpage.js
=> Default to sorting nvts by "Created", newest first

gsa/src/gmp/commands/__tests__/feedstatus.js, gsa/src/gmp/commands/feedstatus.js, gsa/src/web/pages/extras/feedstatuspage.js
=> Change case of currently_syncing

CHANGELOG.md, gsa/src/web/pages/reports/detailspage.js
=> Do not use result filter from store on report detailspage

CHANGELOG.md, gsa/src/gmp/models/report/__tests__/parser.js, gsa/src/gmp/models/report/parser.js
=> Fix flickering reports

gsad/doc/gsad.8, gsad/doc/gsad.8.xml, gsad/doc/gsad.html
Backport of #2369 to the gsa-9.0 branch.
=> [9.0] Updated references in docs / manpages.

gsa/src/gmp/gmpsettings.js
Both urls are not available yet but will be in future.
**Checklist**:
=> Update links to techdoc and gmp api for 20.08 release

CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsad/CMakeLists.txt
=> Prepare new release

CHANGELOG.md
=> Update Changelog for new unreleased release

gsa/package.json, gsa/src/web/entities/__tests__/filterprovider.js, gsa/src/web/pages/audits/__tests__/listpage.js, gsa/src/web/pages/extras/__tests__/cvsscalculatorpage.js, gsa/src/web/pages/help/__tests__/about.js, gsa/src/web/pages/policies/__tests__/listpage.js, gsa/src/web/pages/scanconfigs/__tests__/listpage.js, gsa/src/web/pages/start/__tests__/page.js, gsa/src/web/pages/tlscertificates/__tests__/listpage.js, gsa/src/web/utils/__tests__/usePageFiler.js, gsa/yarn.lock
=> Update to current react testing library

gsa/src/web/pages/tasks/details.js
**What**:
Refactor task details into function component
**Why**:
To support graphql
**How**:
The old tests are still passing.
**Checklist**:
=> Refactor task details into function component

CHANGELOG.md, gsa/src/gmp/models/credential.js, gsa/src/web/graphql/__mocks__/credentials.js, gsa/src/web/graphql/__tests__/credentials.js, gsa/src/web/graphql/credentials.js, gsa/src/web/pages/targets/component.js, gsa/src/web/pages/tasks/component.js
**What**:
Add get_credentials query and corresponding tests.
Use query to load credentials in task component.
Use query to load credentials in target component (because the task dialog can open the target dialog).
Adjusting the alert component will follow in another PR.
**Why**:
To adjust the task page to load everything via graphql.
**How**:
**Checklist**:
=> Load credentials with graphql

CHANGELOG.md, gsa/src/web/graphql/__mocks__/schedules.js, gsa/src/web/graphql/__mocks__/tasks.js, gsa/src/web/graphql/__tests__/schedules.js, gsa/src/web/graphql/schedules.js, gsa/src/web/pages/tasks/__mocks__/mocktasks.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/details.js.snap, gsa/src/web/pages/tasks/__tests__/details.js, gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/details.js
**What**:
This PR adds getSchedule and getSchedules via graphql to GSA
**Why**:
To use the new backend properly
**How**:
Infos are shown in the task details properly. Test suites pass.
**Checklist**:
=> Load schedules via graphQL

CHANGELOG.md, gsa/src/web/graphql/__mocks__/overrides.js, gsa/src/web/graphql/__tests__/overrides.js, gsa/src/web/graphql/overrides.js, gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/pages/tasks/detailspage.js
**What**:
This PR adds getOverrides via graphql to GSA
**Why**:
To use the new backend properly
**How**:
Number of available overrides is shown in the task toolbar icons properly. Test suites pass.
**Checklist**:
=> Add new getOverrides query

CHANGELOG.md, gsa/src/web/graphql/__mocks__/portlists.js, gsa/src/web/graphql/__tests__/portlists.js, gsa/src/web/graphql/portlists.js, gsa/src/web/pages/portlists/component.js, gsa/src/web/pages/portlists/detailspage.js, gsa/src/web/pages/targets/component.js, gsa/src/web/utils/__tests__/readFileToText.js, gsa/src/web/utils/readFileToText.js
**What**:
Also implemented a file reader component in case we need more of that in the future.
**Why**:
Because it is possible to create a port list from the target dialog, which is accessible from the task dialog.
**How**:
Test + manual test
**Checklist**:
=> Implement create and modify port list by graphql

CHANGELOG.md, gsa/src/web/components/form/useFormValidation.js
**What**:
Fix validating  the usersettings dialog.
**Why**:
The usersettings dialog crashes.
**How**:
Open the usersettings dialog, change rows per page, click on save.
**Checklist**:
=> Fix usersettings form validation

CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsa/public/locales/gsa-de.json, gsa/src/gmp/models/__tests__/tlscertificate.js, gsa/src/gmp/models/tlscertificate.js, gsa/src/web/components/form/useFormValidation.js, gsa/src/web/entities/__tests__/filterprovider.js, gsa/src/web/entities/filterprovider.js, gsa/src/web/pages/extras/__tests__/cvsscalculatorpage.js, gsa/src/web/pages/help/about.js, gsa/src/web/pages/usersettings/dialog.js, gsa/src/web/pages/usersettings/filterpart.js, gsa/yarn.lock, gsad/CMakeLists.txt
**What**:
**Why**:
**How**:
**Checklist**:
=> Merge 21.04 into master

CHANGELOG.md, gsa/src/web/components/form/__tests__/field.js, gsa/src/web/components/form/__tests__/textarea.js, gsa/src/web/components/form/field.js, gsa/src/web/components/form/textarea.js, gsa/src/web/components/form/textfield.js
**What**:
Regularly merge into master if there are changes to 21.04 or 20.08
**Why**:
**How**:
**Checklist**:
=> Merge gsa 21.04 into master

gsa/src/web/pages/alerts/__tests__/listpage.js, gsa/src/web/pages/alerts/listpage.js
**What**:
Add tests for alert listpage.
**Why**:
There are no tests for the alert listpage yet. Having tests will help us avoid mistakes when we do the refactoring for Hyperion.
**How**:
**Checklist**:
=> add tests for alert listpage

CHANGELOG.md, gsa/src/web/entities/__tests__/usePagination.js, gsa/src/web/entities/usePagination.js, gsa/src/web/graphql/__mocks__/alerts.js, gsa/src/web/graphql/__tests__/alerts.js, gsa/src/web/graphql/alerts.js, gsa/src/web/pages/alerts/listpage.js, gsa/src/web/pages/tasks/listpage.js
**What**:
Also added `usePagination` hook in order to declutter the listpage, and implemented as much listpage functionalities using hooks as possible. Next PR will probably bring the alerts listpage in line with task listpage.
**Why**:
**How**:
Manual and unit test
**Checklist**:
=> Implement clone, delete and test alert via graphql

gsa/src/web/pages/alerts/__tests__/detailspage.js, gsa/src/web/pages/alerts/detailspage.js
**What**:
Add tests for alert detailspage.
**Why**:
We need tests for the alerts detailspage before we can start the refactoring for Hyperion.
**How**:
**Checklist**:
=> add tests for alert detailspage

gsa/src/web/entities/__tests__/usePagination.js, gsa/src/web/entities/usePagination.js, gsa/src/web/pages/alerts/listpage.js, gsa/src/web/pages/tasks/listpage.js
**What**:
Make usePagination as default export.
**Why**:
**How**:
**Checklist**:
=> Export default usePagination

CHANGELOG.md, README.md, gsa/src/web/components/processmap/processmap.js, gsa/src/web/pages/alerts/dialog.js, gsa/src/web/pages/alerts/filtercountleastconditionpart.js, gsa/src/web/pages/hosts/detailspage.js, gsa/src/web/pages/portlists/component.js, gsa/src/web/pages/reports/deltadetailspage.js, gsad/src/gsad.c
**What**:
**Why**:
**How**:
**Checklist**:
=> Merge 20.08 into 21.04

CHANGELOG.md, gsa/src/web/components/form/useFormValidation.js
**What**:
**Why**:
**How**:
**Checklist**:
=> Merge gsa-20.08 into gsa-21.04

CHANGELOG.md, gsa/src/web/graphql/__mocks__/scanconfigs.js, gsa/src/web/graphql/__tests__/scanconfigs.js, gsa/src/web/graphql/scanconfigs.js, gsa/src/web/pages/scanconfigs/__tests__/detailspage.js, gsa/src/web/pages/scanconfigs/component.js
**What**:
**Why**:
**How**:
**Checklist**:
=> Implement create_scan_config, import_scan_config via graphql

gsa/src/web/pages/tags/component.js
**What**:
Modify tag was missing value variable.
**Why**:
**How**:
**Checklist**:
=> Fix modify tag

gsa/src/gmp/capabilities/capabilities.js, gsa/src/gmp/index.js, gsa/src/gmp/log.js, gsa/src/gmp/model.js, gsa/src/gmp/models/__tests__/cpe.js, gsa/src/gmp/models/filter.js, gsa/src/gmp/models/nvt.js, gsa/src/gmp/parser.js, gsa/src/gmp/utils/entitytype.js, gsa/src/web/components/sortable/item.js, gsa/src/web/pages/certbund/filterdialog.js, gsa/src/web/pages/certbund/table.js, gsa/src/web/pages/cpes/table.js, gsa/src/web/pages/cves/table.js, gsa/src/web/pages/dfncert/table.js, gsa/src/web/pages/ovaldefs/table.js, gsa/src/web/pages/overrides/table.js, gsa/src/web/pages/permissions/table.js, gsa/src/web/pages/policies/header.js, gsa/src/web/pages/portlists/filterdialog.js, gsa/src/web/pages/portlists/portrangestable.js, gsa/src/web/pages/portlists/table.js
**What**:
* Refactoring some code ...
**Why**:
* While digging through the sorting issue I found some code, that needs some freshness ...
**How**:
**Checklist**:
=> Refactoring some code

gsa/src/web/components/dialog/__tests__/error.js
**What**:
Add tests for DialogError
**Why**:
**How**:
**Checklist**:
=> Add tests for DialogError

CHANGELOG.md, gsa/public/locales/gsa-de.json, gsa/src/gmp/models/__tests__/user.js, gsa/src/gmp/models/user.js, gsa/src/web/components/dialog/__tests__/error.js, gsa/src/web/components/form/useFormValidation.js, gsa/src/web/pages/alerts/condition.js, gsa/src/web/pages/hosts/detailspage.js, gsa/src/web/pages/permissions/multipledialog.js, gsa/src/web/pages/users/detailspage.js, gsa/src/web/pages/users/row.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_http.h, gsad/src/gsad_http_handler.c, gsad/src/gsad_http_handler.h, gsad/src/gsad_params.h
**What**:
**Why**:
**How**:
**Checklist**:
=> Merge GSA-20.08 in GSA-21.04

CHANGELOG.md, gsa/package.json, gsa/public/locales/gsa-de.json, gsa/src/gmp/models/__tests__/user.js, gsa/src/gmp/models/user.js, gsa/src/web/components/dialog/__tests__/error.js, gsa/src/web/components/form/useFormValidation.js, gsa/src/web/pages/alerts/condition.js, gsa/src/web/pages/hosts/detailspage.js, gsa/src/web/pages/permissions/multipledialog.js, gsa/src/web/pages/users/detailspage.js, gsa/src/web/pages/users/row.js, gsa/yarn.lock, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_http.h, gsad/src/gsad_http_handler.c, gsad/src/gsad_http_handler.h, gsad/src/gsad_params.h
**What**:
**Why**:
**How**:
**Checklist**:
=> Merge GSA-21.04 in Master

gsa/src/web/pages/notes/__tests__/listpage.js, gsa/src/web/pages/notes/listpage.js
**What**:
Add notes listpage tests
**Why**:
There are none, yet.
**How**:
**Checklist**:
=> Add notes listpage tests

gsa/src/web/pages/overrides/__tests__/listpage.js, gsa/src/web/pages/overrides/listpage.js
**What**:
Add overrides listpage tests
**Why**:
There are none, yet
**How**:
**Checklist**:
=> Add overrides listpage tests

gsa/src/web/pages/notes/__tests__/detailspage.js, gsa/src/web/pages/notes/detailspage.js, gsa/src/web/pages/overrides/__tests__/detailspage.js, gsa/src/web/pages/overrides/detailspage.js
**What**:
Add tests for detailspages of notes and overrides
**Why**:
There are none, yet
**How**:
**Checklist**:
=> Notes and overrides detailspage tests

gsa/src/web/pages/cpes/__tests__/listpage.js, gsa/src/web/pages/cpes/listpage.js
**What**:
* Added tests for the CPE listpage.
**Why**:
* They were missing.
**How**:
**Checklist**:
=> Cpe listpage tests

CHANGELOG.md, gsa/src/web/graphql/__mocks__/schedules.js, gsa/src/web/graphql/__tests__/schedules.js, gsa/src/web/graphql/schedules.js, gsa/src/web/pages/schedules/__tests__/detailspage.js, gsa/src/web/pages/schedules/detailspage.js
**What**:
Convert schedule detailspage to use graphql and add some tests. Adjusted detailspage tests.
**Why**:
**How**:
**Checklist**:
=> Implement schedule detailspage queries and mutations

gsa/src/web/pages/hosts/__tests__/listpage.js, gsa/src/web/pages/hosts/listpage.js
**What**:
Add tests for host listpage.
**Why**:
There are no tests yet and we need them before we can start refactoring.
**How**:
**Checklist**:
=> Add tests for host listpage

gsa/src/web/pages/audits/details.js, gsa/src/web/pages/cpes/detailspage.js, gsa/src/web/pages/scanners/details.js, gsa/src/web/pages/tasks/__tests__/details.js, gsa/src/web/pages/tasks/details.js
**What**:
* Replacing the `dateTimeWithTimeZone()` with `<DateTime />` in the HTML.
* No additional tests, as the full tests for these pages will be implemented with the graphql updates anyways.
* (but tested locally)
* I don't think these changes are worth a Changelog entry, as I have not added an entry for such changes before ...
**Why**:
* Unifying the code
**How**:
**Checklist**:
=> Remove old date time format

gsa/src/web/pages/hosts/__tests__/detailspage.js, gsa/src/web/pages/hosts/detailspage.js
**What**:
Add tests for host detailspage.
**Why**:
There weren't any tests yet and we need them before we can start refactoring for Hyperion.
**How**:
**Checklist**:
=> Host detailspage test

gsa/.eslintrc.js, gsa/package.json, gsa/src/web/components/processmap/processpanel.js, gsa/src/web/pages/credentials/dialog.js, gsa/src/web/pages/reports/details/resultstab.js, gsa/yarn.lock
**What**:
Update to React version 17.0.1.
**Why**:
GSA was still using React 16.14.0.
**How**:
**Checklist**:
=> React 17.0.1 Update

gsa/package.json, gsa/yarn.lock
**What**:
Update to Apollo Client version 3.3.7.
**Why**:
GSA was still using version 3.2.4.
**How**:
**Checklist**:
=> Update to apollo client 3.3.7

CHANGELOG.md, gsa/package.json, gsa/public/locales/gsa-de.json, gsa/src/gmp/parser.js, gsa/src/web/components/structure/__tests__/__snapshots__/footer.js.snap, gsa/src/web/components/structure/__tests__/footer.js, gsa/src/web/components/structure/footer.js, gsa/src/web/pages/help/about.js, gsa/src/web/pages/login/__tests__/__snapshots__/loginform.js.snap, gsa/src/web/pages/login/__tests__/__snapshots__/loginpage.js.snap, gsa/src/web/pages/login/__tests__/loginpage.js, gsa/src/web/pages/login/loginform.js, gsa/src/web/pages/login/loginpage.js, gsa/src/web/pages/usersettings/usersettingspage.js, gsa/yarn.lock
**What**:
**Why**:
**How**:
**Checklist**:
=> Merge gsa21.04 into master

CHANGELOG.md, gsa/package.json
**What**:
**Why**:
**How**:
**Checklist**:
=> Drop Edge <=18 support from package.json for 21.04

gsa/package.json
**What**:
Fix version in master branch
**Why**:
Master will be 21.10. This will allow to differentiate between GSA 21.04
and 21.10.
**How**:
**Checklist**:
=> Fix version for master branch

CHANGELOG.md, gsa/src/web/pages/hosts/component.js
**What**:
Host component is a class component. Refactor it to be a function component instead.
**Why**:
This is needed to be able to use hooks.
**How**:
**Checklist**:
Checked gsa to make sure dialogs and other functions on the host listpage and detailspage still work.
=> refactor host component to function component

CHANGELOG.md, gsa/src/web/graphql/__mocks__/audits.js, gsa/src/web/graphql/__tests__/audits.js, gsa/src/web/graphql/audits.js, gsa/src/web/pages/audits/__tests__/detailspage.js, gsa/src/web/pages/audits/component.js, gsa/src/web/utils/testing/index.js
**What**:
**Why**:
**How**:
Manual and auto testing.
**Checklist**:
=> Implement audit component mutations

CHANGELOG.md, gsa/src/gmp/models/__tests__/host.js, gsa/src/gmp/models/host.js, gsa/src/web/graphql/__mocks__/hosts.js, gsa/src/web/graphql/__tests__/hosts.js, gsa/src/web/graphql/hosts.js, gsa/src/web/pages/hosts/__tests__/detailspage.js, gsa/src/web/pages/hosts/detailspage.js, gsa/src/web/pages/hosts/identifiers.js
**What**:
Refactor host detailspage to use graphql queries and mutations.
**Why**:
**How**:
**Checklist**:
=> Refactor host detailspage

CHANGELOG.md, gsa/src/gmp/utils/entitytype.js, gsa/src/web/graphql/__mocks__/hosts.js, gsa/src/web/graphql/__tests__/hosts.js, gsa/src/web/graphql/hosts.js, gsa/src/web/pages/hosts/__tests__/listpage.js, gsa/src/web/pages/hosts/listpage.js
**What**:
Refactor host listpage to use graphql query and mutations.
For now the host listpage still uses withEntitiesContainer because pagination does not work without it.
**Why**:
**How**:
**Checklist**:
=> Refactor host listpage

gsa/src/web/pages/reports/__mocks__/mockreport.js, gsa/src/web/pages/reports/details/__tests__/resultstab.js
**What**:
Add tests for the report results tab.
**Why**:
There are no tests for this component yet and we need them before we can start refactoring for Hyperion.
**How**:
**Checklist**:
=> add report results tab tests

CHANGELOG.md, gsa/src/gmp/models/note.js, gsa/src/gmp/utils/entitytype.js, gsa/src/web/graphql/__mocks__/notes.js, gsa/src/web/graphql/__tests__/notes.js, gsa/src/web/graphql/notes.js, gsa/src/web/pages/notes/__tests__/detailspage.js, gsa/src/web/pages/notes/__tests__/listpage.js, gsa/src/web/pages/notes/component.js, gsa/src/web/pages/notes/details.js, gsa/src/web/pages/notes/detailspage.js, gsa/src/web/pages/notes/listpage.js
**What**:
Implement graphql usage and tests for the notes entity.
**Why**:
To use it with the new architecture
**How**:
Automated tests
**Checklist**:
=> Use graphql for notes entity

gsa/public/locales/gsa-zh_TW.json
**What**:
**Why**:
Missing bracket.
**How**:
Add the right bracket.
**Checklist**:
=> Fix missing bracket

gsa/public/locales/gsa-zh_TW.json
**What**:
Fix missing left curly bracket.
**Why**:
Display string incorrectly.
**How**:
Additional missing left curly bracket
**Checklist**:
=> Fix missing left curly bracket

CHANGELOG.md, gsa/src/gmp/models/override.js, gsa/src/web/graphql/__mocks__/overrides.js, gsa/src/web/graphql/__tests__/overrides.js, gsa/src/web/graphql/overrides.js, gsa/src/web/pages/overrides/component.js
**What**:
Add mutations for the use with graphql, refactor overrides component, add tests
**Why**:
**How**:
**Checklist**:
=> Add overrides mutations

CHANGELOG.md, gsa/src/gmp/models/audit.js, gsa/src/gmp/utils/entitytype.js, gsa/src/web/graphql/__mocks__/audits.js, gsa/src/web/graphql/__tests__/audits.js, gsa/src/web/graphql/audits.js, gsa/src/web/pages/audits/__tests__/__snapshots__/detailspage.js.snap, gsa/src/web/pages/audits/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/audits/__tests__/actions.js, gsa/src/web/pages/audits/__tests__/listpage.js, gsa/src/web/pages/audits/__tests__/row.js, gsa/src/web/pages/audits/__tests__/table.js, gsa/src/web/pages/audits/actions.js, gsa/src/web/pages/audits/component.js, gsa/src/web/pages/audits/listpage.js, gsa/src/web/pages/audits/row.js, gsa/src/web/pages/tasks/status.js
**What**:
**Why**:
**How**:
**Checklist**:
=> Implement audit listpage queries and mutations

gsa/src/web/graphql/cpes.js, gsa/src/web/graphql/cves.js, gsa/src/web/graphql/hosts.js, gsa/src/web/graphql/permissions.js, gsa/src/web/graphql/policies.js, gsa/src/web/graphql/scanconfigs.js, gsa/src/web/pages/hosts/listpage.js, gsa/src/web/pages/policies/listpage.js, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/scanconfigs/listpage.js
**What**:
Update queries and pages to support pagination via graphql
**Why**:
Several queries didn't support pagination and some list pages still used GMP despite graphql was already implemented.
**How**:
Opened the pages and checked pagination via clicking on the first page, previous page, next page and last page buttons.
**Checklist**:
- n/a [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry
=> Fix graphql pagination

CHANGELOG.md, gsa/src/web/pages/credentials/__tests__/dialog.js, gsa/src/web/pages/credentials/dialog.js
**What**:
Refactor credential dialog into function component.
**Why**:
Because it was still a class component.
**How**:
Added tests.
**Checklist**:
=> Refactor credential dialog into function component and add tests

CHANGELOG.md, gsa/src/web/pages/login/loginform.js
**What**:
Move error message and adjust design on login page
**Why**:
To further unify the login page designs
**How**:
Visual inspection. Automatic tests are still passing.
**Checklist**:
- [N/A] Tests
=> Move error message and adjust design on login page

gsa/src/web/pages/targets/__tests__/detailspage.js, gsa/src/web/pages/targets/__tests__/listpage.js, gsa/src/web/pages/targets/detailspage.js, gsa/src/web/pages/targets/listpage.js
**What**:
Implement tests for target pages.
**Why**:
They are missing.
**How**:
**Checklist**:
=> Implement target listpage and detailspage tests

gsa/src/web/pages/results/__tests__/detailspage.js, gsa/src/web/pages/results/detailspage.js
**What**:
Add tests for results detailspage.
**Why**:
There are no tests for it yet and we need them before we can start refactoring.
**How**:
**Checklist**:
=> Result detailspage tests

CHANGELOG.md, gsa/src/gmp/models/__tests__/policy.js, gsa/src/gmp/models/__tests__/scanconfig.js, gsa/src/gmp/models/policy.js, gsa/src/gmp/models/scanconfig.js, gsa/src/web/graphql/__mocks__/audits.js, gsa/src/web/graphql/__mocks__/policies.js, gsa/src/web/graphql/__mocks__/scanconfigs.js, gsa/src/web/graphql/policies.js, gsa/src/web/graphql/scanconfigs.js
**What**:
* Apply Backend changes to ScanConfigs and Policies
* Update the tests, too
**Why**:
* Split of Preferences into NvtPreferences and ScannerPreferences in Backend, not in Frontend anymore
**How**:
**Checklist**:
=> Refactor the Queries of ScanConfigs and Policies, to match the Backend

CHANGELOG.md, gsa/src/web/pages/results/details.js
**What**:
* Change the HTML Tag of Detection Method to Preformatted, so it does not remove the newlines ...
**Why**:
* Was badly formatted before ...
**How**:
**Checklist**:
=> Change the HTML Tag of detection method to Preformatted

CHANGELOG.md, gsa/src/web/pages/nvts/__tests__/listpage.js, gsa/src/web/pages/nvts/__tests__/row.js, gsa/src/web/pages/nvts/listpage.js, gsa/src/web/pages/nvts/row.js
**What**:
* Refactor NVTs Listpage to use GraphQL
**Why**:
* Backend change
**How**:
**Checklist**:
=> Refactor NVTs Listpage to use GraphQL

CHANGELOG.md, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js, gsa/src/web/pages/nvts/details.js
**What**:
* Add severity Date to NVTs details:
* Will provide Tests in a seperate PR, for backporting.
* Will fix parseDate in a seperate PR
**Why**:
**How**:
**Checklist**:
=> Add Severity Date to NVTs Details

CHANGELOG.md, gsad/src/gsad_gmp.c
**What**:
**Why**:
**How**:
**Checklist**:
=> Merge gsa-21.04 into Master

CHANGELOG.md, gsa/src/web/pages/targets/component.js
**What**:
Refactors target component to use useReducer instead of the more outdated implementation with useState.
**Why**:
To make the target component more uniform with the other recent entities.
**How**:
Manual testing.
**Checklist**:
=> Refactor target component to use useReducer

CHANGELOG.md, gsa/src/gmp/models/__tests__/target.js, gsa/src/gmp/models/target.js, gsa/src/web/graphql/__mocks__/targets.js, gsa/src/web/graphql/__tests__/targets.js, gsa/src/web/graphql/targets.js, gsa/src/web/pages/targets/__tests__/detailspage.js, gsa/src/web/pages/targets/component.js, gsa/src/web/pages/targets/details.js, gsa/src/web/pages/targets/detailspage.js
**What**:
Implement target detailspage queries and mutations
**Why**:
Because it has not yet been converted. 
**How**:
Manual and unit tests.
**Checklist**:
=> Implement target detailspage queries and mutations

CHANGELOG.md, gsa/src/gmp/utils/__tests__/string.js, gsa/src/gmp/utils/string.js
**What**:
Adjust isEmpty to return true for null.
**Why**:
isEmpty was returning false for null which is not correct. Null should be handled the same way as undefined.
**How**:
**Checklist**:
=> Adjust isEmpty to return true for null

CHANGELOG.md, gsa/src/gmp/utils/entitytype.js, gsa/src/web/entity/icon/__tests__/observericon.js, gsa/src/web/graphql/__mocks__/targets.js, gsa/src/web/graphql/__tests__/targets.js, gsa/src/web/graphql/targets.js, gsa/src/web/pages/targets/__tests__/listpage.js, gsa/src/web/pages/targets/listpage.js, gsa/src/web/pages/targets/row.js
**What**:
Converts targets listpage to use graphql
**Why**:
Because it has not been converted yet
**How**:
Manual and unit testing.
**Checklist**:
=> Implement targets listpage queries and mutations

CHANGELOG.md, gsa/src/gmp/models/__tests__/certbund.js, gsa/src/gmp/models/__tests__/cpe.js, gsa/src/gmp/models/__tests__/cve.js, gsa/src/gmp/models/__tests__/dfncert.js, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/__tests__/ovaldef.js, gsa/src/gmp/models/certbund.js, gsa/src/gmp/models/cpe.js, gsa/src/gmp/models/cve.js, gsa/src/gmp/models/dfncert.js, gsa/src/gmp/models/nvt.js, gsa/src/gmp/models/ovaldef.js, gsa/src/web/pages/cves/__tests__/detailspage.js, gsa/src/web/pages/cves/__tests__/row.js
**What**:
* Revert the change from `severity` -> `score`
* It is a float value again
**Why**:
* Changes in Backend
**How**:
**Checklist**:
=> Revert the changes from severity to score.

gsa/src/web/graphql/targets.js, gsa/src/web/pages/targets/__tests__/listpage.js
**What**:
Add comment query and test for comment on targets listpage.
**Why**:
It was inadvertently missing before causing dialog or row to not show any comments.
**How**:
**Checklist**:
=> Query for comment on target listpage

CHANGELOG.md
**What**:
Add date to Changelog. All other files of interest (CMakeLists etc) seem to already have the 21.04 version in them.
**Why**:
To release the branch for 21.04.0
**How**:
**Checklist**:
- [N/A] Tests
=> Prepare new 21.04.0 release

CHANGELOG.md, gsa/src/gmp/utils/entitytype.js, gsa/src/web/graphql/__mocks__/overrides.js, gsa/src/web/graphql/__tests__/overrides.js, gsa/src/web/graphql/overrides.js, gsa/src/web/pages/overrides/__tests__/detailspage.js, gsa/src/web/pages/overrides/component.js, gsa/src/web/pages/overrides/details.js, gsa/src/web/pages/overrides/detailspage.js, gsa/src/web/pages/overrides/dialog.js
**What**:
Use graphql on the override detailspage
**Why**:
To adjust to hyperion
**How**:
**Checklist**:
=> Use GraphQL for overrides detailspage

CHANGELOG.md, gsa/src/web/pages/hosts/listpage.js, gsa/src/web/pages/operatingsystems/listpage.js, gsa/src/web/pages/vulns/listpage.js
**What**:
Added a default filter term to the listpages mentioned so they're sorted by descending seveirty (latest_severity for os)
**Why**:
**How**:
Visual verification.
**Checklist**:
=> Sort host, os and vulns listpage by descending severity

CHANGELOG.md, gsa/src/web/graphql/__mocks__/portlists.js, gsa/src/web/pages/portlists/component.js, gsa/src/web/pages/portlists/dialog.js, gsa/src/web/pages/portlists/portrangedialog.js
**What**:
Adjusts port list mutations to reflect backend changes.
**Why**:
The backend port list entity was refactored, making this PR necessary.
**How**:
Manual verification. Should be able to create and modify port lists via gui.
**Checklist**:
=> Adjust port list mutations to reflect changes in Hyperion

CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsa/src/web/pages/help/about.js, gsad/CMakeLists.txt
**What**:
Update version info for master branch
**Why**:
Hyperion will be releases "when it's ready"(tm).
**How**:
**Checklist**:
- n/a Tests
- n/a [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry
- n/a Labels for ports to other branches
=> Update versions for Hyperion development

CHANGELOG.md, gsa/src/gmp/commands/__tests__/audit.js, gsa/src/gmp/commands/__tests__/task.js, gsa/src/gmp/commands/audits.js, gsa/src/gmp/commands/tasks.js, gsa/src/gmp/models/__tests__/audit.js, gsa/src/gmp/models/__tests__/task.js, gsa/src/gmp/models/audit.js, gsa/src/gmp/models/task.js, gsa/src/web/pages/audits/component.js, gsa/src/web/pages/audits/details.js, gsa/src/web/pages/audits/dialog.js, gsa/src/web/pages/policies/component.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tasks/dialog.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c
**What**:
Remove network source interface from GSA for tasks and audits.
**Why**:
**How**:
Manual testing and adjust tests.
**Checklist**:
=> Remove Network Source Interface from GSA for Tasks and Audits

gsa/package.json, gsa/src/index.js, gsa/src/version.js, gsa/src/web/components/error/errorboundary.js, gsa/src/web/pages/help/about.js, gsa/yarn.lock
**What**:
Integrate sentry into gsa.
**Why**:
To log errors and make it easier to debug issues.
**How**:
**Checklist**:
=> integrate sentry

gsa/src/index.js
**What**:
Make sure sentry integration can handle missing config.js.
**Why**:
GSA was not accessible when config.js was missing because sentry initialization was trying to access it and got index.html instead.
**How**:
Tested manually on local gsa.
**Checklist**:
=> Fix sentry integration for missing config.js

.github/workflows/ci-c.yml, .github/workflows/ci-js.yml, gsa/package.json, gsa/yarn.lock, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp_auth.h, gsad/src/gsad_http.c, gsad/src/gsad_http_handler.c, gsad/src/gsad_session.c, gsad/src/gsad_user.c, gsad/src/gsad_user.h
**What**:
* Refactor the CircleCI Workflows into GitHub Action Workflows
**Why**:
**How**:
**Checklist**:
=> GitHub Action workflows

.github/workflows/ci-c.yml, .github/workflows/ci-js.yml, gsa/package.json, gsa/yarn.lock, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_http_handler.c, gsad/src/gsad_session.c, gsad/src/gsad_user.c, gsad/src/gsad_user.h
**What**:
**Why**:
**How**:
**Checklist**:
=> Remove CircleCI and add GitHub Actions to 21.04

.github/workflows/ci-c.yml, .github/workflows/ci-js.yml, gsa/package.json, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_http_handler.c, gsad/src/gsad_session.c, gsad/src/gsad_user.c, gsad/src/gsad_user.h
**What**:
**Why**:
**How**:
**Checklist**:
=> Remove CircleCI and add GitHub Actions to 21.10

gsa/src/gmp/commands/__tests__/target.js, gsa/src/gmp/commands/targets.js, gsa/src/web/pages/targets/__tests__/details.js, gsa/src/web/pages/targets/__tests__/dialog.js, gsa/src/web/pages/targets/dialog.js
**What**:
React tests for the changes here https://github.com/greenbone/gsa/pull/2954
**Why**:
**How**:
**Checklist**:
=> Add target dialog and ssh elevate credential related tests

.github/workflows/codeql-analysis-c.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add CodeScanning GitHub Action

.github/workflows/codeql-analysis.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Activate CodeScanning for all active branches

.github/workflows/codeql-analysis-c.yml, .github/workflows/codeql-analysis.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add CodeScan to gsa-20.08

.github/workflows/codeql-analysis-c.yml, .github/workflows/codeql-analysis.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add CodeScan to gsa-21.04

.github/workflows/codeql-analysis-c.yml, .github/workflows/codeql-analysis.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add CodeScan to gsa-21.10

CHANGELOG.md, gsa/public/locales/gsa-de.json, gsa/src/web/pages/targets/__tests__/row.js, gsa/src/web/pages/targets/row.js
**What**:
Show SSH Elevate credential on target listpage
**Why**:
**How**:
Manual and unit tests.
**Checklist**:
=> Added SSH Elevate credential to target row

gsa/src/web/pages/targets/__tests__/dialog.js, gsa/src/web/pages/targets/__tests__/row.js
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix copyright header for recently added target tests

gsad/src/gsad_base.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c
* Replace `localtime` with `localtime_r()`
**What**:
**Why**:
* `localtime()` has potential security leaks according to CodeQL
**How**:
**Checklist**:
=> Replace localtime with localtime_r

gsa/src/gmp/models/alert.js, gsa/src/web/pages/alerts/condition.js, gsa/src/web/pages/alerts/details.js, gsa/src/web/pages/alerts/method.js
**What**:
**Why**:
**How**:
Visually verified that alert listpage loads.
**Checklist**:
=> Prevent crash on alert listpage due to undefined subobjects 

gsad/src/gsad_gmp.c
**What**:
* Replace `gmtime` with `gmtime_r`
**Why**:
* potential security issue in `gmtime`
**How**:
**Checklist**:
=> Replace gmtime with gmtime_r

.github/workflows/ci-c.yml, CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsa/src/version.js, gsad/CMakeLists.txt
**What**:
**Why**:
**How**:
**Checklist**:
=> [release] [21.4.2] Prepare the Release

.github/workflows/ci-c.yml, CHANGELOG.md, CMakeLists.txt, INSTALL.md, README.md
**What**:
**Why**:
**How**:
**Checklist**:
=> [release] [20.8.2] Prepare the release

CHANGELOG.md
**What**:
**Why**:
**How**:
**Checklist**:
=> Update changelog after 21.4.1 release

CHANGELOG.md
**What**:
**Why**:
**How**:
**Checklist**:
=> Update CHANGELOG in master after releases

CHANGELOG.md
**What**:
**Why**:
**How**:
**Checklist**:
=> [21.10] Update CHANGELOG in master after releases

CHANGELOG.md, gsa/src/gmp/commands/users.js
**What**:
Remove BPM related commands
**Why**:
Left-overs from https://github.com/greenbone/gsa/pull/3051
**How**:
**Checklist**:
=> Remove BPM user commands

.docker/build/Dockerfile, .docker/testing/Dockerfile, .github/workflows/ci-c.yml, .github/workflows/ci-js.yml, .github/workflows/docker-ci.yml
* Add Docker images
* Add CI workflow for creating and uploading GSA docker images
* Adjust the images in the JS and C CI
**Checklist**:
=> [AP1504] Add Docker to 21.04.

.docker/build/Dockerfile, .docker/testing/Dockerfile, .github/workflows/ci-c.yml, .github/workflows/ci-js.yml, .github/workflows/docker-ci.yml
Add CI workflow for creating and uploading GSA docker images
Adjust the images in the JS and C CI
**Checklist**:
=> [AP1504] Add Docker to 20.08.

gsad/src/gsad_base.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c
=> Fix the CodeQL Code Security Issues for master (again)

CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsa/src/version.js, gsad/CMakeLists.txt
**What**:
**Why**:
**How**:
**Checklist**:
=> Prepare release 21.04.2

CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsa/src/version.js, gsad/CMakeLists.txt
**What**:
**Why**:
**How**:
**Checklist**:
=> Prepare release 20.8.3

CMakeLists.txt, gsa/CMakeLists.txt, gsad/CMakeLists.txt
**What**:
**Why**:
This is required after we changed this for the release
**How**:
**Checklist**:
=> Reset CMakeLists to dev version

CHANGELOG.md, CMakeLists.txt, gsa/CMakeLists.txt, gsa/package.json, gsa/src/version.js, gsad/CMakeLists.txt
**What**:
Set versions accordingly and add empty unreleased section to changelog
**Why**:
**How**:
**Checklist**:
=> Clean up after 20.08.3 release

gsad/config/gsad.service.in
**What**:
**Why**:
**How**:
**Checklist**:
=> Remove duplicated line from config

gsa/src/web/pages/credentials/__tests__/dialog.js, gsa/src/web/pages/schedules/__tests__/dialog.js
**What**:
Add tests for credential and schedule dialog.
**Why**:
They were only implemented for the hyperion branch and still missing in the other branches.
**How**:
**Checklist**:
=> Add tests for credential and schedule dialog

CHANGELOG.md, gsa/src/gmp/commands/users.js, gsa/src/gmp/models/__tests__/user.js, gsa/src/gmp/models/user.js, gsa/src/web/pages/users/component.js, gsa/src/web/pages/users/details.js, gsa/src/web/pages/users/dialog.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c
**What**:
Remove the parameters from GSA and gsad
**Why**:
Support is discontinued
**How**:
**Checklist**:
=> [AP1584][AP1608] Remove interface access of users

gsa/package.json
To make npm issues less likely with babel the indirect runtime
dependency is add explicitly.
**What**:
**Why**:
**How**:
**Checklist**:
=> Add @babel/runtime explicitely

gsa/src/gmp/locale/__tests__/languages.js
**What**:
Adjust the number of languages in the language tests.
**Why**:
After adding the Traditional Chinese language option the tests were failing because they had not been updated.
**How**:
**Checklist**:
=> Fix number of languages in tests

.docker/main.Dockerfile, .dockerignore, .github/workflows/container-pr.yml, .github/workflows/container.yml
**What**:
Build and upload container images for gsa main branch. AP-1751
**Why**:
**How**:
**Checklist**:
=> Container build

src/gmp/commands/__tests__/license.js, src/gmp/commands/license.js, src/web/pages/licenses/__tests__/licensepage.js, src/web/pages/licenses/licensepage.js
**What**:
Add a comment field to the license
**Why**:
It gives the users additional information and is provided by gvmd, so use it
**How**:
**Checklist**:
=> Add license comment

.docker/main.Dockerfile, .docker/stable.Dockerfile, .dockerignore, .github/workflows/container-pr.yml, .github/workflows/container.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> [stable] Add Dockerfiles and Workflow

src/gmp/commands/license.js, src/web/pages/licenses/__tests__/licensepage.js, src/web/pages/licenses/dialog.js, src/web/pages/licenses/licensepage.js
**What**:
Add the possibility to modify licenses
**Why**:
Expand the license feature
**How**:
Uploading a sample license file works without returning errors
**Checklist**:
=> Add modifyLicense() command and usage

src/web/pages/licenses/dialog.js, src/web/pages/licenses/licensepage.js, src/web/pages/page.js
**What**:
1. Don't show notification about license expiration
2. Fix displaying error messages for modifying licenses
3. Remove copy/paste text area for license information
**Why**:
1. This is not part of the basic functionality
2. proper error handling
3. This is too error prone to user input
**How**:
1. visual verification that it's gone
2. trying all variable combination on how to close the dialog and when the message shows up and when it doesn't
3. visual verification that it's gone
**Checklist**:
- [N/A] Tests
=> LicensePage miscellaneous (error handling, text area, notification)

src/web/pages/licenses/licensepage.js
**What**:
Fix license page reloading after uploading a license.
**Why**:
License page did not reload after uploading a license because state was not set correctly. Also fixed resetting the dialog error and file after uploading a license.
**How**:
Manual tests to ensure page reloads and dialog behaves correctly with different combinations of errors and successful uploads.
**Checklist**:
=> Fix license page reload

src/gmp/commands/license.js, src/web/pages/licenses/licensepage.js
**What**:
Change license command to use GMPCommand instead of HTTPCommand.
**Why**:
GMPCommand uses a different promise structure that can possibly fix the reload on the license page.
**How**:
**Checklist**:
=> Use GMPCommand for license command

.github/workflows/ci-js.yml, package.json
**What**:
* Use self-hosted runner set-up by @pascalholthaus for UnitTest CI
**Why**:
* Speed up the unittests
**How**:
* The self-hosted runner has more cores, so we can run more tests simultaniously.
**Checklist**:
=> Use self-hosted runner to speed up javascript unittests

.github/workflows/ci-js.yml, package.json
**What**:
Lower number of test workers to reduce memory consumption on our self hosted runners.
**Why**:
The memory consumption goes crazy otherwise.
**How**:
**Checklist**:
=> Adjust coverage tests

.github/workflows/ci-js.yml
**What**:
remove self-hosted runner
**Why**:
no internal task that need this runner
=> remove self-hosted runner where not needed

package.json
**What**:
Update version in package.json
**Why**:
**How**:
**Checklist**:
- [N/A] Tests
=> Prepare release 21.4.4

public/locales/gsa-de.json, src/web/pages/licenses/licensepage.js
**What**:
Change punctuation
**Why**:
**How**:
**Checklist**:
- [N/A] Tests
=> Update license help text

src/web/components/structure/__tests__/__snapshots__/footer.js.snap, src/web/components/structure/__tests__/footer.js, src/web/components/structure/footer.js, src/web/pages/help/about.js
**What**:
**Why**:
**How**:
**Checklist**:
- [n/a] Tests
- [n/a] PR merge commit message adjusted
=> Update copyright at about page and footer for 2022

src/web/components/notification/__tests__/licensenotification.js, src/web/components/notification/licensenotification.js, src/web/pages/licenses/licensepage.js
**What**:
Don't show LicenseNotification if license status is no_license
**Why**:
**How**:
**Checklist**:
=> Don't show LicenseNotification if license status is no_license

package.json, yarn.lock
**What**:
Adjust dependency version for babel/core to fix translation mechanism
**Why**:
Babel had issues with this https://github.com/gilbsgilbs/babel-plugin-i18next-extract/issues/208
**How**:
Manual test to extract the strings and confirm that gsa-de.json has 1971 rows
**Checklist**:
- [N/A] Tests
=> Fix: Translation via i18n-extract

.github/dependabot.yml
**What**:
Run dependabot each monthly
**Why**:
Reduce workload for future maintenance
**How**:
**Checklist**:
=> Run dependabot on a monthly basis at the first of the month

.github/workflows/container.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Also build arm64 container images

.github/dependabot.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Use dependabot for updating Github Actions too

src/gmp/gmpsettings.js, src/version.js
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: Adjust the release version string for the manual links

.docker/prod.Dockerfile, .github/workflows/container.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Update docker & workflows for oldstable branch

.docker/prod.Dockerfile, .github/workflows/container.yml, src/version.js
**What**:
**Why**:
**How**:
**Checklist**:
=> Update docker, workflows, version for new stable

src/web/pages/permissions/multipledialog.js
**What**:
Small change that makes it possible to set permissions for other user on the object "Task" correctly again.
This PR refers to Jira issue T4-276.
**Why**:
This is a bug-fix
**How**:
Tested locally in my development environment.
**Checklist**:
=> Small change that makes it possible to set permissions for other user on the object "Task" correctly again.

.github/dependabot.yml
**What**:
Target the stable branch for future dependabot updates
**Why**:
Stable is the branch to receive releases
**How**:
**Checklist**:
- [N/A] Tests
=> Configure dependabot to make PRs against stable

.github/workflows/release-manually.yml
**What**:
Add a release workflow to autoamtically release patch versions for GSA
**Why**:
reduce steps to release GSA
**How**:
**Checklist**:
=> Add: Release Workflow for GSA

src/web/pages/alerts/condition.js, src/web/pages/alerts/event.js, yarn.lock
This replaces the yarn.lock file with one rebuilt from just the current `package.json` and adds some missing prop validation for alert conditions and events.
To make it simpler to synchronize it and the `package.json` in the stable and main branches.
=> Rebuild yarn.lock and add missing prop validations

.github/workflows/container.yml
Fix container workflow
Seems the workflow got broken in a merge conflict resolution.
https://github.com/greenbone/gsa/actions/runs/4252880919
=> Fix container workflow

src/web/pages/alerts/dialog.js
=> Revert "Corrected the e-mail subject placeholder in the alerts dialog."

src/web/pages/alerts/dialog.js
=> Revert "Corrected the e-mail subject placeholder in the alerts dialog. (backport #3740)"

public/locales/gsa-de.json, src/web/pages/permissions/multipledialog.js
Improved the layout of the multiple permission dialog.
Now it is more clear for which resources the permission is set.
GEA-74
Tested manually on my local development system.
=> Improved the layout of the multiple permission dialog.

.docker/prod.Dockerfile, .github/workflows/container.yml, .github/workflows/release-pontos.yml
Use new docker build and release workflows
GEA-198
=> Change: Use new docker build and release workflows

src/web/components/structure/__tests__/__snapshots__/footer.js.snap, src/web/components/structure/__tests__/footer.js, src/web/components/structure/footer.js, src/web/pages/help/about.js
Update copyright to 2023
We have finished the half of 2023 already.
=> Change: Update copyright to 2023

.github/workflows/release-pontos.yml
=> Add step to install npm dependencies in release-pontos.yml

public/locales/gsa-de.json, src/web/pages/usersettings/usersettingspage.js
Add delta reports version to user settings.
This is part of a feature toggle to enable the use of the new delta reports implementation.
GEA-322
=> Add: Add delta reports version to user settings

src/web/components/structure/__tests__/__snapshots__/footer.js.snap, src/web/components/structure/__tests__/footer.js, src/web/components/structure/footer.js, src/web/pages/help/about.js
Update copyright in footer and about page
We are in 2024 already.
=> Update copyright in footer and about page

src/web/store/index.js
Fix immutability check for error objects
Avoid maximum recursion issues when checking the redux store for immutability and an error has been dispatched.
=> Fix immutability check for error objects

src/web/pages/cves/__tests__/detailspage.jsx, src/web/pages/cves/__tests__/listpage.jsx, src/web/pages/cves/details.jsx, src/web/pages/cves/row.jsx, src/web/pages/cves/table.jsx
Exploit Prediction Scoring System (EPSS) info is added to CVE info if it is available.
This provides information on the probabily of exploitation activity for vulnerabilities.
GEA-558
=> Add: EPSS scoring info in CVEs

src/web/components/form/select.jsx, src/web/components/powerfilter/powerfilter.jsx, src/web/pages/reports/__tests__/detailscontent.jsx, src/web/utils/testing.jsx
Made PowerFilter input field wider and changed loading UI for Select component
GEA-594
GEA-595
=> Add-Powerfilter-UI-improvements

package-lock.json, package.json, src/web/components/sessionTimer/SessionTimer.jsx, src/web/components/structure/header.jsx, src/web/utils/__tests__/useUserSessionTimeout.jsx, src/web/utils/useUserSessionTimeout.jsx
Update OpenSight version and integrate the session timer into the app header.
GEA-646
=> Update opensight version and session timer

package-lock.json, public/locales/gsa-de.json
- add missing translation for de cvss 4 calculator
GEA-654
=> add: cvss 4 calculator de translation

.eslintrc.cjs, package-lock.json, package.json
- Add eslint rules for test files.
- To enforce best practices and prevent common issues in test files.
=> add: vitest eslint rules

src/gmp/gmpsettings.js
Enable EPSS toggle by default
EPSS should be enabled in 24.10
GEA-718
=> Change: Enable EPSS toggle

package-lock.json, package.json
- Remove unused deps `core-js`
=> deps: remove core-js

.docker/prod.Dockerfile, .github/workflows/ci-js.yml, .github/workflows/container.yml, .github/workflows/push.yml
Update GitHub workflows and Docker compose file
=> Update GitHub workflows and Docker compose file (oldstable)

eslint.config.js, src/gmp/log.js, src/gmp/models/__tests__/schedule.js, src/web/components/dialog/content.jsx, src/web/entities/footer.jsx
- Add eslint warning rule for console function
- Change how the message in the delete confirmation dialog is displayed.
- To avoid console logs to be in the code 
GEA-822
=> Improvements-eslint-logs-and-confirmation-dialog-message

src/web/entities/entitynametabledata.jsx, src/web/pages/tasks/row.jsx
- Align glasses to other icons
GEA-826
=> fix: align glasses

src/web/entities/container.jsx, src/web/pages/usersettings/dialog.jsx, src/web/pages/usersettings/generalpart.jsx, src/web/pages/usersettings/usersettingspage.jsx
Fix some proptype warnings
Update the proptypes to use the expected types.
=> Fix some proptype warnings

src/web/pages/usersettings/usersettingspage.jsx
Update proptypes for userinterface date and time format
Both prop types are objects with comment and value attributes.
=> Fix: Update proptypes for userinterface date and time format

src/web/store/pages/actions.js, src/web/store/pages/selectors.js
Document pageFilter and PageSelector usage
Adding jsdoc comments allows for easier usage of both in the IDE.
=> Document pageFilter and PageSelector usage

README.md
Update formatting of the markdown in the README
Run auto markdown formatter on the README.
=> Update formatting of the markdown in the README

src/web/pages/reports/downloadreportdialog.jsx
Fix opening report download dialog
report_format got renamed to reportFormat as we should always use camelCase.
=> Fix opening report download dialog

src/web/pages/reportconfigs/__tests__/listpage.jsx, src/web/pages/reportconfigs/detailspage.jsx, src/web/pages/reportconfigs/listpage.jsx, src/web/pages/reports/auditreportslistpage.jsx, src/web/pages/reports/details/toolbaricons.jsx
Update links to the manual for report config and audit report pages
Link to more specific section in manual for report config and audit report pages.
https://jira.greenbone.net/browse/GEA-869
=> Update links to the manual for report config and audit report pages

package-lock.json, package.json, src/index.jsx, src/web/components/error/errorboundary.jsx
=> Remove sentry and unused deps

package-lock.json, package.json
- Remove dependency `husky` and `lint-staged`
GEA-798
=> remove unused deps husky and linst-staged

src/web/components/icon/SvgIconWrapper.jsx, src/web/components/icon/svgicon.jsx, src/web/utils/proptypes.jsx
- Cleanup errors in console and tests
=> cleanup svg console errors

src/gmp/utils/__tests__/string.test.js, src/gmp/utils/string.js
Document the string functions.
Add jsdoc comments for string functions
Document the string functions.
=> Add jsdoc comments for string functions

src/web/pages/scanconfigs/NvtPreferences.jsx
- `NvtPreferenceDisplay` should have unique key
- Does not render correctly the list
GEA-960
=> Fix: Update key for NvtPreferenceDisplay to use unique identifier

src/web/pages/performance/StartEndTimeSelection.jsx, src/web/pages/performance/__tests__/StartEndTimeSelection.test.jsx
Improvements for the StartEndTimeSelection
Coding style improvements and remove error during tests.
=> Improvements for the StartEndTimeSelection

src/web/entities/EntityNameTableData.jsx, src/web/hooks/useUserName.js, src/web/pages/audits/Row.jsx
Replace usage of withUserName by useUserName and add docstring for useUserName
Explain what useUserName does (it returns an array) and use more modern react (hook instead of hoc).
=> Username hook

src/web/pages/audits/ListPage.jsx, src/web/pages/hosts/ListPage.jsx, src/web/pages/scanconfigs/DetailsPage.jsx, src/web/pages/scanconfigs/ListPage.jsx, src/web/pages/tasks/icons/NewIconMenu.jsx, src/web/pages/tasks/icons/ResumeIcon.jsx, src/web/pages/tasks/icons/StartIcon.jsx
Replace withCapabilities with useCapabilities in task icons
Be able to get rid of the withCapabilities hoc at the end.
=> Replace withCapabilities with useCapabilities in task icons

src/web/entities/__tests__/Container.test.jsx
- Add test for `bulk download`
=> add test for entities container bulk download

.github/workflows/changelog.yml, .github/workflows/release.yml, cliff.toml
Improved changelog generation for releases and allow to show the changelog for all unreleased changes independent of a release.
The PR introduces 7 groups for the release notes
| Group | Commit Message starts with |
|-----------|------------|
|Added | add, Add |
|Changed |change, Change |
|Bug Fixes | fix, Fix |
| Removed | remove, Remove |
|Documentation | doc, Doc |
| Testing | test, Test |
| Miscellaneous | chore, Chore, ci, Ci misc, Misc |
Each commit message starting with one of these strings will be put in the corresponding group.
* More flexible parsing of changelog messages from git commits
* Easier to adjust changelog generation
* Improved information in release changelogs
https://jira.greenbone.net/browse/GEA-984
=> Release workflow

package-lock.json, package.json, public/locales/gsa-de.json, public/locales/gsa-en.json, public/locales/gsa-zh_CN.json, public/locales/gsa-zh_TW.json, src/web/components/menu/Menu.jsx, src/web/components/structure/Header.jsx, src/web/components/structure/__tests__/Header.test.jsx
- Move the manual link position to the `Header`
=> Change: manual link position

package-lock.json, package.json
- Update `@atlaskit/pragmatic-drag-and-drop-react-beautiful-dnd-migration` to v2
- Fix security issues
=> deps-update-deps-(1) and vulnerabilities

eslint.config.js, src/web/components/dashboard/Dashboard.jsx
- Add ESLint rule to avoid duplicate imports.
=> Add ESLint rule for duplicate imports

src/web/pages/portlists/PortListComponent.jsx
Replace EntityComponent with hooks in PortListComponent
Requires https://github.com/greenbone/gsa/pull/4400
Part 2 of refactoring the PortListComponent.
Use the new useEntity hooks to replace the usage of the EntityComponent in the PortListComponent.
https://jira.greenbone.net/browse/GEA-935
=> Replace EntityComponent with hooks in PortListComponent

package-lock.json, package.json
=> deps: update opensight version

src/web/utils/Testing.tsx
Use TypeScript for the testing module
Add types for all testing functions.
=> Use TypeScript for the testing module

src/gmp/model.ts, src/gmp/models/__tests__/filter.test.js, src/gmp/models/filter.ts, src/gmp/parser.ts
Add type information to base Model and Filter classes.
Get information of all possible properties of a Model and a Filter.
=> Types for Model and Filter

.github/workflows/ci-js.yml
Improve output for linting js and checking translation files
Allow to show the errors and give hints.
=> Improve output for linting js and checking translation files

src/web/components/form/Select.jsx, src/web/components/layout/GlobalStyles.jsx
- Make scrollbar visible on hover for select components.
- Improve notification position.
GEA-907
GEA-1028
=> Fix scrollbar visibility notification position

src/gmp/commands/__tests__/feedstatus.test.js, src/web/components/menu/__tests__/Menu.test.jsx
Address linting errors
Remove unused imports and sort imports.
=> Address linting errors

src/gmp/model.ts
Export Element type from Model
It will be used by other model classes too.
=> Export Element type from Model

src/gmp/utils/__tests__/string.test.js
Ensure behavior for passing a number to isEmpty function
If a number is passed the function should return false.
=> Ensure behavior for passing a number to isEmpty function

src/gmp/http/response.ts
Fix type of meta argument for Response.set
Invalid type used
=> Fix type of meta argument for Response.set

src/gmp/log.ts
Use TypeScript for logging module
Add type information to the logging module.
=> Use TypeScript for logging module

src/gmp/commands/gmp.js, src/gmp/models/filter.ts, src/gmp/models/filter/__tests__/utils.test.ts, src/gmp/models/filter/utils.ts
Update types on Filter model and add types for filterString utility function
=> Filter types

src/gmp/utils/identity.ts, src/web/entity/navigation.ts
Improve type deferring for isDefined, hasValue and isFunction
Get TypeScript to defer the types as expected when using these functions.
=> Improve type deferring for isDefined, hasValue and isFunction

src/web/utils/Theme.tsx
- Update severity class colours.
- Match opensight colours.
GEA-1052
=> Update severity colours values in Theme

src/web/pages/users/Component.jsx, src/web/pages/users/Row.jsx, src/web/utils/withTranslation.tsx
- fix translation error which caused the page not to render
=> fix: user list page

src/gmp/commands/__tests__/portlist.test.ts, src/gmp/commands/portlists.ts, src/gmp/models/__tests__/portlist.test.js, src/gmp/models/portlist.ts, src/web/pages/portlists/Details.tsx, src/web/pages/portlists/DetailsPage.jsx, src/web/pages/portlists/ListPage.jsx, src/web/pages/portlists/PortListComponent.tsx, src/web/pages/portlists/PortListDialog.tsx, src/web/pages/portlists/PortListImportDialog.tsx, src/web/pages/portlists/PortRangeDialog.tsx, src/web/pages/portlists/PortRangesTable.tsx, src/web/pages/portlists/Row.jsx, src/web/pages/portlists/__tests__/PortListComponent.test.jsx, src/web/pages/portlists/__tests__/PortRangeDialog.test.jsx, src/web/pages/targets/Component.jsx
camelCase properties for all Port List and Port Range related classes and components.
Get a common coding style that uses camelCase.
=> Port List Improvements

src/gmp/http/__tests__/utils.test.ts, src/gmp/http/http.ts, src/gmp/http/utils.ts
Fix uploading files which broke during http class refactoring to TypeScript.
Uploading LDAP CA certificates and similar file uploads should work again.
=> File Upload

src/web/components/form/MultiSelect.jsx, src/web/components/form/__tests__/withClickHandler.test.jsx, src/web/components/icon/test/Icon.test.jsx, src/web/components/link/ExternalLink.jsx, src/web/components/notification/LicenseNotification.jsx, src/web/components/powerfilter/__tests__/SeverityValuesGroup.test.jsx, src/web/pages/credentials/CredentialsComponent.jsx, src/web/pages/extras/__tests__/TrashCanPage.test.jsx, src/web/pages/notes/NoteComponent.jsx, src/web/pages/nvts/Details.jsx, src/web/pages/reports/details/AuditThresholdPanel.jsx, src/web/pages/reports/details/EmptyResultsReport.jsx, src/web/pages/targets/__tests__/Row.test.jsx, src/web/utils/withTranslation.tsx, src/web/wizard/__tests__/AdvancedTaskWizard.test.jsx, src/web/wizard/__tests__/ModifyTaskWizard.test.jsx
- Test Suite: clean up console errors
GEA-1080
=> Test Suite  clean up console errors

src/web/components/menu/Menu.jsx
- Changed the menu structure in a single array const adding the permissions based on:
https://raw.githubusercontent.com/greenbone/gsa/42e0689e2b257d5d7dca03defc948517d21a8714/src/web/components/menu/menu.jsx
Some permissions were not being applied
GEA-1053
=> change menu structure for permissions

src/gmp/utils/__tests__/array.test.ts, src/gmp/utils/array.ts
Improve types for array helper functions
All tests are type safe now.
=> Improve types for array helper functions

cliff.toml
Fix generating the Miscellaneous group in the changelog
Resolve some UTF encoding issue.
=> Fix generating the Miscellaneous group in the changelog

package-lock.json, package.json
- deps: major-update-fast-xml-parser
=> deps: major-update-fast-xml-parser

src/web/components/form/__tests__/useFormValues.test.tsx, src/web/pages/extras/cvssV4/__tests__/cvssV4Calculator.test.jsx, src/web/pages/login/__tests__/LoginForm.test.jsx, src/web/pages/login/__tests__/LoginPage.test.jsx, src/web/pages/schedules/__tests__/Dialog.test.jsx, src/web/utils/Testing.tsx
* Drop custom queries render function and `web/utils/Testing`
* Drop within from render function and `web/utils/Testing`
Cleanup `web/utils/Testing` and use `web/testing` instead.
https://jira.greenbone.net/browse/GEA-1096
=> Refactor Testing #3

src/web/components/badge/Badge.tsx, src/web/components/badge/__tests__/Badge.test.tsx
- Added TS for Badge component
GEA-1107
=> Typescript for Badge component

public/locales/gsa-de.json, public/locales/gsa-en.json, public/locales/gsa-zh_CN.json, public/locales/gsa-zh_TW.json, src/gmp/models/scanner.js, src/web/pages/scanners/Dialog.jsx, src/web/pages/scanners/ScannerComponent.jsx, src/web/pages/scanners/__tests__/Dialog.test.jsx
Added agent controller sensor scanner type to scanners Dialog.
This is needed for the implementation of agents.
GEA-964
=> Add: Added agent controller sensor scanner type to scanners Dialog.

src/web/pages/notes/Dialog.jsx, src/web/pages/notes/NoteComponent.jsx, src/web/pages/notes/__tests__/NoteComponent.test.jsx
Fix creating Notes from Results and NVTs
The fields in the Note create dialog should be filled in automatically when creating a Note from a Result or NVT. This got broken while refactoring the NoteComponent into a function component.
https://jira.greenbone.net/browse/GEA-1133
=> Fix creating Notes from Results and NVTs

src/web/Authorized.jsx, src/web/Routes.jsx, src/web/components/menu/Menu.tsx, src/web/pages/login/LoginPage.tsx, src/web/pages/login/__tests__/LoginPage.test.jsx
- User gets redirected to the previous path after being logged out because of session timeout.
- Menu is opened on the correct menu link after logging in on the previous path.
- User is always redirected to `/dashboard` after being logged out because of session timeout
GEA-973
=>  User gets redirected to the previous path after being logged out because of session timeout

src/gmp/models/__tests__/resourcename.test.ts, src/gmp/models/resourcename.ts
Use TypeScript for ResourceName model
https://jira.greenbone.net/browse/GEA-1097
=> Use TypeScript for ResourceName model

src/gmp/commands/license.js, src/gmp/models/__tests__/license.test.ts, src/gmp/models/license.ts, src/web/components/notification/__tests__/LicenseNotification.test.jsx
Use TypeScript for License model
https://jira.greenbone.net/browse/GEA-1097
=> Use TypeScript for License model

src/gmp/models/note.ts
Improve parsing of Note element data
Use similar code as the new Override.
=> Improve parsing of Note element data

src/gmp/models/entitymodel.ts, src/gmp/models/filter.ts, src/gmp/models/policy.ts, src/gmp/models/scanconfig.ts, src/gmp/models/task.ts
Small Model Updates and Improvements
Fix some small naming and type issues found while refactoring the Task components.
=> Small Model Updates and Improvements

src/web/entities/withEntitiesActions.jsx
=> Fix typo Enities -> Entities

src/web/pages/user-settings/SeveritySettings.tsx
fix: dynamic severity checkbox state
=> fix: dynamic severity checkbox state

src/web/pages/user-settings/__tests__/helperFunctions.test.ts, src/web/pages/user-settings/helperFunctions.ts, src/web/utils/Languages.tsx
fix: user setting browser language showing undefined
=> fix: user setting browser language showing undefined

src/web/pages/user-settings/FilterSettings.tsx
Improve type information in FilterSettings component
=> Improve type information in FilterSettings component

src/web/pages/tasks/Table.jsx, src/web/pages/tasks/TaskRow.tsx, src/web/pages/tasks/__tests__/TaskRow.test.tsx
Use TypeScript for TaskRow component and rename module to component name.
Requires https://github.com/greenbone/gsa/pull/4684
=> Use TypeScript for TaskRow

src/web/pages/tasks/TaskRow.tsx, src/web/pages/tasks/TaskTrend.tsx, src/web/pages/tasks/__tests__/TaskTrend.test.tsx
Use TypeScript for TaskTrend component
Requires https://github.com/greenbone/gsa/pull/4688
=> Use TypeScript for TaskTrend component

src/web/pages/extras/TrashCanPage.jsx, src/web/pages/tasks/ListPage.jsx, src/web/pages/tasks/TaskTable.tsx, src/web/pages/tasks/__tests__/TaskTable.test.tsx
Use TypeScript for TaskTable component
Requires https://github.com/greenbone/gsa/pull/4691
=> Use TypeScript for TaskTable component

src/web/pages/tasks/ListPage.jsx, src/web/pages/tasks/TaskFilterDialog.tsx, src/web/pages/tasks/__tests__/TaskFilterDialog.test.tsx
Use TypeScript for TaskFilterDialog
Requires https://github.com/greenbone/gsa/pull/4692
=> Use TypeScript for TaskFilterDialog

src/web/hooks/__tests__/usePageFilter.test.tsx, src/web/hooks/usePageFilter.ts, src/web/pages/portlists/ListPage.jsx
Improve filter update port list page
Bugs:
* Fixed mixed up reset and remove filter handling
* (Re-)loading of data of the filter has changed
=> Improve filter update port list page

.github/dependabot.yml
- Cooldown period for vite deps
=> cooldown period for vite deps

src/web/entities/__tests__/EntitiesFooter.test.tsx, src/web/pages/audits/__tests__/Row.test.jsx, src/web/pages/cves/__tests__/Row.test.jsx, src/web/pages/nvts/__tests__/Row.test.jsx, src/web/pages/policies/__tests__/Row.test.jsx, src/web/pages/reportconfigs/__tests__/Row.test.jsx, src/web/pages/reports/__tests__/AuditReportRow.test.jsx, src/web/pages/results/__tests__/Row.test.jsx, src/web/pages/scanconfigs/__tests__/Row.test.jsx, src/web/pages/targets/__tests__/Row.test.jsx, src/web/pages/tasks/__tests__/TaskRow.test.tsx, src/web/pages/user-settings/__tests__/EditableSettingRow.test.tsx, src/web/testing/Render.tsx
Cleanup and fix rendererWith testing functions
Re-rendering was broken and avoid code duplication. Also the function names were not completely correct about their purpose.
=> Cleanup and fix rendererWith testing functions

package-lock.json, package.json
=> deps: patch update

src/web/pages/scanconfigs/ScanConfigComponent.jsx
fix: Cannot create new scan config
GEA-1234
=> fix: Cannot create new scan config

src/web/entities/EntitiesContainer.tsx
- Adjust variable casing
- Reports could not be deleted
GEA-1240
=> fix: Delete Report button

src/web/components/structure/Header.tsx
change: Adjust user navigation width in Header component
- Text was cropped with longer translations in Firefox.
GEA-1267
=> change: Adjust user navigation width in Header component

src/gmp/capabilities/__tests__/capabilities.test.ts, src/gmp/capabilities/__tests__/features.test.ts, src/gmp/capabilities/capabilities.ts, src/gmp/capabilities/features.ts, src/gmp/commands/__tests__/user.test.ts, src/gmp/commands/user.ts, src/web/components/conditionalRoute/ConditionalRoute.jsx, src/web/components/conditionalRoute/__tests__/ConditionalRoute.test.jsx, src/web/components/provider/FeaturesProvider.tsx, src/web/hooks/__tests__/useFeatures.test.tsx, src/web/hooks/__tests__/useLoadFeatures.test.tsx, src/web/hooks/useFeatures.ts, src/web/hooks/useLoadFeatures.ts, src/web/pages/Page.tsx, src/web/pages/__tests__/Page.test.tsx, src/web/pages/scanners/Dialog.jsx, src/web/pages/scanners/__tests__/Dialog.test.jsx, src/web/testing/Components.tsx, src/web/testing/Render.tsx
Separate Features from Capabilities
Features and Capabilities are two different things and should not mixed within one class.
Required for checking for enabled agent feature and showing the scanner dialog. It also defines which scanners can be created via the dialog.
=> Separate Features from Capabilities

src/web/entities/EntityNameTableData.tsx
Allow to set a data-testid for EntityNameTableData component
Allows for easier testing.
=> Allow to set a data-testid for EntityNameTableData component

src/gmp/models/__tests__/credential.test.ts, src/gmp/models/credential.ts, src/web/components/certinfo/CertInfo.tsx, src/web/components/certinfo/__tests__/CertInfo.test.tsx, src/web/components/table/SimpleTable.tsx, src/web/components/table/Table.tsx, src/web/pages/credentials/DetailsPage.jsx
Fix parsing and displaying certificate information
Parts of the certificate information of credentials were not parsed at all.
=> Fix parsing and displaying certificate information
