CHANGELOG.md, gsa/src/web/components/powerfilter/powerfilter.js, gsa/src/web/entities/page.js, gsa/src/web/pages/reports/detailscontent.js
=> Disable Powerfilter edit icon if isLoading

CHANGELOG.md, gsa/src/web/pages/roles/detailspage.js
=> Filtering General Command Permissions for roles

gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_http.c, gsad/src/gsad_http_handler.c, gsad/src/gsad_session.c, gsad/src/validator.c
We were mixing `__func__` and `__FUNCTION__`, so we're switching all to `__func__`.
GCC manual: `__FUNCTION__` is another name for `__func__`, provided for backward compatibility with old versions of GCC. 
**Checklist**:
- [] Tests
- [] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry N/A
=> Replace __FUNCTION__ with __func__

CHANGELOG.md, gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap, gsa/src/web/components/form/__tests__/multiselect.js, gsa/src/web/components/form/__tests__/select.js, gsa/src/web/components/form/multiselect.js, gsa/src/web/components/form/select.js, gsa/src/web/components/icon/arrowicon.js, gsa/src/web/components/layout/__tests__/__snapshots__/globalstyles.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/relationselector.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severityvaluesgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/tasktrendgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/__snapshots__/ticketstatusgroup.js.snap, gsa/src/web/components/powerfilter/powerfilter.js, gsa/src/web/entities/page.js, gsa/src/web/pages/audits/__tests__/listpage.js, gsa/src/web/pages/policies/__tests__/listpage.js, gsa/src/web/pages/scanconfigs/__tests__/listpage.js, gsa/src/web/pages/tasks/__tests__/listpage.js, gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/dialog.js, gsa/src/web/store/entities/utils/selectors.js
=> Add loading indicator for select

CHANGELOG.md, gsa/src/gmp/__tests__/gmpsettings.js, gsa/src/gmp/gmpsettings.js, gsa/src/web/components/loading/__tests__/reload.js, gsa/src/web/components/loading/reload.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/reports/listpage.js, gsa/src/web/pages/tasks/detailspage.js, gsa/src/web/pages/tasks/listpage.js
Improve Reload component to consider hidden status of the current browser tab for calculating the reload interval.
**Checklist**:
=> [8.0] Reload on inactive tabs

CHANGELOG.md, gsa/src/web/components/date/datetime.js, gsa/src/web/components/menu/usermenu.js, gsa/src/web/utils/__tests__/useGmp.js, gsa/src/web/utils/__tests__/useUserName.js, gsa/src/web/utils/__tests__/useUserSessionTimeout.js, gsa/src/web/utils/__tests__/useUserTimezone.js, gsa/src/web/utils/useGmp.js, gsa/src/web/utils/useUserName.js, gsa/src/web/utils/useUserSessionTimeout.js, gsa/src/web/utils/useUserTimezone.js
=> Timezone in usermenu

CHANGELOG.md, gsa/src/web/pages/scanners/dialog.js
=> Changed default port to 22 for scanner dialog

CHANGELOG.md, gsa/src/gmp/http/http.js
It seems it is not possible to set the responseType of the xhr object
before the loading hasn't started with IE 11.
https://stackoverflow.com/questions/29677339/invalidstateerror-in-internet-explorer-11-during-blob-creation
**Checklist**:
- [n/a] Tests
=> Avoid InvalidStateError when creating xhr on IE 11

CHANGELOG.md, gsa/src/gmp/__tests__/gmp.js, gsa/src/gmp/__tests__/gmpsettings.js, gsa/src/gmp/__tests__/log.js, gsa/src/gmp/gmp.js, gsa/src/gmp/gmpsettings.js, gsa/src/gmp/http/gmp.js, gsa/src/gmp/log.js, gsa/src/web/app.js, gsa/src/web/components/link/__tests__/protocoldoclink.js, gsa/src/web/components/link/protocoldoclink.js, gsa/src/web/entity/withEntityContainer.js
Use consistent settings and setting names in GSA.
**Checklist**:
=> Consistent settings

gsa/src/web/pages/policies/__tests__/listpage.js
Under some race conditions renewSession may be called and causes an
exception. Therefore don't crash if a click handler is called.
**Checklist**:
=> Fix flaky policies list page test

CHANGELOG.md, gsa/src/web/entities/__tests__/filterprovider.js, gsa/src/web/entities/filterprovider.js
=> Fix default filter is not always applied

CHANGELOG.md, gsa/src/gmp/__tests__/parser.js, gsa/src/gmp/parser.js, gsa/src/gmp/utils/__tests__/string.js, gsa/src/gmp/utils/string.js
=> Fix parsing invalid override hosts

CHANGELOG.md, gsa/src/web/pages/overrides/dialog.js, gsa/src/web/utils/render.js
=> Override: Make host/port/task fields editable even when fixed, and display oid when no name is defined

CHANGELOG.md, gsa/src/web/pages/notes/dialog.js
=> New note dialog: make all fields editable when fixed

CHANGELOG.md, gsa/src/web/entities/container.js, gsa/src/web/entities/filterprovider.js, gsa/src/web/entities/withEntitiesContainer.js
Change order of components. The FilterProvider needs to be a parent of
the EntitiesContainerWrapper because it specifies the to be used filter.
**Checklist**:
- [] Tests
=> Fix filter reset a list pages

CHANGELOG.md, gsa/src/web/pages/permissions/dialog.js
I thought about doing the same for users and roles, but I can't imagine a situation where there are no users and roles.
**Checklist**:
- [] Tests
=> New permission dialog: radio button for groups disabled if no groups available

CHANGELOG.md, gsa/src/web/pages/results/details.js
=> Limit the length of result description with a div

CHANGELOG.md, gsad/src/gsad_gmp.c
Requires https://github.com/greenbone/gvm-libs/pull/306.
read_string_c is faster and uses less memory than read_entity_and_string_c.
The delta report case still uses read_entity_and_string_c.  This could also be converted with a little support from the JS side.
**Checklist**:
- [] Tests
=>  Use read_string_c for the XML get_report case (8.0)

CHANGELOG.md, gsa/src/web/pages/reports/details/hoststab.js
=> Fix sorting hosts in report details

CHANGELOG.md, gsa/CMakeLists.txt, gsa/src/web/components/error/__tests__/errorboundary.js, gsa/src/web/components/error/__tests__/errorpanel.js, gsa/src/web/components/error/errorboundary.js, gsa/src/web/components/error/errorpanel.js, gsa/src/web/pages/reports/detailscontent.js, gsa/src/web/utils/proptypes.js
=> Error panel

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/severitylevelsgroup.js, gsa/src/web/components/powerfilter/severitylevelsgroup.js, gsa/src/web/pages/reports/detailsfilterdialog.js, gsa/src/web/pages/results/filterdialog.js
Remove severity levels from filter if all levels are unchecked.
**Checklist**:
=> Severity levels

CHANGELOG.md, gsa/src/web/pages/reports/deltadetailscontent.js, gsa/src/web/pages/reports/deltadetailspage.js, gsad/src/gsad.c
=> Fix delta report

CHANGELOG.md, gsad/src/gsad_gmp.c
This allows limiting the aggregate data for task and config charts to
their scan and compliance usage types.
**Checklist**:
- [] Tests N/A
=> Add usage_type param to get_aggregate_gmp in gsad

gsa/src/web/store/entities/report/__tests__/selectors.js, gsa/src/web/store/entities/report/selectors.js
When requesting a report the report is put into the store with the full
filter. Therefore the selector needs to use the full filter to get the
error too.
**Checklist**:
=> Fix getting an error from the store for a report request

CHANGELOG.md, gsa/src/gmp/commands/tasks.js
=> Add usage_type 'scan' to getAggregates commands for tasks

CHANGELOG.md, gsa/src/web/pages/extras/trashcanpage.js
In case of an error on the trashcanpage the trash might be undefined which would cause the trashcanpage to break. This PR should fix that by catching this special case.
**Checklist**:
- [N/A] Tests
=> handle undefined trash in case of an error

CHANGELOG.md, gsa/src/web/entity/link.js
=> Fix broken entity links for reportformat, scanconfig and portlist

CHANGELOG.md, gsa/src/web/components/form/__tests__/multiselect.js, gsa/src/web/components/form/multiselect.js, gsa/src/web/pages/reports/listpage.js
ComponentWillReceiveProps is deprecated. Update components that still use it to use getDerivedStateFromProps instead.
**Checklist**:
- [N/A] Tests
=> Remove componentWillReceiveProps

CHANGELOG.md, gsa/src/web/pages/hosts/detailspage.js
Fix missing delete button for host identifiers. Click handler needs to be passed to details directly because entity page does not forward props like entities page does.
**Checklist**:
- [N/A] Tests
=> fix missing delete button for host identifiers

CHANGELOG.md, gsa/src/gmp/models/__tests__/task.js, gsa/src/gmp/models/task.js, gsa/src/web/pages/tasks/row.js
ProvideViewIcon in task row was only shown for users. Show it for groups and roles as well.
**Checklist**:
- [N/A] Tests
=> Fix task listpage observer tooltip

CHANGELOG.md, gsa/src/web/components/bar/__tests__/__snapshots__/titlebar.js.snap, gsa/src/web/components/menu/__tests__/__snapshots__/usermenu.js.snap, gsa/src/web/components/menu/__tests__/usermenu.js, gsa/src/web/components/menu/usermenu.js
This adds a small icon to the usermenu allowing to renew the session timeout without triggering another action in GSA.
**Checklist**:
=> Add Renew Session Timeout icon to usermenu

CHANGELOG.md, gsa/src/gmp/http/transform/fastxml.js
Error messages like "Failed to find task &apos;foo&apos;" are now handled correctly. This concerned xml gsad_response and action_result messages.
**Checklist**:
=> Parse xml rejection message (unescape)

CHANGELOG.md, gsa/src/web/pages/tasks/icons/__tests__/resumeicon.js, gsa/src/web/pages/tasks/icons/__tests__/starticon.js, gsa/src/web/pages/tasks/icons/__tests__/stopicon.js, gsa/src/web/pages/tasks/icons/resumeicon.js, gsa/src/web/pages/tasks/icons/starticon.js, gsa/src/web/pages/tasks/icons/stopicon.js
The icons for start task, stop task and resume task were only checking if the user had permission to start/stop/resume tasks in general but not if he had permissions for that task in particular.
**Checklist**:
=> Use correct capabilities for task icons

CHANGELOG.md, gsa/src/gmp/models/override.js, gsa/src/web/pages/results/details.js
With the new scheme as introduced in [this community post](https://community.greenbone.net/t/extending-oid-scheme/4420) the old DEFAULT_OID_VALUE was too strict to work with newer VTs.
This goes together with https://github.com/greenbone/gvmd/pull/984.
**Checklist**:
- [N/A] Tests
=> Adjust DEFAULT_OID_VALUE for use with new oid scheme

CHANGELOG.md, gsa/src/web/components/icon/osicon.js
=> Don't crash OsIcon when osCpe or osTxt are undefined

CHANGELOG.md, gsa/src/web/components/icon/osicon.js
Don't crash OsIcon when osCpe or osTxt is undefined
**Checklist**:
- [N/A] Tests
=> Adjust #1975 after PR

CHANGELOG.md, gsa/src/gmp/utils/__tests__/entitytype.js, gsa/src/gmp/utils/entitytype.js
Fixes all functions that use gmp.vulns commands
**Checklist**:
=> Correctly pluralizing type "vulnerability"

CHANGELOG.md, gsa/src/web/entities/container.js
Instead of sending the resource_ids for the save_tag command as a set, send it as array. Sets don't work as command parameter.
**Checklist**:
- [N/A] Tests
=> Fix bulk tagging by selection

CHANGELOG.md, gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap, gsa/src/web/components/layout/__tests__/__snapshots__/globalstyles.js.snap, gsa/src/web/entity/page.js, gsa/src/web/pages/nvts/detailspage.js
Improve error messages for invalid detailspage links. Show extra information for invalid CVE links.
**Checklist**:
- [N/A] Tests
=> Improve error handling for invalid detailspage links

CHANGELOG.md, gsa/src/web/pages/credentials/dialog.js, gsad/src/gsad_gmp.c
=> Show passphrase field in CredentialDialog for cc type

CHANGELOG.md, gsa/src/web/components/chart/topology.js, gsa/src/web/pages/hosts/dashboard/loaders.js
Set the filter to rows=1000 (MAX_HOSTS) instead fo using rows=-1
**Checklist**:
- [N/A] Tests
=> Tune TopologyChart data loading

CHANGELOG.md, gsa/src/web/pages/audits/component.js, gsa/src/web/pages/audits/dialog.js
In order to run audits on sensor, the scanner selection needs to be implemented for audits as much as for tasks.
**Checklist**:
- [N/A] Tests
=> Allow to select scanners in audit dialog

CHANGELOG.md, gsa/src/gmp/models/__tests__/audit.js, gsa/src/gmp/models/audit.js, gsa/src/gmp/models/task.js, gsa/src/gmp/parser.js, gsa/src/web/pages/audits/__tests__/row.js, gsa/src/web/pages/audits/row.js
ProvideViewIcon in audit row was only shown for users but not for roles and groups. Applied the changes in task model to audits as well to fix this.
**Checklist**:
=> Fix audit listpage observer tooltip

CHANGELOG.md, gsa/src/gmp/models/__tests__/filter.js, gsa/src/gmp/models/filter.js, gsa/src/gmp/models/filter/__tests__/filterterm.js, gsa/src/gmp/models/filter/filterterm.js
Parsing filter strings that include substrings in double quotes is causing issues. Adjust parsing functions to be able to handle double quotes.
**Checklist**:
=> Adjust parsing of filter strings

CHANGELOG.md, gsa/src/web/components/icon/__tests__/svgicon.js, gsa/src/web/components/icon/svgicon.js
This PR introduces two custom hooks to the SvgIcon component.
useStateWithMountCheck() replaces the normal useState() hook in the SvgIcon to set isLoading. It checks whether the component is actually mounted before trying to set state.
Whether the component is mounted is stored in a ref (with useRef()). ref.current will be consistent across renders and will not define a new handleClick() if the icon is rerendered, leading to an inconsistent state use, basically breaking the isLoading functionality.
The whole idea is based in the clean-up function at the end of the hook. Normally, the state update on unmounted components is fixed with a useEffect() hook, like this:
useEffect(() => {
let isMounted = true;
if (isMounted) {setState(...)};
return () => isMounted = false;
})
The definition of …
=> No state update in unmounted SvgIcons

gsa/src/gmp/gmpsettings.js, gsa/src/web/pages/login/__tests__/loginpage.js, gsa/src/web/pages/login/loginpage.js
Right now our hyperion branch and master are mutually exclusive- one only works with `gsad` on and one only works with it off. I amended the gmpsettings module to allow a variable called `enableHyperionOnly` and adjust the login function accordingly. If the value is true, then `hyperion-gsa` should not work with `gsad` on and with `gsad` off, only hyperion-related features will work.
Should that value be false, then we use both hyperion and gsad login, and should be running a hybrid system with both backends. Task related functions will be hyperion only, and the rest use `gsad`. Turning off `gsad` in this case will have the same effect, you get an Unknown Error.
I also edited a loginpage test that was updated for hyperion only. I set `enableHyperionOnly` to true for that test, because …
=> Toggle hyperion for development

gsa/src/web/components/link/detailslink.js, gsa/src/web/entity/icon/cloneicon.js, gsa/src/web/entity/icon/editicon.js, gsa/src/web/entity/icon/trashicon.js, gsa/src/web/pages/page.js, gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/icons/importreporticon.js, gsa/src/web/pages/tasks/icons/newiconmenu.js, gsa/src/web/pages/tasks/listpage.js, gsa/src/web/utils/useGqlCapabilities.js
Pages can now fetch capabilities from graphql, and falls back to gmp if hyperion has as problem. Also gets rid of unnecessary function from earlier, and replaced the withCapabilities HOC with useCapabilities() context hook.
**Checklist**:
=> Get capabilities from graphql into context

CHANGELOG.md, gsa/src/web/pages/policies/component.js
Audits created directly from a policy are not useable right now because the scanner is undefined. Adjust policy component to forward appropriate scanners to dialog to fix this
**Checklist**:
=> fix missing scanner when creating audit from policy

gsa/src/gmp/models/__tests__/scanconfig.js, gsa/src/gmp/models/scanconfig.js, gsa/src/gmp/models/task.js, gsa/src/web/pages/scanconfigs/component.js, gsa/src/web/pages/scanconfigs/details.js, gsa/src/web/pages/scanconfigs/row.js, gsa/src/web/pages/tasks/__mocks__/mocktasks.js, gsa/src/web/pages/tasks/__tests__/__snapshots__/details.js.snap, gsa/src/web/pages/tasks/__tests__/details.js, gsa/src/web/pages/tasks/dialog.js
Due to the scan config type missing in tasks in hyperion-gsa some of the preferences on the task details page are not displayed. Fix missing scan config type and update tests to ensure the preferences are displayed correctly.
**Checklist**:
=> Fix missing scanconfig type hyperion

gsa/src/gmp/http/__tests__/rejection.js, gsa/src/gmp/http/rejection.js, gsa/src/gmp/http/transform/__tests__/xml.js, gsa/src/gmp/http/transform/xml.js
Don't override error message with Unknown Error. If the error didn't had
any response or the repsonse didn't contain xml data it is very likely
that the rejection already contains a more useful error message.
=> Fix setting error message

gsa/src/web/app.js
Always return failing promise from gmp error handler to allow the login
method handle the error. Returning Promise.resolve here would not call
the catch case for the login promise.
=> Fix displaying login errors for gsad based logins

CHANGELOG.md, gsa/src/web/pages/alerts/component.js
The test alert button is missing a loading indicator. Return a promise for handleTestAlert to make the loading indicator show up.
**Checklist**:
=> Fix missing loading indicator for test alert icon

gsa/src/web/entities/withEntitiesContainer.js
Before it was required to pass a loadEntities function to
withEntitiesContainer. This commit changes the withEntitiesContainer to
make the loadEntities function optional. As a result not passing a
loadEntities functions deactivates the reloading via the Reload
component.
**Checklist**:
=> Make reload via GMP optional for list pages

gsa/src/web/graphql/__mocks__/tasks.js, gsa/src/web/graphql/__tests__/tasks.js, gsa/src/web/graphql/tasks.js
The mock objects should be put into the `web/graphql/__mocks__`
directory now. For now the task objects are copied from
`web/pages/tasks/__mocks__/mocktasks.js`. This file should be removed
at the end.
**Checklist**:
=> Add new useGetTasks query

gsa/src/web/pages/login/loginpage.js
The locale is already expected in the response. Therefore add it to the
actual graphql request.
=> Fix request and locale for login

CHANGELOG.md, gsa/src/gmp/models/event.js
Days for custom monthly schedules appear in wrong order. Change sorting from alphabetical to numerical to get the days in the right order.
**Checklist**:
=> sort schedule days numerically instead of alphabetically

CHANGELOG.md, gsa/src/gmp/models/__tests__/cpe.js, gsa/src/gmp/models/cpe.js
The CVEs inside a CPE were not parsed correctly and therefore did not show up on the detailspage.
**Checklist**:
=> Fix missing cves

gsa/src/web/app.js
Use 'cache-and-network' fetch policy for graphql queries by default.
Replaces #2237
=> Set default apollo cache policy for graphql queries

CHANGELOG.md, gsa/src/web/pages/cpes/detailspage.js
=> Add loading indicator for cves on cpe detailspage

CHANGELOG.md, gsa/src/gmp/utils/__tests__/entitytype.js, gsa/src/gmp/utils/entitytype.js, gsa/src/web/entities/container.js
AllSecInfo bulk export was broken because it was calling the wrong command. Use normalizeType in entities container to change "allinfo" to "secinfo" to be able to call the proper command.
**Checklist**:
=> Use normalizeType in entities container to ensure correct command for secinfo

CHANGELOG.md, gsa/src/web/pages/scanconfigs/nvtfamilies.js
Several NVT families are now selectable as a whole only.
The trend is always set to dynamic, static is disabled, and the Edit Icon previously used to select individual NVTs is removed.
**Checklist**:
=> Make some Families selectable as a whole only

CHANGELOG.md, gsa/src/web/pages/overrides/dialog.js
=> Severity in override dialog

CHANGELOG.md, gsa/src/gmp/commands/dashboards.js
=> Deal with duplicate settings in dashboard getSetting()

CHANGELOG.md, gsa/src/gmp/models/__tests__/cve.js, gsa/src/gmp/models/cve.js, gsa/src/web/pages/cves/details.js
Fix parsing in cve model. 
This fixes
- missing reference identifiers
- disappearing vulnerable products section
- missing published and last updated dates
It also removes the cwe id as this has not been displayed starting with GOS 5 and seems not to be needed anymore.
**Checklist**:
=> Adjust parsing in cve model

CHANGELOG.md, gsa/src/gmp/__tests__/parser.js, gsa/src/gmp/models/__tests__/note.js, gsa/src/gmp/models/__tests__/override.js, gsa/src/gmp/models/note.js, gsa/src/gmp/models/override.js, gsa/src/gmp/parser.js
It was parsed and tested for note and override models but not used in GSA.
**Checklist**:
=> Remove textExcerpt parsing and testing

CHANGELOG.md, gsa/src/gmp/models/__tests__/alert.js, gsa/src/gmp/models/alert.js
The radio buttons for email alerts in the alert dialog were not working. The corresponding value from the model was a number but the dialog was expecting a string.
Fix parsing in the alert model to return a string as expected.
**Checklist**:
=> Fix broken radio buttons in alert dialog

CHANGELOG.md, gsa/src/web/pages/tasks/component.js
Always forward schedule and schedule_periods to task dialog. This should ensure checkbox for "once" stays checked after the task was run.
The check for capabilities is removed because the input for the dialog should not depend on capabilities (only the visibility does and that is taken care of in the dialog itself)
**Checklist**:
=> Keep schedule_periods even if there is no schedule

CHANGELOG.md, gsa/src/gmp/models/__tests__/event.js, gsa/src/gmp/models/event.js, gsa/src/web/pages/schedules/details.js
Schedules with recurrence "once" do not have a nextDate. Therefore, tasks with these kinds of schedules are not started.
Calculate nextDate for schedules with recurrence "once" and adjust tests accordingly.
**Checklist**:
=> Schedules with recurrence "once" are missing nextDate

CHANGELOG.md, gsa/src/web/pages/reports/details/resultstab.js, gsa/src/web/pages/reports/detailscontent.js
Our ResultsTab fetches a different CollectionCounts from store to use with the EmptyResultsReport and this causes a significantly different number to be displayed in the EmptyResultsReport when the user filters for a nonexistent result from what is shown on the Results TabTitle component. They should use the same props and be consistent.
**Checklist**:
=> Use the same counts in EmptyResultsReport as the TabTitle

CHANGELOG.md, gsa/src/gmp/commands/wizard.js, gsa/src/web/wizard/modifytaskwizard.js
The radio buttons in the Modify Task Wizard were not working due to a missing convert function. 
Also the calculated date of the schedule was wrong since day() returns the day of the week and not the day of the month. Use date() instead. (See also https://momentjs.com/docs/#/get-set/date/)
**Checklist**:
=> Fix Modify Task Wizard

CHANGELOG.md, gsa/src/gmp/commands/__tests__/feedstatus.js, gsa/src/gmp/commands/feedstatus.js, gsa/src/web/pages/extras/__tests__/feedstatuspage.js, gsa/src/web/pages/extras/feedstatuspage.js
=> Add reload timer to feedstatuspage and displaying when updating is in progress

CHANGELOG.md, gsad/src/gsad_gmp.c
In the gsad functions create_credential_gmp and save_credential_gmp the
parameter "credential_login" was not validated correctly, resulting in
either missing error messages or misleading ones where the parameter was
named "login" instead.
**Checklist**:
=> Fix credential_login in gsad request handlers

gsad/config/gsad.service.in
`Documentation=` is described here:
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#%5BUnit%5D%20Section%20Options
The `networking.service` and `ConditionKernelCommandLine` was picked from https://github.com/greenbone/ospd-openvas/blob/ospd-openvas-20.08/config/ospd-openvas.service
`gvmd.service` was added because no login within the GSA will work until the manager is up.
=> Updated systemd unit file:

CHANGELOG.md, gsa/src/web/pages/reports/details/summary.js
The "Hosts scanned" row in the report details was disappearing every time the page was reloading. Store count for scanned hosts in state to be able to display it the whole time.
**Checklist**:
=> fix disappearing scanned hosts

CHANGELOG.md, gsa/src/web/pages/nvts/nvtpreference.js, gsa/src/web/pages/scanconfigs/editdialog.js, gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js, gsa/src/web/pages/scanconfigs/scannerpreferences.js
In edit scan config dialog: Currently, if we change any value in scanner preferences, or open the edit nvt preferences dialog and edit the values there, the radio buttons are extremely slow to react (take 10-15s for me). This is because there are a lot of form fields, and they are ALL updated whenever one is changed. This is from setting form state using `useState`. Use `useReducer` instead, to set a single value in the state object instead of updating all the form values.
**Checklist**:
=> Improve performance of form fields in edit scan config dialog

CHANGELOG.md, gsa/src/web/entities/__tests__/filterprovider.js, gsa/src/web/entities/filterprovider.js, gsa/src/web/pages/reports/detailspage.js
Don't use the current stored filter of the results list page for loading results at the report details page.
**Checklist**:
=> Fix report result filter determination

CHANGELOG.md, gsa/public/locales/gsa-de.json, gsa/src/web/components/error/errorpanel.js, gsa/src/web/pages/reports/detailspage.js
=> Improve error message for undefined report formats on report detailspage

gsad/config/gsad.default, gsad/config/gsad.service.in
- Mention "daemon" and "gsad" in systemd unit description
- Allow to configure a user / group in gsad.default
- Remove the "Alias" which isn't required
- Add PIDFile call to systemd unit
- Make the EnvironmentFile mandatory
- Renamed a few variables
Changing `EnvironmentFile=${DEFAULT_CONFIG_DIR}/gsad` to `EnvironmentFile=-${DEFAULT_CONFIG_DIR}/gsad` is making the file mandatory:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=
This was done because the `gsad.service` is using the following:
```
ExecStart=${SBINDIR}/gsad --listen $GSA_ADDRESS --port $GSA_PORT $OPTIONS
```
which makes the gsad.default mandatory for the `$GSA_ADDRESS` and `$GSA_PORT`
Related: https://github.com/greenbone/gvmd/pull/1240, https://github.com/greenbone/ospd-openvas/pull/312
=> Minor systemd / config files updates:

gsa/src/web/graphql/__mocks__/alerts.js, gsa/src/web/graphql/__tests__/alerts.js, gsa/src/web/graphql/alerts.js, gsa/src/web/pages/tasks/component.js, gsa/src/web/pages/tasks/dialog.js, gsa/src/web/utils/testing/index.js
=> Load alerts into task dialog from graphql

.circleci/config.yml
We are currently using two different images for the circleci jobs. For
building gsa and gsad we are using our own images that run under the
root user. For the js jobs we are are using images from circleci which
run under a circleci user. If the yarn.lock file is changed and the
build_gsa job is run before a js job the circle ci cache contains files
where root is the owner and with a wrong directory. Afterwards the js
jons will fail during restoring the cache because the circleci user
can't access the files from the cache.
**Checklist**:
=> Try to fix permission of circleci cache

CHANGELOG.md, gsa/src/gmp/models/nvt.js
NVT solution was not parsed correctly and therefore it was missing on listpage and detailspage.
**Checklist**:
=> fix missing nvt solution type

gsa/public/locales/gsa-de.json, gsa/src/web/pages/extras/__tests__/feedstatuspage.js, gsa/src/web/pages/extras/feedstatuspage.js
Our previous implementation of the image loading indicator is not explicitly enough to explain what is happening. We should use text instead. Should not require a changelog entry because it doesn't contradict the previous one, and this is as "new feature"
**Checklist**:
=> Do not use image loading indicator for feed status updates

CHANGELOG.md, gsa/src/web/pages/extras/__tests__/feedstatuspage.js, gsa/src/web/pages/extras/feedstatuspage.js
Currently gsa decides a feed is too old if its last version was over 10 days old. GSA should not be deciding this unless it is really, really old, thus we changed it to 30 days.
**Checklist**:
=> Increase age for feed being too old

CHANGELOG.md, gsa/src/gmp/models/ovaldef.js
On the oval def details page the sub sections were all empty because of a parsing error in the oval def model.
(The error was similar to the one that caused https://github.com/greenbone/gsa/pull/2388)
**Checklist**:
=> fix missing oval def subsections

CHANGELOG.md, gsa/package.json
d3-shape 2.0 and d3-color 2.0 are using ES6 and with the merge of those new dependency versions we will also drop support for the outdated Edge 18 and older versions.
**Checklist**:
=> Drop Edge <= 18 support

CHANGELOG.md, gsa/src/web/pages/alerts/dialog.js
**What**:
There is the new alerts feature of starting a task upon the arrival of new secinfo. gvmd has it implemented in https://github.com/greenbone/gvmd/pull/957 and https://github.com/greenbone/gvmd/pull/960. This PR adds the start task option to the corresponding method selection.
**Why**:
Without these changes, the new feature would not be available in GSA.
**How**:
The "Start Task" event is pushed into the list of possible methods. From this list I chose the 'Start task' together with the secinfo event condition and clicked on "test alert". The corresponding task started.
**Checklist**:
- [N/A] Tests
=> Add option for "Start task" on "new secinfo arrived" for alerts

CHANGELOG.md, gsa/src/web/pages/reportformats/component.js, gsa/src/web/pages/reportformats/detailspage.js, gsa/src/web/pages/reportformats/listpage.js, gsa/src/web/pages/reportformats/row.js, gsa/src/web/pages/reportformats/table.js
**What**:
This PR removes export/download functionalities from listpage and detailspage, and bulk export for report formats.
**Why**:
Report formats can only be used, if signed correctly. Exported and reimported report formats are not signed correctly anymore and are therefore unusable, making the whole idea of exporting report formats obsolete.
**How**:
Icons and unnecessary props have been removed. The user can no longer click on those icons.
**Checklist**:
- [N/A] Tests
=> Remove ReportFormat export/download

gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/utils/__tests__/useTiming.js, gsa/src/web/utils/useTiming.js
**What**:
Allow to disable timers e.g. for reloading data like the tasks in the background
**Why**:
For testing purposes it should be possible to deactivate the reloading because most of the time reloading should not be part of a specific test and at the end running the timer function may lead to *randomly* failing test.
**How**:
Added new a new test for useTiming and run all task detail page tests.
**Checklist**:
=> Allow to not run timers

CHANGELOG.md, gsa/src/web/pages/usersettings/usersettingspage.js, gsa/src/web/utils/proptypes.js, gsa/src/web/utils/severity.js, gsad/src/gsad.c
**What**:
Remove the severity class 'bsi'
**Why**:
These classes are identical with the classes of 'nist'.
**How**:
**Checklist**:
=> Remove severity class 'bsi'

CHANGELOG.md, gsa/src/gmp/commands/users.js, gsa/src/web/components/chart/topology.js, gsa/src/web/components/dashboard/display/cvss/cvsstransform.js, gsa/src/web/components/dashboard/display/severity/severityclasstransform.js, gsa/src/web/pages/nvts/dashboard/familydisplay.js, gsa/src/web/pages/tasks/dashboard/highresults.js, gsa/src/web/pages/tasks/dashboard/mosthighresults.js, gsa/src/web/pages/usersettings/dialog.js, gsa/src/web/pages/usersettings/severitypart.js, gsa/src/web/pages/usersettings/usersettingspage.js, gsa/src/web/utils/proptypes.js, gsa/src/web/utils/severity.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_user.c, gsad/src/gsad_user.h
**What**:
The support for multiple severity class ranges is removed.
There is now only one classification scheme (then one previously
called "nist"). Actually there was only one other classification scheme called
"pci-dss". It wasn't used or needed.
For the user, this essentially means that in "My Settings", the option
to select a severity classification scheme is not there anymore and that
the default is now applied mandatory.
This PR requires: https://github.com/greenbone/gvmd/pull/1288
**Why**:
Removing the overhead about a dynamic handling where actually only static
class ranges are used simplifies code.
**How**:
Basically all aspects are removed, on gsa side, and on gvmd side.
While gvmd appears pretty clean now, in gsa there are some special
handlings with an old range style due to …
=> Drop dynamic severity classes

CHANGELOG.md, gsa/src/web/pages/reportformats/detailspage.js, gsa/src/web/pages/schedules/detailspage.js
**What**:
Change delete icons on report format detailspage and schedule detailspage to trashcan icons.
**Why**:
The report format detailspage and the schedule detailspage misleadingly show delete icons when it should be trashcan icons instead. Clicking on the icon moves the entities to the trashcan.
**How**:
**Checklist**:
=> use trash icons instead of delete icons for report formats and schedules

CHANGELOG.md, gsa/src/web/components/bar/__tests__/__snapshots__/compliancestatusbar.js.snap, gsa/src/web/components/bar/__tests__/compliancestatusbar.js, gsa/src/web/components/bar/__tests__/progressbar.js, gsa/src/web/components/bar/compliancestatusbar.js, gsa/src/web/components/bar/progressbar.js, gsa/src/web/pages/audits/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/audits/__tests__/__snapshots__/row.js.snap, gsa/src/web/pages/audits/__tests__/__snapshots__/table.js.snap
**What**:
Change compliance status bar to always show the ratio of compliant and none compliant results in red and green. 
**Why**:
Before, we used different colors for the bar for low, medium and high compliance. A compliance of 0% would just have a dark background since there were no compliant results. This made it seem as if 0% was not as bad as a low percentage which would be shown in red.
**How**:
**Checklist**:
Example of the new compliance status bar:
=> Change visual appearance of compliance status bar

CHANGELOG.md, gsa/src/web/pages/results/detailspage.js
**What**:
Change tooltip of override icon in result details.
**Why**:
Currently, the tooltip is "Overrides are applied.". This shows even on the result details, but that is misleading because we do not apply the new severity etc. on the result detailspage. 
**How**:
Manual testing in web app.
**Checklist**:
=> Change tooltip of override icon in result details

gsad/src/gsad_gmp.c
**What**:
severity class got deleted within gmp_authenticate_info_opts_t; hence gsad
cannot use auth.severity within authentication.
This is just a fix gsad building the other occurrences of severity should
be checked as well.
**Why**:
Unable to build gsad based on gvm-libs based on master
**How**:
1. build and install newest gvm-libs from master branch
2. build gsad
**Checklist**:
=> fix: severity field within gmp_authenticate_info_opts_t got deleted

gsad/src/gsad_gmp.c, gsad/src/gsad_gmp_auth.h, gsad/src/gsad_user.c, gsad/src/gsad_user.h
**What**:
with only the deletion of  auth_opts.severity = severity; there were
malloc issues hence I remove every occurence of it within the
authentication process.
**Why**:
Due to
```
malloc(): unsorted double linked list corrupted
```
based on the nil pointer gsad got unresponsive.
**How**:
**Checklist**:
=> remove severity from authentication process

CHANGELOG.md, gsa/src/web/graphql/__mocks__/portlists.js, gsa/src/web/graphql/__tests__/portlists.js, gsa/src/web/graphql/portlists.js, gsa/src/web/pages/targets/component.js
**What**:
Loads port lists into target dialog.
**Why**:
Because task dialog can access target dialog which can access portlists, so we want to do this with graphql.
**How**:
**Checklist**:
=> Load port lists into target component with graphql

CHANGELOG.md, gsa/src/web/graphql/__mocks__/notes.js, gsa/src/web/graphql/__tests__/notes.js, gsa/src/web/graphql/notes.js, gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/pages/tasks/detailspage.js
**What**:
Implement useLazyGetNotes query for GSA and load notes at task detailspage
**Why**:
In order to use the new backend
**How**:
Correct number of notes is shown at the notes icon, link is working, automatic tests were adjusted and passed
**Checklist**:
=> Load Notes via graphql into task detailspage

CHANGELOG.md, gsa/public/locales/gsa-de.json, gsa/src/web/pages/usersettings/dialog.js, gsa/src/web/pages/usersettings/filterpart.js
**What**:
Remove the "Secinfo Filter" form part form user settings dialog and remove instances of the `secInfoFilter` variable. Also remove translations for that form field.
**Why**:
Because we no longer have all secinfo and it's confusing to leave that in the dialog.
**How**:
Tests are still passing and it is visually verified to be gone.
**Checklist**:
=> Remove secinfo filter from user settings dialog and elsewhere

CHANGELOG.md, gsa/src/gmp/models/__tests__/tlscertificate.js, gsa/src/gmp/models/tlscertificate.js
**What**:
The TLS certificates model needs to be able to parse the certificate without errors even if the report sub element is not defined.
**Why**:
If a user tries to download a TLS certificate that he is not the owner of it will cause an error in gsa. This happens because the report sub element is missing from the get_tls_certificates response. gsa needs to be able to deal with this case.
**How**:
Tested in gsa. There is no error any more and the TLS certificate is downloaded successfully. The tests for the TLS certificate model have also been adjusted.
**Checklist**:
=> Fix tls certificate download 20.08

CHANGELOG.md, gsa/src/web/components/processmap/processmap.js
**What**:
For a new process map it was not possible to delete a process without having had an edge created first. BPM crashed in that case. The crash now no longer happens.
**Why**:
To fix above mentioned bug
**How**:
Created a new user and go to BPM. Created a process and _no_ edge. Deleted that process and saw BPM not crash.
An automated test was not written for this functionality, because it would only be possible to get an very indirect test _at best_.
**Checklist**:
- [N/A] Tests
=> Allow to delete process without having had edges

CHANGELOG.md, gsa/src/gmp/models/credential.js, gsa/src/web/graphql/__mocks__/credentials.js, gsa/src/web/graphql/__tests__/credentials.js, gsa/src/web/graphql/credentials.js, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/targets/component.js
**What**:
Add mutation for createCredential and corresponding test.
Create credentials with graphql in target component.
Create credentials with graphql in alert component.
**Why**:
It is possible to open the target dialog and the alert dialog from the task dialog. Both dialogs offer the option to create a credential. Therefore, the target component and the alert component need to use graphql to create the credentials.
**How**:
Tested in gsa for all credential types in both dialogs.
**Checklist**:
=> Create credential with graphql

gsa/src/web/entities/bulkactions.js, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/alerts/dialog.js, gsa/src/web/pages/portlists/component.js, gsa/src/web/pages/reports/detailspage.js, gsa/src/web/pages/scanconfigs/editdialog.js, gsa/src/web/pages/scanconfigs/scannerpreferences.js, gsa/src/web/pages/schedules/component.js, gsa/src/web/pages/tasks/component.js, gsa/src/web/utils/__tests__/stateReducer.js, gsa/src/web/utils/stateReducer.js
**What**:
This PR refactors the TaskComponent to unify the state object into one with `useReducer`. It also refactors `stateReducer` to reduce boilerplate, as this function is mostly for replacing `this.setState` for setting large states and will never have any other usecase, I thought all of the boilerplate e.g. `dispatch({type: 'setState', newState: {...}})` is unnecessary. Now we have an action creator `updateState` and pure state updates (with no other logic) can be called with `dispatch(updateState({stateA: 'foo', stateB: 'bar'}))` etc. Adds a test suite for `stateReducer`.
Also, adjusted other components using `stateReducer` to the new syntax. Composed certain (not all. See editnvtdetailsdialog for example of reducer that doesn't need stateReducer logic) custom reducers with …
=> Refactor task component and stateReducer

CHANGELOG.md, gsad/src/gsad.c
Required to work with glibc >= 2.32.
https://sourceware.org/pipermail/libc-announce/2020/000029.html
The deprecated arrays sys_siglist, _sys_siglist, and sys_sigabbrev
are no longer available to newly linked binaries, and their declarations
have been removed from <string.h>. They are exported solely as
compatibility symbols to support old binaries. All programs should use
strsignal instead.
**What**: Same as https://github.com/greenbone/gvmd/pull/1280
**Why**: Same as https://github.com/greenbone/gvmd/pull/1280
**How**: Same as https://github.com/greenbone/gvmd/pull/1280
**Checklist**:
=> Replace deprecated sys_siglist with strsignal

CHANGELOG.md, gsa/src/web/components/form/__tests__/field.js, gsa/src/web/components/form/__tests__/textarea.js, gsa/src/web/components/form/field.js, gsa/src/web/components/form/textarea.js, gsa/src/web/components/form/textfield.js
**What**:
Update form fields to fix a typo, a bug and to remove obsolete behavior.
**Why**:
Cleanup and fixing of form fields.
**How**:
All tests still run, linting is happy and verified that some form fields are still working manually.
**Checklist**:
=> Update form fields

.github/dependabot.yml
**What**:
Change target branch for dependabot to 21.04.
**Why**:
21.04 needs almost the same dependency updates as master. Since we cannot use dependabot for 2 branches at once, moving it to 21.04 and then later merging the changes into master seems to be the solution that will cost the least time and effort.
**How**:
**Checklist**:
=> change dependabot target branch to 21.04

CHANGELOG.md, gsa/src/web/pages/hosts/detailspage.js
**What**:
Exchange the icon
**Why**:
Hosts don't get moved to the trashcan, therefore the icon is misleading.
**How**:
Visual inspection that the icon was properly replaced.
**Checklist**:
- [N/A] Tests
=> Change TrashIcon to DeleteIcon on host detailspage

CHANGELOG.md, gsa/src/gmp/models/__tests__/alert.js, gsa/src/gmp/models/alert.js, gsa/src/web/entity/icon/observericon.js, gsa/src/web/graphql/__mocks__/alerts.js, gsa/src/web/graphql/alerts.js, gsa/src/web/pages/alerts/__tests__/listpage.js, gsa/src/web/pages/alerts/component.js, gsa/src/web/pages/alerts/listpage.js, gsa/src/web/pages/alerts/row.js
**What**:
Convert alerts listpage to use graphql get_alerts and implement parseObject for alerts.
**Why**:
**How**:
Manual and unit testing.
**Checklist**:
=> Implement get_alerts on alerts listpage via graphql, and implement parseObject

CHANGELOG.md, gsa/src/web/pages/portlists/component.js
**What**:
Compare port range start and end via their integer value instead of their string value.
**Why**:
Comparing strings is plain wrong here. It probably happened because of the change of the xml parser.
**How**:
Confirmed by adding a new port range that has a higher first digit at the start than the first digit of its end. No error was thrown and no existing automated test failed.
**Checklist**:
- [N/A] Tests
=> Fix port range check when editing portlists

CHANGELOG.md, gsa/src/web/pages/reports/deltadetailspage.js
**What**:
Always send sort=name with delta report request filters.
**Why**:
To avoid confusion due to differing numbers of results and broken sort-reverse terms.
**How**:
Check whether the filter sent to gvmd always includes sort=name and never anything else or a sort-reverse term.
**Checklist**:
- [N/A] Tests
=> Always send sort=name with delta report request filters

CHANGELOG.md, gsa/src/gmp/models/__tests__/alert.js, gsa/src/web/entity/__tests__/useExportEntity.js, gsa/src/web/entity/useExportEntity.js, gsa/src/web/graphql/__mocks__/alerts.js, gsa/src/web/graphql/__tests__/alerts.js, gsa/src/web/graphql/alerts.js, gsa/src/web/pages/alerts/__tests__/detailspage.js, gsa/src/web/pages/alerts/detailspage.js
**What**:
This PR refactors the detailspage to use graphQL related commands such as adding clone/delete/export handlers. It also adds a custom hook to handle exporting entities via graphQL in the same vein as the new bulk action custom hooks.
**Why**:
Manual and unit testing. 
**How**:
**Checklist**:
=> Implement get_alert via graphql and preliminary refactor of alert detailspage

CHANGELOG.md, gsa/src/web/pages/alerts/dialog.js, gsa/src/web/pages/alerts/filtercountleastconditionpart.js
**What**:
Add "Filter x matches at least y results" condition to task events in alert dialog
**Why**:
This option was present in older versions
**How**:
Created an alert and a filter that would match at least 1 result. After the task status changed to 'Done' the event 'Start task' was called, showing that the new option works with task events.
**Checklist**:
- [N/A] Tests
=> Add "Filter x matches at least y results" condition to task events in alert dialog

CHANGELOG.md, gsa/src/web/components/form/useFormValidation.js
**What**:
While converting the regexp :alnum: to JS (that doesn't have a 1:1 equivalent) äüöÄÜÖß where dropped from the list of allowed characters. This PR reintroduces them to the regexp that is used for checking the "name" fields in forms.
**Why**:
**How**:
Created a process with äüöÄÜÖß in the name. There was no error message any more.
**Checklist**:
- [N/A] Tests
=> Allow umlauts and ß in object names

CHANGELOG.md, gsa/src/gmp/__tests__/model.js, gsa/src/gmp/model.js, gsa/src/gmp/models/__tests__/permission.js, gsa/src/gmp/models/__tests__/reportformat.js, gsa/src/gmp/models/permission.js, gsa/src/gmp/models/reportformat.js, gsa/src/gmp/utils/entitytype.js, gsa/src/web/entity/__tests__/link.js, gsa/src/web/entity/icon/observericon.js, gsa/src/web/entity/link.js, gsa/src/web/graphql/__mocks__/alerts.js, gsa/src/web/graphql/__mocks__/permissions.js, gsa/src/web/graphql/__mocks__/report_formats.js, gsa/src/web/graphql/__tests__/permissions.js, gsa/src/web/graphql/__tests__/report_formats.js, gsa/src/web/graphql/permissions.js, gsa/src/web/graphql/report_formats.js, gsa/src/web/pages/alerts/__tests__/detailspage.js, gsa/src/web/pages/alerts/__tests__/listpage.js, gsa/src/web/pages/alerts/detailspage.js
**What**:
Do not use gmp to load the permissions and report formats required for the alert detailspage. Use as little gmp and HOC as possible. Eventually we'll get rid of withEntityContainer.
- Implemented parseObject for report formats and permissions and tested those
- implemented parseModelFromObject and tested this
- Implemented get_alerts and get_report_formats query tests
- Adjusted detailslink to be able to distinguish between hyperion and gmp entities (to parse them differently)
- Adjusted detailspage tests and mocks to accept the new command mocks
- Use refetchAlert() and refetchPermissions() for onChanged
**Why**:
**How**:
Manual and unit testing.
**Checklist**:
=> Implement get_report_formats and get_permissions via graphQL on alert detailspage

CHANGELOG.md, gsa/src/web/entities/__tests__/useEntitiesTimeout.js, gsa/src/web/entities/useEntitiesTimeout.js, gsa/src/web/entity/__tests__/useEntityTimeout.js, gsa/src/web/entity/useEntityTimeout.js, gsa/src/web/pages/alerts/__tests__/detailspage.js, gsa/src/web/pages/alerts/detailspage.js, gsa/src/web/pages/alerts/listpage.js
**What**:
Refactor detailspage to get rid of `withEntityContainer`. Implemented `useEntitiesTimeout` and `useEntityTimeout` for alert listpage and detailspage
**Why**:
**How**:
**Checklist**:
=> Refactor alerts detailspage to not use withEntityContainer

CHANGELOG.md, gsa/src/gmp/models/__tests__/certbund.js, gsa/src/gmp/models/__tests__/cpe.js, gsa/src/gmp/models/__tests__/dfncert.js, gsa/src/gmp/models/__tests__/ovaldef.js, gsa/src/gmp/models/certbund.js, gsa/src/gmp/models/cpe.js, gsa/src/gmp/models/dfncert.js, gsa/src/gmp/models/ovaldef.js
**What**:
Fixing the severity for several Advisories
**Why**:
The parameter name recently changed in gvmd
**How**:
**Checklist**:
=> Fixing the severity for several Advisories

CHANGELOG.md, gsa/src/web/graphql/__tests__/scanconfigs.js, gsa/src/web/graphql/scanconfigs.js, gsa/src/web/pages/scanconfigs/__tests__/editdialog.js, gsa/src/web/pages/scanconfigs/component.js, gsa/src/web/pages/scanconfigs/detailspage.js, gsa/src/web/pages/scanconfigs/scannerpreferences.js
**What**:
Currently, getLazyQuery does not return a promise. Implement a custom hook that invokes the Apollo client directly that returns such a promise. Also, some minor adjustments to support using hyperion scan configs in the edit dialog.
**Why**:
**How**:
**Checklist**:
=> Implement loadScanConfigPromise for scan config component

CHANGELOG.md, gsa/src/web/pages/alerts/condition.js
**What**:
Show the correct direction of severity change in the condition column of alerts.
**Why**:
The logic behind selecting the correct value was incorrect. It was impossible to get "Severity level changed" and instead we always got "Severity level increased"
**How**:
I created 3 alerts, one for each condition, and visually checked whether the correct value was displayed. After editing those alerts the conditions were correctly updated. The alerts were created by sending the correct parameters to gvmd, so it was really just a displaying error.
**Checklist**:
- [N/A] Tests
=> Fix display of severity level change alert condition

CHANGELOG.md, gsa/public/locales/gsa-de.json, gsa/src/web/pages/hosts/detailspage.js
**What**:
Add an icon and filtered link from the host detailspage to a TLS certificates list with certs that have been found on this host. Use the "new" `host_id=` filter.
**Why**:
This was specified in the feature request for TLS Certificates as assets but was not implemented, yet, because the `host_id=` filter term didn't exist back then.
**How**:
Go to host detailspage, find new icon, click it and find yourself on a filtered TLS Certificate listpage.
**Checklist**:
- [N/A] Tests
=> Link from Hosts to TLS Certificates

CHANGELOG.md, gsad/src/gsad.c, gsad/src/gsad_http.c, gsad/src/gsad_http.h, gsad/src/gsad_http_handler.c, gsad/src/gsad_http_handler.h, gsad/src/gsad_params.h
**What**:
Fix compiling gsad with libmicrohttp 0.9.71 and later
**Why**:
ibmicrohttp 0.9.71 changed the return value of the request handler callback functions. This causes a compiler warning with newer distributions like Ubuntu 20.10. Because we treat warnings as errors (`-Wall`) the compilation fails on such systems.
**How**:
Build gsad on Ubuntu 20.10 successfully.
**Checklist**:
=> Fix compiling gsad with libmicrohttp >= 0.9.71

CHANGELOG.md, gsa/src/web/pages/permissions/multipledialog.js
**What**:
Fix initial value of dropdown for including related resources for permissions in MultiplePermissionsDialog
**Why**:
When the dropdown is initialized with "include related resources", but later there aren't any, the Select component will show a label- and useless value "1". Now we have "for current resource only" as standard if there are no related resources, and a "include related resources" if there are.
**How**:
Visual inspection of the options in the dropdown for entities with and without resources. Also the console doesn't throw a prop warning for Downshift anymore.
**Checklist**:
- [N/A] Tests
=> Fix selection for including related resources in permission dialog

CHANGELOG.md, gsa/src/gmp/models/__tests__/user.js, gsa/src/gmp/models/user.js, gsa/src/web/pages/users/detailspage.js, gsa/src/web/pages/users/row.js
**What**:
Disable the clone icon for superadmin users.
**Why**:
Superadmins can't be cloned, it doesn't make sense to offer the option just to throw an error.
**How**:
**Checklist**:
=> Disable clone icon for superadmin users on listpages and detailspages

CHANGELOG.md, gsad/src/gsad_gmp.c
**What**:
Skip elements in MODIFY_USER that would prevent a superadmin from saving themself.
**Why**:
Superadmins should be able to edit themselves.
**How**:
Login as superadmin s.   Menu > Users.  Click edit icon for user s.  Edit comment.  Click Save.
**Checklist**:
=> Ensure superadmins can edit themselves

CHANGELOG.md, gsa/src/web/pages/extras/cvsscalculatorpage.js, gsa/src/web/pages/extras/feedstatuspage.js, gsa/src/web/pages/extras/trashcanpage.js, gsa/src/web/pages/start/__tests__/page.js, gsa/src/web/pages/start/page.js
**What**:
Don't grow the toolbar on pages where there is only the help icon. This is achieved by simply wrapping it into a span.
**Why**:
The clickable area to link to the manual spread to 100% width of the screen. Other pages (e.g. tickets) already had a reduced click area, because their toolbar is wrapped already.
**How**:
Manually check whether the clickable areas are reduced to the icon on the 4 pages in question and if the links still work. Also updated the startpage test.
**Checklist**:
=> Stop toolbars from growing if they have only the help icon

gsa/src/web/graphql/__mocks__/schedules.js, gsa/src/web/pages/schedules/__tests__/detailspage.js, gsa/src/web/pages/schedules/__tests__/listpage.js
**What**:
Old schedule tests uses a mock schedule that recurs weekly. The problem with that is, if system time changes, so will the Next Run dates. In lieu of setting a mock date, I modify the mock schedule to run once.
**Why**:
**How**:
**Checklist**:
=> Fix schedule tests

gsa/package.json, gsa/src/gmp/http/transform/default.js, gsa/src/gmp/http/transform/fastxml.js, gsa/src/web/components/chart/line.js, gsa/src/web/components/chart/utils/arc.js, gsa/src/web/components/chart/utils/path.js, gsa/src/web/components/powerfilter/dialogproptypes.js, gsa/src/web/utils/cpe.js, gsa/src/web/utils/os.js, gsa/src/web/utils/proptypes.js, gsa/yarn.lock
**What**:
Update to the latest react-scripts (create-react-app) release.
Please be aware after checking out the changes in the PR it is very likely required to delete the node_modules directory and re-install all dependencies with running yarn.
**Why**:
We want up to date versions of jest, eslint and babel.
**How**:
Run `yarn test` and checked all unit tests.
**Checklist**:
=> Update react scripts for 21.04

CHANGELOG.md, gsa/src/web/pages/audits/component.js
**What**:
Refactors component into function. I have decided to not use graphQL queries in lieu of loaders and selectors, at this stage because adding passive queries would necessitate changing listpage and detailspage tests to add mocks and I would like to keep them the same for now.
**Why**:
**How**:
Manually tested. Everything still works as normal.
**Checklist**:
=> Refactor Audit Component into Function

CHANGELOG.md, gsa/src/web/graphql/__mocks__/policies.js, gsa/src/web/graphql/__tests__/policies.js, gsa/src/web/graphql/policies.js, gsa/src/web/pages/policies/component.js
**What**:
**Why**:
**How**:
Manual and auto testing. 
**Checklist**:
=> Implement policy component mutations

gsa/src/web/graphql/__mocks__/hosts.js, gsa/src/web/graphql/__tests__/hosts.js, gsa/src/web/graphql/hosts.js, gsa/src/web/pages/hosts/__tests__/detailspage.js, gsa/src/web/pages/hosts/component.js, gsa/src/web/pages/hosts/detailspage.js
**What**:
Add mutations for create host, modify host and delete identifier.
**Why**:
**How**:
**Checklist**:
=> Implement host mutations

CHANGELOG.md, gsa/src/web/pages/alerts/detailspage.js, gsa/src/web/pages/alerts/listpage.js, gsa/src/web/pages/hosts/detailspage.js, gsa/src/web/pages/hosts/listpage.js, gsa/src/web/pages/policies/detailspage.js, gsa/src/web/pages/policies/listpage.js, gsa/src/web/pages/scanconfigs/detailspage.js, gsa/src/web/pages/schedules/detailspage.js, gsa/src/web/pages/schedules/listpage.js, gsa/src/web/pages/tasks/listpage.js, gsa/src/web/utils/__tests__/useDefaultReloadInterval.js, gsa/src/web/utils/useDefaultReloadInterval.js
**What**:
Fix setting reload interval calculation for all pages using useEntityReloadInterval and useEntitiesReloadInterval hooks.
**Why**:
These two hooks are considering the active status of the entity. The activate status has only a meaning for the reload interval for the task (audit) and report entities where activate depends on the scan status. Therefore if an entity has been active the reload interval has been set to three seconds which is way to often for not changing entities.
**How**:
Added new unittest and run all tests
**Checklist**:
=> Fix reload inteval calculation

gsa/src/web/entities/filterprovider.js
**What**:
Don't mutate the filter in the filter provider
**Why**:
A filter instance should not be mutated if you are not creating a new
filter or if you are not working on a copy of the original filter.
Changing an existing filter in place might have serious impact on other
places where it is used. For example if the filter is put into the redux
store the stored filter is changed too! to avoid that always use a copy
of the original filter before changing it.
**How**:
**Checklist**:
- n/a Tests
- n/a [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry
=> Don't mutate the filter in the filter provider

gsa/src/gmp/models/note.js
**What**:
Remove isInTrash() from Note model
**Why**:
It's obsolete, because it's in the general model already
**How**:
Automated tests are successful and the notes list- and detailspage were visually rendering fine.
**Checklist**:
- [N/A] Tests
=> Remove isInTrash() from Note model

gsa/src/web/components/tab/tab.js, gsa/src/web/pages/audits/__tests__/__snapshots__/detailspage.js.snap, gsa/src/web/pages/reports/__mocks__/mockreport.js, gsa/src/web/pages/reports/__tests__/detailspage.js
**What**:
Add tests for report detailspage.
**Why**:
The page does not have tests yet and we need them before we can start refactoring.
**How**:
**Checklist**:
=> Report detailspage tests

gsa/src/web/pages/results/__tests__/listpage.js
**What**:
Add tests for results listpage.
**Why**:
The page doesn't have tests yet and we need them before we can start refactoring.
**How**:
**Checklist**:
=> add tests for results listpage

CHANGELOG.md, gsa/src/gmp/models/__tests__/setting.js, gsa/src/gmp/models/setting.js, gsa/src/web/graphql/__mocks__/auth.js, gsa/src/web/graphql/__tests__/auth.js, gsa/src/web/graphql/__tests__/reportformats.js, gsa/src/web/graphql/__tests__/settings.js, gsa/src/web/graphql/auth.js, gsa/src/web/graphql/reportformats.js, gsa/src/web/graphql/settings.js, gsa/src/web/pages/audits/component.js
**What**:
- Converts audit component to no longer use any redux. Load all entities with GraphQL. Auxiliary entities should also be loaded via GraphQL
- Implement `useLazyGetReportFormats`, `useLazyGetSettings` and `useGetUsername`
- Implement helper function `getSettingValueByName`
**Why**:
**How**:
**Checklist**:
=> Implement audit component queries

CHANGELOG.md, gsa/src/gmp/models/__tests__/cpe.js, gsa/src/gmp/models/cpe.js, gsa/src/web/pages/cpes/details.js
**What**:
* Added the deprecated_by field to CPEs (again?)
**Why**:
* This field was missing. While refactoring CPEs for GraphQL I came across this field in the `details.js`. So I parsed the field in the model:
**How**:
**Checklist**:
=> Added the deprecated_by field to CPEs

gsa/src/gmp/parser/cvss.js
From codespell:
```
./gsa/src/gmp/parser/cvss.js:25: percision ==> precision
```
Seems the typo already existed in the original / linked .js file. That typo doesn't exist in the gsa-20.08 branch so i have created the PR against master.
=> Fix a typo.

CHANGELOG.md, gsa/src/web/pages/scanners/__tests__/__snapshots__/dialog.js.snap, gsa/src/web/pages/scanners/__tests__/dialog.js, gsa/src/web/pages/scanners/dialog.js
**What**:
Change default port value to 22.
**Why**:
Because 9391 is incorrect for certain scanner types.
**How**:
Adjusted tests and manual confirmation.
**Checklist**:
=> Fix default port value for scanner dialog

gsa/src/web/entities/usePagination.js, gsa/src/web/pages/alerts/listpage.js, gsa/src/web/pages/audits/listpage.js, gsa/src/web/pages/cves/listpage.js, gsa/src/web/pages/notes/listpage.js, gsa/src/web/pages/policies/listpage.js, gsa/src/web/pages/scanconfigs/listpage.js, gsa/src/web/pages/schedules/listpage.js, gsa/src/web/pages/tasks/listpage.js
**What**:
Remove simpleFilter from list pages.
**Why**:
The simpleFilter is always created the same. Therefore it is duplicated code spread across several list pages.
**How**:
Run all testcase to check if something did break.
**Checklist**:
=> Remove simple filter from list pages

gsa/src/web/pages/targets/dialog.js
**What**:
Improve the wording for the allowSimultaneousIPs option in the target dialog
**Why**:
The wording of the label might be a bit inaccurate. Therefore improve the label.
**How**:
**Checklist**:
=> Improve wording of label for allowSimultaneousIPs

gsad/src/gsad.c
With 21.04 GSAD will not be executed in http but in socket_mode behind a
nginx. Therefore it doesn't make sense to start socket_mode as an
subprocess of gsad and start gsad in http mode afterwards.
This removes only the bg start so that gsad.c can pick it up and start in fg:
https://github.com/greenbone/gsa/blob/master/gsad/src/gsad.c#L3160
**What**:
**Why**:
**How**:
**Checklist**:
=> [gsad] Change socket_mode that it will not run besides the main process

gsa/src/web/pages/scanconfigs/editconfigfamilydialog.js
**What**:
The edit scan config dialog still relies on the NVT oid prop being `oid` instead of `id` because it still does not support hyperion. This will fix selecting nvts, sorting and fix selected nvts not being checked by reverting some changes to the dialog. The changes should be made again when hyperion is fully supported.
**Why**:
If we work on scan config further it would be inconvenient if we cannot interact with the dialog properly.
**How**:
Tests are still passing and the dialog works as expected.
**Checklist**:
=> Fix edit scan config family dialog

CHANGELOG.md, gsad/src/gsad_gmp.c
**What**:
Use `params_value()` instead of `params_value_bool()` for getting `allow_simultaneous_ips`.
**Why**:
Although the underlying value is bool we should not use params_value_bool for retrieving the value of reverse_lookup_only because it would break the mechanism of setting a default value for the setting.
params_value() returns a string ("0" or "1") if there is an value and NULL if not. params_value_bool() return 0 if the value is "0"
OR there is no value. This means that if we want to be able to set a default if there is no value (NULL) we need to use params_value() else the information is lost.
Fix crash.
**How**:
Created target with and without PR. Without PR gsad crashes. 
**Checklist**:
=> Use params_value instead of params_value_bool for allow_simultaneous_ips

CHANGELOG.md, gsad/src/gsad.c
**What**:
Allow to set owner, group and mode of the unix socket where gsad is
listening on.
**Why**:
We need to be able to adjust these permissions.
**How**:
**Checklist**:
=> Allow to set unix socket permissions

CHANGELOG.md, gsa/src/gmp/models/__tests__/result.js, gsa/src/gmp/models/result.js, gsa/src/web/graphql/__mocks__/results.js, gsa/src/web/graphql/__tests__/results.js, gsa/src/web/graphql/results.js, gsa/src/web/pages/nvts/references.js, gsa/src/web/pages/results/__tests__/detailspage.js, gsa/src/web/pages/results/details.js, gsa/src/web/pages/results/detailspage.js
**What**:
Refactor results detailspage to use graphql queries instead of gmp commands.
The overrides and delta results section of the detailspage have not been refactored yet and will follow in later PRs.
**Why**:
The results detailspage is still using gmp commands.
Overrides will be added once they are working correctly again and the behaviour can be tested properly. Delta results will be added in another separate PR together with the deltareportspage.
WithEntityContainer is still used for the export until useEntityExport has been adjusted for single entity exports. 
CVE results might still cause problems and will be adjusted after changes to the NVTs.
**How**:
**Checklist**:
=> Refactor results detailspage

CHANGELOG.md, gsa/src/web/pages/tasks/__tests__/actions.js, gsa/src/web/pages/tasks/actions.js
**What**:
Show the start icon for scheduled tasks at the actions column the task listpage.
**Why**:
There is a discrepancy between task detailspage and listpage. The listpage didn't allow to manually start a task. The detailspage, however, offered this functionality. In order to avoid cumbersome searching for functions, the actions on the listpage and detailspage are nowequalized.
**How**:
**Checklist**:
=> Show StartIcon for scheduled tasks on task listpage

CHANGELOG.md, gsad/src/gsad.c
**What**:
The request parameters host, hostport, hostpath, hosts and hosts_opt and
their aliases can now all contain underscores and hyphens.
**Why**:
To allow uses to specify hosts with these characters, for example as scan targets.
**How**:
By trying to create a target that contains an underscore.
**Checklist**:
=> Allow underscores and hyphens in host parameters

CHANGELOG.md, gsa/src/web/graphql/__mocks__/targets.js, gsa/src/web/graphql/targets.js, gsa/src/web/pages/targets/details.js, gsa/src/web/pages/targets/row.js
**What**:
Adjust graphql queries for targets. Remove port range fields and rename maxHosts to hostCount.
**Why**:
The target schema in Hyperion was changed. The queries in gsa needed to be adjusted accordingly.
**How**:
**Checklist**:
=> Fix targets master

CHANGELOG.md, gsa/src/web/pages/scanners/dialog.js
**What**:
For creating a scanner use the greenbone sensor as default scanner type
when opening the dialog.
**Why**:
Customers may be confused by adding a OSP scanner because current sensors are based on OSP too.
**How**:
**Checklist**:
=> Pre-select greenbone sensor as default scanner type

CHANGELOG.md, gsa/src/gmp/models/__tests__/cve.js, gsa/src/gmp/models/__tests__/result.js, gsa/src/gmp/models/cve.js, gsa/src/gmp/models/result.js, gsa/src/web/pages/results/details.js, gsa/src/web/pages/results/row.js
**What**:
Introduced a new method for the Cve model `fromResultElement` to parse CVE type results to avoid unnecessary changes to `Cve.fromElement` (using the latter won't work correctly for the result rows) Also changed `result.nvt` to be `result.information` for clarity, wherever changing it does not alter too much of the code base.
This should not be forward ported, as result entity is very different there.
**Why**:
CVE reports are currently broken because the cve type results are being parsed as NVTs which leads to missing and undefined fields.
**How**:
Unit tests on the models. Also manually confirmed that CVE reports now do not show errors and the results listpage filtered for a CVE report does not show errors.
**Checklist**:
=> Fixed result CVE parsing for result listpage and CVE reports

CHANGELOG.md, gsa/src/web/pages/usersettings/dialog.js
**What**:
The dynamic severity checkbox can be clicked now. It reliably sends the right information.
**Why**:
It was broken before.
**How**:
Manual verification.
**Checklist**:
=> Fix dynamic severity checkbox not being checked upon clicking

CHANGELOG.md, gsa/src/web/pages/results/dashboard/index.js
**What**:
Don't show word cloud as default in result dashboard.
**Why**:
It should not be shown by default
**How**:
Load default dashboard and verify that said display is not visible.
**Checklist**:
- [N/A] Tests
=> Don't show word cloud as default in result dashboard

CHANGELOG.md, gsa/src/web/pages/results/__tests__/listpage.js, gsa/src/web/pages/results/dashboard/index.js
**What**:
backport to master: https://github.com/greenbone/gsa/pull/2883
**Why**:
**How**:
Adjust automatic test, visually inspect results dashboard
**Checklist**:
=> Don't show word cloud as default in result dashboard (manual backport #2883)

CHANGELOG.md, gsa/src/web/pages/notes/dialog.js
**What**:
Set the correct value in the result uuid textfield in the notes dialog.
**Why**:
This allows to change the result UUID in the notes dialog. If it hasn't been set while creating a new note, the id was unchangeable, or at least not changeable to a valid UUID. It was rather taking the value of the _choice_ whether to use a UUID or not.
**How**:
**Checklist**:
- [N/A] Tests
=> Set result UUID in note dialog

CHANGELOG.md, gsa/src/gmp/models/__tests__/result.js, gsa/src/gmp/models/result.js
**What**:
CVE results do not have a name. Use the name of the information sub element instead so it can be displayed on the detailspage.
**Why**:
For CVE results the name was missing on the detailspage.
**How**:
**Checklist**:
=> fix missing name for cve results

CHANGELOG.md, gsa/src/web/pages/scanconfigs/nvtfamilies.js
**What**:
Automatically send trend:0 (static) when a whole-selection only family is unselected.
Needs https://github.com/greenbone/gvmd/pull/1517
**Why**:
gvmd needs an explicit trend:0 with an unselected whole-selection family
**How**:
Observe automatic radio button changes when selecting/unselecting a whole-selection family, verify that the old behavior still works for all other families (no automatic changes), and check parameters in network request.
**Checklist**:
=> Fix changing Trend and Select for NVT-families and whole selection only

CHANGELOG.md, gsa/src/gmp/models/__tests__/audit.js, gsa/src/gmp/models/__tests__/task.js, gsa/src/gmp/models/audit.js, gsa/src/gmp/models/scanconfig.js, gsa/src/gmp/models/task.js, gsa/src/web/graphql/__mocks__/audits.js, gsa/src/web/graphql/__mocks__/tasks.js, gsa/src/web/graphql/audits.js, gsa/src/web/graphql/policies.js, gsa/src/web/graphql/tasks.js, gsa/src/web/pages/audits/__tests__/__snapshots__/detailspage.js.snap, gsa/src/web/pages/audits/__tests__/actions.js, gsa/src/web/pages/audits/__tests__/detailspage.js, gsa/src/web/pages/audits/__tests__/row.js, gsa/src/web/pages/audits/__tests__/table.js, gsa/src/web/pages/audits/details.js, gsa/src/web/pages/tasks/__mocks__/mocktasks.js, gsa/src/web/pages/tasks/__tests__/details.js, gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/pages/tasks/__tests__/trend.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tasks/row.js, gsa/src/web/pages/tasks/trend.js
**What**:
Carries over changes from https://github.com/greenbone/hyperion/pull/133 to ensure that audits listpage and detailspage do not crash and display the correct information. This only addresses changes to task/audit FIELDS to make sure everything displays. These changes are not complete and do not address everything in the linked pull request. Add back some tests that were missing to make sure both parseObject and parseElement work.
**Why**:
**How**:
Manually testing and adjusting unit tests.
**Checklist**:
=> Adjust tasks and audits to display correct information on listpage and detailspage

CHANGELOG.md, gsa/src/web/pages/schedules/dialog.js
When adding a new schedule with a numbers only name `1234` and daily
re occurrence and trying to edit the new schedule than a:
```
TypeError: e.replace is not a function
```
occurs because name is a number and not a string.
To fix that name.toString() is called to explicitly cast it to string.
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix unable to edit schedules with number only name

CHANGELOG.md, gsa/src/web/pages/radius/dialog.js
**What**:
Backport from [#2891](https://github.com/greenbone/gsa/pull/2891)
Use value of dialog internal state for secret key in radius dialog.
**Why**:
The value was fixed and unchangeable.
**How**:
Manual tests
**Checklist**:
=> Fix setting Radius secret key in dialog

CHANGELOG.md, gsa/src/web/pages/scanners/component.js
**What**:
Make https://github.com/greenbone/gsa/pull/2867 work by not presetting the type parameter for the dialog
**Why**:
Greenbone Sensor was still not pre-selected
**How**:
manual test
**Checklist**:
=> Fix "Pre-select greenbone sensor as default scanner type"

CHANGELOG.md, gsa/src/web/pages/scanners/component.js
**What**:
This is a manual backport of https://github.com/greenbone/gsa/pull/2924 because the differences between branches were too big to handle such a small change well.
**Why**:
**How**:
**Checklist**:
=> Fix "Pre-select greenbone sensor as default scanner type" (backport from #2924)

CHANGELOG.md, gsa/src/web/pages/permissions/multipledialog.js
**What**:
Use correct change handler for the `Select` to set whether to include related resources when creating new permissions in a resource.
**Why**:
Only the default to include related resources was sent to gvmd. The value of the dropdown could not be changed.
**How**:
Manual tests whether the value was changeable and if the correct values was sent.
**Checklist**:
- [N/A] Tests
=> Fix setting whether to include related resources in new permissions

CHANGELOG.md, gsa/src/web/pages/results/detailspage.js
**What**:
Adjust `result.nvt` according to renamed field to `result.information`.
**Why**:
This allows to actually get the NVT OID to create notes and overrides in the dialogs.
**How**:
Manual tests to create notes and overrides from the result detailspage.
**Checklist**:
- [N/A] Tests
=> Fix loading NVT information in result details

CHANGELOG.md, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js
**What**:
Fall back to cvss_base when severity subelement is missing from NVT severities
**Why**:
It's possible that after some migration without gvmd -rebuild the severity subelement is missing in the NVT severities. GSA broke in that case and just threw an error without proper fallback.
**How**:
Added a new test. Also manual check which information is shown on the detailspage for which condition.
**Checklist**:
=> Fall back to cvss_base when severity subelement is missing from NVT severities

CHANGELOG.md, gsa/src/web/pages/audits/component.js, gsa/src/web/pages/tasks/component.js
**What**:
Remove remaining references to network source interface in the code. Continuation of https://github.com/greenbone/gsa/pull/2902 A backport PR for master will be made with commits from both PRs.
**Why**:
**How**:
Removed irrelevant tests and manually tested.
**Checklist**:
=> Completely remove network source iface from tasks, audits

CHANGELOG.md, gsa/src/gmp/commands/__tests__/audit.js, gsa/src/gmp/commands/__tests__/task.js, gsa/src/gmp/commands/audits.js, gsa/src/gmp/commands/tasks.js, gsa/src/web/pages/policies/component.js, gsa/src/web/pages/tasks/component.js, gsad/src/gsad.c, gsad/src/gsad_gmp.c
**What**:
Manually port changes from https://github.com/greenbone/gsa/pull/2902 and https://github.com/greenbone/gsa/pull/2942 from gsa-21.10
**Why**:
There are massive changes in tasks and audits between the two branches and required manual attention.
**How**:
Tests are passing. Also did manual tests.
**Checklist**:
=> Remove network source interface from tasks and audits (master)

CHANGELOG.md, gsad/src/gsad_http.c
**What**:
Only allow access to the session cookie from the same site and not for
third parties. 
**Why**:
This avoids CSRF attacks like like e.g.
[BREACH](http://breachattack.com/).
For more details please take a look at
http://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/
**How**:
Build new gsad and did take a look if the samesite cookie settings are present in the response of the login request. Additionally I've clicked though several pages to test if something did break.
**Checklist**:
=> Avoid cross origin forgery by using same-site cookie

CHANGELOG.md, gsa/src/web/components/layout/__tests__/__snapshots__/horizontalsep.js.snap, gsa/src/web/components/layout/__tests__/horizontalsep.js, gsa/src/web/components/layout/horizontalsep.js, gsa/src/web/pages/users/row.js
**What**:
Properly space and linebreak roles and groups in users table row by not using the Divider component, but HorizontalSep with a new wrap prop.
**Why**:
Adding too many roles and/or groups to a user grew the table row too wide and move parts of it out of screen. It was also not very readable even without growing > 100%/width
**How**:
Visually inspect how roles and groups are displayed. Add test for wrapped HorizontalSep
**Checklist**:
=> Properly space and linebreak roles and groups in users table row

CHANGELOG.md, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js
**What**:
Add origin and date from NVT severities to parseObject() in NVT model.
**Why**:
They are not parsed properly and don't show up in the NVT details
**How**:
Visual inspection, if the info is shown. Automatic tests are still passing.
**Checklist**:
=> Add origin and date from NVT severities to parseObject() in NVT model

CHANGELOG.md
Similar to !2991 for the master branch as mentioned in https://github.com/greenbone/gsa/pull/2958#discussion_r646312539
Not sure if this is the correct way to handle this.
=> master: Fix duplicated CHANGELOG.md entries

CHANGELOG.md
As mentioned in https://github.com/greenbone/gsa/pull/2958#discussion_r646312539 some problems have been introduced in this backport:
- The entry on `#2931` already existed in the CHANGELOG.md
- The duplicated entry of `#2931` had linked to the unrelated PR `#2891`
- The entry on `#2891` already existed in the CHANGELOG.md and the second one was broken like seen here:
The master branch seems to be only affected by the duplicated entries, will create another MR for that in a few minutes.
=> gsa-21.04: Fix duplicated and broken CHANGELOG.md entries.

CHANGELOG.md, gsa/src/web/pages/targets/__tests__/dialog.js, gsa/src/web/pages/targets/dialog.js
**What**:
Remove the credential from the elevate credential selection list, that has been used to unlock the option for elevate credentials in the first place.
**Why**:
**How**:
Write a new test, manually inspect options in the dropdowns.
**Checklist**:
=> Disallow using the same credential for ssh and elevate credential in targets

CHANGELOG.md, gsa/src/web/pages/nvts/references.js
**What**:
Show the type of xrefs in the reference section of NVTs, except url.
**Why**:
There seemed to be changes made in the NASL scripts that altered the content of `name` and `type` of xrefs.
NOTE: It is not 100% clear how the change of behavior happened but GSA is already getting the type in lower case only, therefore it will appear as that in the details as well..
**How**:
Visually check whether the type is included.
**Checklist**:
- [N/A] Tests
=> Show xref type in NVT details

gsa/src/web/pages/targets/__tests__/dialog.js, gsa/src/web/pages/targets/component.js, gsa/src/web/pages/targets/dialog.js
**What**:
Filter out ssh_elevate_credential_id from ssh_credential options so the user cannot set an ssh credential to be the same as an elevate credential.
**Why**:
**How**:
Manual and unit tests.
**Checklist**:
=> SSH elevate credential should not appear in dropdown for SSH credential

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/__snapshots__/severityvaluesgroup.js.snap, gsa/src/web/components/powerfilter/__tests__/severityvaluesgroup.js, gsa/src/web/components/powerfilter/severityvaluesgroup.js, gsa/src/web/pages/results/filterdialog.js
**What**:
- Initialize severity value in the powerfilter's SeverityValuesGroup with 0.
- Use severity as filter keyword for result filter instead of cvss_base
**Why**:
- The 0 was the default value of the NumberField, which was displayed, but was not stored in the dialog state to be 
sent with the filter update.
- Using severity is more consistent with other entities' filters
**How**:
Manuel tests and new automatic test added
**Checklist**:
=> Initialize severity value with 0 in powerfilter

CHANGELOG.md, gsa/src/web/components/powerfilter/__tests__/relationselector.js, gsa/src/web/components/powerfilter/__tests__/severityvaluesgroup.js, gsa/src/web/components/powerfilter/relationselector.js, gsa/src/web/components/powerfilter/severityvaluesgroup.js
**What**:
Use UNSET_VALUE as default for relation of severity values in powerfilter
**Why**:
The Select showed "is equal to" as default value, but when updating the filter, this setting was not applied. The displayed item is set to "--" (`UNSET_VALUE`) to prevent confusion. 
**How**:
Manual testing - explicitly whether/which default value is applied when _not_ changing values in the filterdialog. Also adjusted automated tests.
**Checklist**:
=> Use UNSET_VALUE as default for relation of severity values in powerfilter

CHANGELOG.md, gsa/package.json, gsad/src/gsad.c
Remove frame-acestors completely because it isn't included into an
iframe anymore. If this is still required the CSP settings can be
adjusted via a command line parameter.
More important don't allow executing javascript from inline html. Only
from references javascript files.
But allow to load CSS from inline <style> elements via style-src-elem
(not supported by firefox yet) and style-src CSP settings.
Fixes AP-1507
**Checklist**:
=> CSP header adjustments

CHANGELOG.md, gsad/src/gsad_http_handler.c
When updating to a newer GSA version the client's browser may still have
an old version of that index.html file in its cache. In that case it
wont load the new JavaScript files. Therefore don't cache all URLs where
the index.html file is returned. This ensures the browers always loads
the newest JavaScript files.
AP-1550
**Checklist**:
=> Avoid caching of the index.html page

CHANGELOG.md, gsad/src/gsad_gmp.c
Creating or modifying a target will no longer fail if the HTTP request
does not contain the ssh_elevate_credential_id parameter.
This addresses AP-1472 where targets are rejected if an older version
of GSA is still in the browser cache.
This was tested by temporarily modifying GSA to no longer send
ssh_elevate_credential_id when modifying or creating a target.
**Checklist**:
=> Make SSH elevate credential optional in gsad

CHANGELOG.md, gsad/src/gsad.c
**What**:
Adjust Content Security Policy even further and set
* frame-acestors
* default-src
* object-src
* base-uri
to 'none' and
* connect-src
* form-actions
to 'self'. This deactivates unused features by default and only allows
required ones to be used at the current origin.
It is still possible to change the CSP settings via a command line
parameter.
Fixes AP-1613
**Why**:
Improve rating at https://observatory.mozilla.org/
**How**:
Checked running gsad if the headers are included in the response. Logged in created a target. Exported a port list. Started a task.
**Checklist**:
=> Further restrict content security policy

.github/workflows/ci-c.yml, .github/workflows/ci-js.yml, .github/workflows/codeql-analysis.yml, .mergify.yml
**What**:
Remove gsa-21.10 branch from mergify and workflows.
**Why**:
gsa-21.10 has been deleted because it is no longer needed. Current development for gsa-21.10 is done on the master branch.
**How**:
**Checklist**:
=> Remove gsa-21.10 branch from mergify and workflows

CHANGELOG.md, gsa/src/web/pages/targets/__tests__/row.js, gsa/src/web/pages/targets/row.js
**What**:
Don't crash the target table when target.port_list is undefined.
**Why**:
Seems like the trashcan doesn't provide the target's portlist and therefore breaks the target table
**How**:
Visual check if table cell is empty (no crash) and added automatic test.
**Checklist**:
=> [AP1581] Don't crash target table when port_list is undefined (fix trashcan)

CHANGELOG.md, gsa/src/gmp/models/__tests__/nvt.js, gsa/src/gmp/models/nvt.js, gsa/src/web/pages/nvts/references.js, gsa/src/web/pages/results/__tests__/detailspage.js
**What**:
Remove bid and bugtraq_id handling
**Why**:
This "feature" is no longer supported
**How**:
BID refs were  not listed on the detailspages (nvt, result) anymore anyway, because of https://github.com/greenbone/openvas-scanner/pull/724 So removing the code and updatng the tests was everything that needed to be done.
**Checklist**:
=> Remove bid and bugtraq_id handling

CHANGELOG.md, gsa/src/web/pages/reports/details/emptyreport.js
**What**:
Show possibility of dead hosts also for finished scans, not only `progress < 0`
**Why**:
The notification was not shown after scanning a dead host and was reported missing
**How**:
1. Create a target with a non-existing host.
2. Scan that target to produce an empty report.
3. Check that the notification is listed in the Results tab in the report details.
**Checklist**:
- [N/A] Tests
=> [AP1032] Show dead hosts as possible reason in empty report when scan finishes

CHANGELOG.md, gsa/public/locales/gsa-de.json, gsa/src/web/pages/results/detailspage.js
**What**:
Change enabling conditions to:
- not showing the icon when create_ticket permission is missing
- graying out the icon if create_permission and/or get_users permissions are missing
- enabling icon completely only if all three permissions are given
**Why**:
To prevent the user from misunderstandings whether they can actually create a ticket or not, because simply having create_ticket might seem sufficient, but it's not.
**How**:
Automated tests are still succeeding, manually testing the icon with several users with different combinations of permissions.
**Checklist**:
=> [AP1447] Change conditions for enabling CreateTicketIcon on results detailspage

CHANGELOG.md, gsad/src/gsad.c, gsad/src/gsad_gmp.c, gsad/src/gsad_gmp.h, gsad/src/gsad_http_handler.c
**What**:
Added new handler "get_system_report_gmp()" for single performance
reports. Renamed old handler to "get_system_report_gmp_from_url()".
**Why**:
This change is necessary for the adjustment of a bug issue.
**How**:
Tested by running a special html - request.
**Checklist**:
=> Add new handler for single performance report

CHANGELOG.md, gsa/src/web/pages/reports/details/emptyreport.js
**What**:
Don't show a second "Hosts might be dead" notification when a task was interrupted
**Why**:
It was shown twice
**How**:
Tests still pass
**Checklist**:
=> [AP1032] Fix condition for dead host notification in empty report

.docker/testing/Dockerfile, .github/workflows/ci-js.yml, CHANGELOG.md, INSTALL.md, gsa/CMakeLists.txt, gsa/package.json
**What**:
Use a newer node.js version as minimum requirement, because 10 is EOL.
**Why**:
Support for it should outlast GVM 21.10 and we have the first 3rd party dependencies requiring node.js >= 12
**How**:
**Checklist**:
=> Require node.js >= 14

gsa/src/gmp/locale/languages.js
Add traditional Chinese language option to switch to "gsa-zh_TW.json"
**What**:
Add traditional Chinese language options to the list.
**Why**:
I have translated gsa-zh_TW.json before, but I did not add the ability to switch to Traditional Chinese language.
**How**:
Add to languages constant
**Checklist**:
=> Add Traditional Chinese language option

gsa/src/gmp/models/__tests__/policy.js, gsa/src/gmp/models/__tests__/scanconfig.js, gsa/src/gmp/models/policy.js, gsa/src/gmp/models/scanconfig.js, gsa/src/web/pages/audits/__tests__/details.js, gsa/src/web/pages/audits/__tests__/detailspage.js, gsa/src/web/pages/audits/details.js, gsa/src/web/pages/policies/__tests__/details.js, gsa/src/web/pages/policies/__tests__/detailspage.js, gsa/src/web/pages/policies/__tests__/listpage.js, gsa/src/web/pages/policies/component.js, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/listpage.js.snap, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/row.js.snap, gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/table.js.snap, gsa/src/web/pages/scanconfigs/__tests__/details.js, gsa/src/web/pages/scanconfigs/__tests__/detailspage.js, gsa/src/web/pages/scanconfigs/__tests__/editdialog.js, gsa/src/web/pages/scanconfigs/__tests__/listpage.js, gsa/src/web/pages/scanconfigs/__tests__/row.js, gsa/src/web/pages/scanconfigs/__tests__/table.js, gsa/src/web/pages/scanconfigs/component.js, gsa/src/web/pages/scanconfigs/editdialog.js, gsa/src/web/pages/scanconfigs/header.js, gsa/src/web/pages/scanconfigs/row.js, gsa/src/web/pages/scanconfigs/table.js, gsa/src/web/pages/tasks/__tests__/details.js, gsa/src/web/pages/tasks/__tests__/detailspage.js, gsa/src/web/pages/tasks/details.js, gsa/src/web/pages/tasks/dialog.js, gsa/src/web/pages/usersettings/usersettingspage.js
**What**:
scan_config_type and resulting variables are removed from GSA
**Why**:
No support for different types
**How**:
Some manual tests and automatic tests are still passing.
**Checklist**:
=> Remove: scan_config_type and corresponding variables are removed

public/locales/gsa-de.json, src/web/pages/licenses/licensepage.js
**What**:
Add ErrorDialog to catch errors while loading license information
**Why**:
Proper error handling
**How**:
I let the license command `throw` instead of returning data and checked whether the dialog displayed the corresponding message
**Checklist**:
=> [AP1571] Add ErrorDialog to LicensePage

src/gmp/commands/users.js, src/web/pages/usersettings/defaultspart.js, src/web/pages/usersettings/dialog.js, src/web/pages/usersettings/usersettingspage.js
**What**:
Remove the optoion to set/change a default report format
**Why**:
The setting is obsolete, because the default report format is now set in the content composer defaults
**How**:
Manual test of the page if the options are gone. Automatic tests are still passing
**Checklist**:
- [N/A] Tests
=> Remove default report format from usersettings

src/web/components/notification/__tests__/licensenotification.js, src/web/components/notification/licensenotification.js, src/web/components/provider/licenseprovider.js, src/web/pages/licenses/__tests__/licensepage.js, src/web/pages/licenses/licensepage.js, src/web/pages/page.js, src/web/utils/testing.js, src/web/utils/useLicense.js
**What**:
Extract logic and code behind the LicenseNotification out of the page.js into its own module
**Why**:
The code will become more complex and this gives a good basis to keep page.js as clean and simple as possible
**How**:
Manual tests were performed if the notification's behavior changed after moving the code.
**Checklist**:
=> Move LicenseNotification into own module

src/__tests__/version.js, src/gmp/gmpsettings.js, src/index.js, src/version.js, src/web/pages/help/about.js
**What**:
Fix creating the URL for the links to the manual and GMP documentation
by versioning them.
AP-1966
**Why**:
Use correct links for a specific GSA version.
**How**:
**Checklist**:
=> Fix: Use GSA version to create links to manual and GMP documentation

src/gmp/commands/__tests__/license.js, src/gmp/commands/license.js, src/gmp/models/__tests__/license.js, src/gmp/models/license.js, src/web/components/notification/__tests__/licensenotification.js, src/web/components/notification/licensenotification.js, src/web/pages/licenses/__tests__/licensepage.js, src/web/pages/licenses/licensepage.js
**What**:
* Move license into a model module and adjust its parsing
* Introduce functions to display descriptive model names and types
* Fix model and model_type usage in tests
**Why**:
For example trial and 450 are just values for the models. A model type can be virtual or hardware. But both values should not be displayed 1:1 to the user.
**How**:
**Checklist**:
=> Improve displaying license

src/web/pages/licenses/__tests__/dialog.js, src/web/pages/licenses/dialog.js, src/web/pages/licenses/licensepage.js
**What**:
Display confirmation dialog only when replacing a valid license.
Also add tests for LicenseDialog.
**Why**:
AP-1978:
The admin user must confirm overriding a valid license
No confirmation is displayed if the current license is invalid/corrupted or expired
No confirmation is displayed if no current license is available
**How**:
Manual tests uploading a valid license given either:
- a corrupt license -> no confirmation dialog
- a valid license -> -> confirmation dialog
- an expired license -> no confirmation dialog
- no license -> no confirmation dialog
If the confirmation dialog pops up, is also indirectly tested in an automated test.
**Checklist**:
=> Display confirmation dialog only when replacing a valid license

package.json, yarn.lock
**What**:
Downgrade @babel/core to 7.16.7 to fix extracting the i18next
translations.
See https://github.com/gilbsgilbs/babel-plugin-i18next-extract/issues/208
for some details about the issue.
**Why**:
**How**:
**Checklist**:
=> Fix extracting i18next based translation

.github/dependabot.yml
**What**:
Ignore re-occuring dependency update requests for some deps
**Why**:
We can't update some dependencies, because they would break functionalities. Instead we close such PRs when they occur. We now don't want them to occur at all anymore.
**How**:
**Checklist**:
- [N/A] Tests
=> Ignore reoccuring dependency update requests for some dependencies

src/gmp/gmpsettings.js, src/version.js
**What**:
**Why**:
Fix #3459 
**How**:
**Checklist**:
=> Fix: Introduce new function to remove leading zero fron version for correct links to GSM-Manual

.docker/prod.Dockerfile
We should use AMD64 to build the Web-Scripts and from there we can copy it also to ARM64 images.
**What**:
**Why**:
**How**:
**Checklist**:
=> Build ARM64 images faster - use AMD64 for node

package.json, src/gmp/http/transform/fastxml.js, yarn.lock
Update fast-xml-parser to latest release
This fixes a security vulnerability (see #3632).
https://github.com/greenbone/gsa/pull/3632
=> Change: Update fast-xml-parser to latest release

src/gmp/commands/alerts.js, src/web/pages/alerts/component.js, src/web/pages/alerts/dialog.js, src/web/pages/alerts/method.js, src/web/pages/alerts/smbmethodpart.js
The smb_max_protocol field is added to the SMB method data in the Alert dialog and details.
To allow setting the option if the SMB server only supports older versions.
GEA-38
=> Add smb_max_protocol to alert method data

src/gmp/commands/auth.js, src/gmp/commands/users.js, src/web/pages/ldap/__tests__/__snapshots__/dialog.js.snap, src/web/pages/ldap/__tests__/dialog.js, src/web/pages/ldap/dialog.js, src/web/pages/ldap/ldappage.js
This adds an extra authentication option to force LDAPS for LDAP authentication
The normal LDAP port may be blocked by a firewall, in which case only the LDAPS port should be tried.
GEA-82
requires greenbone/gvm-libs/pull/747, greenbone/gvmd/pull/1928 and greenbone/gsad/pull/124 to work properly
=> Add option to force LDAPS for authentication

src/gmp/http/transform/fastxml.js
The ignoreNameSpace option for fast-xml-parser has been renamed to removeNSPrefix.
This fixes some undefined attributes on SecInfo pages.
GEA-157
=> Fix: Use removeNSPrefix in XML parser options

src/web/pages/alerts/smbmethodpart.js
Instead of using a text field for the SMB alert max version, a drop-down selection is used in the create/edit dialog.
This makes the dialog easier to use by limiting it to valid inputs.
GEA-38
=> Change: Use drop-down for SMB max version

src/web/pages/alerts/smbmethodpart.js
The drop-down selection for Max Version for SMB alerts now correctly shows the default option as "Default".
It was incorrectly shown as "undefined".
GEA-161
=> Fix: "Default" label of SMB Max Version dropdown

src/web/components/chart/line.js
This fixes the lines in line charts not being rendered properly.
Raising the vx-shape version introduced a breaking change in the way scale functions are used in vx components.
GEA-143
=> Fix: Adjust scale in line chart to new vx version

src/web/pages/users/details.js
When viewing the details of a user, the correct authentication method is now shown.
Previously only the table showed the correct method while the details always showed "Local".
GEA-27
=> Fix: Show correct auth method in user details

src/gmp/models/report/host.js
In the report hosts table, authentication methods are now shown as
successful whenever there is a "Auth-...-Success" detail for
a given authentication type.
"Auth-...-Failure" details will no longer override this.
This can happen if SNMP authentication with one protocol version fails but another version succeeds.
GEA-131
=> Fix: Do not let host auth failures override successes

src/web/pages/alerts/component.js
When editing an alert, the currently configured TippingPoint credential is now selected in the dialog.
Before it mistakenly always switched to the first available credential.
GEA-158
=> Fix: Use correct TippingPoint credential in dialog

src/web/pages/alerts/component.js
The alert dialog now uses the correct field for TLS workaround option of the TippingPoint SMS method.
Previously the wrong field was used, so the dialog did not work correctly.
GEA-181
=> Fix: Get/save TippingPoint TLS workaround correctly

.github/workflows/ci-js.yml, .github/workflows/release-pontos.yml
The new $GITHUB_OUTPUT env variable is now used instead of the deprecated ::set-output.
Also, the variable name for the yarn cache dir in release-pontos.yml is fixed.
GitHub announced that the old function will be removed eventually.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Use $GITHUB_OUTPUT in ci-js.yml, fix release-pontos.yml

src/web/pages/alerts/dialog.js
Changed the placeholder for the e-mail subject in the alerts dialog from "GVM" to the correct name "Greenbone Enterprise Appliance".
This is a small bug-fix.
GEA-73
Tested on my local development system.
=> Corrected the e-mail subject placeholder in the alerts dialog.

.github/workflows/ci-js.yml
Do not fail CI if codecov upload fails
The coverage upload randomly fails, causing the whole CI workflow to fail with the previous settings.
=> Change: Do not fail CI if codecov upload fails

.github/dependabot.yml
Include dependabot commits in the release changelog
Change the dependabot config to create commit messages that are parsed by our release changelog generator.
=> Include dependabot commits in the release changelog

package.json, src/version.js
Make version compatible with semantic versioning
Correct semver syntax is required for automatic releases
=> Fix: Make version compatible with semantic versioning

.github/workflows/release-pontos.yml
Fix adding dist files to the release
Set missing outputs of the release job to allow uploading and signing of additional release artifact files.
=> Fix: Fix adding dist files to the release

.github/workflows/release-pontos.yml
Add a token to upload the additional release artifacts
Add missing token for uploading the additional release artifacts.
https://github.com/greenbone/gsa/actions/runs/5422135590/jobs/9858423729
=> Fix: Add a token to upload the additional release artifacts

src/gmp/gmpsettings.js
Fix links to the manual and GMP documentation
Despite the fact we are using 22.x.y as versions for our components now the GMP version will stay on 22.04. The URL to the manual requires the language now.
=> Fix links to the manual and GMP documentation

src/web/pages/users/dialog.js
When determining whether to show the superuser confirmation in the user dialog, also check if there is a user being edited.
Without this check, attempting to create a new user would cause an error when saving.
Fixes #3798
GEA-234
=> Fix: Fix creating a new user with added check

src/web/pages/alerts/method.js
Small correction to display the status of "Use workaround for default certificate" of alerts
(method "TippingPoint SMS") correctly.
This is a bug-fix.
GEA-230
Tested manually on my local development system.
=> Show status of "Use workaround for default certificate" of alerts correctly.

src/gmp/gmpsettings.js, src/web/pages/nvts/__tests__/detailspage.js, src/web/pages/nvts/__tests__/listpage.js, src/web/pages/nvts/detailspage.js, src/web/pages/nvts/listpage.js
Fix links to manual
The language must not be included in the default URL. It is added depending on the current user settings.
Also update the links to the GMP docs.
Closes #3814
Closes GEA-262
Closes GEA-261
=> Fix links to manual

.github/workflows/release-pontos.yml
Fix release activated workflow via labels
The if clauses of the dependent jobs haven't been adjusted for the new release process and its different labels. Therefore using a release label didn't run the jobs. This change removes the if statements from the dependent jobs completely because the first job will check them and otherwise the dependent jobs wont run at all.
https://github.com/greenbone/gsa/issues/3816
=> Fix release activated workflow via labels

package.json, src/gmp/models/__tests__/tlscertificate.js, src/gmp/models/tlscertificate.js, src/web/pages/tlscertificates/__tests__/detailspage.js, src/web/pages/tlscertificates/__tests__/listpage.js, src/web/pages/tlscertificates/__tests__/row.js, src/web/pages/tlscertificates/__tests__/table.js, src/web/pages/tlscertificates/details.js, src/web/pages/tlscertificates/filterdialog.js, src/web/pages/tlscertificates/row.js, src/web/pages/tlscertificates/table.js
Instead of the Issuer DN the TLS certificate list now shows the Subject DN in the first column. Both subject and issuer DN are added to the details.
This change was made because the subject DN is the more useful information to users.
GEA-202
Closes #2847
Based on changes proposed in #3023 by @Virsacer
=> Change: Show subject first in TLS certificate list, show both DNs in details

.github/workflows/release-pontos.yml
For Gentoo, we ideally want to build the node modules as part of our "emerge" process. That means we do not want to consume the -dist artifact. What we instead want is the gsa source and the contents of the node_modules/ directory.
Therefore, add a second release artifact to release-ponto, that only contains the content of the node_modules/ directory.
Please consider this addition, as it would reduce the friction of packaging gsa in Gentoo.
Note that this is untested, since I do not know how to test github workflows, but the change seems trivial enough.
=> release-pontos: also create gsa-node-modules release artifact

src/web/components/dashboard/display/cvss/cvsstransform.js
The value "10.0" is now shown instead of the invalid range "10.0 - 10.9" in the charts, e.g. in the bar tooltip of "Results by CVSS".
CVSS scores above 10.0 are not valid.
GEA-265
=> Fix: Show CVSS value "10.0" correctly in charts

src/gmp/commands/alerts.js, src/web/pages/alerts/component.js, src/web/pages/alerts/dialog.js, src/web/pages/alerts/method.js, src/web/pages/alerts/scpmethodpart.js
The alert dialog and details now have a new "Port" field for the SCP alert method.
This allows using a host with a non-default SSH port as the destination.
GEA-280
requires greenbone/gvmd#2057 and greenbone/gsad#139
=> Add: New "Port" field for SCP alert method

src/gmp/models/__tests__/event.js, src/gmp/models/event.js
In Event.nextDate convert dates with the timezone before comparing to now.  This is similar to converting the dates before returning them.
The dates have floating timezones so they need to be converted, else they are treated as UTC when being converted to Unix time.
To reproduce:
1. set machine tz to America/Los_Angeles
2. `faketime '2022-12-05 08:15:42' gsad...`
1. `faketime '2022-12-05 08:15:42' gvmd...`
1. create schedule with this
> BEGIN:VCALENDAR
> VERSION:2.0
> PRODID:-//XXX//NONSGML//EN
> BEGIN:VEVENT
> DTSTART;TZID=/America/New_York:20221220T000100
> RRULE:FREQ=MONTHLY;BYDAY=3WE;
> END:VEVENT
> END:VCALENDAR
4. `export TZ=America/New_York`
1. `faketime '2023-02-14 17:56' some_web_browser`
1. GSA menu: Configuration > Schedules
1. Next Run is in March but should be in Feb
To also …
=> Fix: Also convert dates for nextDate comparisons

src/web/pages/usersettings/dialog.js
Show error message if user settings can't be saved
When the http request returned an error the error message was not shown while changing the user settings in the corresponding dialog. It broke while introducing the JS form validation because its validate function isn't a promise in contrast to the onSave handler.
GEA-175
=> Fix: Show error message if user settings can't be saved

.github/workflows/release-pontos.yml
The command has been changed from `node run build` to `npm run build`.
The release did not work because of the invalid command.
#3862
=> Change build command to npm in release-pontos.yml

src/web/components/form/__tests__/__snapshots__/selectelement.js.snap, src/web/components/form/__tests__/selectelement.js, src/web/components/form/selectelements.js, src/web/pages/tags/dialog.js
Update the position of the drop-down menu for adding resources to be based on the `ScrollableContent` element which has a maximum height.
The position of the drop-down menu to add more resources was set according to the element containing the current resources.
Therefore, having a large number of resources pushes down the drop-down menu until it disappears from the screen.
GEA-251
=> Fix: Fix position of resources drop-down menu for tags

package-lock.json, package.json, src/web/utils/testing.js
Update the versions of d3 libraries and jest-dom.
- import of jest-dom had to be updated since extend-expect is removed starting from jest-dom 6.0.0. See [Releases](https://github.com/testing-library/jest-dom/releases)
- d3 node modules need to be transformed so that jest can parse them. See [3.0.1 doesn't work with Jest](https://github.com/d3/d3-interpolate/issues/96)
To keep the dependencies updated to the latest versions.
GEA-309
=> Change: Update d3 and jest-dom versions

.github/dependabot.yml
Grouping of all Dependabot updates that only increase the patch level is enabled so they will be added in a single commit.
To simplify the update process.
=> Enable Dependabot update grouping

src/web/components/dashboard/display/cvss/cvssdisplay.js, src/web/components/dashboard/display/cvss/cvsstransform.js
The range (0.1-0.9) is now shown in the CVSS chart and the corresponding tooltip and filter are consistent with the range.
Fixed the filter ranges for severity values 9 and 10. Value 9 should exclude 10 and Value 10 filter should filter only for 10 and not for > 10.
The CVSS range (0.1-0.9) was missing.
GEA-266
=> Fix: Add CVSS missing range (0.1-0.9)

README.md, package.json
Update installation instructions and required nodejs version
We are using npm with nodejs >= 18 nowadays.
=> Update install and nodejs

.babelrc, scripts/cleanuptranslations.js, src/gmp/locale/lang.js
Allow loading of locales like zh_TW
Deactivate the `nonExplicitSupportedLngs` i18next setting (see https://www.i18next.com/overview/configuration-options#languages-namespaces-resources for more details) that caused our supported languages needed to contain only short codes of the languages to be a valid locale. Therefore locales like `zh_TW` were considered as not supported and the locale did fall back to `en`.
#3842
#3894
GEA-294
=> Fix: Allow loading of locales like zh_TW

README.md
Document GSA settings in README
These settings were documented externally before and should be put into the GSA repository now to have same at the same location as the code.
=> Add: Document GSA settings in README

src/web/pages/scanconfigs/nvtfamilies.js
Various VT families that should be only selected as a whole have been added so editing individual VTs is disabled for them.
To make the dialogs consistent with the gvmd behavior introduced with updating the list there.
GEA-331
greenbone/gvmd#2058
=> Add: Add new whole selection VT families

README.md
If the nodejs package isn't installed it can't be used later.
Note: https://deb.nodesource.com/ is using different install instructions, we might want to adjust it completely to that:
```
~$ sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
~$ curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
~$ NODE_MAJOR=20
~$ echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
~$ sudo apt-get update && sudo apt-get install nodejs -y
```
Better documentation
None
=> Change: Add missing apt-get install line to README.md

src/web/components/icon/deltadifferenceicon.js, src/web/pages/results/__tests__/row.js, src/web/pages/results/details.js, src/web/pages/results/row.js
Handle delta results with changed severity, qod and hostname. In addition to description differences, differences in severity, qod or hostname are considered as a change in delta results comparison.
Within the new delta reports handling, results that have changes only in severity, qod or hostname are now considered changes instead of gone/new.
GEA-320
=> Change: Handle delta results with changed severity, qod and hostname

src/web/components/form/__tests__/__snapshots__/selectelement.js.snap, src/web/components/form/__tests__/selectelement.js, src/web/components/form/multiselect.js, src/web/components/form/select.js, src/web/components/form/selectelements.js
Dropdown menus for select and multi-select components can now open upwards if space below is not enough to prevent extending beyond the viewport.
When a drop down menu is open and is extending beyond the bottom of the viewport, scrolling the window down leads to infinite scrolling.
GEA-303
=> Change: Change opening direction of dropdown menus

src/gmp/models/__tests__/tlscertificate.js, src/gmp/models/report/__tests__/parser.js, src/gmp/models/report/parser.js, src/gmp/models/tlscertificate.js, src/web/entities/withRowDetails.js, src/web/pages/reports/__mocks__/mockreport.js, src/web/pages/reports/details/__tests__/tlscertificatestab.js, src/web/pages/reports/details/tlscertificatestab.js, src/web/pages/reports/details/tlscertificatestable.js, src/web/pages/tlscertificates/details.js, src/web/pages/tlscertificates/row.js
Show extra details for report TLS certificates. The first column now shows `subject_dn` instead of `issuer_dn` and the certificate entries are now expandable to show extra details including `issuer_dn`, `sha256_fingerprint`, `md5_fingerprint` and `valid`.
To make the behavior consistent with the TLS certificate assets page.
GEA-308
=> Change: Show extra details for report TLS certificates

public/locales/gsa-de.json, src/web/entities/entitynametabledata.js, src/web/pages/portlists/details.js, src/web/pages/reportformats/details.js, src/web/pages/scanconfigs/__tests__/details.js, src/web/pages/scanconfigs/__tests__/row.js, src/web/pages/scanconfigs/details.js, src/web/utils/__tests__/render.js, src/web/utils/render.js
Data objects like configs, port lists and report formats that are deprecated are marked as such on the list and details pages as well as in dialog dropdowns.
To make the deprecation visible to users.
GEA-6
=> Add: New marking of deprecated data objects

src/gmp/models/task.js, src/web/pages/reports/row.js, src/web/pages/tasks/__tests__/status.js, src/web/pages/tasks/status.js
Container tasks now show "Processing" when uploading reports or creating assets and show "Interrupted" when upload is interrupted. Reports show "Uploading" during upload  and "Interrupted" if upload is interrupted.
If a report is uploaded to a container task it will appear done (with the "Container" status in GSA) once it is in the phase of processing the assets. This can be misleading, especially if the processing takes a long time, as is the case for uploading multiple larger reports.
GEA-353
=> Change: Show status information for container tasks and reports

public/locales/gsa-de.json, src/web/pages/tasks/icons/__tests__/starticon.js, src/web/pages/tasks/icons/starticon.js
If a task has a schedule with a duration limit assigned, the start icon will be disabled.
This is done because there is currently no distinction between a scheduled start and a manual one, so the schedule would often stop the task immediately.
GEA-379
=> Change: Disable start icon for tasks with duration limit

package-lock.json, package.json, src/web/components/tab/tab.js, src/web/pages/audits/__tests__/__snapshots__/detailspage.js.snap, src/web/pages/policies/__tests__/__snapshots__/detailspage.js.snap, src/web/pages/scanconfigs/__tests__/__snapshots__/detailspage.js.snap, src/web/pages/tasks/__tests__/__snapshots__/detailspage.js.snap
Prefix pseudo classes with &.
Pseudo selectors no longer work when not prefixed with & in styled-components 6 which causes jumping behavior when hovering over tabs in open reports or alerts. See https://github.com/styled-components/styled-components/issues/4177
GEA-382
Closes: https://github.com/greenbone/gsa/issues/3914
=> Fix: Fix jumping behavior when hovering over tabs of open report/alert.

src/web/components/dashboard/display/cvss/cvssdisplay.js, src/web/components/dashboard/display/cvss/cvsstransform.js, src/web/components/dashboard/display/severity/severityclassdisplay.js
Fix filters for severity "N/A" and "1" in "CVES by CVSS" diagram.
Column "1" of the diagram was incorrectly using the filter severity>0.9 and severity<1 and therefore showing no results.
Additionally, the filter used when clicking the column "N/A" was severity="", which shows zero results on the corresponding list page.
GEA-370
=> Fix: Fix filters for severity "N/A" and "1" in "CVES by CVSS" diagram

src/web/pages/scanconfigs/nvtfamilies.js
The word "Local" has been added to "AlmaLinux Local Security Checks" and "Amazon Linux Local Security Checks" where it was previously missing in the list of VT families that must be selected as a whole.
GEA-387
=> Fix: Fix typos in WHOLE_SELECTION_FAMILIES

src/gmp/collection/parser.js, src/gmp/commands/__tests__/resourcenames.js, src/gmp/commands/resourcenames.js, src/gmp/gmp.js, src/gmp/models/__tests__/resourcename.js, src/gmp/models/resourcename.js, src/web/pages/tags/dialog.js
Make use of the new GMP command get_resource_names to load tag resources.
Show a loading indicator to the user when data is being loaded.
To improve performance, the new GMP command only retrieves the names and ids of tag resources . The loading indicator is added to make it visible to the user that data is being loaded and some wait time is expected.
GEA-380
requires https://github.com/greenbone/gvmd/pull/2116 and https://github.com/greenbone/gsad/pull/159
=> Change: Make use of GMP command get_resource_names to load tag

src/gmp/models/vulnerability.js
When parsing the result dates for vulnerabilities, the correct field is now used for the oldest result.
When date parsing was added to the Vulnerability model class, the newest date was used accidentally.
GEA-414
=> Fix: Use correct oldest result date in vulns

src/gmp/commands/__tests__/policy.js, src/gmp/commands/policies.js
The config dialog now also uses edit_config_family_all alongside edit_config_family.
This fixes the dialog for editing a family in a compliance policy not loading correctly.
GEA-415
Corresponding change for scan configs: #3857
=> Fix: Also use edit_config_family_all for policies

.docker/prod.Dockerfile
Install npm in prod.Dockerfile
Container builds are currently failing because npm is missing.
=> Install npm in prod.Dockerfile

package-lock.json, package.json, src/web/store/index.js
Update the import of redux-thunk after dependabot update https://github.com/greenbone/gsa/pull/3939
The default export has been removed as of v3.1.0 and now there are named exports. See [redux-thunk/releases/tag/v3.1.0](https://github.com/reduxjs/redux-thunk/releases/tag/v3.1.0).
GEA-451
=> Fix: Update the import of redux-thunk

package-lock.json, package.json, src/web/components/bar/__tests__/__snapshots__/titlebar.js.snap, src/web/components/icon/__tests__/__snapshots__/svgicon.js.snap, src/web/components/menu/__tests__/__snapshots__/usermenu.js.snap, src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap, src/web/pages/audits/__tests__/__snapshots__/actions.js.snap, src/web/pages/audits/__tests__/__snapshots__/detailspage.js.snap, src/web/pages/audits/__tests__/__snapshots__/listpage.js.snap, src/web/pages/audits/__tests__/__snapshots__/row.js.snap, src/web/pages/audits/__tests__/__snapshots__/table.js.snap, src/web/pages/policies/__tests__/__snapshots__/detailspage.js.snap, src/web/pages/policies/__tests__/__snapshots__/listpage.js.snap, src/web/pages/policies/__tests__/__snapshots__/row.js.snap, src/web/pages/policies/__tests__/__snapshots__/table.js.snap, src/web/pages/scanconfigs/__tests__/__snapshots__/detailspage.js.snap, src/web/pages/scanconfigs/__tests__/__snapshots__/editconfigfamilydialog.js.snap, src/web/pages/scanconfigs/__tests__/__snapshots__/editdialog.js.snap, src/web/pages/scanconfigs/__tests__/__snapshots__/listpage.js.snap, src/web/pages/scanconfigs/__tests__/__snapshots__/row.js.snap, src/web/pages/scanconfigs/__tests__/__snapshots__/table.js.snap, src/web/pages/tasks/__tests__/__snapshots__/actions.js.snap, src/web/pages/tasks/__tests__/__snapshots__/detailspage.js.snap, src/web/pages/tasks/__tests__/__snapshots__/row.js.snap, src/web/pages/tasks/__tests__/__snapshots__/table.js.snap
Updating test snapshots after dependabot update https://github.com/greenbone/gsa/pull/3951 which bumps styled-components from v6.1.1 to v6.1.8.
Test cases were failing.
GEA-451
=> Test: Update snapshots after dependency update

src/web/entities/filterprovider.js
Avoid unnecessary re-renders in FilterProvider when getting the rowsPerPage settings from the redux store.
The behavior of `useSelector` hook and "old" `connect` function is differently. `useSelector` uses identity comparison `===` for detecting if the returned object has changed and a re-render is necessary. In contrast `connect` uses shallow comparison. See https://react-redux.js.org/api/hooks#equality-comparisons-and-updates for all details.
Therefore to avoid re-renders in the FilterProvider we need to compare the contents of returned array from the user settings selector via `shallowEqual` because with every call a new array is created and the identity changes.
=> Fix: Avoid re-render when user settings haven't changed for FilterProvider

package-lock.json, package.json, src/web/components/form/formgroup.js, src/web/pages/login/loginform.js, src/web/utils/theme.js
Drop ui-components as a dependency and instead use existing GSA form components for the login.
The ui-components are only used by GSA for the button and input components in the login form. It makes sense to move those components to GSA instead of having to maintain a separate repository.
GEA-393
=> Change: Drop ui-components as a dependency for GSA

.github/workflows/container.yml
Allow to rebuild a specific container image
Use workflow dispatch event to trigger a re-build of a specific container image. Therefore the passed tag will be checked out. The git tag and sha from the checkout will be used to determine the container image labels instead of deriving them from the github workflow context.
https://forum.greenbone.net/t/update-path-for-community-containers-to-version-23/16594/4
=> Allow to rebuild a specific container image

package-lock.json, package.json, src/web/components/form/datepicker.js, src/web/pages/performance/startendtimeselection.js, src/web/pages/schedules/dialog.js, src/web/wizard/advancedtaskwizard.js, src/web/wizard/modifytaskwizard.js
Update datepicker to use current version of react-datepicker
react-datepicker > 1.8.0 dropped the usage of moment.js and requires native JS Date objects as inputs. Therefore we didn't update it for a long time. This change adjusts our own datepicker component to still use moment.js dates and passes the wrapped JS Date objects to react-datepicker. Because native Date objects don't know anything about timezone the datepicker component requires a timezone prop now to be able to convert the native Date object into a timezone aware moment.js date.
This change might also fix a small issue with out datepicker component on initial creation. The datepicker created a moment.js date having possibly the wrong timezone information.
Also with updating react-datepicker to the latest release all blockers …
=> Change: Update datepicker to use current version of react-datepicker

package.json
Remove warning when running lint staged pre-commit hook
Running `git add` is obsolete with the lint-staged version in use.
=> Fix: Remove warning when running lint staged pre-commit hook

src/web/components/powerfilter/dialog.js
Simplify DefaultFilterDialog
Get the capabilities via the useCapabilities hook instead of using the withCapabilities HOC. Higher order components (HOCs) are more difficult to understand then react hooks.
=> Change: Simplify DefaultFilterDialog

src/web/components/powerfilter/withFilterDialog.js
Allow to set a filter type to create in withFilterDialog
With this change it is possible to define the filter type to use when a new filter is created directly when writing a filter dialog component. Before it was required to pass it via a prop. Passing via a prop is still optional.
Example usage now (implicitly):
```
createFilterDialog({
createFilterType: 'portlist',
sortFields: SORT_FIELDS,
});
```
=> Change: Allow to set a filter type to create in withFilterDialog

src/web/pages/extras/trashcanpage.js
Don't display loading error on trashcan page if an error occurred
Deactivate the loading indicator if an error occurred while loading the trashcan data. This change also cleans up the loading code a bit.
=> Fix: Don't display loading error on trashcan page if an error occurred

src/web/hooks/__tests__/useTranslation.js, src/web/hooks/useTranslation.js
Introduce a useTranslation hook
Provide a possibility to migrate our translation mechanism to react-i18n by introducing a similar useTranslation hook.
When we started developing GSA hooks didn't exist and react-i18n including its translation mechanisms were not easy to use. Therefore I've implemented our own abstraction on top of i18next directly. With react hooks react-i18n become much easier to use and we should migrate to it at the end.
To allow for an easy migration introduce a similar useTranslation hook as react-i18n that wraps our current translation code.
OpenSight UI uses useTranslation already.
DEVOPS-1000
=> Add: Introduce a useTranslation hook

src/web/pages/schedules/dialog.js
Pass missing timezone to DatePicker component.
Timezone was not passed to DatePicker for the "Run Until".
GEA-523
=> Fix: Pass missing timezone to DatePicker component

src/web/components/dialog/footer.js, src/web/components/notification/__tests__/dialognotification.js, src/web/components/notification/dialognotification.js, src/web/components/notification/useDialogNotification.js, src/web/components/notification/withDialogNotifiaction.js
Refactor DialogNotification into a function component
The DialogNotification component is intended to show messages (for example errors) in a dialog easily. With this change it got refactored to a function component which is easier to understand. Also tests for the DialogNotification component are added.
=> Change: Refactor DialogNotification into a function component

.github/workflows/container.yml, .github/workflows/remove-container.yml
Build and upload container image for pull requests
Allow to test container images for pull request. The images are uploaded to ghcr.io only. The uploaded container images will be deleted if the pull request is closed.
DEVOPS-1000
=> Build and upload container image for pull requests

package-lock.json, package.json, src/gmp/__tests__/gmp.js, src/gmp/__tests__/gmpsettings.js, src/gmp/locale/__tests__/detector.js, src/gmp/setupTests.js, src/gmp/utils/__tests__/event.js, src/setupTests.js, src/web/setupTests.js, vite.config.ts, vitest.projects.ts
Improve settings for vitest
Vitest is highly configurable and has a lot of potential for improvements. This PR uses the [vitest workspace feature](https://vitest.dev/guide/workspace.html) to use different test settings for the gmp and web parts of GSA.
GEA-540
=> Vitest improvements

src/gmp/__tests__/gmpsettings.js, src/gmp/gmpsettings.js
Fix default setting for the api server
The api server must be determined from the current host. Otherwise it all ajax requests would go to localhost:9292 by default and it would be required to set the correct host name in the config.js for every installation.
=> Fix default setting for the api server

package-lock.json, package.json
Update jest-dom dependency to 6.4.5.
Dependabot recommends version 6.4.3 in [#4019](https://github.com/greenbone/gsa/pull/4019) which has an issue with importing 'lodash/isEqualWith' that causes CI tests to fail. See https://github.com/testing-library/jest-dom/issues/598. This issue is now fixed in 6.4.5.
GEA-551
=> Update jest-dom dependency.

src/web/components/observer/localeobserver.jsx, src/web/hooks/__tests__/useLocale.jsx, src/web/hooks/useLocale.jsx
Fix getting and setting the locale via useLocale hook
Change the LocaleObserver to not store the locale locally and instead always rely on useLocale. This means useLocale is the new source of truth for the current active locale for the whole application.
Therefore ensure that useLocale returns the applied locale. Either fromi the store when the user is logged in or as a fallback directly from i18n when the user is not logged in or the locale has not been dispatched to the store yet.
=> Fix getting and setting the locale via useLocale hook

src/web/store/index.js
Fix enabling the redux store logging
The middlewares object is immutable and therefore concatenating creates an object. To add the logging middleware the new middlewares object must be returned.
=> Fix enabling the redux store logging

package-lock.json, package.json, src/gmp/locale/lang.js
Replace i18next-xhr-backend with i18next-http-backend
i18next-xhr-backend is deprecated and the i18next-http-backend is a drop in replacement.
=> Change: Replace i18next-xhr-backend with i18next-http-backend

src/gmp/commands/reportformats.js, src/web/pages/reportformats/dialog.jsx
The section for editing params has been removed from the report formats dialog.
Parameters should now only be passed to report formats using report configs.
Additionally, the officially supported report formats that use params are all part of the feed and thus not editable anyway.
GEA-403
=> Remove: Params from report formats dialog

src/web/entities/container.jsx
Deleting an entity should return a promise.
To display a progress indicator to the user, the `SvgIcon` component expects a promise. 
With this change deleting a report shows a progress indicator.
GEA-410
=> Change: Display a progress indicator on delete.

src/gmp/commands/__tests__/reportconfig.js, src/gmp/commands/reportconfigs.js, src/gmp/models/__tests__/reportformat.js, src/gmp/models/reportconfig.js, src/gmp/models/reportformat.js, src/gmp/parser.js, src/web/pages/reportconfigs/__tests__/__snapshots__/details.jsx.snap, src/web/pages/reportconfigs/__tests__/__snapshots__/detailspage.jsx.snap, src/web/pages/reportconfigs/__tests__/__snapshots__/dialog.jsx.snap, src/web/pages/reportconfigs/__tests__/component.jsx, src/web/pages/reportconfigs/__tests__/dialog.jsx, src/web/pages/reportconfigs/details.jsx, src/web/pages/reportconfigs/dialog.jsx, src/web/pages/reportformats/detailspage.jsx
A new parameter type for report formats and report configs is added that allows selecting multiple predefined options.
Some small style changes have been made to make params with multi-line values more readable and to make the params in report formats and report configs more consistent.
The new param type can later be used to add new customization options to report formats like a column selection for CSV.
GEA-403
=> Add: New multi_selection report format param type

.github/workflows/ci-js.yml
Added the codecov token to the CI workflow
The codecov action v4 requires a token except for forks of public repositories.
=> Add codecov token to CI workflow

.gitignore
Ignore eslint cache file from git
The file gets created on every eslint run and should not be added to git
=> Ignore eslint cache file from git

src/web/hooks/__tests__/useInstanceVariable.jsx, src/web/hooks/useInstanceVariable.js
Add a react hooks for storing instance variables
An instance variable stores the value directly and doesn't cause re-renders if it is changed. Variables returned from this hooks are comparable to instance variables for class components.
Required for HOC less entities pages.
=> Add a react hook for storing instance variables

.github/workflows/dependency-review.yml
Allow the dependency review workflow to write a message to the PR
The dependency review workflow is able to write a summary message to the PR if it is allowed to write to the workflow.
=> CI: Allow the dependency review workflow to write a message to the PR

src/web/hooks/__tests__/useShallowEqualSelector.jsx, src/web/hooks/useShallowEqualSelector.js
Add a useShallowEqualSelector hook
The useShallowEqualSelector hooks allows to avoid re-renders if an object is selected from the redux store but its value(s) didn't change. With the standard selector which uses `===` comparison even updating an object's value to the same value will cause a re-render (because a new state object is created).
This pattern can be found at https://react-redux.js.org/api/hooks#recipe-useshallowequalselector
=> Add a useShallowEqualSelector hook

src/web/entities/filterprovider.jsx, src/web/hooks/__tests__/usePageFilter.jsx, src/web/hooks/usePageFilter.js
Implement a usePageFilter hook for getting the current applied filter of a page and also to change, reset and remove this filter.
Some background:
Every (entities) page can have a filter for querying the data. The filter can be specified by
1. the user via the powerfilter or some button that modifies the current filter
1. the filter query argument of the current page via the browser URL (`http://...?filter=...`)
1. the last used filter when returning to the page which is stored in the redux store (aka. page filter)
1. the default filter of the entity (which is stored in the database at the user settings and can be received via a specific UUID)
1. the default filter settings for all pages (for example the rows per page setting)
The precedence of the applied filter is specified in the …
=> Use page filter hook

src/web/hooks/__tests__/usePreviousValue.jsx, src/web/hooks/usePreviousValue.js
Add a usePreviousValue hook
Add a new hooks that allows to get the previous value after the value is changed. For example this hook can be used to check whether a filter has changed.
=> Add a usePreviousValue hook

src/web/hooks/__tests__/useTiming.jsx, src/web/hooks/useTiming.js
Implement a useTiming hook
The hook can be used to run a function after a specific amount of time for example for doing a reload of data.
=> Implement a useTiming hook

src/web/hooks/__tests__/useReload.jsx, src/web/hooks/useReload.js
Add a useReload hook to make the Reload component obsolete
The new useReload hook is based in useTiming. It calls a timing function before every reload to calculate the timeout before the reload. This timing function gets a isVisible argument passed. Using the argument the timing function can decide to extend the timeout when the current browser window is not visible.
Part of creating HOCless list page implementations
=> Add a useReload hook to make the Reload component obsolete

src/web/hooks/__tests__/useFilterSortBy.jsx, src/web/hooks/useFilterSortBy.js
Add a useFilterSortBy hook
The hook determines the sort field and direction of a filter and allows to change both via a returned function. The hook can be used to implement the filter changes when clicking on the different header columns of a entities list.
Get rid of entities pages HOCs
=> Add a useFilterSortBy hook

src/web/hooks/__tests__/usePagination.jsx, src/web/hooks/usePagination.js
Add a usePagination hook
The hook returns functions the update a filter for getting the next, previous, first and last page for a list of entities. This is required for the pagination at the bottom and top of each table for a list page.
HOCless entities pages
=> Add a usePagination hooks

src/web/hooks/__tests__/useSelection.jsx, src/web/hooks/useSelection.js
Add a useSelection hook
The useSelection hook implements the entity selection at a entities list table. It is possible to select/deselect specific entities from the list/table, to select all entities displayed at the page or all entities for the current filter (filter without rows value applied).
HOCless entities pages
=> Add a useSelection hook

src/web/entities/__tests__/useEntitiesReloadInterval.jsx, src/web/entities/useEntitiesReloadInterval.js
Add new hook to determine the loading interval for entities pages
Add a useEntitiesReloadInterval hook to replace in conjunction with the useReload hook the Reload component. useEntitiesReloadInterval calculates the timeout for the next reload and useReload actually calls a function after this timeout to allow reloading data.
HOCless entities pages
=> Add new hook to determine the loading interval for entities pages

src/web/entities/BulkTags.jsx, src/web/entities/__tests__/BulkTags.jsx, src/web/entities/tagsdialog.jsx, src/web/pages/tags/dialog.jsx
Add a BulkTags component for handling tagging of entities
The BulkTags component provides dialogs and functions for tagging several
entities with an existing or new tag.
HOC less entities pages
=>  Add a BulkTags component for handling tagging of entities

src/web/components/form/__tests__/useDownload.jsx, src/web/components/form/useDownload.jsx
Add a useDownload hook
The useDownload hook in conjunction with the Download component should replace the withDownload HOC in future.
HOCless enities pages
=> Add a useDownload hook

README.md, src/gmp/gmpsettings.js, src/web/pages/cves/__tests__/detailspage.jsx, src/web/pages/cves/__tests__/listpage.jsx, src/web/pages/cves/details.jsx, src/web/pages/cves/row.jsx, src/web/pages/cves/table.jsx, src/web/pages/nvts/__tests__/detailspage.jsx, src/web/pages/nvts/__tests__/listpage.jsx, src/web/pages/nvts/details.jsx, src/web/pages/nvts/row.jsx, src/web/pages/nvts/table.jsx
The EPSS fields for CVEs and VTs can now be toggled with an option in the config.js file.
This is done because no EPSS feed is provided yet, so the new fields should only be enabled for testing.
GEA-571
=> Add: Toggle to enable EPSS fields

src/web/pages/portlists/listpage.jsx
Refactor PortLists page to a HOC less entities page
Use the PortLists page as an example on howto refactor an entities page to use the new hooks instead of the withEntitiesContainer HOC. Despite having some more lines of code it should be easier to understand then before.
HOC less entities pages
=> Refactor PortLists page to a HOC less entities page

src/gmp/commands/wizard.js, src/gmp/models/event.js
This PR addresses two bugs:
1. **Incorrect Duration Display in Schedules Table**: The issue was with the `event.duration` getter, which incorrectly included weeks in the duration calculation, leading to inaccurate duration displays in the schedules table.
2. **Start Date Issue in Task Advance Wizard**: The problem is from using `moment.day()` (which returns the day of the week) instead of `moment.date()` (which returns the calendar day) when setting the start date for a new task, resulting in incorrect start dates.
These fixes ensure the application's scheduling and task management functionalities work as intended, preventing confusion.
GEA-610
=> Dates inconsistencies in new advance task wizard and schedules

src/web/pages/reports/deltadetailspage.jsx
Allow applying report configs when exporting delta reports. The missing props were passed to the component `DownloadReportDialog` from `DeltaReportDetails` similar to how it is done from `ReportDetails`.
Trying to export delta reports from GSA was throwing an error caused by report configs not being defined.
GEA-609
=> Fix: Allow applying report configs to delta reports.

.github/workflows/release-pontos.yml
Update node version to 18
Avoid build errors during release that prevent tarballs creation. See https://github.com/greenbone/gsa/actions/runs/9709185199/job/26797380392
GEA-616
=> Change: Update node version for build in release-pontos

.docker/prod.Dockerfile, .github/workflows/push.yml
Add: Push workflow for greenbone registry
DEVOPS-1073
DEVOPS-1073
=> Add: Push workflow for greenbone registry

src/web/components/conditionalRoute/ConditionalRoute.jsx, src/web/components/conditionalRoute/__tests__/ConditionalRoute.jsx
The `ConditionalRoute` component utilizes this hook to control access to routes. It decides whether a particular route should be accessible or if it should redirect to a "not found" page, depending on the feature's enablement status.
The component `ConditionalRoute`, it is reusable across the application and the provides a declarative way to apply these toggles to route accessibility.
GEA-643
=> Add: conditional route component for feature flag

src/web/pages/reports/downloadreportdialog.jsx
- Changed `handleSave` to async function.
Once clicked `Ok` on the download report, the button did not show `loading` status.
GEA-648
=> Fix: bug loading status button in download report dialog

.github/workflows/ci-js.yml
- Add `opensight-ui` branch to ci jobs
- CI jobs aren't running on the branch and respective PR against the branch
=> Add: ci job to run on opensight-ui branch

src/gmp/commands/alerts.js, src/web/pages/alerts/dialog.jsx, src/web/pages/alerts/emailmethodpart.jsx, src/web/pages/alerts/scpmethodpart.jsx, src/web/pages/alerts/sendmethodpart.jsx, src/web/pages/alerts/smbmethodpart.jsx, src/web/pages/alerts/verinicemethodpart.jsx, src/web/pages/reports/downloadreportdialog.jsx
If the report configs are not available, the report export and alert dialogs will hide the report config fields.
This will make the dialogs work as expected if the report config commands are disabled.
GEA-647
=> Fix: Make report configs optional in alerts and reports

src/web/components/form/__tests__/select.jsx, src/web/components/form/select.jsx, src/web/utils/__tests__/render.jsx, src/web/utils/render.jsx
Enhancements to the `Select` component and its item rendering labels.
- Modified `renderSelectItems` to always return String as label as expected for the opensight lib.
- Add  `SelectItem` component to support rendering labels with a special notation, ex. deprecated items. 
To accommodate the Mantine Select component's requirements, which allow for a more complex item rendering beyond simple strings.
GEA-651
=> Fix select component label

vite.config.ts
The production build now uses terser with the "mangle" option deactivated.
This addresses a false positive Lintian warning from a mangled variable name.
=> Fix: Disable mangling in production build minify

src/web/authorized.jsx
- Error from rejected requests are overwritten with a new error message.
- During the migration from `react-router-dom` v5 to v6 the `authorized.jsx` component was refactored, introducing the change.
https://github.com/greenbone/gsa/pull/4156
GEA-702
=> fix: rejected request error message

src/web/routes.jsx
This PR adds a loading state to the `routes.jsx` component to handle the scenario where the authentication status `isLoggedIn` is not immediately available.
These changes are necessary to prevent the application from incorrectly redirecting to the logged-out routes when the authentication status is not yet determined. 
GEA-708
=> fix: add loading state to handle authentication status check

index.html, src/web/components/layout/__tests__/__snapshots__/pagetitle.jsx.snap, src/web/components/layout/__tests__/pagetitle.jsx, src/web/components/layout/pagetitle.jsx, src/web/utils/applianceData.js
- Add appliance model to the page title.
- To have the page title more specific.
GEA-697
=> add: appliance model to page title

src/web/hooks/__tests__/usePageFilter.jsx, src/web/hooks/usePageFilter.js
##What
Updated the `usePageFilter` hook. Introduced `useRef` and `useState` to manage the `returnedFilter` to avoid directly modifying the redux store.
##Why
- Redux error in the charts on first render when resetting the filter to default. 
- Error example
=> fix: filtering error on first render for create display

public/locales/gsa-de.json, src/web/pages/usersettings/usersettingspage.jsx
Remove the display of delta reports version in user settings
Feature toggle has been removed from gvmd as well as the non-default code (v1) in [#2317](https://github.com/greenbone/gvmd/pull/2317). No need to keep showing the setting.
GEA-701
=> Remove: Remove delta reports version from user settings

src/web/hooks/__tests__/usePageFilter.jsx, src/web/hooks/usePageFilter.js
Revert fix filtering error on first render for create display 
- Different loading issue, on first render it blocks in loading state
GEA-714
https://github.com/greenbone/gsa/pull/4200
=> Revert fix filtering error on first render for create display 

.docker/compose.yml, .github/workflows/ci-js.yml, .github/workflows/container.yml, .github/workflows/push.yml
Update GitHub workflows and Docker compose file
=> Update GitHub workflows and Docker compose file (main)

src/web/pages/results/row.jsx, src/web/pages/results/table.jsx
Hide EPSS scores columns in compliance view.
EPSS scores only make sense for vulnerability scans.
GEA-803
=> Fix: Hide EPSS scores columns in compliance view

package-lock.json, package.json, src/web/components/comment/__tests__/__snapshots__/comment.jsx.snap, src/web/components/sortable/emptyrow.jsx, src/web/components/sortable/grid.jsx, src/web/components/sortable/item.jsx, src/web/components/sortable/row.jsx, src/web/pages/tasks/__tests__/listpage.jsx
- Migrate to `@atlaskit/pragmatic-drag-and-drop-react-beautiful-dnd-migration`
- `react-beautiful-dnd` is going to be archived
GEA-778
=> deps: migrate-to-pragmatic-drag-and-drop-react-beautiful-dnd-migration

allowedSnakeCase.cjs, src/web/pages/scanconfigs/__tests__/editconfigfamilydialog.jsx, src/web/pages/scanconfigs/editconfigfamilydialog.jsx
- Fixed NVT `React.Memo` comparison for allowing selection
- Improve code readability and standards
- Select checkboxes in Scan config edit were not selectable
GEA-795
=> fix: Scan Config check box not selectable

src/web/components/folding/__tests__/folding.jsx, src/web/components/folding/folding.jsx
- Fix folding component
- When clicking fold and unfold had no effect
GEA-812
=> Fix-folding

src/web/components/table/row.jsx, src/web/pages/scanconfigs/nvtpreferences.jsx
- Improved table row key
- Fix `Nvt prferences` text wrapping
- In rows the index is used as key and should be avoided
- text in cells was not wrapping, causing it to overflow.
GEA-813
=> fix: improve row key and update nvt preference text wrapping

eslint.config.js, src/web/components/structure/footer.jsx
- Update the copyright year in the header and footer to reflect the current year dynamically. 
- Updates the year automatically without manual intervention.
GEA-819
=> change: copyright year is set dynamically

src/web/components/icon/ArrowDown.jsx, src/web/components/icon/ArrowUp.jsx, src/web/components/icon/ArrowUpDown.jsx, src/web/components/label/__tests__/severityclass.jsx, src/web/components/label/severityclass.jsx, src/web/components/sortby/sortby.jsx, src/web/components/table/head.jsx, src/web/pages/alerts/__tests__/listpage.jsx, src/web/pages/reports/__tests__/auditdeltadetailspage.jsx, src/web/pages/reports/__tests__/auditreportslistpage.jsx, src/web/pages/reports/details/__tests__/applicationstab.jsx, src/web/pages/reports/details/__tests__/closedcvestab.jsx, src/web/pages/reports/details/__tests__/cvestab.jsx, src/web/pages/reports/details/__tests__/errorstab.jsx, src/web/pages/reports/details/__tests__/hoststab.jsx, src/web/pages/reports/details/__tests__/operatingsystemstab.jsx, src/web/pages/reports/details/__tests__/tlscertificatestab.jsx, src/web/pages/scanconfigs/__tests__/editconfigfamilydialog.jsx, src/web/pages/scanconfigs/editconfigfamilydialog.jsx, src/web/pages/tasks/__tests__/listpage.jsx, src/web/pages/tlscertificates/__tests__/listpage.jsx
1. fix:  sorting indicators in `editconfigfamilydialog.jsx` header table
2. change: sorting icons to match opensight
3. change: ui for `severityclass.jsx` to align with opensight
1. Once clicking sort on one column the header icons of all columns would change in the table of `editconfigfamilydialog`
GEA-814
=> Sorting indicators and align UI with OpenSight

.docker/prod.Dockerfile
Fix dockerfile linting issue with using different casing.
See https://docs.docker.com/reference/build-checks/from-as-casing/ for details. This change fixes an warning wich is shown in every PR.
https://github.com/greenbone/gsa/pull/4266/files
=> Fix dockerfile linting issue with using different casing

src/gmp/models/credential.js, src/web/pages/credentials/__tests__/dialog.jsx, src/web/pages/credentials/details.jsx, src/web/pages/credentials/dialog.jsx
- Migrated the component to RFC
- Fixed the field being disabled on first render if the checkbox is not selected
- Updated test
- In the credential dialog when in edit mode the fields for replacing `password`, `passphrase`,  `privacy_password`  are not disabled if the checkbox for replacing is not selected on first render.
GEA-834
=> Bug edit credentials dialog fields not disabled

README.md
Update README about translation usage
All devs should be able to update translations correctly.
GEA-835
=> Change: Update README about translation usage

public/locales/gsa-de.json, src/web/components/dialog/composercontent.jsx, src/web/pages/audits/__tests__/detailspage.jsx, src/web/pages/audits/detailspage.jsx, src/web/pages/reports/__tests__/auditdeltadetailspage.jsx, src/web/pages/reports/auditdeltadetailspage.jsx, src/web/pages/reports/auditdetailspage.jsx, src/web/pages/reports/deltadetailscontent.jsx, src/web/pages/reports/details/__tests__/toolbaricons.jsx, src/web/pages/reports/details/alertactions.jsx, src/web/pages/reports/details/summary.jsx, src/web/pages/reports/details/toolbaricons.jsx, src/web/pages/reports/downloadreportdialog.jsx, src/web/pages/reports/triggeralertdialog.jsx
Fix compliance reports links redirecting to scan reports, update tooltips to remove override and hide override checkbox in download and alert dialogs
Links should redirect to compliance reports, overrides are not used for compliance reports.
GEA-844
=> Fix: Fix compliance reports links and tooltips, hide overrides

src/web/components/form/radio.jsx, src/web/pages/nvts/__tests__/nvtpreference.jsx, src/web/pages/nvts/nvtpreference.jsx, src/web/pages/scanconfigs/editnvtdetailsdialog.jsx
- Refactored `nvtpreference.jsx` to RFC
- Added test for `nvtpreference.jsx`
- `Radio.jsx` assures that label is a string
- In `nvtpreference.jsx` modified `onChange` to use inline arrow function
-  Added styling for long strings `TableData`
- Improved layout of the `editnvtdetailsdialog.jsx`
- If the radio component expects a string, if a value number 0 is passed it results in some unexpected UI issues.
- Not using an arrow in the handler, it will not receive the specific value.
- Long strings in `TableData` created h-overflow.
GEA-841
=> Fix nvtpreference dialog

src/web/hooks/__tests__/usePageFilter.jsx, src/web/hooks/usePageFilter.js
Don't mutate a Filter instance in usePageFilter hook when setting rows
The Filter instance might be in the redux store and therefore must not be mutated. Always ensure a copy is mutated.
=> Fix: Don't mutate a Filter instance

src/web/entities/__tests__/filterprovider.jsx, src/web/entities/filterprovider.jsx, src/web/entities/withEntitiesContainer.jsx, src/web/hooks/__tests__/usePageFilter.jsx, src/web/hooks/usePageFilter.js
Drop `usePageFilter` `locationQueryFilterString` because the query param filter gathered from `useSearchParams` is the only valid value.
Drop `FilterProvider` `locationQuery` prop because a string was passed instead of the expected query object and because usePageFilter already handles its use case internally via `useSearchParams`.
Allow to pass filters via URL query argument like `/tasks?filter=name=bar`.
=> Fix: Allow to set the filter via URL query parameter

vite.config.ts
Set host in vite config
Ensure the development server is running on the IPv4 address of the localhost.
=> Set host in vite config

src/web/pages/reports/auditreportslistpage.jsx
Fix the user manual link in audit reports list page to point to the current compliance/audits chapter until the manual is updated with a new chapter for audit reports.
Link is currently pointing to a non-existing section
GEA-852
=> Fix: Fix the link to user manual in audit reports list page

src/gmp/models/__tests__/cve.js, src/gmp/models/cpe.js, src/gmp/models/cve.js, src/web/pages/cves/detailspage.jsx
- Adjust `cve.js` and `cpe.js` to new data structure.
- Data structure change.
GEA-730
=> change: cve.js for new data structure

src/web/components/powerfilter/solutiontypegroup.jsx, src/web/pages/reports/detailsfilterdialog.jsx
- In filter details dialog, the `solutiontypegroup` radio buttons are not selectable
- Removed span and used title prop for  `solutiontypegroup`
GEA-856
=> fix: not selectable radio btn in details filter

src/web/components/badge/__tests__/badge.jsx, src/web/components/badge/badge.jsx, src/web/components/structure/footer.jsx
- Improved `Badge`  component UI to ensure icons are still visible.
- Footer link to greenbone is `https`.
- Badge was overlapping and hiding the icons.
GEA-860
=> Change badge 

src/gmp/commands/__tests__/reportconfig.js, src/gmp/commands/reportconfigs.js, src/gmp/models/__tests__/reportconfig.js, src/gmp/models/reportconfig.js, src/web/pages/reportconfigs/__mocks__/mockreportconfig.jsx, src/web/pages/reportconfigs/__tests__/component.jsx, src/web/pages/reportconfigs/__tests__/dialog.jsx, src/web/pages/reportconfigs/component.jsx, src/web/pages/reportconfigs/details.jsx, src/web/pages/reportconfigs/detailspage.jsx, src/web/pages/reportconfigs/dialog.jsx, src/web/pages/reportconfigs/row.jsx
Fix displaying the selected report format in the report config dialog and being at it use camelCase for all report config variables.
Get a working report config dialog and always use camelCase for variables.
https://jira.greenbone.net/browse/GEA-838
=> Refactor Report Config

src/web/components/form/__tests__/select.jsx, src/web/components/form/select.jsx
- Fix:  Select component list to show deprecated in the labels.
- Fix: Select component to search on select/deselect
- When selecting an item for the second time, the dropdown list would show only the selected item
GEA-861
=> fix: select component render options and search

src/gmp/models/__tests__/cpe.js, src/gmp/models/cpe.js, src/web/pages/cpes/details.jsx
Display CPE Name ID and deprecation status at CPE details
Ensure the model data is parsed correctly and contains the expected values. Display the CPE Name ID instead of the former NVD ID at the CPE details. Also the CPE status is not available anymore and only the deprecation status is shown.
=> Display CPE Name ID and deprecation status at CPE details

src/web/components/form/radio.jsx
- Ensure that label is a string
- Radio component doesn't always have the prop `title`, ex. if `title` is missing, it would display `undefined`.
=> Fix: remove Radio component title string conversions

.docker/prod.Dockerfile, .github/workflows/ci-js.yml, .github/workflows/release-pontos.yml, README.md, package-lock.json, package.json, src/gmp/locale/__tests__/detector.js
- Update the Node.js version in `package.json` to set the new minimum version to 20.
- Node.js version 18 will not be maintained beyond April 2025
https://jira.greenbone.net/browse/GEA-850
https://jira.greenbone.net/browse/GEA-891
=> deps: update node version

public/locales/gsa-de.json, public/locales/gsa-en.json, public/locales/gsa-zh_CN.json, public/locales/gsa-zh_TW.json, src/web/pages/reportformats/details.jsx, src/web/pages/reports/downloadreportdialog.jsx
Restrict available report formats when downloading a report according to the supported report type.
requires [#2370](https://github.com/greenbone/gvmd/pull/2370)
Avoid inconsistencies between reports and report formats.
GEA-873
=> Change: Differentiate scan and audit report formats

src/gmp/commands/__tests__/feedstatus.test.js, src/gmp/commands/__tests__/tasks.test.js
Add feed version to tests to avoid momentjs warnings
The feed version is parsed as date and if it is missing momentjs will complain. Therefore add the version to all feed sync tests to avoid warnings when running them.
https://jira.greenbone.net/browse/GEA-923
=> Add feed version to tests to avoid momentjs warnings

src/gmp/__tests__/parser.test.js, src/gmp/model.js, src/gmp/models/__tests__/tlscertificate.test.js, src/gmp/models/testing.js, src/gmp/models/tlscertificate.js, src/gmp/parser.js, src/web/components/form/multiselect.jsx
Ensure name properties of our models are always of type string.
Fix a crash of the group dialog when a user name only contains digits. Our XML to JS parsing library converts converts XML content and attributes which only contain digits as numbers. Sadly our MultiSelect component can't handle non-string values and labels anymore.
https://forum.greenbone.net/t/error-in-new-group-dialog-when-there-are-users-with-login-names-formed-by-numbers-only/20465/3
https://jira.greenbone.net/browse/GEA-922
=> Ensure name is string

eslint.config.js, src/gmp/capabilities/capabilities.js, src/gmp/models/event.js, src/web/Routes.jsx, src/web/entities/Header.jsx
- Remove v6 react router flags
- Add `eslint` strict equality rule and adjust lint files
- Best practice to have strict equality and avoid falsy, truthy coercion.
GEA-933
=> Eslint rule for strict equality and react router unused flags

src/web/components/dashboard/display/utils.js
Ensure that random colors have always six characters
Fix a flacky test by ensuring the random color function always returns a RGB color code with six characters.
https://github.com/greenbone/gsa/actions/runs/13515752252/job/37764029875?pr=4348
=> Ensure that random colors have always six characters

.gitignore, src/web/pages/scanconfigs/NvtFamilies.jsx
Add `openSUSE Local Security Checks` and `openEuler Local Security Checks` into the `LSC_FAMILY_LIST` and `FAMILIES_WHOLE_ONLY`
These families have been added by VT-Dev Team
GEA-921
GEA-929
=> Add: Add new whole only families

src/web/entity/Component.jsx, src/web/entity/__tests__/Component.tests.jsx
Use onInteractive passed from parent in EntityComponent
Don't override onInteractive prop in EntityComponent and use the prop passed from the parent component. All parent components using EnitityComponent already provide that prop.
Part of https://jira.greenbone.net/browse/GEA-935
=> Use onInteractive passed from parent in EntityComponent 

src/web/components/form/TextField.jsx, src/web/components/form/__tests__/TextField.test.jsx
Allow to pass a convert function to TextField
Add a convert function to TextField which is used for example in the port range dialog. It allows to change the value automatically to only valid values. This feature seems to have been removed when changing to the new UI.
Use in the PortRangeDialog component.
=> Allow to pass a convert function to TextField

src/web/components/form/DatePicker.jsx
Fix proptypes for DatePicker component
A value of false is allowed for the minDate to deactivate the minimum date and use date proptype to get better error messages. This fixes some warnings in the tests.
=> Fix proptypes for DatePicker component

src/web/pages/portlists/ListPage.jsx
- Continues re-render on the port list page
- `UseEffect` is always triggered, causing continues api calls.
=> fix: PortLists page continues rerender

src/web/entities/Header.jsx
Fix passing true as actions column to withEntitiesHeader
List pages that allow bulk selections but have no dedicated actions column like CVEs pass false for the action column when using withEntitiesHeader. This allows displaying the action column conditionally if the user selection is selected for the list table. Additionally the variables are changed to camelCase naming instead of underscore.
This changes removes proptype warnings in a bunch of tests and during development.
=> Fix passing true as actions column to withEntitiesHeader

src/web/utils/Testing.jsx
Add renderer functions to render within tables
Introduce new renderer function rendererWithTable and rendererWithTableRow for testing purposes and avoid warnings when rendering table row or table data elements.
=> Add renderer functions to render within tables

src/web/components/form/__tests__/useClickHandler.test.jsx, src/web/components/form/useClickHandler.js
Introduce a useClickHandler hook to replace withClickHandler
Add a new useClickHandler hook that implements the behavior of the withClickHandler HOC. This allows to replace the HOC at the end.
=> Introduce a useClickHandler hook to replace withClickHandler

src/web/entities/Row.jsx, src/web/entities/__tests__/RowDetailsToggle.test.jsx
Refactor RowDetailsToggle
Replace withClickHandler with useClickHandler and add data-testid for easier testing. Export RowDetailsToggle as default export too.
I am going to rename the Row js module to RowDetailsToggle in a future PR too. 
Easier testing and get rid of HOC.
=> Refactor RowDetailsToggle

src/web/entities/EntityNameTableData.jsx, src/web/entities/RowDetailsToggle.jsx, src/web/entities/__tests__/RowDetailsToggle.test.jsx, src/web/pages/audits/Row.jsx, src/web/pages/certbund/Row.jsx, src/web/pages/cpes/Row.jsx, src/web/pages/cves/Row.jsx, src/web/pages/dfncert/Row.jsx, src/web/pages/hosts/Row.jsx, src/web/pages/notes/Row.jsx, src/web/pages/nvts/Row.jsx, src/web/pages/overrides/Row.jsx, src/web/pages/reports/details/TlsCertificatesTable.jsx, src/web/pages/results/Row.jsx, src/web/pages/tasks/Row.jsx, src/web/pages/tlscertificates/Row.jsx
Rename Row module to RowDetailsToggle and remove named export
The Row module only contains the RowDetailsToggle component. Therefore the name of the module is adjusted. Because the module only has a single export using the default export only is cleaner.
=> Rename Row module to RowDetailsToggle and remove named export

src/web/entity/EntityComponent.jsx, src/web/entity/hooks/__tests__/usEntityClone.test.js, src/web/entity/hooks/__tests__/useEntityDelete.test.js, src/web/entity/hooks/__tests__/useEntityDownload.test.js, src/web/entity/hooks/__tests__/useEntitySave.test.js, src/web/entity/hooks/actionFunction.js, src/web/entity/hooks/useEntityClone.js, src/web/entity/hooks/useEntityDelete.js, src/web/entity/hooks/useEntityDownload.js, src/web/entity/hooks/useEntitySave.js
Introduce useEntityXyz action hooks
Allow to replace the render props based EntityComponent with hooks.
https://jira.greenbone.net/browse/GEA-935
=> Entity hooks

src/web/components/structure/Footer.jsx, src/web/components/structure/__tests__/Footer.test.jsx
- The footer link now dynamically opens `greenbone.net` based on the language setting. Currently only German and English.
- Previously, the link always opened the German version of the site.
GEA-944
=> Add: Update footer link to support localization based on user language

src/web/components/form/Select.jsx
- For select components, enforced by default the `type: hover` and `scrollbarSize` property for the dropdown scrollbar.
- Previously, scrollbar was visible only if scrolling.
GEA-907
=> change: Select dropdown scrollbar to show on hover

src/web/components/dialog/Dialog.jsx
- Ensure that only the top modal is applying the overlay.
- Previously, each modal would apply and overlay increasing opacity,
GEA-962
=> fix: stacking modal overlay opacity

src/web/pages/usersettings/UserSettingsPage.jsx
Re-throw any error received while updating the user settings.
Before, if there was an error response when saving the users settings, there would be no error
message shown
https://jira.greenbone.net/browse/GEA-782
=> Fix: show response error on user settings save

src/web/components/notification/__tests__/handleNotificationForAction.test.js, src/web/components/notification/handleNotificationForAction.js
Optional onError and onSuccess in handleNotificationForAction
Update handleNotificationForAction to make onSuccess and onError handlers optional. Sometimes these handler wont be provided. Especially in tests.
=> Optional onError and onSuccess in handleNotificationForAction

cliff.toml
Allow use `drop` and `Drop` for commits that should go into the `Removed` category in the release changelog and re-introduce the `Dependencies` category which was missing in the new changelog generation process. For the `Dependencies` category, commits starting with `deps` or `Deps` are considered.
Updated list is now
| Group | Commit Message starts with |
|-----------|------------|
|Added | add, Add |
|Changed |change, Change |
|Bug Fixes | fix, Fix |
| Removed | remove, Remove, drop, Drop |
|Documentation | doc, Doc |
| Testing | test, Test |
| Miscellaneous | chore, Chore, ci, Ci misc, Misc |
| Dependencies | deps, Deps |
Improved changelog generation.
https://jira.greenbone.net/browse/GEA-984
=> Changelog categories

src/web/entity/hooks/__tests__/actionFunction.test.js, src/web/entity/hooks/actionFunction.js
-  Show success notification only if `successMessage` is defined in `actionFunction`
- Add test for `actionfunction`
- 
- Show notification was always triggered show an empty notification
=> fix: Show success notification only if successMessage is defined in actionFunction

src/web/pages/portlists/PortListComponent.jsx, src/web/pages/portlists/__tests__/PortListComponent.test.jsx
Display errors during port list update and creation
Ensure errors are displayed when saving or creating a port list fails.
https://jira.greenbone.net/browse/GEA-935
=> Display errors during port list update and creation

public/locales/gsa-de.json, public/locales/gsa-en.json, public/locales/gsa-zh_CN.json, public/locales/gsa-zh_TW.json, src/web/pages/portlists/PortListComponent.jsx
Refactor PortListComponent into a function component using hooks
Part 1 of refactoring the PortListComponent. In a next step EntityComponent will be removed too.
The change removes the notification on port range deletions because this is raising a notification for each deleted port range and might cause a lot of notifications. IMHO also deleting the port range is only an internal detail of the port list.
Use modern react for the PortListComponent.
https://jira.greenbone.net/browse/GEA-935
=> Refactor PortListComponent into a function component using hooks

src/web/entity/hooks/__tests__/useActiveTab.test.ts, src/web/entity/hooks/useActiveTab.ts
Add a useActiveTab react hook
The hook will allow to simplify the rendering of section components of entity detail pages in future. It may replace render props.
=> Add a useActiveTab react hook

src/gmp/commands/__tests__/scanconfig.test.js, src/gmp/commands/scanconfigs.js, src/web/pages/scanconfigs/Component.jsx
When selecting VTs in a VT family and in the same step changing some VT settings, the selection of VTs was revoked. This is fixed now. Furthermore the display of the timeout values is fixed.
This is a bug-fix.
GEA-952
Tested manually on my local development system.
=> Fix: Fixed the revocation of the VT selection.

src/gmp/__tests__/log.test.js
Use our own version of that function instead.
Remove a warning using deprecated isFunction from nodejs utils
Less noise when running the tests.
=> Remove a warning using deprecated isFunction from nodejs utils

src/web/hooks/__tests__/useInstanceVariable.test.tsx, src/web/hooks/useInstanceVariable.ts, src/web/hooks/useTiming.js
Refactor useInstanceVariable to return a setter function too and convert it module to TypeScript.
Refactor useInstanceVariable to return the value and a setter function to allow changing the value and not having to use a mutable object.
=> Refactor useInstanceVariable to return a setter function too

README.md
Update the heading level for the severity rating setting in README
It should be in the Settings chapter.
=> Update the heading level for the severity rating setting in README

src/gmp/__tests__/parser.test.js, src/gmp/models/host.js, src/gmp/parser.ts
Remove unused object argument from parseProperties function
The second argument (object) of the parseProperties function in the
parser module is actually not used anywhere.
Requires https://github.com/greenbone/gsa/pull/4439
=> Simplify parse properties

src/web/pages/scanconfigs/EditDialog.jsx
- Handle inside the component of `name` and `comment` the input values.
- Memoize heavy component.
- Input fields are having slow responsiveness. 
GEA-884
=> fix: edit scan config dialog slow input fields

src/web/pages/performance/PerformancePage.jsx, src/web/pages/reports/details/ToolbarIcons.jsx
- Fix date handling in `ToolbarIcons` component reports details performance icon
- Trying to format a not valid date.
https://github.com/greenbone/gsa/issues/4444
https://jira.greenbone.net/browse/GEA-1024
=> fix: correct date handling in ToolbarIcons component in reports details

public/locales/gsa-de.json, public/locales/gsa-en.json, public/locales/gsa-zh_CN.json, public/locales/gsa-zh_TW.json, src/gmp/models/__tests__/scanner.test.js, src/gmp/models/scanner.js, src/web/pages/tasks/Dialog.jsx, src/web/pages/tasks/__tests__/Dialog.test.jsx
This PR adds support for the `OPENVASD_SCANNER_TYPE` to the scanner selection in the TaskDialog component. When this scanner is selected, the "Scan Config" section is now conditionally rendered. The default scanner remains OPENVAS. These changes ensure that OPENVASD is displayed and supported if it is defined in the GVMD.
This update ensures that the new `OPENVASD_SCANNER_TYPE` is properly supported, maintaining consistency with other scanner types and enabling configuration when the OPENVASD scanner is selected.
GEA-938
=> Add: Add openvasd scanner type to scanner select options

.github/workflows/ci-js.yml
Fix code coverage upload by removing lint report
The linting report got removed with #4447. Therefore fix the code coverage upload by not expecting an available linting report.
#4447
=>  Fix code coverage upload by removing lint report

src/gmp/capabilities/__tests__/capabilities.test.js, src/gmp/capabilities/capabilities.js, src/web/components/menu/Menu.jsx, src/web/components/menu/__tests__/Menu.test.jsx
- Renders "Remediation Tickets" only when `capabilities.mayAccess('tickets') `returns `true`.
- Adds a unit test to verify that "Remediation Tickets" is not rendered when the capability is missing.
- Ensures the frontend respects backend limitations and avoids showing inaccessible links.
- Previously, the menu was visible on unsupported models, leading to a "Service unavailable: Command disabled" error.
- This change fixes that issue by aligning the frontend visibility with backend permissions.
GEA-1008
=> Fix: Hide remediation tickets depends on capabilities

README.md, index.html, src/gmp/__tests__/gmpsettings.test.ts, src/gmp/gmpsettings.ts
Rename GMPSettings "title" field to "vendorTitle"
In order to keep naming consistent
https://jira.greenbone.net/browse/GEA-747
=> Change: rename title to vendorTitle

src/web/pages/schedules/Dialog.jsx, src/web/pages/schedules/__tests__/Dialog.test.jsx
Add check to ensure time is valid before updating state
A method call on an invalid moment throws an error
https://jira.greenbone.net/browse/GEA-948
=> Fix: Ensure time is valid before settings

.github/workflows/ci-js.yml
Fix typo in CI step summary for translation command
The command is named `i18n-extract` instead of `i18next-extract`.
=> Fix typo in CI step summary for translation command

src/gmp/locale/__tests__/date.test.js, src/gmp/locale/date.ts, src/web/components/date/DateTime.tsx, src/web/components/date/__tests__/DateTime.test.jsx, src/web/components/section/Header.tsx, src/web/pages/reports/DetailsContent.jsx, src/web/pages/reports/__tests__/DetailsContent.test.jsx, src/web/utils/userSettingTimeDateFormatters.js
- Improve `DateTime` to be able to split into lines date-time and timezone.
- Line breaks were splitting words. 
GEA-1026
=> improve report details name 

src/web/pages/login/LoginPage.tsx, src/web/pages/login/__tests__/LoginPage.test.jsx
The timezone was not updated in the redux store on login.
Currently, after login an incorrect timezone is displayed, the user needs to refresh the page to display the user setting timezone.
GEA-1051
=> fix: bug timezone not set for store in login

.github/workflows/ci-js.yml
Fix linting job to fail again if a warning or error was found
Piping the linting output to tee will hide the status code of the npm command if pipefail is not set.
=> Fix linting job to fail again if a warning or error was found

src/web/pages/nvts/NvtPreference.jsx
Moved checkbox to enable credentials file upload and file input onto separate files
Originally the checkbox to enable uploads and the file input where on the same line.
This caused issues with actually being able to upload files due to the file input being too
small to click.
The checkbox to enable and the file input arenow on separate lines.
https://jira.greenbone.net/browse/GEA-1036
=> Change: file type preference styling

src/web/pages/login/LoginPage.tsx
Use guest as password and username by default for guest login
If the guestUsername and guestPassword settings are not set use "guest" as username and password when trying to login. With this change we ensure that we get an error from the backend if the settings are not set.
=> Use guest as password and username by default for guest login

src/web/components/form/NumberField.tsx
Mark type and size props of NumberField optional
Both props have a default. Therefore they are actually optional.
=> Mark type and size props of NumberField optional

src/gmp/parser.ts
Use parseFloat function for parseSeverity
The current implementation provided no extra value compared to parseFloat. Therefore map parseSeverity to parseFloat.
=> Use parseFloat function for parseSeverity

src/gmp/model.ts
Try to fix issue with polymorphic static fromElement method
The static Model.fromElement returns an instance of the current class and not Model.
=> Try to fix issue with polymorphic static fromElement method

src/gmp/utils/array.ts
Use TypeScript for array utils module
Add type information to the array utils module. Some things in this module are not "typeable" sadly.
=> Use TypeScript for array utils module

src/web/pages/portlists/PortListComponent.tsx
Show errors if a port range could not be created
Return a promise to show errors if a to be created port range has issues with existing port ranges.
=> Show errors if a port range could not be created

package.json, tsconfig.json, vitest.projects.ts
Improve vitest: 
- Remove inline import for opensight UI in vitest config.
- add command to run test in `vm` for faster results.
=> add node cmd for faster testing

src/web/App.tsx, src/web/utils/Testing.tsx
Use TypeScript for App component and fix setting the Theme
The API of the ThemeProvider did change a while ago and it isn't possible to override the theme anymore. With using TypeScript now this issue became visible.
=> Use TypeScript for App component and fix setting the Theme

src/web/pages/overrides/Dialog.jsx
Fix setting the new severity for overrides
Use a NumberField for the new severity value and set appropriate boundaries for a severity value (min, max, precision).
https://jira.greenbone.net/browse/GEA-1059
=> Fix setting the new severity for overrides

src/web/pages/operatingsystems/dashboard/VulnScoreDisplay.jsx
Fix displaying the OS by Vulnerability Score chart
The display ID was not set correctly and therefore the Operating System by Vulnerability Score chart was not available at all. Not having the display ID set raised a warning in the browser console which is fixed now.
https://jira.greenbone.net/browse/GEA-1067
=> Fix displaying the OS by Vulnerability Score chart

src/gmp/utils/array.ts
Update type for first forEach function argument
The forEach function explicitly allows for non arrays as first argument because our responses may return a single object instead of an array with a single object if only one response object is available.
=> Update type for first forEach function argument

src/gmp/model.ts
Update Model.fromElement type info to return a Model by default
For many use cases (for example testing) it is fine to just return a Model instance.
=> Update Model.fromElement type info to return a Model by default

.github/workflows/changelog.yml, .github/workflows/ci-js.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/conventional-commits.yml, .github/workflows/dependency-review.yml, .github/workflows/release.yml, .github/workflows/sbom-upload.yml
When workflows are triggered by a new commit, still running instances of the same workflow on the same git ref / branch will be cancelled to save resources.
We usually dont need to continue running old jobs when a new commit comes in that starts the same jobs again.
This saves us some running time and ressources.
See DEVOPS-1538
- [ NA] Tests
=> Add: cancellation of running CI jobs on new commit

src/web/pages/targets/Details.jsx, src/web/pages/targets/__tests__/Details.test.jsx
Ensure Kerberos credentials are displayed in target details, even when they are the only credential type defined.
Currently, Kerberos credentials aren't displayed when they're the only credential available. This change ensures they're consistently shown in the target details regardless of other credential types.
GEA-1066
=> fix:  TargetDetails to conditionally render Kerberos credentials

src/web/pages/audits/Dialog.jsx, src/web/pages/tasks/Dialog.jsx
A fallback value was added for the alert ids in the audits and the tasks dialog to avoid problems with the MultiSelect.
This fixes a bug.
GEA-1063
Tested manually on my local development system.
=> Fix: Added a fallback value to avoid problems with the MultiSelect.

src/web/components/icon/createIconComponents.tsx, src/web/components/icon/test/createIconComponent.test.tsx
Svg icons color should reflect the state, which should be gray if disabled.
GEA-1081
=> fix: svg icons color disabled

src/web/components/icon/DeleteIcon.tsx, src/web/components/icon/DynamicIcon.tsx, src/web/components/icon/ExportIcon.tsx, src/web/components/icon/createIconComponents.tsx, src/web/components/icon/index.tsx, src/web/components/icon/test/DynamicIcon.test.tsx, src/web/components/icon/test/createIconComponent.test.tsx, src/web/components/structure/__tests__/Header.test.jsx
- Refactor how icons are managed, creating a more defined differentiation between SVG and Lucide icons.
- Some SVGs were not showing the correct colors.
=> fix: active icons color

src/web/pages/portlists/PortListDialog.tsx
Add file to PortListDialog save data
The file was missing from the data type description when the PortListDialog gets saved.
=> Add file to PortListDialog save data

src/gmp/commands/__tests__/portlist.test.ts, src/gmp/commands/portlists.ts, src/web/pages/portlists/PortListComponent.tsx, src/web/pages/portlists/PortListImportDialog.tsx
Port list import xmlFile is a File not a string
The xmlFile argument of the port list import is actually a File instance and not a string.
=> Port list import xmlFile is a File not a string

src/web/testing/customQueries.ts
Raise error if Dialog X Button could not be found
Don't return null from getDialogXButton query function and instead raise an error if the button couldn't be found.
=> Raise error if Dialog X Button could not be found 

src/web/components/menu/Menu.jsx, src/web/components/menu/__tests__/Menu.test.jsx
Fix capabilities checks for displaying menu entries
`scan_config` or `scan_config` is currently not a type that can be passed to the capabilities methods. It must be `config`, `configs`, `scanconfig` or `scanconfigs` at the moment. This is quite confusing and has to be improved in future.
Because I had the stunning idea to use *"better"* names for the entities in the UI then in the backend we introduced a translation mechanism between UI entity types and backend entity types. The backend entity types are used for the capabilities. Sadly we also  removed the underscore word separation for the UI entity names and this made the UI entity names even more confusing. As last resort of confusion, the capabilities methods accept both UI and backend entity types.
=> Fix capabilities checks for displaying menu entries

src/web/utils/Theme.tsx
Adapt colors for medium and low severity
Use '#A0C5F9' for low and '#F3B865' for medium severity now.
Use same colors as OPENVAS REPORT
https://jira.greenbone.net/browse/GEA-1111
=> Adapt colors for medium and low severity

src/web/pages/cves/DetailsPage.jsx
Fix rendering CVE details
When clicking opening the CVE details page via clicking on an entry in the CVE list page an error was raised (at least in the development mode). This was caused by a redux check for a mutated state. With redux the state must not be mutated at all. Therefore Array sort can't be used to sort the CVE products because it sorts in-place which mutates the state of the CVE model. As a solution the sort method got exchanged with the newer toSorted method which returns a sorted array but doesn't change the original array.
https://jira.greenbone.net/browse/GEA-910
https://jira.greenbone.net/browse/GEA-1062
=> Fix rendering CVE details

public/locales/gsa-de.json, public/locales/gsa-en.json, public/locales/gsa-zh_CN.json, public/locales/gsa-zh_TW.json, src/gmp/models/__tests__/scanner.test.js, src/gmp/models/scanner.js, src/web/pages/tasks/Dialog.jsx, src/web/pages/tasks/__tests__/Dialog.test.jsx
This PR adds support for the new OPENVASD_SENSOR_SCANNER_TYPE in GSA.
This change is needed to distinguish OpenVASD sensor scanners from other types in the frontend.
It aligns with GVMD changes introducing `SCANNER_TYPE_OPENVASD_SENSOR`
GEA-940
=> Add: Support OPENVASD_SENSOR_SCANNER_TYPE in GSA

src/web/components/dialog/SaveDialog.tsx
Mark the onSave method of the SaveDialog as optional
Actually it was optional already before but the type info was incorrect.
=> Mark the onSave method of the SaveDialog as optional

src/web/components/form/Checkbox.tsx, src/web/components/form/__tests__/Checkbox.test.tsx
Render name for Checkbox component
Actually pass the name prop to the underlying component so that it shows up in the DOM.
=>  Render name for Checkbox component

src/web/pages/user-settings/FilterSettings.tsx, src/web/store/usersettings/defaultfilters/__tests__/actions.test.js, src/web/store/usersettings/defaultfilters/__tests__/reducers.test.js, src/web/store/usersettings/defaultfilters/actions.js, src/web/store/usersettings/defaultfilters/reducers.js
fix: update optimistic update action to use filter object instead of filderId
=> fix: update optimistic update action to use filter object instead of filderId

src/web/pages/tags/ListPage.jsx
fix:  typo in TagsPage component filter prop not populating filters
=> fix:  typo in TagsPage component filter prop not populating filters

src/gmp/models/__tests__/filter.test.ts, src/gmp/models/filter.ts, src/web/pages/portlists/ListPage.jsx, src/web/pages/user-settings/__tests__/FilterSettings.test.tsx, src/web/pages/user-settings/__tests__/UserSettingsPage.test.tsx, src/web/store/utils.js
Introduce a Filter identifier method
The identifier method returns a unique string for being used in the store. By adding an explicit method for the identifier we can change the implementation details without having to change the toFilterString method which the store relied on before. For example we could consider the id as part of the identifier in future or consider the order of terms irrelevant.
=> Introduce a Filter identifier method

src/web/components/provider/SubscriptionProvider.tsx, src/web/components/provider/__tests__/SubscriptionProvider.test.tsx
Use TypeScript for the SubsciptionProvider
The SubsciptionProvider is used in withEntitiesContainer and therefore at every list page. Having a types version allows for converting withEntitiesContainer to TypeScript too.
=> Use TypeScript for the SubsciptionProvider

src/web/pages/tasks/TaskFilterDialog.tsx
filter prop of TaskFilterDialog is optional
There might be no filter at all.
=> filter prop of TaskFilterDialog is optional

src/web/pages/reports/ListPage.jsx
Fix rendering of ReportListPage after withEntitiesContainer refactoring
Reorder applied HOCs for the ReportListPage to fix its rendering. The withEntitiesContainer HOC has been refactored and doesn't forward all props unsolicitedly anymore. Just forwarding all props has the disadvantage of figuring out where the prop actually comes from. Therefore being explicit about the props is better at the end.
=> Fix rendering of ReportListPage after withEntitiesContainer refactoring

src/web/entities/withRowDetails.tsx, src/web/pages/tasks/TaskTable.tsx
Use TypeScript for withRowDetails HOC
It seems all the components in src/web/entities need to be converted to TypeScript first, before being able to fix all issues with the list pages.
=> Use TypeScript for withRowDetails HOC

src/web/components/icon/TagsIcon.tsx
Use TypeScript for TagsIcon
It's used in the EntitiesFooter component which I am going to refactor next.
https://jira.greenbone.net/browse/GEA-1094
=> Use TypeScript for TagsIcon

src/web/pages/alerts/AlertComponent.jsx, src/web/pages/credentials/CredentialsComponent.jsx, src/web/pages/filters/FilterComponent.jsx, src/web/pages/groups/GroupComponent.jsx, src/web/pages/hosts/HostComponent.jsx, src/web/pages/overrides/OverrideComponent.jsx, src/web/pages/permissions/PermissionsComponent.jsx, src/web/pages/policies/PoliciesComponent.jsx, src/web/pages/roles/RoleComponent.jsx, src/web/pages/scanners/ScannerComponent.jsx, src/web/pages/schedules/ScheduleComponent.jsx, src/web/pages/tags/TagsComponent.jsx, src/web/pages/targets/Component.jsx, src/web/pages/users/UserComponent.jsx
fix creating new elements for the following:
- alerts
- credentials
- filters
- groups
- hosts
- overrides
- permissions
- policies
- roles
- scanners
- schedules
- tags
- targets
- users
- scanconfigs
With the change of differentiating between save and create in the dialog was not able to create new element any more.
GEA-1189
=> fix: creating list of different entity

.github/workflows/auto-merge.yml
Enable auto-merge rebase for each PR
Set auto-merge to rebase for each PR by default without user interaction. This allows to merge a PR after an approval automatically.
=> Enable auto-merge rebase for each PR

src/web/pages/tasks/TaskDialog.tsx
Fix opening task dialog for alert selection
It seems that task.alerts may contain alerts with ID 0. ID 0 is an invalid aka. empty ID. With the XML transformation XML strings with numbers are converted to numbers in JS/TS. Therefore the existing safety check in the TaskDialog failed and the MultiSelect element crashed. The filtering of the 0 alert ID should be moved to the Task parsing code in future too.
=> Fix opening task dialog for alert selection

src/web/components/dashboard/display/DataDisplay.tsx, src/web/utils/__tests__/withTranslation.test.tsx, src/web/utils/withTranslation.tsx
Improve types of withTranslation HOC and add a test
A component using the withTranslation should be aware of the props that are provided.
=> Improve types of withTranslation HOC and add a test

src/gmp/utils/object.ts
Improve excludeObjectProps function to be useable with as const arrays
The list of to be excluded props is read only. This allows passing arrays marked with `as const`.
=> Improve excludeObjectProps function to be useable with as const arrays ## Why

src/web/entities/createEntitiesFooter.tsx, src/web/entities/createEntitiesHeader.tsx, src/web/entities/withEntitiesFooter.tsx, src/web/entities/withEntitiesHeader.tsx
Improve types EntitiesFooter and EntitiesHeader HOCs
Use the same patter for the type information at all entities HOCs. A component using these HOCs need to extend from a specific interface if options are available these options need to be of the specific interface with optional properties.
=>  Improve types EntitiesFooter and EntitiesHeader HOCs

src/gmp/models/__tests__/note.test.ts, src/gmp/models/__tests__/override.test.ts, src/gmp/models/note.ts, src/gmp/models/nvt.ts, src/gmp/models/override.ts
- Fix select the same VT when editing an override
- Cannot select the same VT when editing an override, expected different backend response structure.
GEA-1189
=> Fix select the same VT when editing an override

src/gmp/models/__tests__/policy.test.ts, src/gmp/models/__tests__/scanconfig.test.ts, src/gmp/models/policy.ts, src/gmp/models/scanconfig.ts
- On opening of the scancofig and policy edit dialog, it would display error.
- Object structure was missing key/value
GEA-1195
=> fix: scan config and policy dialog error

.github/workflows/container.yml
Don't cancel manually run container build from main
When starting a container image build manually github.ref will be main but we are building a for some different ref most likely for a tag. In this case all pushes to main will cancel the manually run container build despite it's building for a different ref. To fix this behavior use input.ref-name as an identifier for cancelling a workflow run and fallback to github.ref if it is not set.
=> Don't cancel manually run container build from main

src/web/testing/Render.tsx
Allow to render without user having any capabilities easily
Extend rendererWith functions to allow rendering without having any capability for easier testing.
=> Allow to render without user having any capabilities easily

src/gmp/commands/__tests__/role.test.ts, src/gmp/commands/__tests__/roles.test.ts, src/gmp/commands/entities.ts, src/gmp/commands/roles.ts, src/gmp/gmp.ts, src/gmp/models/role.ts, src/web/entity/EntityPermissions.tsx
Use TypeScript for RoleCommand and RolesCommand
Also add tests for both commands.
Allow to validate all role specific http requests and responses.
https://jira.greenbone.net/browse/GEA-1098
=> Use TypeScript for RoleCommand and RolesCommand

README.md, src/gmp/__tests__/gmpsettings.test.ts, src/gmp/gmpsettings.ts, src/web/components/layout/PageTitle.tsx
Update setting the default page title
Move the default title into the gmp settings module to have a central place for defining the page title.
=> Update setting the default page title

src/web/components/menu/IconMenu.tsx, src/web/components/menu/__tests__/IconMenu.test.tsx, src/web/pages/tasks/__tests__/TaskDetailsPage.test.tsx, src/web/pages/tasks/icons/__tests__/NewIconMenu.test.tsx, src/web/pages/tasks/icons/__tests__/TaskToolBarIcons.test.tsx
- Change the new task to button, opened by clicking and not hovering.
- To be more consistent and for accesibility.
GEA-1269
=> change: Update 'New Task' to button in task view

src/web/components/powerfilter/__tests__/useFilterDialog.test.tsx, src/web/components/powerfilter/useFilterDialog.tsx
Allow to change the initial filter string in useFilterDialog hook
When using the useFilterDialog hook for handling the state of a powerfilter dialog, allow to adjust the initial filter string. This allows for not displaying parts of the filter string that are handled via an form input. Ensure this behavior by adding tests for the hook too.
=>  Allow to change the initial filter string in useFilterDialog hook

src/gmp/commands/report.ts, src/web/components/form/Download.tsx, src/web/components/form/useDownload.ts, src/web/pages/reports/DeltaDetailsPage.tsx
Fix downloading a delta report
Downloading a report from the backend returns an ArrayBuffer and must not be converted into some json string.
https://jira.greenbone.net/browse/GEA-1287
=> Fix downloading a delta report
