src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/web/components/link/target.js

Anchors will not be hidden behind the top menu bar.

Add new component for inner link anchors

---

src/gsad.c

README got renamed to README.md

Adapt Doxygen settings to recent filename change

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/gmp/commands/trashcan.js
src/html/classic/ng/src/gmp/gmp.js
src/html/classic/ng/src/web/app.js
src/html/classic/ng/src/web/components/bar/menubar.js
src/html/classic/ng/src/web/components/icon/restoreicon.js
src/html/classic/ng/src/web/components/icon/trashdeleteicon.js
src/html/classic/ng/src/web/pages/extras/trashactions.js
src/html/classic/ng/src/web/pages/extras/trashcanpage.js

The trashcan page is added with corresponding new api and icons.

Trashcan added

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/gmp/capabilities/capabilities.js
src/html/classic/ng/src/gmp/models/certbund.js
src/html/classic/ng/src/web/app.js
src/html/classic/ng/src/web/pages/certbund/details.js
src/html/classic/ng/src/web/pages/certbund/detailspage.js
src/html/classic/ng/src/web/pages/certbund/row.js
src/html/classic/ng/src/web/pages/certbund/table.js

Implemented the cert bund details page.

Cert bund details

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/gmp/capabilities/capabilities.js
src/html/classic/ng/src/gmp/models/dfncert.js
src/html/classic/ng/src/web/app.js
src/html/classic/ng/src/web/pages/dfncert/details.js
src/html/classic/ng/src/web/pages/dfncert/detailspage.js
src/html/classic/ng/src/web/pages/dfncert/row.js
src/html/classic/ng/src/web/pages/dfncert/table.js

Dfn cert details

---

.gitignore

Don't ignore ng/src/web/pages/tags directory.

Only ignore global tags file

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/web/app.js
src/html/classic/ng/src/web/entities/entitynametabledata.js
src/html/classic/ng/src/web/pages/users/component.js
src/html/classic/ng/src/web/pages/users/details.js
src/html/classic/ng/src/web/pages/users/detailspage.js
src/html/classic/ng/src/web/pages/users/row.js
src/html/classic/ng/src/web/pages/users/table.js

User details

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/web/entities/withRowDetails.js
src/html/classic/ng/src/web/pages/allsecinfo/details.js
src/html/classic/ng/src/web/pages/allsecinfo/row.js
src/html/classic/ng/src/web/pages/allsecinfo/table.js
src/html/classic/ng/src/web/pages/cves/details.js
src/html/classic/ng/src/web/pages/nvts/details.js
src/html/classic/ng/src/web/pages/nvts/references.js
src/html/classic/ng/src/web/pages/ovaldefs/details.js

Add details for allsecinfo list page.

Allsecinfo details

---

src/html/classic/ng/src/gmp/gmp.js
src/html/classic/ng/src/web/components/icon/helpicon.js

Help link anchors

---

src/html/classic/ng/src/web/components/dialog/savedialog.js
src/html/classic/ng/src/web/utils/state.js

Save dialog initial data

---

src/html/classic/ng/src/gmp/commands/overrides.js
src/html/classic/ng/src/web/pages/overrides/component.js
src/html/classic/ng/src/web/pages/overrides/dialog.js

Fix setting the port and hosts of an override

Override port and location

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/gmp/commands/overrides.js
src/html/classic/ng/src/gmp/models/override.js
src/html/classic/ng/src/gmp/models/user.js
src/html/classic/ng/src/web/pages/cpes/detailspage.js
src/html/classic/ng/src/web/pages/users/css/row.css
src/html/classic/ng/src/web/pages/users/row.js

Update different parts of code.

Code cleanup

---

src/html/classic/ng/src/web/entity/info.js

Entities without an owner are in the "globale space". They are not owned
by any user.

Display entites without owner as global objects

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/gmp/models/group.js
src/html/classic/ng/src/web/app.js
src/html/classic/ng/src/web/pages/groups/component.js
src/html/classic/ng/src/web/pages/groups/details.js
src/html/classic/ng/src/web/pages/groups/detailspage.js
src/html/classic/ng/src/web/pages/groups/listpage.js
src/html/classic/ng/src/web/pages/groups/row.js
src/html/classic/ng/src/web/pages/groups/table.js

Group details

---

src/html/classic/ng/src/web/entity/container.js
src/html/classic/ng/src/web/pages/permissions/component.js

Fix permission edit dialog and add seconds permission loader for the details pages.

Permission handling changes

---

src/html/classic/ng/CMakeLists.txt
src/html/classic/ng/src/gmp/commands/roles.js
src/html/classic/ng/src/gmp/models/role.js
src/html/classic/ng/src/web/app.js
src/html/classic/ng/src/web/entity/container.js
src/html/classic/ng/src/web/pages/roles/component.js
src/html/classic/ng/src/web/pages/roles/details.js
src/html/classic/ng/src/web/pages/roles/detailspage.js
src/html/classic/ng/src/web/pages/roles/listpage.js
src/html/classic/ng/src/web/pages/roles/row.js
src/html/classic/ng/src/web/pages/roles/table.js

Role details

---

ng/CMakeLists.txt
ng/src/gmp/capabilities/capabilities.js
ng/src/gmp/models/portlist.js
ng/src/web/app.js
ng/src/web/components/folding/folding.js
ng/src/web/entities/entitynametabledata.js
ng/src/web/pages/portlists/component.js
ng/src/web/pages/portlists/details.js
ng/src/web/pages/portlists/detailspage.js
ng/src/web/pages/portlists/dialog.js
ng/src/web/pages/portlists/listpage.js
ng/src/web/pages/portlists/portrangedialog.js
ng/src/web/pages/portlists/portrangestable.js
ng/src/web/pages/portlists/row.js
ng/src/web/pages/portlists/table.js

Port list details

---

ng/CMakeLists.txt
ng/src/gmp/commands/credentials.js
ng/src/gmp/models/credential.js
ng/src/gmp/models/filter.js
ng/src/web/app.js
ng/src/web/pages/credentials/component.js
ng/src/web/pages/credentials/details.js
ng/src/web/pages/credentials/detailspage.js
ng/src/web/pages/credentials/dialog.js
ng/src/web/pages/credentials/downloadicon.js
ng/src/web/pages/credentials/listpage.js
ng/src/web/pages/credentials/row.js
ng/src/web/pages/credentials/table.js

Credential details

---

ng/src/web/pages/roles/dialog.js

Set the correct name prop on the select component to be able to choose
an entry.

Fix selection permission at role dialog

---

ng/src/gmp/collection/collectioncounts.js
ng/src/gmp/collection/parser.js
ng/src/gmp/commands/filters.js
ng/src/web/components/bar/menubar.js

Don't crash and don't show menus and its entries if the user hasn't some specific permissions .

Fix several permission based issues

---

ng/CMakeLists.txt
ng/src/gmp/commands/schedules.js
ng/src/gmp/models/filter.js
ng/src/gmp/models/schedule.js
ng/src/web/app.js
ng/src/web/entities/actions.js
ng/src/web/pages/schedules/component.js
ng/src/web/pages/schedules/details.js
ng/src/web/pages/schedules/detailspage.js
ng/src/web/pages/schedules/listpage.js
ng/src/web/pages/schedules/render.js
ng/src/web/pages/schedules/row.js
ng/src/web/pages/schedules/table.js

Schedule details

---

ng/CMakeLists.txt
ng/src/gmp/capabilities/capabilities.js
ng/src/gmp/models/reportformat.js
ng/src/web/app.js
ng/src/web/pages/reportformats/component.js
ng/src/web/pages/reportformats/details.js
ng/src/web/pages/reportformats/detailspage.js
ng/src/web/pages/reportformats/listpage.js
ng/src/web/pages/reportformats/row.js
ng/src/web/pages/reportformats/table.js
ng/src/web/utils/render.js

Add new components for displaying the report format details.

Report format details

---

ng/src/web/pages/targets/row.js

Improve several things at the target row rendering.

Target row updates

---

ng/CMakeLists.txt
ng/src/gmp/commands/auth.js
ng/src/gmp/commands/users.js
ng/src/gmp/gmp.js
ng/src/web/app.js
ng/src/web/components/bar/menubar.js
ng/src/web/pages/ldap/ldappage.js

The LDAP authentication page is added with a corresponding new API to save auth settings and the possibility to get certificate info from cmd: auth_settings, that where not returned until now.

Ldap authentication

---

ng/CMakeLists.txt
ng/src/gmp/models/filter.js
ng/src/web/app.js
ng/src/web/pages/agents/component.js
ng/src/web/pages/agents/details.js
ng/src/web/pages/agents/detailspage.js
ng/src/web/pages/agents/listpage.js
ng/src/web/pages/agents/row.js
ng/src/web/pages/agents/table.js

Add components for displaying the agent details.

Agent details

---

ng/src/gmp/collection/collectioncounts.js

Used the wrong variable for checking if last should be zero.

Fix displaying the pagination

---

ng/CMakeLists.txt
ng/src/gmp/commands/auth.js
ng/src/web/app.js
ng/src/web/components/bar/menubar.js
ng/src/web/pages/radius/radiuspage.js

Add new RADIUS authentication page with corresponding API updates etc.

Radius authentication

---

ng/src/web/components/loading/loading.js

Use some CSS animation to show a rotating circle in green(bone) colors

Make the Loading component look nice

---

ng/CMakeLists.txt
ng/src/web/app.js
ng/src/web/components/bar/menubar.js
ng/src/web/pages/help/about.js

About page

---

ng/CMakeLists.txt
ng/src/gmp/models/filter.js
ng/src/web/app.js
ng/src/web/pages/filters/component.js
ng/src/web/pages/filters/details.js
ng/src/web/pages/filters/detailspage.js
ng/src/web/pages/filters/listpage.js
ng/src/web/pages/filters/row.js
ng/src/web/pages/filters/table.js

Add components for displaying the filter details.

Filter details

---

ng/CMakeLists.txt
ng/src/gmp/models/filter.js
ng/src/web/app.js
ng/src/web/pages/tags/component.js
ng/src/web/pages/tags/details.js
ng/src/web/pages/tags/detailspage.js
ng/src/web/pages/tags/dialog.js
ng/src/web/pages/tags/listpage.js
ng/src/web/pages/tags/row.js
ng/src/web/pages/tags/table.js

Add components for displaying the tag details

Tag details

---

ng/CMakeLists.txt
ng/src/web/app.js
ng/src/web/pages/permissions/component.js
ng/src/web/pages/permissions/details.js
ng/src/web/pages/permissions/detailspage.js
ng/src/web/pages/permissions/listpage.js
ng/src/web/pages/permissions/row.js
ng/src/web/pages/permissions/table.js

Add components for permission details

Permission details

---

ng/src/web/components/link/link.js
ng/src/web/entity/link.js

Allow to link to anchors within pages.

Links with anchor

---

ng/src/web/entities/container.js

The operations on a single entity are handled by their corresponding
entity component now. Therefore these code paths can safely be removed
from EntitiesContainer

Remove single entity handling from EntitiesContainer

---

ng/src/web/pages/users/listpage.js
ng/src/web/pages/users/row.js

Remove code duplication by using the UserComponent also at the users
list page. This allows to remove the UserDialog from the list page
component.

Refactor users list page to use UserComponent

---

ng/src/web/components/form/datepicker.js

We need to get rid of the jquery-ui datepicker (https://api.jqueryui.com/datepicker/) at the end...

Datepicker update

---

ng/src/web/components/menu/iconmenu.js
ng/src/web/components/menu/menuentry.js

Update menu entry components and fix some display issues.

Menu improvements

---

ng/src/web/pages/credentials/listpage.js

Upon click the dialog did not open. This bug is now fixed and coding style is updated.

Fix "create credentials"

---

ng/CMakeLists.txt
ng/src/gmp/commands/performance.js
ng/src/gmp/gmp.js
ng/src/web/app.js
ng/src/web/components/bar/menubar.js
ng/src/web/pages/performance/performancepage.js
ng/src/web/pages/performance/startendtimeselection.js

Add components for a react version of the performance page

Performance page

---

ng/CMakeLists.txt
ng/src/gmp/capabilities/capabilities.js
ng/src/web/pages/scanconfigs/component.js
ng/src/web/pages/scanconfigs/listpage.js
ng/src/web/pages/scanconfigs/row.js

Fix for the scan configs list page after #100 got merged.

Scanconfig component

---

ng/src/web/pages/agents/row.js
ng/src/web/pages/alerts/row.js
ng/src/web/pages/credentials/row.js
ng/src/web/pages/groups/row.js
ng/src/web/pages/hosts/row.js
ng/src/web/pages/notes/row.js
ng/src/web/pages/os/row.js
ng/src/web/pages/overrides/row.js
ng/src/web/pages/permissions/row.js
ng/src/web/pages/portlists/row.js
ng/src/web/pages/reportformats/row.js
ng/src/web/pages/reports/row.js
ng/src/web/pages/roles/row.js
ng/src/web/pages/scanners/row.js
ng/src/web/pages/tags/row.js
ng/src/web/pages/targets/row.js
ng/src/web/pages/tasks/actions.js

Add IconDivider or update existing ones to center icons in table column
and add margins.

Fix action icon margins

---

src/html/classic/omp.xsl

Use the filt_id "0" instead of "--" to use the built-in default filter
or one defined by GSA instead of the user default when resetting the
filter.

Fix "Reset Filter" button and "--" filter.

---

ng/src/web/pages/usersettings/dialog.js

The option -- (select no option) is added to the option_lists of settings.

Allow to _not_ set a setting

---

ng/CMakeLists.txt
ng/src/web/components/dialog/linkconfirmationdialog.js
ng/src/web/components/icon/helpicon.js
ng/src/web/components/icon/icon.js
ng/src/web/components/link/externallink.js
ng/src/web/pages/cves/details.js
ng/src/web/pages/nvts/references.js

External links now feature a disclaimer/confirmation dialog and users are required to confirm that they are leaving GSA and opening an external website.

Confirmation Dialog for ExternalLink

---

ng/CMakeLists.txt
ng/src/gmp/models/scanconfig.js
ng/src/web/app.js
ng/src/web/pages/scanconfigs/details.js
ng/src/web/pages/scanconfigs/detailspage.js
ng/src/web/pages/scanconfigs/row.js
ng/src/web/pages/scanconfigs/table.js

Scanconfig details

---

ng/src/web/components/bar/menubar.js
ng/src/web/pages/cves/details.js
ng/src/web/pages/nvts/details.js
ng/src/web/pages/results/detailspage.js
ng/src/web/pages/scanconfigs/editnvtdetailsdialog.js

Get rid of legacy links part two.

No legacy links part 2

---

ng/src/gmp/commands/agents.js
ng/src/web/pages/agents/component.js
ng/src/web/pages/agents/detailspage.js
ng/src/web/pages/agents/listpage.js
ng/src/web/pages/agents/row.js

Add an api for downloading an agent installer.

Agent installer download

---

ng/src/gmp/commands/credentials.js
ng/src/web/pages/credentials/component.js
ng/src/web/pages/credentials/detailspage.js
ng/src/web/pages/credentials/downloadicon.js
ng/src/web/pages/credentials/listpage.js
ng/src/web/pages/credentials/row.js

Don't use LegacyLinks for downloading credentials anymore.

Credential download refactoring

---

ng/src/web/pages/scanners/component.js
ng/src/web/pages/scanners/detailspage.js
ng/src/web/pages/scanners/listpage.js
ng/src/web/pages/scanners/row.js

Remove usage of LegacyLink component for downloading scanner certificates.

Scanner cert downloads

---

ng/src/web/entities/entitynametabledata.js
ng/src/web/pages/roles/listpage.js
ng/src/web/pages/tasks/autodeletereportsgroup.js

Update code to get rid of the warnings in the console.

Fix console warnings

---

ng/src/web/entities/container.js
ng/src/web/entities/page.js

Improve handling of filter updates at the entities list pages.

List page filter reset

---

src/po/gsad_js-ar.po
src/po/gsad_xsl-ar.po

The Arabic translations on https://translate.greenbone.net/ar/
have been updated, so this integrates the changes into GSA.

Update Arabic translations

---

ng/CMakeLists.txt
ng/src/web/components/dialog/container.js
ng/src/web/components/dialog/content.js
ng/src/web/components/dialog/dialog.js
ng/src/web/components/dialog/footer.js
ng/src/web/components/dialog/linkconfirmationdialog.js
ng/src/web/components/dialog/resizer.js
ng/src/web/components/dialog/savedialog.js
ng/src/web/components/dialog/scrollablecontent.js
ng/src/web/components/dialog/title.js
ng/src/web/components/dialog/withDialog.js

The three dialog types are given the option to resize. This includes dialogs using the withDialog() HOC, SaveDialogs, and LinkConfirmationDialogs.

Resizable dialogs

---

LICENSE

Use same formatting as at https://choosealicense.com/licenses/gpl-2.0/#

Update GPLv2 license text formatting

---

ng/src/web/entities/container.js
ng/src/web/entity/container.js
ng/src/web/pages/reports/detailspage.js

Make refreshing data more flexible by concentrating the refresh interval logic into central methods. This will allow to introduce a adjustable logic for reloading in future.

Autorefresh adjustments

---

ng/src/web/pages/alerts/detailspage.js
ng/src/web/pages/credentials/detailspage.js
ng/src/web/pages/portlists/detailspage.js

Add missing permission_resouce_loaders for alert, credential and
portlist details pages.

Fix permission loading for some detail pages

---

ng/CMakeLists.txt
ng/public/config.js
ng/src/gmp/gmp.js
ng/src/gmp/locale.js
ng/src/web/components/icon/manualicon.js
ng/src/web/components/powerfilter/powerfilter.js

Infrastructure and first example for linking to the manual instead of the legacy help pages.

Link to manual for help

---

ng/src/web/entities/container.js
ng/src/web/entity/container.js

When having a fast refresh time like the default one it is possible that the rendering flips around when the user e.g. changes the filter or clicks on the next page. This was caused by a long running reload request (timer already fired but the http request was still not finished). With this change all running requests will be canceled before loading any new data for list and details pages.

Cancel reload requests

---

ng/src/web/entities/container.js

This was a leftover from PR #156

Fix showing the last page at entities list pages

---

ng/src/web/components/dialog/dialog.js
ng/src/web/components/dialog/linkconfirmationdialog.js
ng/src/web/components/dialog/savedialog.js
ng/src/web/components/dialog/scrollablecontent.js
ng/src/web/components/dialog/withDialog.js
ng/src/web/components/notification/dialognotification.js
ng/src/web/components/powerfilter/withFilterDialog.js

With this change all dialogs using the Dialog component should get an initial auto height and should be realizable afterwards.

Fix initial heights for Dialog based dialogs

---

ng/src/web/components/section/section.js

Adjust margin of fold icon for SectionHeader

Fix icon alignment

---

ng/src/web/entities/container.js

Fix table reloading

---

src/html/classic/js/greenbone.js

In OMPRequest.prototype.do it has to be taken into account that the file
content of file inputs is not stored the "value" field, but in "files".
Also fix the code style of this section of the function.

Fix file uploads in forms and code style

---

src/html/classic/js/greenbone.js

It's possible that the form is undefined OMPRequest.prototype.do, e.g.
in inline forms like the bulk actions, so a check for that is needed.

Test if form is defined in OMPRequest.prototype.do

---

ng/.eslintrc.js

Eslint changes

---

ng/src/web/pages/reports/listpage.js

This is a leftover from #156 "Refactor entities command responses"

Fix loading of container tasks for report import dialog

---

ng/src/web/components/sortby/sortby.js
ng/src/web/components/table/head.js
ng/src/web/entities/header.js
ng/src/web/entities/table.js
ng/src/web/pages/allsecinfo/table.js
ng/src/web/pages/certbund/table.js
ng/src/web/pages/cpes/table.js
ng/src/web/pages/cves/table.js
ng/src/web/pages/dfncert/table.js
ng/src/web/pages/groups/header.js
ng/src/web/pages/hosts/table.js
ng/src/web/pages/notes/table.js
ng/src/web/pages/nvts/table.js
ng/src/web/pages/os/table.js
ng/src/web/pages/ovaldefs/table.js
ng/src/web/pages/overrides/table.js
ng/src/web/pages/portlists/table.js
ng/src/web/pages/reports/table.js
ng/src/web/pages/results/table.js
ng/src/web/pages/scanconfigs/header.js
ng/src/web/pages/targets/table.js
ng/src/web/pages/tasks/table.js
ng/src/web/pages/users/header.js
ng/src/web/pages/vulns/table.js

A small icon is shown to indicate which column is sorted and in which direction.

Add sorting indicator to table columns

---

ng/src/web/entities/table.js

All detail views will be collapsed when the table page is changed.

Change All Details Toggle behavior for switching table pages.

---

ng/src/web/components/sortby/sortby.js
ng/src/web/components/table/head.js
ng/src/web/entities/container.js
ng/src/web/entities/table.js
ng/src/web/pages/overrides/table.js
ng/src/web/pages/reports/applicationstable.js
ng/src/web/pages/reports/closedcvestable.js
ng/src/web/pages/reports/cvestable.js
ng/src/web/pages/reports/errorstable.js
ng/src/web/pages/reports/hoststable.js
ng/src/web/pages/reports/operatingsystemstable.js
ng/src/web/pages/reports/portstable.js
ng/src/web/pages/reports/reportentitiescontainer.js
ng/src/web/pages/reports/tlscertificatestable.js
ng/src/web/pages/reports/vulnerabilitiestable.js

Make the sorting independent of the filter and allow sorting for all report detail pages.

Report tables sorting

---

ng/src/web/pages/reports/tlscertificatestable.js

The column isn't useful for the gsr html report. Therefore allow to
deactivate it.

Allow to deactivate actions column of TLS Certs table

---

ng/src/gmp/locale.js
ng/src/gmp/parser.js
ng/src/gmp/utils.js
ng/src/web/components/bar/severitybar.js
ng/src/web/components/form/yesnoradio.js
ng/src/web/components/powerfilter/applyoverridesgroup.js
ng/src/web/pages/alerts/condition.js
ng/src/web/pages/notes/dialog.js
ng/src/web/pages/scanners/dialog.js
ng/src/web/pages/targets/dialog.js
ng/src/web/pages/tasks/details.js
ng/src/web/pages/tasks/dialog.js

Move parse_int, parse_float and parse_yesno from gmp/utils.js to
gmp/parser.js.

Finally move all parser function to gmp/parser.js

---

ng/src/gmp/models/certbund.js
ng/src/web/pages/certbund/detailspage.js

Cert bund details additions

---

ng/src/gmp/__tests__/utils.js
ng/src/gmp/utils.js
ng/src/web/entities/table.js

Allow to render extra rows at EntitiesTable components.

Extra entities rows

---

ng/src/gmp/__tests__/parser.js
ng/src/gmp/__tests__/utils.js
ng/src/gmp/parser.js
ng/src/gmp/utils.js

Add additional unit tests for some parse and utility functions

Additional tests

---

ng/src/web/entities/table.js
ng/src/web/entities/withRowDetails.js
ng/src/web/pages/tasks/details.js
ng/src/web/pages/tasks/detailspage.js

Some small ui detail improvements.

Ui updates

---

ng/src/web/components/bar/toolbar.js
ng/src/web/components/powerfilter/powerfilter.js
ng/src/web/components/provider/iconsizeprovider.js
ng/src/web/entity/page.js
ng/src/web/pages/tasks/listpage.js

Remove displayed filter string and increase icon size of all toolbars

Powerfilter update and toolbar medium icon size

---

gsad/src/gsad.c
ng/src/gmp/http/transform/x2js.js
ng/src/web/entities/container.js
ng/src/web/entity/container.js

Improve error situation a bit if gvmd is down.

Improve error if manager not available

---

ng/src/web/components/bar/progressbar.js
ng/src/web/components/section/header.js
ng/src/web/entities/table.js
ng/src/web/pages/reports/detailscontent.js

Update the layout of the report details page

Report tabs update

---

ng/src/web/entity/info.js
ng/src/web/entity/page.js

Put entity info in the section header and update its rendering.

Entity info in section header

---

ng/src/gmp/capabilities/capabilities.js
ng/src/gmp/http/utils.js
ng/src/gmp/list.js
ng/src/gmp/models/filter.js
ng/src/gmp/utils.js
ng/src/web/components/dashboard/legacy/chart/line.js
ng/src/web/components/dashboard/legacy/display.js
ng/src/web/components/form/select2.js
ng/src/web/entity/tags.js

Still missing has been:
Symbol
Array.from
Array.prototype.find
Array.prototype.findIndex
Object.is

Add missing polyfills for IE 11

---

src/html/classic/help.xsl

* src/html/classic/help.xsl (template mode=help match=users.html)
Add help to use the uid attribute LDAP login.

Backport r29875, by Juan Jose Nicola.

---

ng/src/gmp/models/__tests__/filter.js
ng/src/gmp/models/filter.js
ng/src/gmp/models/filter/__tests__/filterterm.js
ng/src/gmp/models/filter/convert.js

Fix filter equals for multi keywords like severity ranges.

Filter equals multi keywords

---

ng/src/web/components/form/select.js
ng/src/web/components/powerfilter/powerfilter.js
ng/src/web/stories/config.js
ng/src/web/stories/select/index.js
ng/src/web/utils/__tests__/render.js
ng/src/web/utils/os.js
ng/src/web/utils/render.js

Update the new Select component to fix layout in flexbox and support more styling features.

Select dropdown

---

gsad/src/gsad_gmp.c
ng/src/gmp/commands/entities.js
ng/src/web/components/powerfilter/powerfilter.js
ng/src/web/entities/container.js

Fix selection a pre defined filter in the Powerfilter component.

Filter selection fixes

---

ng/CMakeLists.txt
ng/src/web/pages/certbund/detailspage.js
ng/src/web/pages/cpes/detailspage.js
ng/src/web/pages/cves/detailspage.js
ng/src/web/pages/dfncert/detailspage.js
ng/src/web/pages/nvts/component.js
ng/src/web/pages/nvts/detailspage.js
ng/src/web/pages/ovaldefs/detailspage.js

Add download/export icons to all secinfo detail pages.

Secinfo download

---

ng/src/gmp/__tests__/utils.js
ng/src/gmp/utils.js
ng/src/web/components/form/select.js
ng/src/web/components/form/selectelements.js

These are the first commits in order to add the MultiSelect component later on.

Multi select

---

ng/CMakeLists.txt
ng/src/gmp/commands/alerts.js
ng/src/gmp/models/alert.js
ng/src/web/pages/alerts/component.js
ng/src/web/pages/alerts/dialog.js
ng/src/web/pages/alerts/tippingpointmethodpart.js

Add alert method for TippingPoint SMS

Tipping point alert

---

ng/src/web/components/tab/tab.js
ng/src/web/components/tab/tablist.js

The tabs got a modern design, inspired by current browsers.

Redesign Tabs

---

ng/src/web/components/form/__tests__/select.js
ng/src/web/components/form/multiselect.js
ng/src/web/components/form/select.js
ng/src/web/components/form/selectelements.js
ng/src/web/pages/targets/component.js
ng/src/web/pages/targets/dialog.js
ng/src/web/utils/render.js
ng/src/web/utils/warning.js

Fix several issues with Select and MultiSelect. Implement also first real component tests for Select. Still many dialogs are broken because of using the wrong default value which is not in the select items. For these issues a console warning is raised now.

Select fixes

---

ng/src/web/components/form/__tests__/multiselect.js
ng/src/web/components/form/__tests__/select.js
ng/src/web/components/form/multiselect.js
ng/src/web/components/form/select.js
ng/src/web/pages/tasks/component.js
ng/src/web/pages/tasks/dialog.js

Part 2 of updates for our new Select components. There are still broken dialogs.

Select fixes #2

---

ng/src/web/pages/loginpage.js

The new design has a more welcoming and light color scheme, is tidied up
and doesn't appear overloaded.

New design for login page

---

ng/CMakeLists.txt
ng/src/web/components/dialog/closebutton.js
ng/src/web/components/dialog/title.js
ng/src/web/utils/theme.js

Allow to reuse dialog close button.

Dialog close button

---

ng/src/web/components/dialog/closebutton.js
ng/src/web/components/icon/icon.js
ng/src/web/components/icon/withIconCss.js
ng/src/web/components/icon/withIconSize.js

Improve setting the icon size. Only require to use withIconSize HOC to be usable.

Icon size css

---

ng/src/gmp/utils.js

Update debounce docstring and add function to throttle display (animation) changes. Will be used for the grid row resizer.

Throttle helper

---

src/gsad_omp.c
src/html/classic/omp.xsl

This includes two commits:
* sending the method data to manager (which has to be included in master as well)
* the changes to the dialogs

Tipping point alert for GSA 7.0

---

ng/src/web/pages/alerts/emailmethodpart.js
ng/src/web/pages/alerts/filtercountchangedconditionpart.js
ng/src/web/pages/portlists/importdialog.js
ng/src/web/pages/scanconfigs/importdialog.js
ng/src/web/wizard/advancedtaskwizard.js
ng/src/web/wizard/modifytaskwizard.js

Some forms got styling fixes incl. a typo.

Fix Formstyling

---

ng/src/web/pages/os/listpage.js
ng/src/web/pages/os/row.js

Fix os listpage by providing the correct handlers for the list table
actions.

Use OsComponent for os listpage action handlers

---

ng/src/web/pages/extras/cvsscalculatorpage.js

Calculated vectors were always one step behind changes in the metrics.
Now they instantly change when selecting new values.

Fix CVSS calculator

---

.gitignore

These files are created by the file/image preview in KDE's dolphin

Ignore .directory files not only .directory directories

---

ng/CMakeLists.txt
ng/src/web/components/dashboard/display.js
ng/src/web/components/dashboard/displaymenu.js
ng/src/web/components/dialog/content.js
ng/src/web/components/dialog/scrollablecontent.js
ng/src/web/components/icon/arrowicon.js
ng/src/web/components/menu/iconmenu.js
ng/src/web/components/menu/menuentry.js
ng/src/web/components/sortable/grid.js
ng/src/web/stories/dashboard/index.js
ng/src/web/utils/theme.js

New DashboardDisplay component.

Dashboard next generation part #1

---

ng/src/web/stories/dashboard/index.js

Set correct parens for yarn to build storybook without error.

Fix story for DashboardDisplay

---

ng/src/web/pages/agents/component.js
ng/src/web/pages/agents/dialog.js

The withDialog HOC is replaced by using the SaveDialog component.
Contributes to #28

Use SaveDialog for Agents

---

ng/src/web/pages/agents/dialog.js
ng/src/web/pages/reportformats/component.js
ng/src/web/pages/reportformats/dialog.js
ng/src/web/pages/roles/component.js
ng/src/web/pages/roles/dialog.js

Roles and ReportFormats use the SaveDialog component.
(Multi)Selects in Roles and ReportFormats now use the items prop instead of <option/>
The Agents dialog receives defaults as a constant.

Update dialogs to use SaveDialog

---

ng/src/web/components/dialog/closebutton.js
ng/src/web/components/dialog/content.js
ng/src/web/pages/reports/applicationstable.js

This won't work with the html report.

Don't use absolute imports in web related js modules

---

ng/src/gmp/commands/reportformats.js
ng/src/web/pages/reportformats/component.js
ng/src/web/pages/reportformats/detailspage.js
ng/src/web/pages/reportformats/dialog.js
ng/src/web/pages/reportformats/listpage.js

Fix importing/creating new report formats. This seemed to got broken since a while.

Report format import

---

ng/src/web/utils/state.js

children prop should not be passed as data to the children function.

Don't add State's children prop into the state

---

gsad/src/gsad.c
gsad/src/gsad_gmp.c

The comments did not apply anymore.

Removed last occurances of "xsl" in comments.

---

gsad/src/gsad.c
gsad/src/gsad_gmp.c
gsad/src/gsad_gmp.h
gsad/src/gsad_log_conf.cmake_in
ng/src/gmp/commands/login.js
ng/src/gmp/http/http.js

Improve handling login and errors during login.

Login no redirect

---

ng/public/index.html
ng/src/web/components/dialog/dialog.js
ng/src/web/components/portal/portal.js

The same Portal will be required for tooltips in future. Also create
portals div automatically in the dom if it doesn't exist yet. This
allows using Portal based components in storybook.

Extract a distinct Portal component from Dialog

---

ng/package.json
ng/src/web/components/chart/bar.js
ng/src/web/components/chart/donut.js
ng/src/web/components/chart/legend.js
ng/src/web/components/chart/tooltip.js
ng/src/web/stories/chart/index.js
ng/yarn.lock

Start to rewrite bar and donut charts in react.

Start implementing chart components

---

ng/src/web/components/chart/bar.js
ng/src/web/components/chart/donut.js
ng/src/web/components/chart/donut3d.js
ng/src/web/components/chart/legend.js
ng/src/web/stories/chart/index.js

Update styling and make Legend more flexible by using render props.

Update Legend component

---

ng/src/web/components/chart/axis.js
ng/src/web/components/chart/bar.js
ng/src/web/components/chart/donut.js
ng/src/web/components/chart/donut3d.js
ng/src/web/components/chart/line.js
ng/src/web/components/chart/svg.js

Extract common code into own reusable components.

Add own Svg and Axis components

---

ng/src/web/components/form/multiselect.js
ng/src/web/components/form/select.js
ng/src/web/components/form/selectelements.js

The dropdown positioning changed in order to "pop out" of the dialog
window.
Using Portal made it necessary to introduce an onMouseDown handler for
Item in order to select it.

Fix Select in Dialogs

---

ng/src/web/pages/alerts/scpmethodpart.js
ng/src/web/pages/alerts/smbmethodpart.js
ng/src/web/pages/alerts/tippingpointmethodpart.js
ng/src/web/pages/alerts/verinicemethodpart.js
ng/src/web/pages/extras/cvsscalculatorpage.js
ng/src/web/pages/extras/feedstatuspage.js
ng/src/web/pages/ldap/ldappage.js
ng/src/web/pages/notes/dialog.js
ng/src/web/pages/overrides/dialog.js
ng/src/web/pages/performance/performancepage.js
ng/src/web/pages/radius/radiuspage.js
ng/src/web/pages/usersettings/usersettingspage.js
ng/src/web/wizard/taskwizard.js

Fix last design issues with forms and some icon sizes on pages.

Form and icon styling

---

ng/src/web/components/form/field.js
ng/src/web/components/form/radio.js
ng/src/web/components/form/spinner.js

Concerns form/ field, radio, and spinner. SelectElements needs to be
changed later on.

Inherit font settings for input elements

---

ng/src/web/components/form/multiselect.js
ng/src/web/components/form/select.js
ng/src/web/components/form/selectelements.js

Attempt x to fix the select components finally. Hopefully this was the last issue with the popover menu.

Fix select components part 100

---

ng/src/gmp/gmp.js
ng/src/gmp/models/target.js
ng/src/web/components/sticky/container.js
ng/src/web/pages/reports/resultstab.js

Add several small improvements.

Code improvements

---

ng/src/gmp/models/tag.js
ng/src/web/pages/tags/row.js

Delete .modified property from tags model and fix row for tags-table.

Fix "Modified" date for tags

---

ng/src/gmp/utils/__tests__/id.js
ng/src/gmp/utils/id.js

Add a helper function for checking the id of a model instance.

has_id helper function

---

ng/src/gmp/commands/notes.js
ng/src/gmp/commands/overrides.js
ng/src/gmp/models/note.js
ng/src/gmp/models/override.js
ng/src/web/entity/override.js
ng/src/web/pages/notes/component.js
ng/src/web/pages/notes/details.js
ng/src/web/pages/notes/dialog.js
ng/src/web/pages/overrides/component.js
ng/src/web/pages/overrides/details.js
ng/src/web/pages/overrides/dialog.js
ng/src/web/pages/results/details.js
ng/src/web/pages/results/detailspage.js
ng/src/web/pages/targets/dialog.js
ng/src/web/utils/render.js

This PR includes several fixes and improvements mostly for Override and Note dialogs. At the end it is possible to create notes from result details again.

Fix creating notes from result details

---

ng/src/web/pages/scanners/component.js
ng/src/web/pages/scanners/dialog.js

This PR includes several fixes of the ScannersDialog and the
ScannerComponent.

Improve ScannersDialog

---

src/po/gsad_js-zh_CN.po
src/po/gsad_xsl-zh_CN.po

This updates the Chinese translations for GSA 7.0 to the current state
on https://translate.greenbone.net

Update Chinese translations for GSA 7.0.

---

ng/package.json
ng/src/web/components/chart/bar.js
ng/src/web/components/chart/bubble.js
ng/src/web/components/chart/donut3d.js
ng/src/web/components/chart/line.js
ng/src/web/components/chart/pie.js
ng/src/web/components/chart/schedule.js
ng/src/web/components/chart/wordcloud.js
ng/yarn.lock

Replace vx/group by our own implementation. Our own Group component is
able to scale the group too.

Use own svg Group component

---

CHANGES

Preparing the gsa 6.0.13 release.

---

ng/CMakeLists.txt
ng/src/web/components/dashboard2/chartdisplay.js
ng/src/web/components/dashboard2/data/__tests__/actions.js
ng/src/web/components/dashboard2/data/__tests__/reducers.js
ng/src/web/components/dashboard2/data/actions.js
ng/src/web/components/dashboard2/data/display.js
ng/src/web/components/dashboard2/data/reducers.js
ng/src/web/stories/dashboard/dashboard.js

* Fix error cases for loading dashboard data
* Add tests for redux actions and reducers
* Rename ChartDisplay to DataDisplay

Update dashboard data

---

ng/CMakeLists.txt
ng/src/web/components/bar/severitybar.js
ng/src/web/components/chart/topology.js
ng/src/web/components/dashboard/legacy/chart/bar.js
ng/src/web/components/dashboard/legacy/chart/horizontalbar.js
ng/src/web/components/dashboard/legacy/helper.js
ng/src/web/entity/override.js
ng/src/web/pages/notes/details.js
ng/src/web/pages/notes/dialog.js
ng/src/web/pages/overrides/component.js
ng/src/web/pages/overrides/details.js
ng/src/web/pages/overrides/dialog.js
ng/src/web/pages/overrides/row.js
ng/src/web/pages/usersettings/usersettingspage.js
ng/src/web/utils/proptypes.js
ng/src/web/utils/render.js
ng/src/web/utils/severity.js

Move the severity handling from the render utils module into an own js module and differentiate between the values and to be displayed localized labels.

Severity rendering cleanup

---

ng/CMakeLists.txt
ng/package.json
ng/src/gmp/commands/entities.js
ng/src/gmp/commands/tasks.js
ng/src/web/app.js
ng/src/web/components/chart/bar.js
ng/src/web/components/chart/donut3d.js
ng/src/web/components/chart/line.js
ng/src/web/components/chart/schedule.js
ng/src/web/components/chart/tooltip.js
ng/src/web/components/chart/topology.js
ng/src/web/components/chart/wordcloud.js
ng/src/web/components/dashboard2/data/display.js
ng/src/web/entities/page.js
ng/src/web/pages/tasks/dashboard/common.js
ng/src/web/pages/tasks/dashboard/index.js
ng/src/web/pages/tasks/dashboard/loaders.js
ng/src/web/pages/tasks/dashboard/schedulesdisplay.js
ng/src/web/pages/tasks/dashboard/severityclassdisplay.js
ng/src/web/pages/tasks/dashboard/statusdisplay.js
ng/src/web/pages/tasks/listpage.js
ng/src/web/utils/severity.js
ng/yarn.lock

Add an initial draft version for the new tasks dashboard

Add a new TasksDashboard draft

---

gsad/src/gsad_log_conf.cmake_in

Related to a PR 62 in gvm-libs.

Add separator variable and modify prepend format to include it.

---

ng/src/web/components/chart/bar.js
ng/src/web/components/chart/donut3d.js
ng/src/web/components/chart/line.js
ng/src/web/components/chart/schedule.js
ng/src/web/components/dashboard2/data/display.js

Avoid unnecessary render calls if data hasn't changed. This improves the drag n' drop behavior at the dashboard a lot.

Dashboard performance improvements

---

ng/po/gsa-de.po

Update also includes some additional translations.

Fix German translation for "CPEs" in .po file

---

ng/.eslintrc.js
ng/package.json
ng/src/gmp/collection/parser.js
ng/src/gmp/commands/scanconfigs.js
ng/src/gmp/http/http.js
ng/src/gmp/locale/detector.js
ng/src/gmp/models/filter.js
ng/src/gmp/models/report/parser.js
ng/src/gmp/models/report/task.js
ng/src/gmp/sort.js
ng/src/gmp/utils/__tests__/array.js
ng/src/gmp/utils/string.js
ng/src/web/components/chart/bar.js
ng/src/web/components/dashboard/datasource.js
ng/src/web/pages/alerts/component.js
ng/src/web/pages/extras/trashactions.js
ng/src/web/pages/page.js

Pedantic fixes for a number of typos pointed out by codespell, mainly in
comments.

Fix typos and spelling errors

---

ng/src/web/components/dashboard2/display/datadisplay.js
ng/src/web/components/dashboard2/display/severityclassdisplay.js
ng/src/web/pages/tasks/dashboard/cvssdisplay.js
ng/src/web/pages/tasks/dashboard/schedulesdisplay.js
ng/src/web/pages/tasks/dashboard/severityclassdisplay.js
ng/src/web/pages/tasks/dashboard/statusdisplay.js
ng/src/web/pages/vulns/dashboard/cvssdisplay.js
ng/src/web/pages/vulns/dashboard/severityclassdisplay.js

* Fix displaying loading indicator.
* Filter drill down for SeverityClassDisplays

Dashboard NG

---

ng/src/web/components/chart/bar.js
ng/src/web/components/dashboard2/display/cvssdisplay.js
ng/src/web/pages/tasks/dashboard/cvssdisplay.js
ng/src/web/pages/tasks/dashboard/mosthighresults.js
ng/src/web/pages/vulns/dashboard/cvssdisplay.js

Add axis labels for bar charts.

Axis labels

---

gsad/src/gsad_gmp.c
ng/src/gmp/commands/users.js
ng/src/web/components/dashboard2/dashboard.js
ng/src/web/components/dashboard2/settings/__tests__/actions.js
ng/src/web/components/dashboard2/settings/__tests__/reducers.js
ng/src/web/components/dashboard2/settings/__tests__/selectors.js
ng/src/web/components/dashboard2/settings/actions.js
ng/src/web/components/dashboard2/settings/reducers.js
ng/src/web/components/dashboard2/settings/selectors.js
ng/src/web/components/sortable/grid.js

Save dashboard settings and other dashboard settings improvements.

Save dashboard settings

---

ng/src/web/components/dashboard2/dashboard.js
ng/src/web/components/dashboard2/settings/__tests__/actions.js
ng/src/web/components/dashboard2/settings/__tests__/reducers.js
ng/src/web/components/dashboard2/settings/actions.js
ng/src/web/components/dashboard2/settings/reducers.js

Update dashboard settings reducers and action creators to add defaults for a dashboard id to the store.

Store dashboard defaults in redux store

---

ng/CMakeLists.txt
ng/src/gmp/commands/vulns.js
ng/src/web/components/chart/bar.js
ng/src/web/components/dashboard2/display/utils.js
ng/src/web/pages/vulns/dashboard/hostsdisplay.js
ng/src/web/pages/vulns/dashboard/index.js
ng/src/web/pages/vulns/dashboard/loaders.js

The Vulnerabilities by Hosts display is added. This concludes the migration of the vulns dashboard.

Vulns Dashboard

---

gsad/src/gsad.c
gsad/src/gsad_gmp.c
gsad/src/gsad_gmp.h
gsad/src/gsad_gmp_auth.h
gsad/src/gsad_user.c
gsad/src/gsad_user.h
ng/src/gmp/commands/users.js

Cleanup gsad for handling dashboard settings (called chart preferences before)

Gsad dashboard settings

---

gsad/src/gsad.c
gsad/src/gsad_cmd.c
gsad/src/gsad_cmd.h
gsad/src/gsad_http.c
gsad/src/gsad_http.h
gsad/src/gsad_http_handler.c

This is a replacement for #386: Forbid caching except for static files.
Something went wrong merging the latest state of the master branch there and it was easier for me to just create a new PR and cherry pick the relevant commits.

 Forbid caching except for static files. (New version)

---

ng/package.json
ng/src/web/components/chart/bar.js
ng/src/web/components/chart/bubble.js
ng/src/web/components/chart/label.js
ng/src/web/components/chart/tooltip.js
ng/src/web/components/dashboard2/display/datadisplay.js
ng/src/web/utils/proptypes.js
ng/yarn.lock

Dashboards will be usable again :smiley:

Dashboard improvements

---

ng/src/web/components/dialog/container.js
ng/src/web/components/dialog/dialog.js

Improve moving performance of dialogs.

Dialog performance improvements

---

ng/src/web/components/dialog/dialog.js
ng/src/web/components/dialog/savedialog.js
ng/src/web/components/link/externallink.js
ng/src/web/components/notification/dialognotification.js

* Allow to set minHeight and minWidth
* Remove visible prop
* Use React.createRef API in Dialog

Dialog updates

---

ng/src/web/components/dashboard2/controls.js
ng/src/web/components/dashboard2/dashboard.js
ng/src/web/components/dashboard2/registry.js
ng/src/web/components/dashboard2/settings/actions.js

Open dialog to select which display to add when clicking on the add display button of a dashboard control.

Use dialog for adding new dashboard display

---

ng/src/web/components/form/select.js

Use the proptypes of Select component to document the expected object
shape for the items array prop.

Document expected object shape for items array prop of Select

---

ng/src/web/components/dialog/savedialog.js
ng/src/web/utils/proptypes.js

* Always use default export for proptypes
* Add a deprecation function
* Update mayRequire function
* Warn if SaveDialog initialData is still used

Proptypes updates

---

ng/src/web/pages/hosts/component.js
ng/src/web/pages/notes/component.js
ng/src/web/pages/overrides/component.js
ng/src/web/pages/permissions/component.js
ng/src/web/pages/users/listpage.js
ng/src/web/pages/usersettings/usersettingspage.js

The visible prop got removed from Dialog. Every component must ensure
to only render a Dialog if it should be visible.

Don't render dialogs if they should not be visible

---

ng/CMakeLists.txt
ng/src/gmp/commands/hosts.js
ng/src/web/components/dashboard2/controls.js
ng/src/web/pages/hosts/dashboard/cvssdisplay.js
ng/src/web/pages/hosts/dashboard/index.js
ng/src/web/pages/hosts/dashboard/loaders.js
ng/src/web/pages/hosts/dashboard/severityclassdisplay.js
ng/src/web/pages/hosts/dashboard/vulnscoredisplay.js
ng/src/web/pages/os/dashboard/vulnscoredisplay.js

Add Hosts by Severity Class / CVSS / VulnScore displays. Last one missing: Modification Time (LineChart).

Host dashboard

---

ng/CMakeLists.txt
ng/src/gmp/commands/dfncert.js
ng/src/web/components/dashboard2/data/loader.js
ng/src/web/pages/certbund/dashboard/index.js
ng/src/web/pages/certbund/dashboard/loaders.js
ng/src/web/pages/cpes/dashboard/index.js
ng/src/web/pages/cpes/dashboard/loaders.js
ng/src/web/pages/cves/dashboard/index.js
ng/src/web/pages/cves/dashboard/loaders.js
ng/src/web/pages/dfncert/dashboard/cvssdisplay.js
ng/src/web/pages/dfncert/dashboard/index.js
ng/src/web/pages/dfncert/dashboard/loaders.js
ng/src/web/pages/dfncert/dashboard/severityclassdisplay.js
ng/src/web/pages/dfncert/listpage.js
ng/src/web/pages/hosts/dashboard/index.js
ng/src/web/pages/hosts/dashboard/loaders.js
ng/src/web/pages/nvts/dashboard/index.js
ng/src/web/pages/nvts/dashboard/loaders.js
ng/src/web/pages/os/dashboard/index.js
ng/src/web/pages/os/dashboard/loaders.js
ng/src/web/pages/tasks/dashboard/index.js
ng/src/web/pages/tasks/dashboard/loaders.js
ng/src/web/pages/vulns/dashboard/index.js
ng/src/web/pages/vulns/dashboard/loaders.js

Includes removing defaultDisplay props and moving loaderProptypes for all dashboards.

DFN-CERT Dashboard

---

src/html/classic/help.xsl
src/html/classic/help_ru.xsl
src/html/classic/help_zh_CN.xsl

This PR is for various updates to the help pages, including:
* Updating the copyright and version on the about page
* Updating the German help pages

Update help pages

---

ng/src/web/components/chart/topology.js

* Update TopologyChart if hosts and links have changed in the backend
* Don't allow d3 to mutate data.

Dashboard next gen

---

ng/src/web/components/powerfilter/withFilterDialog.js
ng/src/web/entities/page.js

Use state to keep track of the visibilitiy of the PowerfilterDialog.

Fix Powerfilter to not use imperative API

---

ng/public/index.html

Remove the NG from title string in index.html

Change SPA Title

---

ng/src/web/pages/certbund/dashboard/loaders.js
ng/src/web/pages/cpes/dashboard/loaders.js
ng/src/web/pages/cves/dashboard/loaders.js
ng/src/web/pages/dfncert/dashboard/loaders.js
ng/src/web/pages/notes/dashboard/loaders.js
ng/src/web/pages/nvts/dashboard/loaders.js
ng/src/web/pages/os/dashboard/loaders.js
ng/src/web/pages/ovaldefs/dashboard/loaders.js
ng/src/web/pages/overrides/dashboard/loaders.js
ng/src/web/pages/reports/dashboard/loaders.js
ng/src/web/pages/results/dashboard/loaders.js
ng/src/web/pages/secinfo/dashboard/loaders.js

I also checked the subscriptions and changed them, where necessary.

Use common naming for constants in loaders

---

ng/CMakeLists.txt
ng/src/web/components/dashboard2/display/createDisplay.js
ng/src/web/pages/tasks/dashboard/schedulesdisplay.js
ng/src/web/pages/tasks/dashboard/severityclassdisplay.js
ng/src/web/pages/tasks/dashboard/statusdisplay.js

Introduce a helper function createDisplay to simplify display creation.

createDisplay helper function

---

ng/src/web/components/form/select.js

Improve Select component for object based item values.

Select update

---

ng/CMakeLists.txt
ng/src/web/store/entities/__tests__/selectors.js
ng/src/web/store/entities/filters/__tests__/actions.js
ng/src/web/store/entities/filters/__tests__/reducers.js
ng/src/web/store/entities/filters/actions.js
ng/src/web/store/entities/filters/reducers.js
ng/src/web/store/entities/filters/selectors.js
ng/src/web/store/entities/reducers.js
ng/src/web/store/entities/selectors.js
ng/src/web/store/reducers.js

First changes to store the entites also in the redux store.

Entities in store

---

ng/src/web/components/chart/utils/arc.js

Make donut chart arcs more robust against floating point inaccuracies.
This fixes displaying a donut 3d chart for single values.

Make donut charts more robust

---

ng/src/web/components/chart/wordcloud.js

Update to react 16.3 api (remove cWRP usage, add
getDerivedStateFromProps and use cDU for updating the displayed words).
Also ensure that the data (the word placement) only gets recalculated
if it is really necessary to avoid extra render calls.
Using d3-cloud is not optimal for react usage because it has an async
api. The code would be much easier if d3-cloud had a synchronous api
because we are only interested in the final word layout.

Fix resizing of WordCloudChart

---

ng/src/web/pages/reports/detailspage.js

The show api on dialogs got removed with the current Dialog component
API. This is a leftover from the dialog migrations.
Closes #677

Fix displaying the powerfilter edit dialog for report details

---

ng/CMakeLists.txt
ng/src/gmp/commands/dashboards.js
ng/src/gmp/commands/entity.js
ng/src/gmp/commands/gmp.js
ng/src/gmp/commands/users.js
ng/src/gmp/gmp.js
ng/src/web/store/dashboard/settings/actions.js

Move loading of the dashboard settings and converting between different formats into own Dashboard command classes.

Update loading dashboard settings

---

ng/CMakeLists.txt
ng/src/web/components/bar/menubar.js
ng/src/web/components/dashboard/controls.js
ng/src/web/components/dashboard/dashboard.js
ng/src/web/components/sortable/grid.js
ng/src/web/pages/start/confirmremovedialog.js
ng/src/web/pages/start/dashboard.js
ng/src/web/pages/start/newdashboarddialog.js
ng/src/web/pages/start/page.js
ng/src/web/store/dashboard/settings/actions.js

Allow to add several dashboards at the main start page.

Multi Dashboard Start Page

---

INSTALL.md

* INSTALL.md: Some fixes and streamlining of terminology.

Update INSTALL information

---

src/gsad.c

The maximum number of connections per IP address can now be changed with
a new gsad command line argument, per-ip-connection-limit.
This can be useful when GSA is accessed through a proxy.

Add option to change per-IP connection limit (7.0)

---

ng/src/web/pages/usersettings/usersettingspage.js

Filters will now be suggested in the drop-downs in the dialog and set filters will show up in the overview.

Fix FilterTypes in UserSettings

---

ng/src/gmp/capabilities/capabilities.js
ng/src/web/components/link/detailslink.js
ng/src/web/pages/cves/detailspage.js
ng/src/web/pages/hosts/identifiers.js
ng/src/web/pages/os/row.js

Remove page prop from DetailsLink

---

ng/src/web/pages/certbund/listpage.js
ng/src/web/pages/cpes/listpage.js
ng/src/web/pages/cves/listpage.js
ng/src/web/pages/dfncert/listpage.js
ng/src/web/pages/nvts/listpage.js
ng/src/web/pages/ovaldefs/listpage.js
ng/src/web/pages/secinfo/listpage.js

Set filters filter on info entities pages to load the correct list of applicable filters.

Set correct filters filter to load info entity type filter lists

---

ng/src/web/pages/tags/dialog.js

There is still a prop warning if a pasted ID isn't contained in the
loaded resources (max 1000 items), saving a tag for this ID works
nevertheless.

Improve setting resources in Tags dialog

---

ng/src/web/components/form/datepicker.js

Update input styles to make it obvious that the datepicker component is
disabled.

Allow to disable Datepicker components

---

ng/src/web/pages/nvts/details.js
ng/src/web/pages/nvts/detailspage.js
ng/src/web/pages/nvts/row.js
ng/src/web/pages/nvts/table.js

* remove displaying nvt version field
* move nvt family from start of the details after references
* link to nvt list with family filter

Update displaying nvt details

---

ng/src/gmp/locale/date.js

Remove obsolete and unsed interval function from gmp/locale/date module.

Remove obsolete and unsed interval function

---

ng/src/web/pages/tasks/dialog.js

* Use React.Fragment to only have one capabilities check
* Show add tag if user may access and create tags only

Update displaying add tags in task dialog

---

gsa/src/web/store/entities/filters.js

createAll must get a plural name as parameter.

Fix typo in filter entities store module

---

gsa/src/gmp/models/event.js

This fixes selecting the weekdays at the ScheduleDialog

Fix checking if a weekday is set

---

gsa/src/gmp/models/event.js

ical.js raises an exception when the same next date occurs twice. This
isn't a valid exception for monthly rrules with last day and e.g. 31.
day selected. Therefore ignore the exception and retry at least 5 times
to get a new different next date.

Fix getting the nextDates

---

gsa/package.json
gsa/yarn.lock

After #763 gets merged react can be updated to 16.4 again.

Update react to 16.4.1 again

---

gsa/CMakeLists.txt
gsa/src/gmp/capabilities/capabilities.js
gsa/src/gmp/utils/__tests__/entitytype.js
gsa/src/gmp/utils/__tests__/string.js
gsa/src/gmp/utils/entitytype.js
gsa/src/gmp/utils/string.js
gsa/src/web/entities/container.js
gsa/src/web/entity/link.js
gsa/src/web/entity/tags.js
gsa/src/web/pages/filters/row.js
gsa/src/web/pages/permissions/details.js
gsa/src/web/pages/permissions/multipledialog.js
gsa/src/web/pages/permissions/row.js
gsa/src/web/pages/secinfo/table.js
gsa/src/web/pages/tags/component.js
gsa/src/web/pages/tags/details.js
gsa/src/web/pages/tags/dialog.js
gsa/src/web/pages/tags/row.js
gsa/src/web/utils/render.js

Part 1:
* create an extra utils module for entity type functions
* move existing entity functions to this module
* use new/existing entity functions

Improve entity type handling

---

gsa/src/gmp/commands/entities.js
gsad/src/gsad.c
gsad/src/gsad_gmp.c
gsad/src/gsad_gmp.h

Fix exporting entities via bulk actions. The original bulk export got removed with 52fdee6c8efadc6c8e035e3f95512d8aaf58bd52 in pr #725 accidentally.

Bulk export cmd

---

gsa/src/gmp/commands/entities.js
gsa/src/gmp/commands/entity.js
gsa/src/gmp/commands/gmp.js

Fix single entity exports by using cmd=bulk_export instead of cmd=process_bulk

Entity export

---

gsa/src/gmp/utils/entitytype.js
gsa/src/web/entities/container.js
gsa/src/web/entities/tagsdialog.js
gsa/src/web/pages/tags/component.js
gsa/src/web/pages/tags/dialog.js

Improve several tag related components for being able to load the entities from the store at the end.
Also update the components to allow to change the entity type naming scheme more easily in future.

Improve Tags handling for entity types and entities loading

---

gsa/src/gmp/capabilities/capabilities.js
gsa/src/gmp/commands/permissions.js
gsa/src/gmp/commands/tags.js
gsa/src/gmp/commands/trashcan.js
gsa/src/gmp/utils/entitytype.js
gsa/src/web/components/form/multiselect.js
gsa/src/web/entities/container.js
gsa/src/web/entities/entitynametabledata.js
gsa/src/web/entity/icon/cloneicon.js
gsa/src/web/entity/icon/createicon.js
gsa/src/web/entity/icon/deleteicon.js
gsa/src/web/entity/icon/editicon.js
gsa/src/web/entity/icon/trashicon.js
gsa/src/web/entity/permissions.js
gsa/src/web/entity/tags.js
gsa/src/web/entity/tagshandler.js
gsa/src/web/pages/extras/trashactions.js
gsa/src/web/pages/permissions/component.js
gsa/src/web/pages/portlists/component.js
gsa/src/web/pages/tags/component.js

Start to always use internal entity type

---

gsa/CMakeLists.txt
gsa/src/web/components/form/numberfield.js
gsa/src/web/components/form/spinner.js
gsa/src/web/pages/usersettings/dialog.js
gsa/src/web/pages/usersettings/severitypart.js

- Fix setting a spinner value and allow removing the input.
- Use more consistent expected values.

UserSettings Severity Spinner

---

gsa/CMakeLists.txt
gsa/src/web/pages/nvts/nvtpreference.js
gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js

Move NvtPreferences to web/pages/nvts

---

gsa/src/web/pages/reports/detailscontent.js

Makes it obsolete and closes #823

Show Report page header before report is loaded

---

gsa/CMakeLists.txt
gsa/src/web/entities/container2.js
gsa/src/web/entities/withEntitiesContainer2.js
gsa/src/web/pages/tasks/listpage.js
gsa/src/web/store/__tests__/utils.js
gsa/src/web/store/entities/__tests__/targets.js
gsa/src/web/store/entities/__tests__/tasks.js
gsa/src/web/store/entities/tasks.js
gsa/src/web/store/entities/utils/__tests__/actions.js
gsa/src/web/store/entities/utils/__tests__/reducers.js
gsa/src/web/store/entities/utils/__tests__/selectors.js
gsa/src/web/store/entities/utils/actions.js
gsa/src/web/store/entities/utils/reducers.js
gsa/src/web/store/entities/utils/selectors.js
gsa/src/web/store/entities/utils/testing.js
gsa/src/web/store/pages/__tests__/actions.js
gsa/src/web/store/pages/__tests__/reducers.js
gsa/src/web/store/pages/__tests__/selectors.js
gsa/src/web/store/pages/actions.js
gsa/src/web/store/pages/reducers.js
gsa/src/web/store/pages/selectors.js
gsa/src/web/store/utils.js

Allow to load entities for list pages from the redux store.

Entities loading

---

gsa/src/web/entities/row.js

RowDetailsToggle must be a withClickGhandler component to pass the name
prop to the click handler function.

Fix toggling entities table details

---

gsa/src/web/pages/reports/detailscontent.js
gsa/src/web/pages/reports/detailspage.js

Reloading due to manual filter change still shows loading indicator.
Makes obsolete and closes #829

Avoid displaying loading indicator for automatic reloads

---

gsa/src/web/pages/agents/dialog.js
gsa/src/web/pages/alerts/dialog.js
gsa/src/web/pages/credentials/dialog.js
gsa/src/web/pages/filters/dialog.js
gsa/src/web/pages/groups/dialog.js
gsa/src/web/pages/hosts/dialog.js
gsa/src/web/pages/permissions/dialog.js
gsa/src/web/pages/portlists/dialog.js
gsa/src/web/pages/portlists/importdialog.js
gsa/src/web/pages/portlists/portrangedialog.js
gsa/src/web/pages/reportformats/dialog.js
gsa/src/web/pages/roles/dialog.js
gsa/src/web/pages/scanconfigs/dialog.js
gsa/src/web/pages/scanconfigs/editconfigfamilydialog.js
gsa/src/web/pages/scanconfigs/editdialog.js
gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js
gsa/src/web/pages/scanconfigs/importdialog.js
gsa/src/web/pages/scanners/dialog.js
gsa/src/web/pages/tags/dialog.js
gsa/src/web/pages/targets/dialog.js
gsa/src/web/pages/tasks/dialog.js
gsa/src/web/pages/users/dialog.js

- Remove unnecessary visible prop from last dialogs
- update imports in those dialogs

Visible prop

---

gsa/src/web/components/bar/titlebar.js
gsa/src/web/components/powerfilter/powerfilter.js
gsa/src/web/pages/hosts/component.js
gsa/src/web/pages/page.js
gsa/src/web/pages/results/detailspage.js
gsa/src/web/pages/tasks/task.js
gsa/src/web/pages/users/component.js

With this PR gmp should be accessed via props and not the context anymore in all components.

Gmp Context

---

gsa/src/web/components/bar/titlebar.js
gsa/src/web/components/link/detailslink.js
gsa/src/web/components/powerfilter/powerfilter.js
gsa/src/web/entity/link.js
gsa/src/web/pages/agents/row.js
gsa/src/web/pages/alerts/emailmethodpart.js
gsa/src/web/pages/filters/component.js
gsa/src/web/pages/hosts/component.js
gsa/src/web/pages/operatingsystems/detailspage.js
gsa/src/web/pages/scanconfigs/detailspage.js
gsa/src/web/pages/tags/listpage.js
gsa/src/web/pages/users/dialog.js

- use withRouter
- use with Capabilities
- fix typos
- update imports
- merge duplicate propType declaration

Use withXY() not this.context #1

---

gsa/src/web/pages/alerts/row.js
gsa/src/web/pages/hosts/detailspage.js
gsa/src/web/pages/hosts/row.js
gsa/src/web/pages/operatingsystems/detailspage.js
gsa/src/web/pages/targets/details.js
gsa/src/web/pages/targets/detailspage.js
gsa/src/web/pages/tasks/actions.js
gsa/src/web/pages/tasks/detailspage.js
gsa/src/web/pages/tasks/icons/importreporticon.js
gsa/src/web/pages/tasks/icons/newiconmenu.js
gsa/src/web/pages/tasks/icons/starticon.js

- use withCapabilities
- update imports
With this, all usages of capabilities should be handled via withCapabilities() instead of the context.

Use withCapabilities() not this.context #2

---

gsa/CMakeLists.txt
gsa/src/gmp/commands/users.js
gsa/src/web/pages/usersettings/usersettingspage.js
gsa/src/web/store/usersettings/defaults/__tests__/actions.js
gsa/src/web/store/usersettings/defaults/__tests__/reducers.js
gsa/src/web/store/usersettings/defaults/__tests__/selectors.js
gsa/src/web/store/usersettings/defaults/actions.js
gsa/src/web/store/usersettings/defaults/reducers.js
gsa/src/web/store/usersettings/defaults/selectors.js
gsa/src/web/store/usersettings/reducers.js

Re-arrange the usersettings store. It will store additional data (like session timeout, timezone, ...) in future too.

Usersettings store #1

---

gsad/src/gsad.c
gsad/src/gsad_credentials.c
gsad/src/gsad_credentials.h
gsad/src/gsad_gmp.c
gsad/src/gsad_http_handler.c

Remove unnecessary parts from credentials_t

Credentials cleanup

---

gsa/CMakeLists.txt
gsa/src/gmp/models/tag.js
gsa/src/web/entities/container.js
gsa/src/web/entity/container.js
gsa/src/web/pages/tags/component.js
gsa/src/web/pages/tags/detailspage.js
gsa/src/web/pages/tags/resourcelist.js
gsa/src/web/pages/tags/row.js

- Fix proptype warning
- Fix selection of bulk action targets with checkboxes
- update Tags model
- update ResourceList (new component, improved loading)
- update Tags detailspage
- camelCase and GSA-type in tag model
- withRouter() for EntityContainer

Fix ResourceList and UserSelection for Tags

---

gsa/src/web/components/badge/badge.js
gsa/src/web/components/footnote/footnote.js
gsa/src/web/components/icon/arrowicon.js
gsa/src/web/components/icon/icon.js
gsa/src/web/components/layout/autosize.js
gsa/src/web/components/link/link.js
gsa/src/web/components/link/target.js
gsa/src/web/components/menu/iconmenu.js

Convert glamorous to styled-components #1

---

src/po/CMakeLists.txt
src/po/gsad_js-ja.po
src/po/gsad_xsl-ja.po

Translate files related to gsa_js-ja.po and gsa_xsl-ja.po

---

gsa/src/gmp/models/secinfo.js
gsa/src/web/pages/alerts/event.js
gsa/src/web/pages/secinfo/details.js
gsa/src/web/pages/secinfo/row.js
gsa/src/web/pages/secinfo/table.js

Abstract access to the SecInfo info_type and fix detail links at the secinfo list page.

Secinfo type

---

gsa/src/gmp/commands/entity.js

This was a leftover from copy and pasting.

Update entity command logger name

---

gsa/src/web/pages/permissions/component.js
gsa/src/web/pages/permissions/dialog.js
gsa/src/web/pages/permissions/multipledialog.js

- Adjust permission description
- Rename dialog

Permission Dialogs

---

gsa/src/web/pages/start/newdashboarddialog.js

SaveDialog provides a "values" prop, not "data".

Fix NewDashboardDialog

---

gsa/src/web/components/sortable/row.js
gsa/src/web/components/structure/footer.js
gsa/src/web/components/structure/header.js
gsa/src/web/components/structure/main.js
gsa/src/web/components/tab/tab.js
gsa/src/web/components/tab/tablayout.js
gsa/src/web/components/table/body.js
gsa/src/web/components/table/detailstable.js
gsa/src/web/components/table/head.js
gsa/src/web/components/table/header.js
gsa/src/web/components/table/infotable.js
gsa/src/web/entities/row.js
gsa/src/web/pages/nvts/preformatted.js
gsa/src/web/pages/operatingsystems/dashboard/vulnscoredisplay.js
gsa/src/web/pages/tasks/status.js

Convert glamorous to styled-components #3

---

gsa/src/web/pages/reports/detailsfilterdialog.js

Remove sorting from report details powerfilter dialog

Report details sorting

---

gsa/src/web/components/bar/progressbar.js
gsa/src/web/components/dashboard/display/display.js
gsa/src/web/components/dashboard/display/displaymenu.js
gsa/src/web/components/dialog/closebutton.js
gsa/src/web/components/dialog/resizer.js
gsa/src/web/components/dialog/scrollablecontent.js
gsa/src/web/utils/theme.js

Convert glamorous to styled-components #9

---

gsa/src/web/components/dashboard/display/datatable.js
gsa/src/web/components/table/table.js

Fixes two bugs that came up while rewriting to styled-components
Contributes to #643

Convert glamorous to styled-components #11

---

gsa/src/web/pages/hosts/dashboard/vulnscoredisplay.js
gsa/src/web/pages/nvts/dashboard/familydisplay.js
gsa/src/web/pages/nvts/dashboard/qoddisplay.js
gsa/src/web/pages/nvts/dashboard/qodtypedisplay.js

Don't require onFilterChanged for dashboard displays

---

gsa/src/web/pages/permissions/dialog.js

forEach got removed in 331d2789c182ca990699917ed8af87d2014b3bf2

Fix iterating over capabilities

---

gsa/package.json
gsa/src/web/components/layout/__tests__/Layout.js
gsa/src/web/components/layout/__tests__/__snapshots__/Layout.js.snap
gsa/src/web/components/layout/__tests__/__snapshots__/withLayout.js.snap
gsa/src/web/components/layout/__tests__/withLayout.js
gsa/src/web/components/layout/withLayout.js
gsa/yarn.lock

Rewrite withLayout to use template literals and convert most glamorous specific code to styled components.
Add snapshot tests for withLayout and Layout
Should replace #960

With layout

---

gsa/src/web/components/chart/topology.js
gsa/src/web/components/dashboard/display/datadisplay.js
gsa/src/web/components/form/filefield.js
gsa/src/web/components/layout/layout.js

Remove old withLayout HOC

---

gsa/src/web/entities/withRowDetails.js

Remove border-bottom for RowDetailsTable

---

gsa/src/web/components/dashboard/display/datadisplay.js
gsa/src/web/components/dashboard/display/datadisplayicons.js

* Fix toggling legend
* Change temporary icons

Fix DataDisplay

---

.github/ISSUE_TEMPLATE.md

Always link to community platform. Be more stricter about not using the
issue tracker as support forum.
Add some notes for adding content to the sections.

Update and improve issue template

---

gsa/src/web/pages/results/row.js

The commit b208ec0755af05f0b7f3a7c99c496fba8d5c427e was missing the file 
with the split, due to merge conflicts.

Actually split Results Host column into IP and Name

---

gsa/src/web/components/dashboard/dashboard.js
gsa/src/web/store/dashboard/settings/__tests__/actions.js
gsa/src/web/store/dashboard/settings/__tests__/reducers.js
gsa/src/web/store/dashboard/settings/actions.js
gsa/src/web/store/dashboard/settings/reducers.js

* Make setting the default dashboards settings explicit
* Don't set error in dashboard setting if no error is available

Dashboard Settings Store improvements

---

gsa/src/web/components/dashboard/dashboard.js
gsa/src/web/pages/start/page.js

* Fix main chart at start page
* Improve layout of dashboard loading animation

Chart improvements

---

.circleci/config.yml
gsa/package.json
gsa/yarn.lock

See https://circleci.com/docs/2.0/collect-test-data/ and https://www.viget.com/articles/using-junit-on-circleci-2-0-with-jest-and-eslint/ for details

Circleci test metadata

---

INSTALL.md

Follow-up of https://github.com/greenbone/gsa/pull/1006 to include the required version in the INSTALL.md as well.

Include required version of yarn in INSTALL.md

---

gsa/src/gmp/models/__tests__/alert.js
gsa/src/gmp/models/__tests__/credential.js
gsa/src/gmp/models/__tests__/permission.js

* Alert
* Credential
* Permission

More Model Tests #2

---

gsa/src/web/components/bar/progressbar.js
gsa/src/web/components/label/severityclass.js
gsa/src/web/pages/reports/applicationstable.js
gsa/src/web/pages/reports/closedcvestable.js
gsa/src/web/pages/reports/cvestable.js
gsa/src/web/pages/reports/errorstable.js
gsa/src/web/pages/reports/hoststable.js
gsa/src/web/pages/reports/operatingsystemstable.js
gsa/src/web/pages/reports/portstable.js
gsa/src/web/pages/reports/table.js
gsa/src/web/pages/reports/tlscertificatestable.js
gsa/src/web/pages/reports/vulnerabilitiestable.js
gsa/src/web/pages/scanconfigs/detailspage.js
gsa/src/web/pages/scanconfigs/table.js
gsa/src/web/pages/tasks/details.js
gsa/src/web/pages/tasks/detailspage.js
gsa/src/web/pages/tasks/row.js
gsa/src/web/pages/tasks/table.js

* Fix table alignments
* Change things for Task details and listpage
* Change things for Reports table
* Add link to family-filtered NVTS on ScanConfig detailspage

GUI miscellaneous #5

---

gsa/src/web/components/bar/progressbar.js

This makes the font appear more centered

Increase ProgressBar height

---

gsa/src/gmp/models/__tests__/certbund.js
gsa/src/gmp/models/__tests__/cve.js
gsa/src/gmp/models/testing.js

Tests for: 
* CertBundAdv
* CVE

More model test #3

---

gsa/src/gmp/models/__tests__/host.js
gsa/src/gmp/models/__tests__/note.js
gsa/src/gmp/models/__tests__/override.js
gsa/src/gmp/parser.js

Includes tests for:
* Host
* Note
* Override
Also fixes parseTextElement()

More model tests #4

---

gsa/src/gmp/models/__tests__/note.js
gsa/src/gmp/models/__tests__/portlist.js
gsa/src/gmp/models/__tests__/reportformat.js
gsa/src/gmp/models/reportformat.js

Fixes reportformat model parsing
Includes model tests for:
* Note
* PortList
* ReportFormat

More model tests #5

---

gsa/src/gmp/models/__tests__/result.js
gsa/src/gmp/models/__tests__/scanconfig.js
gsa/src/gmp/models/__tests__/scanner.js
gsa/src/gmp/models/result.js
gsa/src/gmp/models/scanner.js

PR includes:
* fixes for models:
** Result
** Scanner
* tests for models:
** Result
** ScanConfig
** Scanner

More model tests #6

---

gsa/src/gmp/models/__tests__/credential.js
gsa/src/gmp/models/__tests__/scanconfig.js
gsa/src/gmp/models/__tests__/scanner.js
gsa/src/gmp/models/__tests__/schedule.js
gsa/src/gmp/models/__tests__/secinfo.js
gsa/src/gmp/models/__tests__/settings.js
gsa/src/gmp/models/__tests__/tag.js
gsa/src/gmp/models/__tests__/target.js
gsa/src/gmp/models/__tests__/user.js
gsa/src/gmp/models/__tests__/vulnerability.js
gsa/src/gmp/models/settings.js
gsa/src/gmp/models/user.js

Includes a polyfill fix for settings model and tests for:
* Scanner
* ScanConfig
* Credential
* Schedule
* SecInfo
* Settings
* Tag
* Target
* User
* Vulnerability

More model tests #7

---

gsa/src/gmp/models/__tests__/login.js
gsa/src/gmp/models/__tests__/ovaldef.js
gsa/src/gmp/models/__tests__/settings.js

Includes tests for: 
* Settings
* Login
* Ovaldef

More model tests #8

---

gsa/src/gmp/commands/users.js
gsa/src/web/pages/alerts/dialog.js
gsa/src/web/pages/scanners/details.js
gsa/src/web/pages/schedules/dialog.js
gsad/src/gsad.c

PR includes bugfixes and styling updates

GUI miscellaneous #7

---

src/po/gsad_js-ja.po
src/po/gsad_xsl-ja.po

This updates the Japanese translations to the current state from
https://translate.greenbone.net/ja/gsa_7.0/ .

Update Japanese translation

---

gsa/src/web/components/icon/edit.svg
gsa/src/web/components/icon/editicon.js
gsa/src/web/components/icon/icon.js
gsa/src/web/components/icon/svgicon.js

Starting point for svgs as components.

Edit icon as svg component

---

gsa/src/web/components/dialog/composercontent.js

...and change ordering of options to have the default at first place

Apply overrides by default

---

CHANGES.md
gsa/src/gmp/models/__tests__/nvt.js
gsa/src/gmp/models/nvt.js
gsa/src/gmp/models/testing.js

Add possibly missing scheme to NVT xref URLs

---

gsa/src/web/components/bar/menubar.js

Fix typo descibe_auth -> describe_auth

Fix checking for describe_auth permission

---

.github/PULL_REQUEST_TEMPLATE.md

Add a template that's shown when creating new Pull Requests.

Add a template for PRs

---

CHANGES

This adds a list of changes made since GSA 7.0.3 to the CHANGES file.

Add CHANGES for gsa 7.0.4

---

gsa/src/web/components/menu/menu.js
gsa/src/web/pages/alerts/component.js
gsa/src/web/pages/alerts/method.js
gsa/src/web/pages/alerts/smbmethodpart.js

Fixes three bugs: smb credential filtering, displaying vFire alert type, crashing when wrong permissions for menu
**Checklist**:

GUI miscellaneous #11

---

gsa/src/web/pages/alerts/component.js
gsa/src/web/pages/alerts/dialog.js

Updates for UUIDs changes and fixes #1134
**Checklist**:

Git issue gvmd302

---

gsa/src/gmp/capabilities/__tests__/capabilities.js
gsa/src/web/entity/icon/cloneicon.js
gsa/src/web/entity/icon/deleteicon.js
gsa/src/web/entity/icon/editicon.js
gsa/src/web/entity/icon/trashicon.js

Update checking for entity permission at list table action icons.

Update entity icons permission checks

---

CHANGES.md
gsad/src/gsad.c

Allow forward slashes in tag values

---

CHANGES
src/gsad.c

Allow forward slashes in tag values [7.0]

---

gsa/src/web/pages/tasks/detailspage.js

When hovering over the bade now the title is displayed too. Also
clicking on the badge follows the link now.

Include badges at the task details page into the links

---

.circleci/config.yml
gsa/.eslintrc.js
gsa/.prettierrc.js
gsa/package.json
gsa/yarn.lock

Add prettier to format js and json code automatically. After running yarn again a git pre-commit hook is installed that formats the js and json files automatically.

Prettier with pre commit hook

---

gsa/src/web/pages/reports/detailscontent.js

Move DownloadIcon before the AlertActions icon.

Update Icon bar at report details page

---

.clang-format
CMakeLists.txt
gsad/src/gsad.c
gsad/src/gsad_base.c
gsad/src/gsad_base.h
gsad/src/gsad_cmd.c
gsad/src/gsad_cmd.h
gsad/src/gsad_content_type.h
gsad/src/gsad_credentials.c
gsad/src/gsad_credentials.h
gsad/src/gsad_gmp.c
gsad/src/gsad_gmp.h
gsad/src/gsad_gmp_auth.h
gsad/src/gsad_http.c
gsad/src/gsad_http.h
gsad/src/gsad_http_handler.c
gsad/src/gsad_http_handler.h
gsad/src/gsad_i18n.c
gsad/src/gsad_i18n.h
gsad/src/gsad_params.h
gsad/src/gsad_session.c
gsad/src/gsad_session.h
gsad/src/gsad_settings.c
gsad/src/gsad_settings.h
gsad/src/gsad_user.c
gsad/src/gsad_user.h
gsad/src/utils.c
gsad/src/utils.h
gsad/src/validator.c
gsad/src/validator.h

This adds .clang-format config file to the repository, format C code under gsad/src/, and adds make format command.
**Checklist**:

Apply clang-format

---

gsad/src/gsad_gmp.c

This is to speed up the Report Details page, by requesting less info from Manager.
**Checklist**:

Get reports without result tags, to save time (8.0)

---

CHANGES.md
gsa/src/web/components/link/link.js
gsa/src/web/pages/performance/performancepage.js
gsa/src/web/pages/performance/startendtimeselection.js
gsa/src/web/pages/reports/detailscontent.js
gsa/src/web/pages/reports/detailspage.js

* Allow to pass start time, end time and sensor scanner id as url parameters to performance page
* Link to performance page from report details page if report is not from a container task
- [n/a] Tests

Performance link

---

gsad/src/gsad_gmp.c

Remove unused code path from the get_report function in gsad

Cleanup get_report function in gsad

---

.circleci/config.yml
gsa/.eslintrc.js
gsa/.prettierrc.js
gsa/package.json
gsa/yarn.lock

Prettier for gsa 8

---

gsa/src/gmp/http/transform/fastxml.js

**Checklist**:
- [ will be in master ] Tests

Parse text nodes in xml as __text

---

.clang-format
CMakeLists.txt
gsad/src/gsad.c
gsad/src/gsad_base.c
gsad/src/gsad_base.h
gsad/src/gsad_cmd.c
gsad/src/gsad_cmd.h
gsad/src/gsad_content_type.h
gsad/src/gsad_credentials.c
gsad/src/gsad_credentials.h
gsad/src/gsad_gmp.c
gsad/src/gsad_gmp.h
gsad/src/gsad_gmp_auth.h
gsad/src/gsad_http.c
gsad/src/gsad_http.h
gsad/src/gsad_http_handler.c
gsad/src/gsad_http_handler.h
gsad/src/gsad_i18n.c
gsad/src/gsad_i18n.h
gsad/src/gsad_params.h
gsad/src/gsad_session.c
gsad/src/gsad_session.h
gsad/src/gsad_settings.c
gsad/src/gsad_settings.h
gsad/src/gsad_user.c
gsad/src/gsad_user.h
gsad/src/utils.c
gsad/src/utils.h
gsad/src/validator.c
gsad/src/validator.h

Backport https://github.com/greenbone/gsa/pull/1184. Keep code formatting between gsa-8.0 branch and Master consistent in order to reduce unneeded pain when backporting future fixes.
**Checklist**:

Clang format 8.0

---

gsa/src/web/components/icon/restoreicon.js
gsa/src/web/components/icon/svgicon.js
gsa/src/web/components/icon/testing.js
gsa/src/web/components/pagination/pagination.js

Disable pagination icon when there are no more pages to flip through.
**Checklist**:
- [ X ] Tests

Fix Pagination

---

CHANGES
src/po/gsad_js-de.po
src/po/gsad_xsl-de.po

This fixes one string having a wrong translation and adds ones added
since the last translation update.
**Checklist**:
- Tests N/A

Update German translations

---

gsa/src/gmp/commands/scanconfigs.js
gsa/src/web/pages/scanconfigs/component.js
gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js
gsad/src/gsad_gmp.c

NVT preferences format changed to OID:PrefID:PrefType:PrefName.
Related PRs: https://github.com/greenbone/gvmd/pull/413  https://github.com/greenbone/openvas-scanner/pull/282  https://github.com/greenbone/gvm-libs/pull/192
**Checklist**:

Handle ID addition in NVT preferences.

---

gsa/CMakeLists.txt
gsa/src/gmp/commands/auth.js
gsa/src/gmp/commands/users.js
gsa/src/web/pages/ldap/__tests__/__snapshots__/dialog.js.snap
gsa/src/web/pages/ldap/__tests__/dialog.js
gsa/src/web/pages/ldap/dialog.js
gsa/src/web/pages/ldap/ldappage.js

**Checklist**:
- [N/A] [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) Entry

Fix LDAP page and authentication

---

gsa/src/web/pages/tags/details.js

Fix displaying tags resource type in details

---

gsa/src/web/components/table/__tests__/__snapshots__/detailstable.js.snap
gsa/src/web/components/table/__tests__/detailstable.js
gsa/src/web/components/table/detailstable.js
gsa/src/web/components/table/infotable.js
gsa/src/web/pages/tasks/details.js

This PR includes loading details data about scanconfigs in tasks and presenting those in a new DetailsTable.
**Checklist**:
- [N/A] [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) Entry

Config details in task

---

gsa/src/web/pages/notes/component.js

Fix Notes active status in EditNotesDialog

---

gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap
gsa/src/web/entities/__tests__/tagsdialog.js
gsa/src/web/entities/container.js

Resource_type needed to be converted to API-type for the filter to work.
**Checklist**:

 Fix tag selection in Bulk Tag dialog for "special" resource_types

---

gsa/src/web/pages/results/row.js

Remove parantheses around hostname in results view

---

gsa/src/gmp/models/__tests__/scanner.js
gsa/src/gmp/models/scanner.js
gsa/src/web/pages/performance/performancepage.js
gsa/src/web/pages/scanners/component.js
gsa/src/web/pages/scanners/dialog.js
gsa/src/web/pages/tasks/dialog.js
gsa/src/web/pages/tasks/row.js

Adjust scanner dialog according to scanner type

---

CHANGES.md
gsa/CMakeLists.txt
gsa/src/web/components/dialog/__tests__/__snapshots__/confirmationdialog.js.snap
gsa/src/web/components/dialog/__tests__/confirmationdialog.js
gsa/src/web/components/dialog/confirmationdialog.js
gsa/src/web/components/dialog/scrollablecontent.js
gsa/src/web/components/dialog/title.js
gsa/src/web/components/link/externallink.js
gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap
gsa/src/web/pages/ldap/__tests__/__snapshots__/dialog.js.snap
gsa/src/web/pages/radius/__tests__/__snapshots__/dialog.js.snap
gsa/src/web/pages/tasks/__tests__/__snapshots__/containerdialog.js.snap
gsa/src/web/pages/tickets/__tests__/__snapshots__/createdialog.js.snap
gsa/src/web/pages/tickets/__tests__/__snapshots__/editdialog.js.snap
gsa/src/web/pages/users/dialog.js

Add notification if user is to be created without a role

---

gsa/src/web/components/form/select.js
gsa/src/web/components/powerfilter/powerfilter.js

Used to make the purpose of the filter selection clearer.
**Checklist**:

Set tooltip to filter selection of PowerFilter

---

gsa/src/web/components/bar/menubar.js

Remove obsolete section prop passed to MenuEntry components

---

gsa/src/gmp/__tests__/parser.js
gsa/src/gmp/models/result.js
gsa/src/gmp/models/testing.js
gsa/src/gmp/parser.js

* Entity names
* Result descriptions in report result details
**Checklist**:

Unescape more things

---

gsa/src/web/pages/tasks/detailspage.js

More unescaping

---

gsa/src/web/pages/reports/detailscontent.js

Add title to performance icon at report details

---

gsa/src/web/components/chart/line.js

Don't put scales, values, min, max into state use memoization instead.
Before a re-render was triggered if data or height has changed since
last state update. This did lead first to an unnecessary render and
second to an inconsistent state for the rendering before the state
update. In this rendering phase it could be possible that the rendered
data didn't fit to the scales. This resulted in errors being logged in
the browser console.
**Checklist**:
- [n/a] Tests

Improve rendering of LineChart

---

gsa/src/web/components/bar/__tests__/__snapshots__/statusbar.js.snap
gsa/src/web/components/bar/__tests__/statusbar.js
gsa/src/web/components/bar/statusbar.js

Prevent linebreak in StatusBar

---

gsa/src/gmp/log.js
gsa/src/web/app.js
gsa/src/web/store/index.js

**Checklist**:
- [N/A] Tests
- [N/A] [CHANGES](https://github.com/greenbone/gsa/blob/master/CHANGES.md) Entry

Allow to debug the redux store in production

---

gsa/src/web/pages/schedules/render.js

**Checklist**:
- [ tbd ] Tests

Lazy translate weekdays in schedule render

---

gsa/src/web/pages/schedules/render.js

Fix "The last XY"-recurrence display for schedules

---

gsa/src/web/pages/nvts/details.js
gsa/src/web/pages/results/details.js

Make ordering NVT metadata consistent

---

gsa/src/web/pages/schedules/dialog.js

Use the dates as the main point for hour and minute information and
don't track them separately in a state. When hours and minutes are
changes the corresponding moment date is updated too now.
**Checklist**:
- [n/a] Tests

Fix calculating the duration of a schedule

---

gsa/src/web/entity/icon/cloneicon.js

We need get_ permissions to clone stuff.
**Checklist**:

Fix permissions for CloneIcon

---

CHANGES.md
gsa/src/gmp/commands/tasks.js
gsa/src/gmp/http/transform/fastxml.js
gsa/src/web/components/errorboundary/errorboundary.js
gsa/src/web/components/errorboundary/errormessage.js
gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap
gsa/src/web/entity/container.js
gsa/src/web/entity/page.js
gsa/src/web/entity/withEntityContainer.js
gsa/src/web/pages/reports/detailscontent.js
gsa/src/web/pages/reports/detailspage.js
gsa/src/web/pages/tasks/detailspage.js
gsad/src/gsad_gmp.c
gsad/src/gsad_http.c

Display error if loading of single entities wasn't possible e.g. when the user passed an invalid or unknown id.
- [n/a] Tests

Handle unknown ids

---

gsa/src/web/entity/icon/__tests__/__snapshots__/cloneicon.js.snap
gsa/src/web/entity/icon/__tests__/__snapshots__/createicon.js.snap
gsa/src/web/entity/icon/__tests__/__snapshots__/deleteicon.js.snap
gsa/src/web/entity/icon/__tests__/__snapshots__/editicon.js.snap
gsa/src/web/entity/icon/__tests__/__snapshots__/observericon.js.snap
gsa/src/web/entity/icon/__tests__/__snapshots__/trashicon.js.snap
gsa/src/web/entity/icon/__tests__/cloneicon.js
gsa/src/web/entity/icon/__tests__/createicon.js
gsa/src/web/entity/icon/__tests__/deleteicon.js
gsa/src/web/entity/icon/__tests__/editicon.js
gsa/src/web/entity/icon/__tests__/observericon.js
gsa/src/web/entity/icon/__tests__/trashicon.js

Add tests for entity icons

---

gsa/src/web/pages/secinfo/listpage.js

Don't allow to bulktag on the SecInfo page

---

.circleci/config.yml
CHANGES.md
gsad/src/gsad.c

Fix release build of gsa

---

CHANGES.md
RELEASE.md
gsa/src/gmp/gmpsettings.js
gsa/src/web/pages/help/about.js

Fix version and link to protocol docs at about page
**Checklist**:
- [n/a] Tests

About page fixes

---

CHANGES.md
gsa/src/gmp/models/alert.js
gsa/src/web/pages/alerts/emailmethodpart.js

Sometimes disable some inputs in Alert dialog

---

gsa/src/web/pages/reports/vulnerabilitiestable.js
gsa/src/web/pages/vulns/table.js

Fix typos for "No Vulnerabilities"

---

gsa/CMakeLists.txt
gsa/src/gmp/__tests__/gmpsettings.js
gsa/src/gmp/gmpsettings.js
gsa/src/web/components/bar/titlebar.js
gsa/src/web/pages/help/about.js

Improve version handling

---

gsa/src/web/components/dialog/__tests__/__snapshots__/confirmationdialog.js.snap
gsa/src/web/components/dialog/__tests__/__snapshots__/dialog.js.snap
gsa/src/web/components/dialog/overlay.js
gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap
gsa/src/web/pages/ldap/__tests__/__snapshots__/dialog.js.snap
gsa/src/web/pages/radius/__tests__/__snapshots__/dialog.js.snap
gsa/src/web/pages/tasks/__tests__/__snapshots__/containerdialog.js.snap
gsa/src/web/pages/tickets/__tests__/__snapshots__/createdialog.js.snap
gsa/src/web/pages/tickets/__tests__/__snapshots__/editdialog.js.snap

This prevents the dialogs from becoming stuck beneath the menu.
**Checklist**:
- [ X ] Tests

Dialog menu overlay

---

gsa/src/web/components/footnote/__tests__/__snapshots__/footnote.js.snap
gsa/src/web/components/footnote/__tests__/footnote.js

Add test for footnote component

---

CHANGES.md
gsa/src/web/pages/users/dialog.js

 Fix showing authentication methods in UserDialog

---

CHANGES.md
gsa/src/web/pages/schedules/dialog.js

Schedule no fifth gsa8

---

CHANGES.md
gsa/src/web/pages/targets/component.js

Fix New Target dialog contains value from Edit Target

---

CHANGES.md
gsa/src/gmp/models/__tests__/result.js
gsa/src/gmp/models/result.js
gsa/src/web/pages/results/details.js

Display details about diff results (results with delta state changed) at delta reports.
Fixes #369 
**Checklist**:

Delta results changed diff

---

.gitignore
CHANGES.md
gsa/.storybook/config.js
gsa/package.json
gsa/src/stories/button.js
gsa/src/stories/checkbox.js
gsa/src/stories/confirmationdialog.js
gsa/src/stories/containerdialog.js
gsa/src/stories/datepicker.js
gsa/src/stories/filefield.js
gsa/src/stories/formgroup.js
gsa/src/stories/multiselect.js
gsa/src/stories/mydialog.js
gsa/src/stories/numberfield.js
gsa/src/stories/passwordfield.js
gsa/src/stories/radio.js
gsa/src/stories/savedialog.js
gsa/src/stories/select.js
gsa/src/stories/spinner.js
gsa/src/stories/textarea.js
gsa/src/stories/textfield.js
gsa/src/stories/timezoneselect.js
gsa/src/stories/togglebutton.js
gsa/src/stories/yesnoradio.js
gsa/src/web/components/dialog/__tests__/confirmationdialog.js
gsa/src/web/components/dialog/confirmationdialog.js
gsa/yarn.lock

Add storybook

---

gsa/src/gmp/__tests__/gmpsettings.js
gsa/src/gmp/gmpsettings.js
gsa/src/web/components/img/product.js
gsa/src/web/pages/login/__tests__/loginform.js

Vendor label

---

CHANGES.md
gsa/src/web/pages/portlists/dialog.js

Fix port ranges from file radio button

---

CHANGES.md
gsa/src/web/pages/permissions/dialog.js

fix permission description

---

CHANGELOG.md
gsa/src/web/components/dialog/dialog.js

Fix dialog can be moved outside browser frame

---

CHANGELOG.md
gsa/src/web/components/form/__tests__/__snapshots__/select.js.snap
gsa/src/web/components/form/__tests__/__snapshots__/timezoneselect.js.snap
gsa/src/web/components/form/__tests__/select.js
gsa/src/web/components/form/select.js
gsa/src/web/entities/__tests__/__snapshots__/tagsdialog.js.snap
gsa/src/web/pages/tickets/__tests__/__snapshots__/createdialog.js.snap
gsa/src/web/pages/tickets/__tests__/__snapshots__/editdialog.js.snap

Adjust clickable area of Select

---

CHANGELOG.md
gsa/src/web/pages/secinfo/table.js

Fix detailslinks in AllSecInfo

---

CHANGELOG.md
gsa/src/web/pages/scanners/component.js

Fix host param for Scanner dialog

---

CHANGELOG.md
gsa/jsconfig.json
gsa/src/web/entities/container.js
gsa/src/web/pages/reports/detailsfilterdialog.js
gsa/src/web/pages/reports/detailspage.js

Fix filter in Report Results view cannot be saved

---

gsa/src/web/entities/container.js

Mark tag selection titles as translatable

---

CHANGELOG.md
gsa/src/web/components/badge/__tests__/__snapshots__/badge.js.snap
gsa/src/web/components/badge/__tests__/badge.js
gsa/src/web/components/badge/badge.js
gsa/src/web/components/comment/__tests__/__snapshots__/comment.js.snap
gsa/src/web/components/comment/__tests__/comment.js

Add tests for comment and badge

---

gsa/src/web/pages/alerts/method.js
gsa/src/web/pages/reports/scaninfo.js
gsa/src/web/pages/scanners/dialog.js
gsa/src/web/pages/tasks/row.js
gsa/src/web/wizard/advancedtaskwizard.js

Translation german

---

CHANGELOG.md
gsa/po/gsa-de.po

Translate GSA to German

---

gsad/src/gsad_gmp.c

Remove unused code path from delete_filter_gmp in gsad

---

CHANGELOG.md
gsa/src/web/pages/login/loginform.js
gsa/src/web/pages/login/loginpage.js

Add warning for IE11

---

CHANGELOG.md
gsa/po/gsa-de.po

Translate IE11 warning

---

gsa/src/gmp/commands/filters.js
gsad/src/gsad.c
gsad/src/gsad_gmp.c

Resource type

---

gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap
gsa/src/web/pages/login/__tests__/__snapshots__/loginform.js.snap
gsa/src/web/pages/login/loginform.js
gsa/src/web/pages/login/loginpage.js

Improve LoginPage

---

CHANGELOG.md
gsa/src/web/pages/credentials/downloadicon.js

Add missing tool tips to credential download icons

---

CHANGELOG.md
gsa/src/gmp/locale/__tests__/languages.js
gsa/src/gmp/locale/languages.js

Remove not implemented languages from options

---

CHANGELOG.md
gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap
gsa/src/web/components/structure/footer.js
gsa/src/web/pages/login/__tests__/__snapshots__/loginform.js.snap
gsa/src/web/pages/login/loginform.js
gsa/src/web/pages/login/loginpage.js

Improve login page

---

CHANGELOG.md
gsa/src/web/entities/container.js
gsa/src/web/entities/page.js
gsa/src/web/entities/withEntitiesContainer.js
gsa/src/web/utils/proptypes.js

Display loading error

---

gsa/src/web/entities/container.js

All list pages should be already be converted to use isLoading instead
of loading.

Remove obsolete loading prop

---

CHANGELOG.md
gsa/src/web/entities/container.js

Use same procedure as report details for loading time measurements.
Start the measurement at a single place only.
**Checklist**:
- [n/a] Tests

Start measurement when loading is requested

---

CHANGELOG.md
gsa/src/web/components/chart/topology.js

Don't crash topology chart, if host has no severity

---

CHANGELOG.md
gsa/src/gmp/models/report/report.js

Parse report timestamp as date

---

CHANGELOG.md
gsa/src/gmp/models/__tests__/filter.js
gsa/src/gmp/models/filter.js

Fix filter

---

CHANGELOG.md
gsa/src/web/pages/roles/row.js

Fix cloning permissions for Roles

---

CHANGELOG.md
gsa/src/web/components/date/__tests__/datetime.js
gsa/src/web/components/date/datetime.js

* Avoid *Invalid Date* message rendering
* Add tests
**Checklist**:

Datetime improvement and tests

---

gsa/src/web/components/form/formgroup.js
gsa/src/web/pages/performance/__tests__/__snapshots__/startendtimeselection.js.snap
gsa/src/web/pages/performance/__tests__/startendtimeselection.js
gsa/src/web/pages/performance/startendtimeselection.js

Tests for StartEndTimeSelection component

---

CHANGELOG.md
gsa/src/gmp/__tests__/gmpsettings.js
gsa/src/gmp/gmpsettings.js
gsa/src/web/components/link/__tests__/manuallink.js
gsa/src/web/components/link/manuallink.js
gsad/src/gsad_http_handler.c

Local manual

---

CHANGELOG.md
gsa/CMakeLists.txt
gsa/src/web/entity/icon/__tests__/__snapshots__/verifyicon.js.snap
gsa/src/web/entity/icon/__tests__/verifyicon.js
gsa/src/web/entity/icon/verifyicon.js
gsa/src/web/pages/reportformats/row.js

Don't allow to verify predefined report formats
**Checklist**:
- [ X ] Tests

Verify report formats

---

gsa/src/web/authorized.js
gsa/src/web/pages/login/loginpage.js

This issue got introduces with https://github.com/greenbone/gsa/pull/1377
**Checklist**:
- [n/a] Tests

Fix redirect to login page

---

CHANGELOG.md
gsa/src/web/pages/scanconfigs/details.js

Separate tasks using this scan config with commas

---

gsa/po/gsa-de.po
gsa/src/web/pages/login/loginpage.js

With https://github.com/greenbone/gsa/pull/1366 the handling of 401
error got changed which resulted in displaying an unknown error message
if username or password was invalid during login.
**Checklist**:
- [n/a] Tests

Display failed login message at login page

---

CHANGELOG.md
gsa/src/web/pages/vulns/listpage.js

Becasue there is no corresponding chapter in the manual, yet, start a search in the manual instead of linking to an undefined anchor.
**Checklist**:

Fix Vulnerabilities ManualIcon

---

CHANGELOG.md
gsa/src/web/components/structure/__tests__/__snapshots__/footer.js.snap
gsa/src/web/components/structure/__tests__/__snapshots__/header.js.snap
gsa/src/web/components/structure/__tests__/__snapshots__/main.js.snap
gsa/src/web/components/structure/__tests__/footer.js
gsa/src/web/components/structure/__tests__/header.js
gsa/src/web/components/structure/__tests__/main.js
gsa/src/web/pages/login/__tests__/__snapshots__/loginpage.js.snap
gsa/src/web/pages/login/__tests__/loginform.js
gsa/src/web/pages/login/__tests__/loginpage.js

Add tests for loginpage and structure components

---

CHANGELOG.md
gsa/src/web/pages/nvts/dashboard/familydisplay.js

Fix missing 'Applied filter' message for 'NVTs by Family'

---

CHANGELOG.md
gsa/src/web/pages/reports/detailspage.js
gsad/src/gsad_gmp.c

Don't crash without report formats

---

CHANGELOG.md
gsa/po/gsa-de.po
gsa/src/web/components/dashboard/controls.js
gsa/src/web/components/powerfilter/__tests__/__snapshots__/solutiontypegroup.js.snap
gsa/src/web/components/powerfilter/solutiontypegroup.js

Fix some problems with German translation in dialogs

---

gsa/src/web/pages/reports/tlscertificatestable.js

Fix typo in TLS certificate "not valid after" rendering

---

CHANGELOG.md
gsa/src/web/pages/results/details.js

Fix showing result2 in delta result details

---

CHANGELOG.md
gsa/src/web/pages/results/details.js

Fix result undefined error on result details

---

CHANGELOG.md
gsa/src/gmp/__tests__/parser.js
gsa/src/gmp/parser.js

Fix parsing CVSS authentication SINGLE_INSTANCE

---

gsa/src/web/pages/users/dialog.js

Cleanup User dialog.
**Checklist**:
- [n/a] Tests

User dialog

---

gsad/src/gsad_gmp.c

The responses from these extra gmp requests aren't used in GSA anymore
and can therefore be dropped safely.
**Checklist**:
- [n/a] Tests

Drop unnecessary code from get_config function

---

gsa/package.json
gsa/src/web/components/badge/badge.js
gsa/yarn.lock

* Update Badge to use new ref API
* Remove peerDependency warning

Badge ref update

---

gsa/.storybook/config.js
gsa/src/stories/badge.js
gsa/src/stories/comment.js
gsa/src/stories/footnote.js
gsa/src/stories/progressbar.js

Rendered four components with storybook.
**Checklist**:
- [] Tests

Added stories for components: badge, comment, footnote and progressbar

---

gsa/src/gmp/__tests__/parser.js
gsa/src/gmp/commands/overrides.js
gsa/src/gmp/models/__tests__/note.js
gsa/src/gmp/models/__tests__/override.js
gsa/src/gmp/models/note.js
gsa/src/gmp/models/override.js
gsa/src/gmp/parser.js
gsa/src/web/entity/override.js
gsa/src/web/pages/overrides/component.js
gsa/src/web/pages/overrides/dialog.js
gsa/src/web/pages/overrides/filterdialog.js
gsa/src/web/pages/overrides/row.js
gsa/src/web/pages/overrides/table.js

Changed the names to camelCase for Note and Override models. Tested the changes with GSA.
**Checklist**:
- [] Tests

Api to camel case 

---

gsa/src/gmp/models/__tests__/os.js
gsa/src/gmp/models/os.js
gsa/src/web/pages/operatingsystems/detailspage.js
gsa/src/web/pages/operatingsystems/row.js

**Checklist**:
Changed variables in "OS" to camelCase. Pushing these changes one by one because they require testing.
- [] Tests

os vars to camelCase

---

gsa/src/gmp/models/__tests__/user.js
gsa/src/gmp/models/user.js
gsa/src/web/pages/users/details.js
gsa/src/web/pages/users/row.js

updated variables to camelCase. Everything seems to work from manual testing. I ignored the commands/users code because changing it breaks the functionality to change password. Also ignored parts of dialog.
**Checklist**:
- [] Tests

updated user auth_method to camelCase

---

gsa/src/gmp/models/__tests__/scanner.js
gsa/src/gmp/models/scanner.js
gsa/src/web/pages/scanners/component.js
gsa/src/web/pages/scanners/detailspage.js
gsa/src/web/pages/scanners/dialog.js
gsa/src/web/pages/scanners/row.js

Updated scanner vars (ca_pub and param_type) to camelCase. Ignored component, command and dialog (except to change '.' to '_'). Also updated tests.
**Checklist**:
- [] Tests

changed scanner vars to camelCase

---

gsa/src/gmp/models/__tests__/nvt.js
gsa/src/gmp/models/nvt.js
gsa/src/web/pages/nvts/detailspage.js
gsa/src/web/pages/nvts/preferences.js
gsa/src/web/pages/scanconfigs/editconfigfamilydialog.js
gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js

restored deleted edits... perhaps. basically, updated nvt_types and default_timeout and wrote a line of test to make sure default_timeout is deleted.
**Checklist**:
- [] Tests

updated nvt vars to camelCase

---

gsa/src/gmp/models/__tests__/dfncert.js
gsa/src/gmp/models/cpe.js
gsa/src/gmp/models/dfncert.js
gsa/src/web/pages/dfncert/details.js
gsa/src/web/pages/dfncert/detailspage.js

Updated some instances of ret to elem in cpe, updated dfncerts vars to camelCase
**Checklist**:
- [] Tests

updated dfncerts vars to camelCase

---

gsa/src/gmp/models/__tests__/cve.js
gsa/src/gmp/models/cve.js
gsa/src/web/pages/cves/details.js

Specifically, cwe_id.
**Checklist**:
- [] Tests

changed cve vars to camelCase

---

gsa/src/gmp/models/__tests__/certbund.js
gsa/src/gmp/models/certbund.js
gsa/src/web/pages/certbund/details.js
gsa/src/web/pages/certbund/detailspage.js

changed variables additional_information, remote_attack, reference_source, reference_url and revision_history
**Checklist**:
- [] Tests

changed certbund vars to camelCase

---

gsa/src/gmp/models/__tests__/ovaldef.js
gsa/src/gmp/models/ovaldef.js
gsa/src/web/pages/ovaldefs/detailspage.js

updated: short_id, applicability_check, test_ref, extended_definitions, definition_ref, test_ref
**Checklist**:
- [] Tests

updated ovaldef vars to camelCase

---

.github/CODEOWNERS

Set maintainers for gsa and gsad

---

CHANGELOG.md
gsa/src/gmp/commands/__tests__/task.js
gsa/src/gmp/commands/scanconfigs.js
gsa/src/gmp/commands/tasks.js

Add usage type to task and scanconfig commands

---

gsa/src/gmp/models/filter.js
gsa/src/web/components/powerfilter/filterdialog.js

changed method name for the filter model. that's it.
**Checklist**:
- [] Tests

changed filter method _merge to merge

---

CHANGELOG.md
gsa/src/gmp/models/__tests__/event.js
gsa/src/gmp/models/event.js

Ical timezone

---

gsa/src/web/components/folding/folding.js

Folding with styled components

---

CHANGELOG.md
CMakeLists.txt
RELEASE.md
gsa/package.json

Prepare relase 8.0.1

---

gsa/src/web/components/powerfilter/filterdialog.js
gsa/src/web/components/powerfilter/filtersearchgroup.js

made filtersearchgroup accommodate spaces in search term.
**Checklist**:
- [] Tests

fixed filtersearch component

---

CHANGELOG.md
RELEASE.md
gsa/src/gmp/models/__tests__/event.js
gsa/src/gmp/models/event.js
gsad/CMakeLists.txt
gsad/config/CMakeLists.txt
gsad/config/gsad.default
gsad/config/gsad.logrotate.in
gsad/config/gsad.service.in

Fix merge from #1490 by cherry picking desired commits from gsa-8.0 branch. I've used `git merge --strategy=ours` to merge gsa-8.0 into master which just marks the commits from the gsa-8.0 branch as merged but actually ignores them.
Fixes #1492 too
**Checklist**:
- [n/a] Tests

Fix merge gsa 8.0

---

CHANGELOG.md
gsa/src/web/components/dialog/composercontent.js

Let FilterField in ContentComposer grow with term length

---

CHANGELOG.md
gsa/src/web/pages/alerts/condition.js
gsa/src/web/pages/alerts/event.js
gsa/src/web/pages/alerts/method.js

...with erroneous event, condition or method
**Checklist**:
- [] Tests

Don't crash Alerts listpage and trashcan

---

gsa/src/web/pages/extras/cvsscalculatorpage.js

fixed issue where authentication = single results in error in cvssbasevector.
**Checklist**:
- [] Tests

fixed auth=single results in error in calculator

---

CHANGELOG.md
gsa/src/web/pages/reports/resultstab.js
gsa/src/web/pages/results/details.js

Fix displaying Result delta information

---

gsa/src/web/pages/extras/cvsscalculatorpage.js

changed SINGLE_INSTANCS to SINGLE_INSTANCE in auth

---

gsa/src/web/pages/extras/cvsscalculatorpage.js

Mention cvss v2 at title of cvss calculator page

---

CHANGELOG.md
gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap
gsa/src/web/components/layout/__tests__/__snapshots__/horizontalsep.js.snap
gsa/src/web/components/layout/__tests__/horizontalsep.js
gsa/src/web/components/layout/horizontalsep.js
gsa/src/web/pages/alerts/details.js
gsa/src/web/pages/credentials/details.js
gsa/src/web/pages/filters/details.js
gsa/src/web/pages/groups/details.js
gsa/src/web/pages/notes/details.js
gsa/src/web/pages/overrides/details.js
gsa/src/web/pages/roles/details.js
gsa/src/web/pages/targets/details.js
gsa/src/web/pages/tasks/details.js
gsa/src/web/pages/users/details.js

List divider

---

gsa/src/gmp/commands/__tests__/task.js
gsa/src/gmp/commands/tasks.js

Fix create container task

---

CHANGELOG.md
gsad/config/gsad.service.in

Allow to pass additional options to gsad

---

CHANGELOG.md
gsa/src/web/pages/results/__tests__/__snapshots__/diff.js.snap
gsa/src/web/pages/results/__tests__/diff.js
gsa/src/web/pages/results/details.js
gsa/src/web/pages/results/diff.js

Diff highlighting

---

CHANGELOG.md
gsa/src/gmp/locale/date.js
gsa/src/web/entities/container.js
gsa/src/web/entity/component.js
gsa/src/web/pages/agents/component.js
gsa/src/web/pages/credentials/component.js
gsa/src/web/pages/reports/detailspage.js
gsa/src/web/pages/results/detailspage.js
gsa/src/web/pages/scanners/component.js
gsa/src/web/utils/__tests__/render.js
gsa/src/web/utils/render.js

Fix using filename templates

---

gsa/src/web/pages/performance/startendtimeselection.js

Backport fix to date selection

---

gsa/src/web/utils/__tests__/render.js

Don't use current dates for testing as they will obviously change.
**Checklist**:
- [ x ] Tests

Fix render/generateFilename test

---

gsa/src/web/pages/schedules/dialog.js

Backport edit schedule dialog change

---

gsa/src/web/pages/permissions/multipledialog.js

Changed the default option to "including related resources". Probably needs to be backported.
**Checklist**:
- [] Tests

changed default option for create permissions dialog (task)

---

CMakeLists.txt
gsa/package.json

Update version after release

---

gsa/src/web/components/powerfilter/__tests__/__snapshots__/severityvaluesgroup.js.snap
gsa/src/web/components/powerfilter/__tests__/severityvaluesgroup.js
gsa/src/web/components/powerfilter/severityvaluesgroup.js

refactored severityvaluesgroup with react hooks

---

CHANGELOG.md
gsa/src/web/pages/hosts/detailspage.js

Instead of linking to a broken cpe page, link to the corresponding OS
**Checklist**:

Fix host details OS link

---

CHANGELOG.md
gsa/src/gmp/models/certbund.js
gsa/src/gmp/models/cpe.js
gsa/src/gmp/models/cve.js
gsa/src/gmp/models/dfncert.js
gsa/src/gmp/models/nvt.js
gsa/src/gmp/models/ovaldef.js

fixed secinfo severitybars

---

gsa/src/web/components/date/datetime.js
gsa/src/web/pages/schedules/details.js
gsa/src/web/pages/schedules/row.js

backport changed displayed timezone to schedule timezone

---

gsa/src/web/components/bar/__tests__/__snapshots__/titlebar.js.snap
gsa/src/web/components/img/__tests__/__snapshots__/greenbone.js.snap
gsa/src/web/components/img/greenbone.js
gsa/src/web/components/structure/__tests__/__snapshots__/header.js.snap
gsa/src/web/pages/login/__tests__/__snapshots__/loginpage.js.snap

Also there is no need for translating Greenbone Security Assistant.
**Checklist**:
- [] Tests

Load Greenbone logo early to get it into the browser cache

---

CHANGELOG.md
gsa/package.json
gsa/po/gsa-de.po
gsa/src/web/components/date/datetime.js
gsa/src/web/entities/withEntitiesContainer.js
gsa/src/web/pages/hosts/detailspage.js
gsa/src/web/pages/schedules/details.js
gsa/src/web/pages/schedules/row.js

Merge gsa 8

---

gsa/src/web/components/layout/__tests__/__snapshots__/horizontalsep.js.snap
gsa/src/web/components/layout/horizontalsep.js
gsa/src/web/pages/alerts/details.js
gsa/src/web/pages/targets/details.js

Also fix small typo
**Checklist**:
- [] Tests

Don't show last Comma in hosts lists at target details

---

gsa/src/web/entities/container.js
gsa/src/web/entity/component.js
gsa/src/web/pages/reports/detailspage.js

All export filename props are strings.
**Checklist**:
- [] Tests

Fix proptypes for export filenames

---

CHANGELOG.md
gsa/src/web/pages/alerts/condition.js
gsa/src/web/pages/alerts/event.js
gsa/src/web/pages/alerts/method.js

Don't crash Alerts page with when missing data

---

gsa/src/web/pages/reports/detailspage.js

Prevent adding a superfluous .xml
**Checklist**:
- [] Tests

Pass report extension to generateFilename

---

CHANGELOG.md
gsa/src/gmp/models/nvt.js
gsa/src/web/pages/results/row.js

Always show result link

---

gsa/src/web/pages/alerts/method.js
gsa/src/web/pages/reports/vulnerabilitiestable.js
gsa/src/web/pages/vulns/table.js

Fix typos.

---

CHANGELOG.md
gsa/src/web/components/powerfilter/powerfilter.js

Adjust ManualIcon in Powerfilter

---

gsa/src/web/pages/tasks/dialog.js

Finetune select width in Task dialog

---

CHANGELOG.md
gsa/src/web/pages/reportformats/detailspage.js

Fix inactive Verify Report Format Icon at detailspage

---

README.md

References https://github.com/greenbone/openvas/issues/368
- [n/a] Tests

Add hint for the release file signatures key to README

---

CHANGELOG.md
gsa/src/gmp/models/scanconfig.js
gsa/src/web/pages/scanconfigs/trend.js

Fix showing ScanConfig trend

---

CHANGELOG.md
gsa/src/web/pages/reports/detailspage.js

Fix displaying only usable report formats at report download

---

gsa/src/web/pages/reportformats/listpage.js

added success dialog to report formats listpage

---

CHANGELOG.md
gsa/src/web/pages/hosts/listpage.js

Fix hosts count

---

CHANGELOG.md
gsa/src/web/pages/audits/__tests__/__snapshots__/row.js.snap
gsa/src/web/pages/audits/__tests__/row.js
gsa/src/web/pages/audits/row.js
gsa/src/web/pages/policies/__tests__/__snapshots__/row.js.snap
gsa/src/web/pages/policies/__tests__/row.js
gsa/src/web/pages/tasks/row.js

Improve audit row and add tests for audit row and policy row

---

CHANGELOG.md
gsa/src/web/pages/hosts/component.js
gsa/src/web/pages/hosts/detailspage.js

Remove CloneIcon and functionality from Host Detailspage and Component.
**Checklist**:
- [] Tests

Don't allow to clone hosts

---

gsa/src/gmp/models/tlscertificate.js
gsa/src/web/pages/reports/detailscontent.js
gsa/src/web/pages/tlscertificates/details.js
gsa/src/web/pages/tlscertificates/row.js

Further extend TLS Certificate Assets

---

CHANGELOG.md
gsa/src/web/pages/usersettings/usersettingspage.js

Disable editing settings if permission is denied

---

CHANGELOG.md
gsa/src/gmp/models/__tests__/scanconfig.js
gsa/src/gmp/models/scanconfig.js
gsa/src/web/pages/scanconfigs/trend.js

Scan config trend

---

CHANGELOG.md
gsa/src/web/pages/alerts/method.js

added details to alert details page

---

CHANGELOG.md
gsa/src/web/components/bar/__tests__/severitybar.js
gsa/src/web/components/bar/severitybar.js
gsa/src/web/pages/tickets/details.js
gsa/src/web/pages/tickets/table.js

Fix special ticket status

---

gsa/src/gmp/commands/__tests__/audit.js
gsa/src/gmp/commands/__tests__/policy.js
gsa/src/gmp/commands/audits.js
gsa/src/gmp/commands/policies.js

Add tests for audit and policy commands

---

gsa/src/web/components/form/download.js
gsa/src/web/components/form/withDownload.js
gsa/src/web/pages/reports/detailspage.js

Allow to set download mimetype

---

CHANGELOG.md
gsa/src/web/pages/portlists/detailspage.js
gsa/src/web/pages/portlists/listpage.js

Adjust PortList manual links

---

CHANGELOG.md
gsa/src/web/components/dialog/savedialog.js

Replaced savedialogcontent class with hooks

---

gsa/src/gmp/models/tlscertificate.js
gsa/src/web/components/dialog/composercontent.js
gsa/src/web/components/form/__tests__/__snapshots__/datepicker.js.snap
gsa/src/web/components/layout/__tests__/__snapshots__/globalstyles.js.snap
gsa/src/web/components/section/header.js
gsa/src/web/entity/page.js
gsa/src/web/pages/policies/__tests__/__snapshots__/detailspage.js.snap
gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/editconfigfamilydialog.js.snap
gsa/src/web/pages/scanconfigs/__tests__/__snapshots__/editdialog.js.snap
gsa/src/web/pages/tlscertificates/component.js
gsa/src/web/pages/tlscertificates/detailspage.js
gsa/src/web/pages/tlscertificates/listpage.js
gsa/src/web/pages/tlscertificates/row.js

This PR adds a download functionality to the already existing export-method. I kept the latter to be consistent with the other assets, which can be exported.
**Checklist**:
- [] Tests

Add download functionality to TLS Certificates
